### ISSUE TITLE
Custom recipes hinders the downloading of other ones.

### ISSUE THREAD

**Issue by yaki29** [kivy/python-for-android#1001]
I have added some of my recipes to the python-for-android directory. It recognizes them while building but when it starts downloading hostpython2, the build is crashed. So how could another recipe make it crash while downloading hostpython2. If it is some kind of bug I would be glad to solve it. I just need some reviews on this.
Here is the build crash report: https://gist.github.com/yaki29/7014b36f88992d9a0e2aaefaadda7988

**Comment by inclement** [comment]
Are you sure this is related to your use of custom recipes? Does it work if you exclude them and have the same problem every time you include them? It looks like an internet connection problem not related to p4a.

**Comment by yaki29** [comment]
I have done the same thing again and again ... It always stops while downloading the hostpython2. It works fine without adding my custom recipes.

**Comment by yaki29** [comment]
@inclement It comes out that my libxml2 recipe was making mess. Thanks for reviewing.
