### ISSUE TITLE
Shouldn't P4A Raise Exception On User File Having Syntax Error

### ISSUE THREAD

**Issue by FeralBytes** [kivy/python-for-android#1009]
I recently had a build failing; now admittedly it was my fault with a syntax error; but since P4A detects this as shown below shouldn't it stop the build and tell the user?

```
Compiling /home/wolfrage/0.Projects/EzTunes/src/build/bdist.android-armeabi/Tunes/Logic.py ...
SyntaxError: ('invalid syntax', ('/home/wolfrage/0.Projects/Tunes/src/build/bdist.android-armeabi/Tunes/Logic.py', 160, 21, '            except as e:\n'))

Compiling /home/wolfrage/0.Projects/Tunes/src/build/bdist.android-armeabi/Tunes/OldLogic.py ...
```

**Comment by inclement** [comment]
This would be a nice feature, I actually hadn't even noticed that the compilation step happens to detect this sometimes. I'm not quite sure how to check it properly (it looks like the compilation failure doesn't actually raise an error), but I guess it should be doable.
