### ISSUE TITLE
Python 3 branch still uses python 2.x

### ISSUE THREAD

**Issue by kosiara** [kivy/python-for-android#1022]
1. I'm trying to use Kivy's python-for-Android to compile a python interpreter and embed it in Android applications
2. I need a **python 3.x** interpreter and the main branch still uses 2.x.

Why is python3 branch still using python 2.x? (As in recipes/hostpython/recipe.sh and
recipes/python/recipe.sh ) ?

Does python-for-Android work as a python3 interpreter?

Where can I find patches to python 3 (like the ones for python 2) ?

Thanks

**Comment by inclement** [comment]
The `python3` branch is an ancient experiment with the old python-for-android toolchain. The current toolchain (i.e. master branch) supports Python 3 without patching via the [CrystaX NDK](https://www.crystax.net/en/android/ndk). The Python 3 recipes is [here](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/python3crystax/__init__.py), but doesnt actually do anything special as we currently use the precompiled CrystaX binaries. There's also some brief documentation about it [here](http://python-for-android.readthedocs.io/en/latest/buildoptions/#python3).

You can definitely use this method to embed a Python interpreter in your Android applications. If you just want Python itself you could even skip python-for-android and use the CrystaX builds directly, although python-for-android is probably useful if you want to compile extra mdoules.

You can alternatively find patches for some Python 3 versions in other projects, but I never had much luck with them when trying it. However, I haven't looked for a while.
