### ISSUE TITLE
python-for-android doesn't work with current Android SDK

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1050]
The rearranged SDK internals mean that python-for-android uses the wrong path to call the android binary, which also no longer should be used. p4a needs to know how to call sdkmanager instead.

**Comment by hemna** [comment]
I just noticed this today too.  I just tried and the new Android SDK = Android studio.  I can't find the older SDK anywhere to try and get p4a to work.

**Comment by inclement** [comment]
Fixed by https://github.com/kivy/python-for-android/pull/1057
