### ISSUE TITLE
ImportError when importing files containing \N{name} escape sequence

### ISSUE THREAD

**Issue by WillDHB** [kivy/python-for-android#1060]
Attempting to run an apk that imports a module using a unicode string with a \N{name} escape sequence will result in an ImportError.  Inspecting the apk will show that the relevant files are indeed missing from the installation.  This occurs when attempting to use httplib2 (someone filed a Kivy bug for this at https://github.com/kivy/kivy/issues/2499, but apparently never filed one for p4a), as well as for BeautifulSoup.  The apk is built successfully; however, for whatever reason, the affected files are omitted entirely.  This is easily reproducible.  

For anyone interested, the relevant httplib2 file is httplib2.iri2uri, and the relevant BeautifulSoup is bs4.builder._htmlparser.

I'm assuming this is a bug, rather than the result of some sort of flagged that I've missed.

**Comment by VineethRaghavan** [comment]
I too had the same problem when I was using python 2.7. There is a link that has a solution regarding this:
https://github.com/kivy/buildozer/issues/135

I don't know if it works since I switched to Python 3.6 to avoid unicode errors.

**Comment by Julian-O** [comment]
Closing as stale because it seems to only apply to Python 2.7.

If you are still seeing this, please let us know.
