### ISSUE TITLE
ImportError: No module named audioop

### ISSUE THREAD

**Issue by jacebrowning** [kivy/python-for-android#1067]
With `requirements = hostpython2,kivy` or `requirements = python2,kivy`, `import audioop` fails with:

```
06-17 16:57:54.328 15569 15649 I python  : Traceback (most recent call last):
06-17 16:57:54.328 15569 15649 I python  :   File ".../.buildozer/android/app/main.py", line 4, in <module>
06-17 16:57:54.328 15569 15649 I python  : ImportError: No module named audioop
```

**Comment by KeyWeeUsr** [comment]
Same like with `sqlite3`, even `audioop` will either need a recipe or some flag if the code is in python source, so that's most likely why it doesn't work.

**Comment by jacebrowning** [comment]
Is there any sort of guide on building recipes? I'd like to help make this work.

**Comment by KeyWeeUsr** [comment]
Sure, you can see the documentation [here](http://python-for-android.readthedocs.io/en/latest/recipes/). :)
