### ISSUE TITLE
'Context' object has no attribute 'hostpython'

### ISSUE THREAD

**Issue by maquedexiju** [kivy/python-for-android#1073]
I've checked the issues before, and I use the command below
`p4a apk —private /Users/XuXiaotian/Git/DaytimeLog —package=com.xiaotian.daytimelog —name “Daytime Log” —version 2.1 —bootstrap=sdl2 —requirements=python3crystax,kivy --arch=armeabi-v7a`

But it won't help, I use Python3.6 and the newest Android SDK.
Need help.

**Comment by inclement** [comment]
Are you using the latest python-for-android master branch?

**Comment by maquedexiju** [comment]
Yes, I just install it from git today, do you need any other infomations?

**Comment by maquedexiju** [comment]
> [INFO]:    Copying python distribution
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/p4a", line 11, in <module>
>     load_entry_point('python-for-android==0.5', 'console_scripts', 'p4a')()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pythonforandroid/toolchain.py", line 906, in main
>     ToolchainCL()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pythonforandroid/toolchain.py", line 512, in __init__
>     getattr(self, args.subparser_name.replace('-', '_'))(args)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pythonforandroid/toolchain.py", line 147, in wrapper_func
>     build_dist_from_args(ctx, dist, args)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pythonforandroid/toolchain.py", line 192, in build_dist_from_args
>     ctx.bootstrap.run_distribute()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pythonforandroid/bootstraps/pygame/__init__.py", line 48, in run_distribute
>     hostpython = sh.Command(self.ctx.hostpython)
> AttributeError: 'Context' object has no attribute 'hostpython'

Hop this can help you

**Comment by maquedexiju** [comment]
Seems that the problem is that I input the command in my evernote first, when I copy that to the terminal, the "--" is converted to "-", and the paras can't be recognized then.
