### ISSUE TITLE
Android 7 complains about Kivy 1.10.0 apps: "detected problems with app native libraries"

### ISSUE THREAD

**Issue by brady-ds** [kivy/python-for-android#1078]
When running any (Python 2) Kivy 1.10.0 app packaged by p4a 0.4 on Android 7.0 (x86), I get a toast reading:

> Detected problems with app native libraries (please consult log for detail):
> `libavcodec.so`: text relocations
> `libavutil.so`: text relocations
> `libswresample.so`: text relocations
> `libglapi.so`: text relocations

A quick search suggest that this is cause by the new behaviour described [here](https://developer.android.com/about/versions/nougat/android-7.0-changes.html#ndk).

Let me know if I need to provide more info.  Apologies if I am reporting a duplicate or against the wrong project.

**Comment by inclement** [comment]
Is this still happening? I'm surprised I haven't heard anything else about it, but I'm not aware of anyone specifically fixing it.

**Comment by inclement** [comment]
I'm going to close this as not reproducible, I haven't seen any other reports about this even though I expected to when I saw the original report. If anyone does still have this issue, please feel free to reopen it.

**Comment by Electrojones** [comment]
Still having the same Problem.

Python: v3.7.4
Android: 7.1.2 (lineage OS)
kivy: v1.11.1
