### ISSUE TITLE
Remove WRITE_EXTERNAL_STORAGE default permission

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1081]
This may need a small change in Kivy, but is otherwise non-essential.

**Comment by KeyWeeUsr** [comment]
It's forced [here](https://github.com/kivy/python-for-android/blob/0d491b916efd3fdc1671deb8028a89a7936d0c41/pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml#L28), it's needed for https://github.com/kivy/kivy/issues/4777 and fixed in the linked PR.

**Comment by inclement** [comment]
Oh, great, I hadn't seen that PR. I was going to propose also checking the old location first, but otherwise defaulting to the new (better) one. I think that would be worthwhile to fix this annoying problem on Android, even if it's slightly more complex.

We could also use the app's official external storage directory, found by querying the Android API. That would be more consistent with the spirit of the current behaviour.

**Comment by KeyWeeUsr** [comment]
I was thinking about it, but then it'd mean including at least `pyjnius` to each android application, which isn't the happiest solution. We could maybe use the old-ish `android` package/recipe, but that might still need some editing and also requiring from user to include it (or add it to `kivy` as a requirement).

If we can't do any of these cases, we end up with an environment variable. As that thing is set in(/for) [`start.c`](https://github.com/kivy/python-for-android/blob/c45bd81ea15b345815450dc2fd14ff884fb12fbb/pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java#L351), we can use `sys.executable`

**Comment by inclement** [comment]
`pyjnius` is already a Kivy dependency on Android.

**Comment by KeyWeeUsr** [comment]
That kind of skipped my mind completely 😄

**Comment by fyookball** [comment]
I am having a problem and I don't know whether it is related to this issue, but I just built an apk for my project, which gives a parsing error (can't install)...but it works fine if i manually copy the apk file to the phone with a usb cable.  Is there something I can do to force my android phone to properly download the apk?

**Comment by inclement** [comment]
@fyookball There is no reason to think that this issue is related to your problem. Please post instead on the [kivy-users mailing list](https://groups.google.com/forum/#!forum/kivy-users).

**Comment by JonasT** [comment]
Is there a switch to remove this permission for non-kivy projects that use python-for-android?

**Comment by inclement** [comment]
No, there isn't. Philosophically I'd prefer to just fix Kivy and then remove the default permission entirely, but it would be fair enough to add a toggle for it as it stands.

**Comment by JonasT** [comment]
Okay, once the SDL2 version bump is in, this should be relatively simple to do. I'll look into it, I need to add another option I want to `AndroidManifest.xml` anyway (the one that makes the whole app window shrink/downsize to make room for an opening virtual keyboard, rather than get overlapped by it)

**Comment by JonasT** [comment]
I think with Android 5+ versions this is obsolete anyway, right? Which is all we support as minimum, since there runtime permissions requests are needed anyway. I think therefore it makes sense to close this ticket, anyone feel free to poke me if this is wrong and I'll gladly reopen!
