### ISSUE TITLE
p4a does not yet work with clang

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1097]
Since clang is the only supported compiler in the official NDK, this is a problem. It seems to have not come up yet mainly because of developing with the CrystaX NDK.

I intend to focus on getting this working following the upcoming release.

**Comment by inclement** [comment]
This issue might just be the same as https://github.com/kivy/python-for-android/pull/1095 .

**Comment by inclement** [comment]
Following https://github.com/kivy/python-for-android/pull/1103, clang is used by the jni components (sdl2, sdl2_image etc.) but other recipes still use gcc. However, it's promising that clang seems to work fine where it does get used, and it shouldn't be too hard to add clang compiler paths in p4a.

**Comment by AndreMiras** [comment]
@inclement this is working now right?

**Comment by Julian-O** [comment]
@inclement: Is this working now?

**Comment by misl6** [comment]
> @inclement: Is this working now?

Absolutely yes!
