### ISSUE TITLE
Running on Android 4.0 doesn't work when building for target api 19

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1104]
I noticed this while debugging https://github.com/kivy/python-for-android/pull/903. The error is as follows:

```
D/dalvikvm( 1265): Trying to load lib /data/data/org.test.testapp_python2/lib/libpython2.7.so 0xa1d050d0
V/python  ( 1265): Library loading error: Cannot load library: reloc_library[1285]:   650 cannot locate 'wait4'...

```

Building the same app for target api 15 seems to work.

I don't know if we can do anything about this, but we should probably at least document it. It would be good to verify if this affects non-emulator devices, as I only have the emulator to test with for this android version.

**Comment by tempdban** [comment]
target api 19 - android 4.4.2

**Comment by inclement** [comment]
Probably fixed by the ndk-api addition and other recipe fixes since then.
