### ISSUE TITLE
"crystax_python does not exist" with python3crystax

### ISSUE THREAD

**Issue by eudoxos** [kivy/python-for-android#1105]
I am new to buildozer/kivy and I tried to build the camera example and run it on the phone. I cloned buildozer git repo and installed buildozer (via `python3 setup.py install`). Then I downloaded the latest release from crystax.net and after `buildozer.init`, I change in the buildozer.spec:

 ```
title = Kivy Camera Examples
package.name = KivyCamEx
requirements = kivy==master, python3crystax
android.ndk = 10.3.2
android.ndk_path = /home/user/kivy/crystax-ndk-10.3.2
```

When I run `buildozer android debug deploy run logcat` I find the problematic spot here:

```
08-30 14:17:56.750 18316 18336 I python  : Initialize Python for Android
08-30 14:17:56.750 18316 18336 I python  : Changing directory to the one provided by ANDROID_ARGUMENT
08-30 14:17:56.750 18316 18336 I python  : /data/user/0/org.test.kivycamex.kivycamex/files/app
08-30 14:17:56.751 18316 18336 I python  : Preparing to initialize python
08-30 14:17:56.751 18316 18336 I python  : crystax_python does not exist
08-30 14:17:56.789 18316 18336 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 18336 (SDLThread)
```

Inspecting the `.buildozer` directory, I can see `android/platform/build/dists/crystax_python/crystax_python` but when I inspect the APKs (`android/platform/build/dists/KivyCamEx/bin`, they are both (plain and unaligned) only 2.6MB in size and do not contain `crystax_python`.

Is that an error? Omission? In https://github.com/kivy/buildozer/issues/529, the reporter implies setting python3crystax + pointing to the NDK is sufficient to get running with python3, which is not the case here. Similarly in https://github.com/kivy/python-for-android/issues/752 where the reporter only add python3crystax to requirements and has `crystax_python exists` in the log.

**Comment by inclement** [comment]
Closing as obseleted by moving away from python3crystax to the normal python3 recipe. Also, this might have been fixed anyway, there have been various changes to the python3 loading since then.
