### ISSUE TITLE
Kivy python  android build issue?

### ISSUE THREAD

**Issue by angy1551** [kivy/python-for-android#1110]
**when i run command buildozer android debug.
Following error i get
[angad@angad-pc ~]$ cd Python
[angad@angad-pc Python]$ ls
bin  buildozer.spec  main.py
[angad@angad-pc Python]$ buildozer android debug
 Check configuration tokens
 Ensure build layout
 Check configuration tokens
 Preparing build
 Check requirements for android
 Install platform
 Apache ANT found at /home/angad/.buildozer/android/platform/apache-ant-1.9.4
 Android SDK found at /home/angad/.buildozer/android/platform/android-sdk-20
 Android NDK found at /home/angad/.buildozer/android/platform/android-ndk-r9c
 Check application requirements
 Check garden requirements
 Compile platform
 Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/angad/Python/.buildozer/android/platform/build

 Buildozer failed to execute the last command
 If the error is not obvious, please raise the log_level to 2
 and retry the latest command.
 In case of a bug report, please add a full log with log_level = 2**

**Comment by AndreMiras** [comment]
Hi @angy1551,
```
In case of a bug report, please add a full log with log_level = 2
```
Without this line and the debug output, there's nothing much we can do.
Could you please also use proper formatting with triple backquotes (\`\`\`)?

**Comment by AndreMiras** [comment]
Closing after a year with no reply
