### ISSUE TITLE
Suggestion: Allow a recipe to checkout a module from a local git repository

### ISSUE THREAD

**Issue by wexi** [kivy/python-for-android#1119]
diff --git a/pythonforandroid/recipe.py b/pythonforandroid/recipe.py
index 234a111a..8e76daca 100644
--- a/pythonforandroid/recipe.py
+++ b/pythonforandroid/recipe.py
@@ -149,7 +149,7 @@ class Recipe(with_metaclass(RecipeMeta)):
 
             urlretrieve(url, target, report_hook)
             return target
-        elif parsed_url.scheme in ('git', 'git+ssh', 'git+http', 'git+https'):
+        elif parsed_url.scheme in ('git', 'git+file', 'git+ssh', 'git+http', 'git+https'):
             if isdir(target):
                 with current_directory(target):
                     shprint(sh.git, 'fetch', '--tags')

**Comment by AndreMiras** [comment]
This was merged two weeks ago in https://github.com/kivy/python-for-android/pull/1139
@wexi feel free to close if you think it's OK.
