### ISSUE TITLE
Webview loading animation doesn't work

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1123]
Due to a missing `static/style.css` in the webview bootstrap source, the webview loading page probably doesn't show any animation by default. The code it assumes to be present is included in the test app, at https://github.com/kivy/python-for-android/blob/master/testapps/testapp_flask/static/style.css . 

Further, it would be even better to make the loading page somehow customisable.

**Comment by KeyWeeUsr** [comment]
Perhaps we could use some template for the loading screen with a default `.css` unless specified otherwise e.g. via console argument or `.spec` property?
