### ISSUE TITLE
pyopenssl cryptography dependence

### ISSUE THREAD

**Issue by wexi** [kivy/python-for-android#1127]
Has anyone got a working distribution with pyopenssl.
This package depends (undocumented) on cryptography which refuses to build.
I am using the standard android-sdk-20  and android-ndk-r9c (buildozer reommend).
Using CrystaX 10.3.2 does not help.
Using python2.

Thanks, Enoch.

**Comment by rnixx** [comment]
With this changes, I got cryptography working https://github.com/kivy/python-for-android/pull/1381

**Comment by inclement** [comment]
Closing as stale, I think the cryptography recipe is currently working.
