### ISSUE TITLE
SDL Error: Error Could not load any libpythonXXX.so

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/python-for-android#1142]
Deploying on Android 4.3 (seems to only happens on versions < 4.4), ASUS MEMOPad, ME302C.

Using the latest checkout of buildozer, removing the apps ./builodozer folder and rebuilding.

    commit 8f3f1bc3e92f78adc1319f0e97b8003c9c932c39
    Author: Peter Badida <KeyWeeUsr@users.noreply.github.com> 
    Date:   Fri Aug 11 21:39:18 2017 +0200

The requirements file is here, with p4a using master:

    https://gist.github.com/Zen-CODE/ece649dc97e0f28e56967d10dd2d64bc

The output is here:

    https://gist.github.com/Zen-CODE/671065a8b7bf66984a3106c1e19a81cd
    

Does not seems to be fixed by: https://github.com/kivy/python-for-android/pull/903

**Comment by inclement** [comment]
Thanks for the detailed report. Your log seems to indicate that the APK wasn't actually successfully pushed to the device (`Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]`), so the error shown is not from the newly built APK. Could you post the log that you get if you fix this? Just uninstalling the old version should be enough.

I guess buildozer shouldn't proceed if the adb call fails, but that's a separate bug.

I also noticed that this looks like an x86 device running libhoudini, and I think the libpython2.7.so error `dlopen failed: "/data/app-lib/speedtest.maths.camiweb.com-1/libpython2.7.so" has unexpected e_machine: 40` can relate to that. If that turns out to be the same issue with the master branch, it may be possible to solve things by building an x86 APK.

**Comment by Zen-CODE** [comment]
Thanks. Will do. Yes, that device is Intel device using libhoudini, but we get the same error on another 4.2 ARM device.

**Comment by Zen-CODE** [comment]
Here is the output from another device that generates the same error. It's an ARM device, Quad core Cortex A7.

https://gist.github.com/Zen-CODE/b2b1e19329068519f22ffd76139d134c

Mecer 8 inch Pad
Android 4.2.2
Model 800p31C

**Comment by Zen-CODE** [comment]
A colleague had the following suggestion as to the cause
```
On unix systems (or on Windows using cygwin or mingw+msys) the command typically looks something like this:

    gcc shell.c sqlite3.c -lpthread -ldl

The pthreads library is needed to make SQLite threadsafe. But since the CLI is single threaded, we could instruct SQLite to build in a non-threadsafe mode and thereby omit the pthreads library:

    gcc -DSQLITE_THREADSAFE=0 shell.c sqlite3.c -ldl

The -ldl library is needed to support dynamic loading, the sqlite3_load_extension() interface and the load_extension() SQL function. If these features are not required, then they can be omitted using SQLITE_OMIT_LOAD_EXTENSION compile-time option:

    gcc -DSQLITE_THREADSAFE=0 -DSQLITE_OMIT_LOAD_EXTENSION shell.c sqlite3.c


``

**Comment by Zen-CODE** [comment]
@tshirtman. Although the errors messages are similar, I doubt they have the same cause. Our error message is literally "libPythonXXX.so", with the X's and not numbers. The fact that yours includes a number implies to me it occurs in a different place? Anyway, for us, this message was almost certainly  OS related e.g. it occurred only on a phone with an older OS, so I don't think it relevant any more. Ours was using python2 only (not deploying 3 yet).

So I am going to close this as I think you would be better served creating a new ticket? My info here will only serve to obscure yours....;-)

**Comment by tshirtman** [comment]
I cleaned up, got out of my kivy venv, upgraded pip and setuptools, and rebuilt, i now have a different error, i think it's trying to build things it wasn't before, hopefully when i get through i won't have this bug.

**Comment by anooprana985** [comment]
I have created my application using buildozer.And everything works fine.But the moment i replace:

1)"package.name = myapp" to "package.name = anoop"
2)"package.domain = org.test" to "package.domain = org.singh"
in the .spec file the app crashes on my andoid with the error "An error occured while trying to start the application.Please try again and/or reinstall.
Error: Could not load any libpythonXXX.so".

Note that the when i run buildozer android debug everything works fine its omly that the app crashes on android.
I am attaching the error screenshot.

**Comment by urbanoTF** [comment]
Same issue here, renamed variables and it broke.
I think that something gets cached and you need to delete the .buildozer folder. (Testing it right now)

"package.name = myapp" to "package.name = whatever"
"package.domain = org.test" to "package.domain = whatever"
