### ISSUE TITLE
lxml uses etree.so that throws an unexpected e_machine error 

### ISSUE THREAD

**Issue by dav01it** [kivy/python-for-android#1147]
If I use lxml in my app the app crashes with this error:
logcat:

> **ImportError: dlopen failed: "/data/data/org.apptest.test/files/app/lib/python2.7/site-packages/lxml/etree.so" has unexpected e_machine: 3**

I tried in a 64bit and 32bit debian installation, message changes, so I suspect that etree.so is compiled with the hosting machine on which buildozer runs instead of the target android machine.

in  64 bit enviroment I get:

> **ImportError: dlopen failed: "/data/data/org.apptest.test/files/app/lib/python2.7/site-packages/lxml/etree.so" is 64-bit instead of 32-bit**

**Comment by therealmarv** [comment]
lxml is a library around libxslt & libxml. So it's more or less a beautiful interface to handle a native system library and python for android does not support that.

**Comment by dav01it** [comment]
Ok.. going to avoid lxml... looking for a portable alternative to navigate an xml structure; I mean some complex one. any Ideas? I've found very useful "suds" to parse an xml web service response but its documentation is very poor and I'm not able to use it for a plain xml (i.e without webservices, soap envelope and wsdl)

**Comment by therealmarv** [comment]
I think https://docs.python.org/3/library/xml.etree.elementtree.html is Python only (this is the standard). I would also look into html5lib or Beautifulsoup. If you want to navigate through an XML I would also suggest to google for "pure python xpath", there are a bunch of libraries out there.

**Comment by dav01it** [comment]
Thanks I close the Issue. Useful answer!
