### ISSUE TITLE
--ndk_ver cli option not working, but ANDROIDNDKVER does

### ISSUE THREAD

**Issue by bionoid** [kivy/python-for-android#1149]
Running a basic ``p4a apk`` command with ``--ndk_ver="r15c"`` fails:

``
[INFO]:    Got NDK version from $ANDROIDNDKVER
[WARNING]: Android NDK version could not be found, exiting.
``

Fixed by ``export ANDROIDNDKVER="r15c"``

**Comment by inclement** [comment]
The cli option is `--ndk-version` or `--ndk_version`. The documentation for this at https://python-for-android.readthedocs.io/en/latest/quickstart/#installing-android-sdk was wrong, I've corrected it. If you found it documented somewhere else, let me know and I'll try to fix that too.
