### ISSUE TITLE
Reopen running instance instead of starting a new one upon tapping app icon

### ISSUE THREAD

**Issue by Davincible** [kivy/python-for-android#1161]
I always get an 'app has crashed' message if I open my app on android when I already opened the app before. My suspicion is that the already running instance crashes, and that a new one is started(which opens fine). 
But I would like to re-open the already running instance (if there is one), instead of starting a new one when I tap on the app icon. 

How can I achieve this?

**Comment by inclement** [comment]
Have you added `def on_pause(self): return True` to your App class?

**Comment by Davincible** [comment]
Yes I've done that, although I thought the default was to return True

**Comment by Fogapod** [comment]
Ref: https://github.com/kivy/python-for-android/issues/1099

**Comment by inclement** [comment]
Closing as apparently not an active issue, I haven't seen other issues like this.

**Comment by Davincible** [comment]
Yes turns out to be an issue related to that specific app, others work fine. Have no clue where to start looking for the problem though
