### ISSUE TITLE
no module named tty

### ISSUE THREAD

**Issue by sm-jalali-f** [kivy/python-for-android#1165]
i'm running testapp in your repository but when run application it crashe.
log cat error show this : 
11-10 21:06:50.949 17674 17698 I python  :  Traceback (most recent call last):
11-10 21:06:50.949 17674 17698 I python  :    File "/home/mohamad/PycharmProjects/kivyDeepLearn/.buildozer/android/app/main.py", line 5, in <module>
11-10 21:06:50.949 17674 17698 I python  :    File "/home/mohamad/PycharmProjects/kivyDeepLearn/.buildozer/android/platform/build/dists/kivyAndcai/private/lib/python2.7/site-packages/pythonforandroid/recipes/android/__init__.py", line 1, in <module>
11-10 21:06:50.950 17674 17698 I python  :    File "/home/mohamad/PycharmProjects/kivyDeepLearn/.buildozer/android/platform/build/dists/kivyAndcai/private/lib/python2.7/site-packages/pythonforandroid/recipe.py", line 10, in <module>
11-10 21:06:50.950 17674 17698 I python  :    File "/home/mohamad/PycharmProjects/kivyDeepLearn/.buildozer/android/platform/build/dists/kivyAndcai/private/lib/python2.7/site-packages/sh.py", line 96, in <module>
11-10 21:06:50.950 17674 17698 I python  :    File "/home/mohamad/PycharmProjects/kivyDeepLearn/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a/python2/python-install/lib/python2.7/pty.py", line 11, in <module>
11-10 21:06:50.950 17674 17698 I python  :  ImportError: No module named tty

how to fix it???

**Comment by inclement** [comment]
The tty module isn't included in the apk as a minor optimisation (almost nothing uses it). You can un-blacklist it if necessary using the whitelist options of buildozer/python-for-android. The term to whilelist is `tty.pyo`.

Also, you say you're using one of the testapps, but the traceback seems to indicate the code is trying to use the sh module. Is this something you added to the testapp, or did you change anything else away from the parameters in the repository?

**Comment by sm-jalali-f** [comment]
My problem is solved. i remove sh library.
but i write my program that  receive intent in android app.
my code is:
```
from kivy.app import App
from pythonforandroid.recipes.android.src.android.broadcast import BroadcastReceiver

class MyApp(App):
    # def __init__(self, **kwargs):
    #     super().__init__(**kwargs)
    #     print("init")

    def build(self):
        print("build")
        self.br = BroadcastReceiver(self.on_broadcast, actions=['new_picture_added'])
        self.br.start()
        

    def on_broadcast(self, context, intent):
        extras = intent.getExtras()
        pictureAddress = str(extras.get('picture_address'))
        print(pictureAddress)
        self.out.write("onBroadcast\n")

    def on_pause(self):
        self.br.stop()
        print("onPause")
        self.out.write("onPause")
        return super(MyApp, self).on_pause()


    def on_resume(self):
        self.br.start()
        print("onResume")
        self.out.write("onResume")
        super(MyApp, self).on_resume()



if __name__ == '__main__':
    MyApp().run()

```
and add python-for-android in requirement on spec file like this:
requirements = kivy,python-for-android
but when build and run android application with this command:
sudo buildozer android debug deploy run logcat 
when running this error occured:
11-12 21:49:53.843  2872  2909 I python  :  Traceback (most recent call last):
11-12 21:49:53.843  2872  2909 I python  :    File "/home/mohamad/PycharmProjects/kivyDeepLearn/.buildozer/android/app/main.py", line 5, in <module>
11-12 21:49:53.843  2872  2909 I python  :  ImportError: No module named pythonforandroid.recipes.android.src.android.broadcast
11-12 21:49:53.861  2872  2909 I python  : Python for android ended.

what is my mistake?

**Comment by inclement** [comment]
python-for-android is a build tools for Android, you don't need or want it in your app itself. You just want the android module, so include that in your requirements and import from there.

**Comment by sm-jalali-f** [comment]
I change requirements line to this but not work. and error occured again
requirements = kivy,android

**Comment by inclement** [comment]
Please post the details of the error on the [kivy-users mailing list](https://groups.google.com/forum/#!forum/kivy-users).
