### ISSUE TITLE
python2 recipe always builds for armeabi regardless of what arch you tell it to target

### ISSUE THREAD

**Issue by bobpoekert** [kivy/python-for-android#1174]
Hard-coding `arm-eabi` as the arch [here](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/python2/__init__.py#L86) means that it will target `arm-eabi` regardless of what arch you intend to target (x86, mips, arm64, etc)

**Comment by inclement** [comment]
Thanks for the report. I'm not sure how that's happened, since I've built for other archs before, but it hopefully shouldn't be too hard to fix.

**Comment by JonasT** [comment]
I think this should be fixed on latest master due to the many revisions & improvements of the core recipe. @bobpoekert could you possibly check again, if you're still a p4a user?
