### ISSUE TITLE
Local recipes can not be patched any longer

### ISSUE THREAD

**Issue by bobatsar** [kivy/python-for-android#1185]
It seems since commit 9242bea826a2bdc58915d4954343aee5165d9ad4 local recipes which try to patch files can not run any longer. The call to get_recipe_dir() always returns a path in the ctx.root_dir and that is wrong for local recipes.

I tried to revert that commit here locally and now the patching works again.

**Comment by inclement** [comment]
That's my mistake, sorry about that. I'll aim to push a fix soonish, although probably it's better to fix `get_recipe_dir` than to re-add the old behaviour.

**Comment by AndreMiras** [comment]
Yes I'm also affected by this issue. What is you suggestion to fix `get_recipe_dir()` I'm willing to take a look because I'd like to submit my app to F-Droid.
