### ISSUE TITLE
[INFO]:        Building with ant, as no gradle executable detected

### ISSUE THREAD

**Issue by mangodan2003** [kivy/python-for-android#1186]
This is maybe a out of date docs issue rather than a bug.

Ubuntu 16.04
ii  gradle                                    2.13-4                    all                       Powerful build system for the JVM

From what I can gather it has something to do with a wrapper being missing rather than gradle itself but I can find no mention of howto install this anywhere in the p4a docs :/.

i'm trying to build with:

p4a apk --private ./myapp --package=org.example.myapp --name "My SDL2 application" --version 0.1 --bootstrap=sdl2 --requirements=websocket-client --arch=armeabi-v7a

**Comment by inclement** [comment]
It isn't clear what, if anything, has gone wrong for you. Nothing you have posted is an error.

Please post a full explanation of the issue, including the build log.
