### ISSUE TITLE
macOS Hight Siera installation issue

### ISSUE THREAD

**Issue by a-klimashevsky** [kivy/python-for-android#1192]
Hello,
I've try to install p4a using `pip install python-for-android` command
but I have an error `IOError: [Errno 13] Permission denied: '/lib/python2.7/site-packages/sh.py'`

In case of using `sudo pip install python-for-android` command I have warnings about cache folders.

Everything is ok using --user flag, but command p4a is not available from command line

P.S. /usr/local/bin in PATH

**Comment by inclement** [comment]
It sounds like everything is fine, except whatever your cache issue is (probably unrelated to p4a), and that probably the --local bin folder containing the p4a scripts is not in your $PATH. It would be `~/.local/bin` on linux, I don't know if macOS is different.

Also, I would avoid using `sudo pip install`, it's best to leave the root python installation to the root level tools, and use the `--user` argument for your own things.
