### ISSUE TITLE
Kivy basic button program doesnt work

### ISSUE THREAD

**Issue by matanix** [kivy/python-for-android#1199]
Hey
I am trying to make my first app in kivy so i copied a basic button code.

class TestApp(App):
    def build(self):
        btn = Button(text="Press me")
        return btn

if __name__ == '__main__':
    TestApp().run()

however the button doesnt seem to be pressed when i click it with my mouse.

any suggestions how to fix this?

thanks

**Comment by matanix** [comment]
please im very stupid and i dont know how to do basic programming, i was born in an abortion so i am mentally unstable and might commit suicide if you dont reply. please its jhust a button for fuck's sake somebody help me im lonely. 
sincerely, me

**Comment by germn** [comment]
Your program works fine, you can bind some function to button state change as shown [here](https://kivy.org/docs/api-kivy.uix.button.html) to see it:

```
from kivy.app import App
from kivy.uix.button import Button


class TestApp(App):
    def build(self):
        btn = Button(text="Press me")
        
        def print_state(_, val):
            print(val)
        btn.bind(state=print_state)

        return btn


if __name__ == '__main__':
    TestApp().run()
```
