### ISSUE TITLE
sqlite pre-populated database not being found

### ISSUE THREAD

**Issue by Areopagitics** [kivy/python-for-android#1203]
hi there,

I get the exception error 'no such table: Readings' when trying to execute this part of main.py on android, but it works fine when running on Windows.  Is there a special place to put a pre-populated sqlite database?

I have followed these instructions with no luck [https://github.com/kivy/python-for-android/issues/1053](url)

```
def set_day(self, text, popup, *args):
        try:
            conn = sqlite3.connect('bible.db')
            conn.row_factory = sqlite3.Row
            c = conn.cursor()
            c.execute('select * from Readings where Date="2017-12-22"')
            text = c.fetchone()['Day']
        except Exception as e:
            text = str(e)
        self.ids.day.text = text
        popup.dismiss()
```

**Comment by germn** [comment]
Are you sure db you connect to on Android contains `Readings` table?
My guess is that `sqlite3.connect('bible.db')` tries to connect to file `bible.db` in some other place than you expect and opens empty db.
Try to pass [absolute path](https://stackoverflow.com/a/51523/1113207) of `bible.db` file to `connect`.

**Comment by inclement** [comment]
There shouldn't be any special procedures needed on Android, the most likely issue is that the database on the device isn't in the place you expect, if it's there at all. I'll close this as probably not a p4a issue, unless more information suggests otherwise.

**Comment by Areopagitics** [comment]
thanks for getting back so quick!  you guys are amazing! yes, I checked the app data folder with root access and my **bible.db** is was being added to the assets folder, when I added **db** extension in the **source.include_exts = py, db** .  

Thanks to [germn ](https://github.com/germn) it now works with **sqlite3.connect('assets/bible.db')** ; maybe one could add this to the documentation that other files get imported into assets!?
