### ISSUE TITLE
Kivy not working on Sony devices

### ISSUE THREAD

**Issue by darwusch** [kivy/python-for-android#1206]
Kivy using python3 is not working on Sony android devices.
See also:
https://github.com/kivy/python-for-android/issues/1188

It crashes immediately on startup.
Please fix this.

**Comment by inclement** [comment]
If you have more information that narrows down the issue to Sony devices, could you update the previous issue instead of opening a new one? Feel free also to change the title to reflect this.

**Comment by darwusch** [comment]
In the thread I gave a complete syslog as well as device information and android version.
What information do you need further?

**Comment by inclement** [comment]
Nothing in particular, I just meant that if you have some particular information that has led to you opening a new issue, but that it's an extension of the previous one (as you implied), it would be better to add that information to the previous one.
