### ISSUE TITLE
Buildozer android application crashs on android

### ISSUE THREAD

**Issue by ccharoux** [kivy/python-for-android#1215]
An application running ok under the windows python interpreter crashs when it has to scroll a list

android 7.0, buildozer python 2.7, windows interpreter Python 3.5
**Q**: is it possible to get a logging of errors under android ??
Here are the sources
[Annivs.zip](https://github.com/kivy/python-for-android/files/1594410/Annivs.zip)

**Comment by kuzeyron** [comment]
Have you set in the buildozer.spec: 
`log_level = 2
android.logcat_filters = *:S python:D`
- Log_level = 2 will show you any errors.
- android.logcat_filters will ignore everything else that doesn't have with Python to do with.

And when you run Buildozer: `buildozer android debug deploy run logcat`

And that's all what I can think of.
Lets hope you'll find the problem with your code!

**Comment by ccharoux** [comment]
thanks for your answer
I made what you said
But the question is : when i run the appli on my smartphone, can I have somewhere a log to read.
Because i should we aware of what happens

**Comment by kuzeyron** [comment]
Kivy should be logging. But I'm not 100% sure about that, if it's default or not.
Let's see if I can tag @tshirtman

**Comment by tito** [comment]
The only way for us right now to get logs is you to use adb. And even if somehow we would have a way to get them from the application, you'll need to have a rooted phone to activate READ_LOGS permission on the application.

So adb is the only way for us to get the logs. That's what buildozer does.

When your run the application on your smartphone, just connect the usb cable, and run `adb logcat` on a terminal before starting the app. You can filter it by running `adb logcat *:S python:D`.
Or use buildozer.

**Comment by tito** [comment]
And prefer to use mailing list kivy-users, or IRC to get user support. Thanks you :)
