### ISSUE TITLE
p4a cant find android sdk

### ISSUE THREAD

**Issue by borzeh** [kivy/python-for-android#1218]
im trying to create apk with p4a with such command
`p4a apk --private ~/ --package=com.something.BorCal --name "BorCal" --version 0.1 --bootstrap=sdl2 --requirements=python,kivy --sdk_dir PATH="mnt/sda6/usr2/android/" --android_api 20`

note that sda6 is mounted
inside android folder there is tools folder that contains 'android' and inside tools/bin there is 
sdkmanager
but after run above command it says:

`[INFO]:   Will compile for the following archs: armeabi
  [INFO]:    Getting Android API version from user argument
[ERROR]:   Could not find `android` or `sdkmanager` binaries in Android SDK. Exiting.
....` 

something like that happen when using buildozer and it cant find android-sdk (sdk location is mentioned in buildozer.spec)

whats the problem

*** I'm in a region that censored google services and buildozer cant download sdk - i have download it through proxy

thanks for any help

**Comment by inclement** [comment]
I'm not sure your folder structure is quite correct, can you post the contents of the folder `mnt/sda6/usr2/android/` (and also, should that have a leading `/`?)
