### ISSUE TITLE
Recipe for pyzmq ($25 bounty) [$25]

### ISSUE THREAD

**Issue by cfobel** [kivy/python-for-android#122]
Write a recipe for cross compilation of the Python ZeroMQ bindings module.﻿

$25 bounty on BountySource: https://www.bountysource.com/#issues/339347-recipe-for-pyzmq
##

**Comment by AndreMiras** [comment]
THaks @drowssaPdnAemanresU I'm closing.
@tito please claim your bounty, the issue was resolved by you in https://github.com/kivy/python-for-android/commit/7bcedd3f40e6f56c8679317e50c51de0b3c4496b
