### ISSUE TITLE
Didn't find any valid dependency graphs.

### ISSUE THREAD

**Issue by see01995** [kivy/python-for-android#1222]
version: Python 3.5.4,pythonforandroid0.6.0
commond:
p4a apk --private ./ --package=org.morningsun.kivy_flask --name "kivy_flask" --version 0.1 --bootstrap=webview --requirements=python3crystax,flask --sdk-dir /home/sun/android/android-sdk-20 --android_api 19  --ndk-dir /home/sun/android/crystax-ndk-10.3.2/ --ndk_version 10.3.2 --port=5000

log:
[INFO]:    Will compile for the following archs: armeabi
[INFO]:    Getting Android API version from user argument
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Getting NDK dir from from user argument
[INFO]:    Got NDK version from from user argument
[INFO]:    Using Crystax NDK 10.3.2
[INFO]:    Found virtualenv at /usr/local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[ERROR]:   Didn't find any valid dependency graphs.
[ERROR]:   This means that some of your requirements pull in conflicting dependencies.
[ERROR]:   Exiting

**Comment by JDevPy** [comment]
I'm with the same error.

**Comment by AndreMiras** [comment]
I'm closing in favor of the recently created #1253 
There's a pull request that might fix it, see in the linked ticket above. Please give it a try and let us know.

**Comment by JDevPy** [comment]
i don't quite understand what should be done.

**Comment by AndreMiras** [comment]
You can either use my python-for-android fork/branch or wait for it to be merged and run an p4a update.
It's probably easier to wait then. It should be merged by the end of the week hopefully

**Comment by JDevPy** [comment]
Ok!! Thank you..

Em ter, 11 de dez de 2018 06:43, Andre Miras <notifications@github.com
escreveu:

**Comment by JDevPy** [comment]
I've already make changes in the p4a code but the problem insists.

**Comment by JDevPy** [comment]
Do i have to change the __init__.pyc file as well?

**Comment by AndreMiras** [comment]
no need to touch the pyc files. I'll take a look later then

**Comment by JDevPy** [comment]
Ok!

Em ter, 11 de dez de 2018 12:13, Andre Miras <notifications@github.com
escreveu:

**Comment by caver456** [comment]
I just grabbed python-for-android 0.6.0 (via pip3 install python-for-android - that's the merged update you spoke of above, right?) but am still getting the error (using python3 (not crystax - should I be using python3crystax?) and kivy - nothing else for this test)

```
TomZen:/mnt/c/Users/caver/Documents/GitHub/buckshotApp> buildozer -v android debug | tee buildozer.log
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/tom/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool
# Install platform
# Run "/usr/bin/python3 -m pip install -q --user 'appdirs' 'colorama>=0.3.3' 'jinja2' 'six'"
# Cwd None
# Apache ANT found at /home/tom/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/tom/.buildozer/android/platform/android-sdk-20
# Android NDK found at /home/tom/.buildozer/android/platform/android-ndk-r9c
# Check application requirements
# Check garden requirements
# Compile platform
# Run '/usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=buckshotApp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/mnt/c/Users/caver/Documents/GitHub/buckshotApp/.buildozer/android/platform/build"'
# Cwd /mnt/c/Users/caver/Documents/GitHub/buckshotApp/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (19)
[INFO]:    Requested API target 19 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Google NDK r9c
[INFO]:    Found virtualenv at /home/tom/.local/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.6', '4.8', 'clang3.3']
[INFO]:    Picking the latest gcc toolchain, here 4.8
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[ERROR]:   Didn't find any valid dependency graphs.
[ERROR]:   This means that some of your requirements pull in conflicting dependencies.
[ERROR]:   Exiting.
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=buckshotApp --bootstrap=sdl2 --requirements=python3,kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir="/mnt/c/Users/caver/Documents/GitHub/buckshotApp/.buildozer/android/platform/build"
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
TomZen:/mnt/c/Users/caver/Documents/GitHub/buckshotApp>
```

**Comment by AndreMiras** [comment]
It should be p4a master not `0.6.0` so delete your `.buildozer/android/platform/python-for-android-new-toolchain/` directory and set `p4a.branch = master` in your `buildozer.spec` before running your `buildozer android update` again.
You'll get better help on Discord `#support` channel

**Comment by caver456** [comment]
Thanks for the quick and complete response!  That worked to get past the
dependency graph error.

**Comment by allaboutmikey** [comment]
> It should be p4a master not `0.6.0` so delete your `.buildozer/android/platform/python-for-android-new-toolchain/` directory and set `p4a.branch = master` in your `buildozer.spec` before running your `buildozer android update` again.
<tries it>
<it works>
<tears of joy start flowing> I can't tell you how much frustration I've felt over the last months and even years. I've never been able to figure out how to get python3 working with buildozer. I tried crystax in the past with no luck. Gave up on it for 12 months or more.
Recently, I took it up again. I've been hammering at this for a solid week since I read that p4a can do python3 properly now. 
I tried containers, vms, real machines; none of them would even try to compile the distribution because it seemed that python3 was still not allowable as a requirement. Every time I put it in, I'd get the no valid dependancy graph problem. I don't ever recall reading that I needed to set p4a.branch to master, but as soon as I did, it built the distribution, which is further than I've ever got before.
Here's hoping the rest of the steps don't kill me!

**Comment by caver456** [comment]
Another 'valid dependency graph' issue: seems like some modules will allow a valid dependency graph to be built, and others will break it - if I have python3, kivy, and parse, it is all good; when I add the 'regex' module to the requirements list it has the same 'Didn't find any valid dependency graphs.' message.  Is there a way to tell what modules work and what modules cause it to fail?  Or am I misinterpreting?

**Comment by fr3nzy** [comment]
@allaboutmikey did you get buildozer running with python 3? I managed to get it running myself using the crystax ndk, and using with the p4a command. If you're having some trouble, I might be able to help you out :)

**Comment by mahomahomaho** [comment]
check if some module has ['python2', 'python3crystax'] reqs
if yes, then extend it by 'python3'

I had the same with cython (which doesn't build BTW with py3)

**Comment by allaboutmikey** [comment]
Seems like the master branch has fixed my dependency graph issues. It's a pity the official vm is so out of date. I couldn't follow the instructions regarding using the right versions of SDK/NDK/etc for python3 without an enormous amount of pain and updates. It'd be nice if there was a pre-built vm that actually worked with python3.

Next hurdle is pymssql, but I'm not holding out much hope there as it apparently needs a recipe, which noone else seems to want and I'm not sure if I'm up to creating. I've no real idea what they even do!

I've been away from the computer over christmas, but I'll have another go in the next few days and @fr3nzy, I'll certainly ask for help if I need it. Thanks.

**Comment by caver456** [comment]
Switching to the master branch got me past that issue too.  I've since run
into the same dependency graph issue a few more times after adding another
item to 'requirements'.  I'm still pretty new to this structure, but I took
these notes that seem to be the general method to address it - if someone
else can correct/clarify these notes that would be great:

in linux, look in
~/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/recipes
- dirs here have __init__.py files that specify what modules are
prerequisites.  The error happens when one of the specified prerequisites
does not exist - try deleting that directory under recipes and adding
appropriate replacement modules to buildozer.spec ‘requirements’.  For
example, see
https://github.com/kivy/python-for-android/issues/1072#issuecomment-379770443

**Comment by allaboutmikey** [comment]
> @allaboutmikey did you get buildozer running with python 3? I managed to get it running myself using the crystax ndk, and using with the p4a command. If you're having some trouble, I might be able to help you out :)
@fr3nzy Thanks for the offer. I figure this is not really relevant to the original post as I am past that problem now. I've opened a new issue:
https://github.com/kivy/python-for-android/issues/1564
Happy to get any help I can over there. Thanks.
