### ISSUE TITLE
TextInput display text only when suggestion validate on Asus ZenPhone3

### ISSUE THREAD

**Issue by khertan** [kivy/python-for-android#1227]
TextInput display text only when suggestion validate with enter or space on Asus ZenPhone3. even with keyboard_suggestions: False.

Oups should probably be an Kivy issues ...

**Comment by inclement** [comment]
Thanks for the report. It's actually the same root problem as https://github.com/kivy/python-for-android/issues/1102, so I'll close it in favour of that, but I'll add your device details there.
