### ISSUE TITLE
Testing/Enabling armeabi-v7a

### ISSUE THREAD

**Issue by bob-the-hamster** [kivy/python-for-android#123]
Currently, python-for-android compiles for armeabi but not for armeabi-v7a

According to this page, armeabi-v7 allows better performance because it can use the FPU
http://stackoverflow.com/questions/7080525/why-use-armeabi-v7a-code-over-armeabi-code

distribute.sh already has support for compiling for armeabi-v7a, but it is commented out. I uncommented and tested it with my game, and it seemed to work great. I have not yet done any profiling to figure out how much (if at all) faster it is.

Would it be best to compile for both? Or to add a command line option to pick between building for one or the other or both?

**Comment by inclement** [comment]
The new toolchain has an arch toggle and supports both (plux x86 etc).

**Comment by ZhangKuixun** [comment]
@bob-the-hamster I have same question. How do you build other versions of ABI？
