### ISSUE TITLE
WebView.setWebContentsDebuggingEnabled

### ISSUE THREAD

**Issue by primaeval** [kivy/python-for-android#1240]
I'm trying to debug a p4a webview Flask app. If you set  WebView.setWebContentsDebuggingEnabled(true) somewhere in the code it is supposed to enable Chrome browser debugging.
Here is an example of how it should work:
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews
and a code example of how to enable it
https://github.com/nshmura/android-rss-reader/blob/4a22cc090f108c6535aca4ddad5a994ce7649cea/app/src/main/java/com/nshmura/feed/presentation/util/WebViewUtil.java

I have tried adding it in a couple of places such as /build/src/org/kivy/android/PythonService.java but nothing appears in Chrome chrome://inspect

**Comment by primaeval** [comment]
I've got a workaround so far by opening a Chrome Browser on the android device at http://localhost:5000 and then opening Chrome on my local machine and going to chrome://inspect to remotely link to the device Chrome tab.

**Comment by inclement** [comment]
Closing as not an active issue, although it's convenient to know.
