### ISSUE TITLE
Custom Recipes For Pandas, Matplotlib and Statsmodels

### ISSUE THREAD

**Issue by seantmcmahon** [kivy/python-for-android#1241]
Hi,

I'm trying to create a Kivy app using numpy, pandas and matplotlib to be able to view and analyse a data set. I see that python-for-android doesn't have recipes for pandas, matplotlib or statsmodels so I will have to create these myself. I've read the article on [how to create your own recipe](http://python-for-android.readthedocs.io/en/latest/recipes/) but I don't know much about how to know if a module requires patches and what these patches should do, and what I may need to do in each of the three build methods.

Has anyone written their own custom recipes for any of these that they could share? Is there a kind of trial and error way to create one by viewing error and writing patches? Or would someone be able to help with what I would need to place in the recipe. 

I'm running buildozer on ubuntu 16.04 and have switched python-for-android to the fix-numpy branch.

Thanks in advance for any help.

**Comment by kuparez** [comment]
@seantmcmahon Were you successful in finding solution?

**Comment by AntoniRomera** [comment]
@seantmcmahon  Any solution?

**Comment by inclement** [comment]
Closing as not an active issue, it would be great to have recipes for these but we aren't dedicating any special effort to it.
