### ISSUE TITLE
openSSL recipe uses system-wide headers; app fails to run: cannot locate symbol EC_curve_nist2nid

### ISSUE THREAD

**Issue by Fak3** [kivy/python-for-android#1243]
If app was built with `openssl` recipe, and you have system-wide openssl devel package installed, resulting apk fails to run:
```
dlopen failed: cannot locate symbol "EC_curve_nist2nid" referenced by "libssl1.0.2h.so"
```
If system-wide openssl headers are removed, and app is rebuilt - it works just fine.

**Comment by inclement** [comment]
Thanks for the report. Is this with Linux, and what distro?

**Comment by Fak3** [comment]
I was building on openSUSE tumbleweed with system-wide libopenssl-devel 1.0.2l

**Comment by inclement** [comment]
I believe this is currently working, after all the openssl-related recipe changes recently.
