### ISSUE TITLE
Confusing / Outdated Bootstraps

### ISSUE THREAD

**Issue by famecastle** [kivy/python-for-android#1244]
I am trying to create a new bootstrap for a webview since the old one does not work anymore. So I copied the sdl2 gradle bootstrap. I adjusted it a bit and removed some lines of code. It's almost working except the fact that for some reason I can't figure out, this error happens: 
```
java.lang.UnsatisfiedLinkError: No implementation found for int org.kivy.android.PythonActivity.nativeInit(java.lang.Object) (tried Java_org_kivy_android_PythonActivity_nativeInit and Java_org_kivy_android_PythonActivity_nativeInit__Ljava_lang_Object_2)
E/AndroidRuntime(11788): 	at org.kivy.android.PythonActivity.nativeInit(Native Method)
E/AndroidRuntime(11788): 	at org.kivy.android.PythonMain.run(PythonActivity.java:527)
E/AndroidRuntime(11788): 	at java.lang.Thread.run(Thread.java:818)
```

I am not an expert but it seems to me that a nativeInit implementation in `C` language is missing. However I none of the bootstraps (including the original sdl2 bootstrap) I found a declaration of `nativeInit` in C. Where do I find the nativeInit C function? Where should it be declared? Why could it be excluded? Logcat says that it loaded any libraries (main, sdl, python2.7) except python3.5m (since I did not compile with Python 3) -> so this looks fine. However a C function for nativeInit seems to be missing.

**Comment by inclement** [comment]
> I am trying to create a new bootstrap for a webview since the old one does not work anymore.

What's wrong with it, and why not try to fix it instead of duplicating the original work?

> However I none of the bootstraps (including the original sdl2 bootstrap) I found a declaration of nativeInit in C. Where do I find the nativeInit C function? Where should it be declared?

For the SDL2 bootstrap, it's defined in SDL2 (in `src/main/android/SDL_android_main.c` if you get the code). For the webview bootstrap, it *is* declared in the code, and can be found [here](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/webview/build/jni/src/start.c#L333).
