### ISSUE TITLE
Didn't find any valid dependency graphs. - Flask and websocket-client

### ISSUE THREAD

**Issue by feelfreelinux** [kivy/python-for-android#1253]
In my app I use both flask and websocket-client. However, when i try to add both of these dependencies to my app, p4a fails. However, when I build my app only with `flask`, or only with `websocket-client` p4a works correctly.
```
p4a apk --private /home/user/sample/ --package=samplepackage --name="Sample app" --version 0.1 --bootstrap=sdl2 --requirements=python2,websocket-client,flask
[ERROR]:   Didn't find any valid dependency graphs.
[ERROR]:   This means that some of your requirements pull in conflicting dependencies.
[ERROR]:   Exiting.```

**Comment by inclement** [comment]
Assuming websocket-client doesn't really depend on Kivy, the issue is in Kivy being listed in [its requirements](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/websocket-client/__init__.py#L25).

**Comment by JonasT** [comment]
I just checked here https://github.com/debauchery1st/websocket-client and it doesn't seem to be related to kivy in any obvious way. So it looks like it might just be an accident...?

**Comment by AndreMiras** [comment]
Well this is actually nastier than it looks https://github.com/debauchery1st/websocket-client/commit/29b91ee2b24d2138124daf77e1de0ebbbd466661
So basically it looks like the recipe links to a fork that hacked in kivy logging.
The funny thing is it was forked without making it obvious, but I'm assuming the original repository is that one https://github.com/websocket-client/websocket-client
I'll make a PR to fix all of that
