### ISSUE TITLE
Prebuilt python does not contain binaries for any architecture.

### ISSUE THREAD

**Issue by Abysselene** [kivy/python-for-android#1254]
Hello, I have a problem and I can't find a solution on internet BUT I may have found why I got this problem and wish to know your thoughts.

First I explain shortly what I'm doing and why:
I need to build a python/kivy app for android with ssl activated and python3.
To make my app I followed the kivy guide and installed crystax Ndk but their version of python has not been built after ssl so even if I add openssl as a requirement it still doesn't exists in python.

I found on a forum someone saying that the last non official versions of crystax https://dl.crystax.net/ have ssl integrated so I gave it a try.
Unfortunately I always get the error : 
```
[INFO]:    # Building recipes
[INFO]:    Building hostpython3crystax for armeabi-v7a
[INFO]:    Building openssl for armeabi-v7a
[INFO]:    -> directory context /media/axel/reste/buildozer/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a/openssl
[INFO]:    -> running perl Configure shared no-dso no-krb5 android-armv7
           working: *** Because of configuration changes, you MUST do the following before                 [INFO]:    Applying patch disable-sover.patch                                
[INFO]:    -> running patch -t -d /media/axel/reste/buildozer/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a/openssl -p1 -i /media/...(and 134 more)
[INFO]:    Applying patch rename-shared-lib.patch
[INFO]:    -> running patch -t -d /media/axel/reste/buildozer/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a/openssl -p1 -i /media/...(and 138 more)
[INFO]:    -> running make build_libs                                                                                                                                                   
           working: make[3]: Leaving directory '/media/axel/reste/buildoz[INFO]:    -> running cp libssl1.0.2h.so libcrypto1.0.2h.so /media/axel/reste/buildozer/.buildozer/android/platform/build/build/libs_collections/medmanip/armeabi-v7a
[INFO]:    <- directory context /media/axel/reste/buildozer/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building python3crystax for armeabi-v7a
[ERROR]:   The prebuilt Python for version 3.5 does not contain binaries for your chosen architecture "armeabi-v7a".
```

I need armeabi-v7a for my phone but whatever I was frustrated to have nothing working and decided to try the other archs.
I have the same error for each arch as if none was present. I looked for the error on internet and found this page:
https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/python3crystax/__init__.py
and if we look how the code searches for the archs, it goes to
`crystax-ndk-10.3.2/sources/python/3.5/libs`
but in the beta versions of crystax I can see that it's different, the folders are in
`crystax-ndk-10.3.2/sources/python/3.5/shared`
If I compare the android.mk of those 2 versions, the offi and the beta we can see the difference:
Offi:
```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := python_shared
LOCAL_SRC_FILES := libs/$(TARGET_ARCH_ABI)/libpython3.5m.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include/python
include $(PREBUILT_SHARED_LIBRARY)
```
Beta:
```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := python_shared
LOCAL_SRC_FILES := shared/$(TARGET_ARCH_ABI)/libs/libpython3.5m.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include/python
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := python_static
LOCAL_SRC_FILES := static/libs/$(TARGET_ARCH_ABI)/libpython3.5m.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include/python
include $(PREBUILT_STATIC_LIBRARY)
```

For now I intend to give it a try by moving the files and renaming folders in the beta version to get it to build but I was wondering if there is somewhere a p4a version which works with this different structure when looking for an architecture given python3.5 binaries, I found nothing yet.
Maybe it could be interesting to edit the `__init__.py` file to have it looking for an other structure/other folders if it doesn't find what it's looking for?

I'm looking for your thoughts about this problem.

**Comment by inclement** [comment]
So the actual issue is that you're using a beta crystax NDK whose folder structure is different to the released version, and is not understood by p4a?

**Comment by Abysselene** [comment]
Yep, the last non beta release of crystax ndk (10.3.2) date is august 2016 and doesn't support ssl with python3.
Here someone says to use the last one available which was the 10.3.2 b919 if I compare the post date and the last one available at that date. https://github.com/crystax/android-platform-ndk/issues/19

Honestly I'm kind of lost, I'm not even sure if I should post here.
I'm trying to find a way to have kivy works with python3 and ssl but it seems it necessitates a beta of crystax and I don't know why but they changed the folder structure and since I didn't find anything in the p4a source code indicating a verification of the structure I wonder if it will be done or are beta releases of crystax ignored?

**Comment by inclement** [comment]
python-for-android does not currently support the beta versions of the crystax NDK, although it probably wouldn't be hard to add this support.

There's a PR at https://github.com/kivy/python-for-android/pull/1195 that adds openssl for python3 by building it ourselves.

**Comment by Abysselene** [comment]
I saw this one and thought I would try it if the rest doesn't work.
Thanks for the tip, now I know what to do :-)

By the way, if someone wonders what happens when reorganizing the structure folder of b919 to have it working with p4a when building python3.5. The building seems to work, the app is made and launched on the phone but it crashes with a fatal signal 11 sigsegv error, it seems sdl2 has a problem, maybe an other bootstrap like pygame could work, I didn't try.

**Comment by nayarlabs** [comment]
@Abysselene could you elaborate on the 3 files that needed modification. Thanks in advance.

**Comment by Abysselene** [comment]
Yes, I didn't do it neatly by pulling this or that because there were few changes and I was afraid to mess with git commands so what I did is this:
I used the latest official crystax ndk 10.3.2
About buildozer.spec I have:
`requirements = python3crystax,kivy, openssl`
then it will automatically download the latest stable branch in a subfolder /.buildozer/android/platform/python-for-android-new-toolchain when building
Once done on the prompt you can interrupt the build, it's no use to let it continue. I copied the new toolchain directory to an other location and edited buildozer.spec accordingly:
`p4a.source_dir = /whatever/buildozer/p4aCustom/python-for-android-new-toolchain_modded`
The in this copy I changed the 3 files to have them this way : https://github.com/kivy/python-for-android/pull/1195/files
So there are 2 init files to edit and patch_python3.6.patch to add but I doubt the patch file is needed, maybe it's only useful if you have the last master or stable branch.
Now you can build and it will use the modded p4a which is able to add ssl when building python 3+
