### ISSUE TITLE
Buildozer command failed 

### ISSUE THREAD

**Issue by ritesshguptaa** [kivy/python-for-android#1258]
I ran following command on buildozer -v android debug on Ubuntu 16.04 and Kivy 1.8.0 code build on python 3.6

it stops in between and gave following error 

Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=EasyHome --bootstrap=sdl2 --requirements=kivy --arch armeabi-v7a --copy-libs --color=always --storage-dir=/mnt/c/UbuntuPython/.buildozer/android/platform/build

**Comment by kuzeyron** [comment]
The buildozer.spec should look like this:
```
		requirements = python3crystax, kivy
		android.ndk_path = /home/user/.buildozer/crystax-ndk-10.3.2
```

**Comment by ritesshguptaa** [comment]
python3Crystax is 3 rd party

**Comment by AndreMiras** [comment]
@ritesshguptaa I would suggest you to increase the log level from `buildozer.spec` -> `log_level = 2` and share a more detailed error output.
Also why using such an old version of Kivy? I would recommend to use at least `Kivy==1.10.0` if not master. And by the way, good luck with Python 3.6. I could make it work on Ubuntu 18.04, but I think the team played more with Python 3.5 so far, so perhaps you should stick with it for now.
