### ISSUE TITLE
When the apk is turned on it gives me an error in the hashlib python3.6

### ISSUE THREAD

**Issue by AntoniRomera** [kivy/python-for-android#1260]
I created the apk with buildozer and when I turn it on my device it gives me a hashlib error that does not recognize the hash type...

I use python3.6, with python_crystax
In ubuntu 16.04

`I/python  ( 3589): ERROR:root:code for hash blake2b was not found.
I/python  ( 3589): Traceback (most recent call last):
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>
I/python  ( 3589):     globals()[__func_name] = __get_hash(__func_name)
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor
I/python  ( 3589):     raise ValueError('unsupported hash type ' + name)
I/python  ( 3589): ValueError: unsupported hash type blake2b
I/python  ( 3589): ERROR:root:code for hash blake2s was not found.
I/python  ( 3589): Traceback (most recent call last):
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>
I/python  ( 3589):     globals()[__func_name] = __get_hash(__func_name)
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor
I/python  ( 3589):     raise ValueError('unsupported hash type ' + name)
I/python  ( 3589): ValueError: unsupported hash type blake2s
I/python  ( 3589): ERROR:root:code for hash sha3_224 was not found.
I/python  ( 3589): Traceback (most recent call last):
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>
I/python  ( 3589):     globals()[__func_name] = __get_hash(__func_name)
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor
I/python  ( 3589):     raise ValueError('unsupported hash type ' + name)
I/python  ( 3589): ValueError: unsupported hash type sha3_224
I/python  ( 3589): ERROR:root:code for hash sha3_256 was not found.
I/python  ( 3589): Traceback (most recent call last):
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>
I/python  ( 3589):     globals()[__func_name] = __get_hash(__func_name)
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor
I/python  ( 3589):     raise ValueError('unsupported hash type ' + name)
I/python  ( 3589): ValueError: unsupported hash type sha3_256
I/python  ( 3589): ERROR:root:code for hash sha3_384 was not found.
I/python  ( 3589): Traceback (most recent call last):
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>
I/python  ( 3589):     globals()[__func_name] = __get_hash(__func_name)
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor
I/python  ( 3589):     raise ValueError('unsupported hash type ' + name)
I/python  ( 3589): ValueError: unsupported hash type sha3_384
I/python  ( 3589): ERROR:root:code for hash sha3_512 was not found.
I/python  ( 3589): Traceback (most recent call last):
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>
I/python  ( 3589):     globals()[__func_name] = __get_hash(__func_name)
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor
I/python  ( 3589):     raise ValueError('unsupported hash type ' + name)
I/python  ( 3589): ValueError: unsupported hash type sha3_512
I/python  ( 3589): ERROR:root:code for hash shake_128 was not found.
I/python  ( 3589): Traceback (most recent call last):
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>
I/python  ( 3589):     globals()[__func_name] = __get_hash(__func_name)
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor
I/python  ( 3589):     raise ValueError('unsupported hash type ' + name)
I/python  ( 3589): ValueError: unsupported hash type shake_128
I/python  ( 3589): ERROR:root:code for hash shake_256 was not found.
I/python  ( 3589): Traceback (most recent call last):
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 243, in <module>
I/python  ( 3589):     globals()[__func_name] = __get_hash(__func_name)
I/python  ( 3589):   File "/data/data/org.astro.demo/files/app/crystax_python/stdlib.zip/hashlib.py", line 113, in __get_builtin_constructor
I/python  ( 3589):     raise ValueError('unsupported hash type ' + name)
I/python  ( 3589): ValueError: unsupported hash type shake_256
`

**Comment by karolyi** [comment]
+1

**Comment by inclement** [comment]
From https://github.com/Homebrew/legacy-homebrew/issues/21329 and https://github.com/Homebrew/legacy-homebrew/issues/22816 talking about macOS builds, I think this arises from openssl not being present. As far as I cant tell it doesn't actually cause any problems in itself. It will be interesting to see if https://github.com/kivy/python-for-android/pull/1217 prevents these errors from occurring.

**Comment by agilewalker** [comment]
Assuming you're using crystax-ndk-10.3.2, try this out:
Insert following lines into file crystax-ndk-10.3.2/build/tools/build-target-python.sh under line no. 642
`
#_hashlib
   if [ -n "$OPENSSL_HOME" ]; then
       local BUILDDIR_SSL="$BUILDDIR/ssl"
       local OBJDIR_SSL="$BUILDDIR_SSL/obj/local/$ABI"

       run mkdir -p "$BUILDDIR_SSL/jni"
       fail_panic "Can't create directory: $BUILDDIR_SSL/jni"

       {
           echo 'LOCAL_PATH := $(call my-dir)'
           echo 'include $(CLEAR_VARS)'
           echo 'LOCAL_MODULE := _hashlib'
           echo "MY_PYTHON_SRC_ROOT := $PYTHON_SRCDIR"
           echo 'LOCAL_SRC_FILES := \'
           echo '  $(MY_PYTHON_SRC_ROOT)/Modules/_hashopenssl.c'
           echo 'LOCAL_STATIC_LIBRARIES := python_shared openssl_static opencrypto_static'
           echo 'include $(BUILD_SHARED_LIBRARY)'
           echo "\$(call import-module,python/$PYTHON_ABI)"
           echo "\$(call import-module,$OPENSSL_HOME)"
       } >$BUILDDIR_SSL/jni/Android.mk
       fail_panic "Can't generate $BUILDDIR_SSL/jni/Android.mk"

       run $NDK_DIR/ndk-build -C $BUILDDIR_SSL -j$NUM_JOBS APP_ABI=$ABI V=1
       fail_panic "Can't build python$PYTHON_ABI-$ABI module '_hashlib'"

       log "Install python$PYTHON_ABI-$ABI module '_hashlib' in $PYBIN_INSTALLDIR_MODULES"
       run cp -p -T $OBJDIR_SSL/lib_hashlib.so $PYBIN_INSTALLDIR_MODULES/_hashlib.so
       fail_panic "Can't install python$PYTHON_ABI-$ABI module '_hashlib' in $PYBIN_INSTALLDIR_MODULES"
   fi
`

**Comment by AntoniRomera** [comment]
It's solved by patch openssl

**Comment by karolyi** [comment]
is it released?

**Comment by AntoniRomera** [comment]
no
