### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [kivy/python-for-android#1264]
Can i submit my design ?

**Comment by loydjayme25** [comment]
How about this ?
I am open for any suggestions

![proposals](https://user-images.githubusercontent.com/37318022/39958418-134c86a4-5635-11e8-9f05-04924c0ea26c.png)

**Comment by loydjayme25** [comment]
Or pick any of the two designs 

![proposals](https://user-images.githubusercontent.com/37318022/39958720-74d834fa-5639-11e8-99b4-31b0a570e4b3.png)

**Comment by loydjayme25** [comment]
![proposals](https://user-images.githubusercontent.com/37318022/40242944-9c9fcca2-5af1-11e8-83ea-ab1acbafcb7c.png)

**Comment by Julian-O** [comment]
Thanks for the proposal.

Closing as there are no plans to introduce a non-Kivy-related Logo. This should be considered if there ever are plans.
