### ISSUE TITLE
SDL Error: ... could not load library "libpython2.7.so" ... on Android 4.2.2

### ISSUE THREAD

**Issue by EinExperte** [kivy/python-for-android#1290]
Hi folks,

today I finally managed to produce my first apk using the latest p4a code from the master branch ...

`pip install git+https://github.com/kivy/python-for-android.git`
(I ran into a lot of problems with the `pip install python-for-android` variant)

... and I was happy to install it on my Fairphone 1 (Android 4.2.2) ... just to see it crash on startup :-(
A popup tells me:

> SDL Error
> 
> An Error occured while trying to start the application. Please try again and/or reinstall.
> 
> Error: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libpython2.7.so" needed by "libmain.so"; caused by find_library(linker.cpp:889): "libpython2.7.so" failed to load previously
>
> Exit

(Typos possible, I copied by hand)

The same apk works fine (or at least does not crash) on a newer device (Android 7.0).

I built with the following command:
`p4a apk --private $HOME/temp/tjapp --package=org.example.taskjuggler --name "Task Juggler" --version 0.3 --bootstrap=sdl2 --requirements=python2,kivy --dist_name=tjapp`

API Version: 16
NDK Version: r10e-rc4
Build-Tools Version: 26.0.2

Any advice?

Thanks,
Christoph

**Comment by clevermindgames** [comment]
I have spent several hours last night with exactly the same problem. I am using p4a via buildozer though.
My knowledge is very limited in the subject but hope my experience could be usefull to you until a proper fix is developed: in the end I was able to run my APK on Android 4.x by specifying android.sdk = 24, leaving all other parameters to their default values (such as target API, NDK etc). All other combinations resulted in various crashes from PythonUtil.java, which I also tried to modify with no success and finally reverted to the current master branch version.

**Comment by AndreMiras** [comment]
I think I also so that on Android 4. Reported in different places:

- https://github.com/AndreMiras/PyWallet/issues/98 
- https://github.com/HelloZeroNet/ZeroNet-kivy/issues/10
- https://groups.google.com/forum/#!topic/kivy-users/lkrolZjym0Y

**Comment by homdx** [comment]
Maybe it's fixed?
https://github.com/kivy/python-for-android/issues/1501

**Comment by JonasT** [comment]
Yea, should be fixed. I remember more tickets about this and pull requests that went in. I'll close it for now.

@EinExperte hope things will work for you now, let us know if you encounter any more problems!
