### ISSUE TITLE
"/data/user/0/org.gmail.gmail/files/app/libpymodules.so" not found

### ISSUE THREAD

**Issue by akshayaurora** [kivy/python-for-android#1309]
_From @farzinh on June 23, 2018 6:11_

 when I run my python code in buildozer there is not any problem , but when lanching apk, it crash.

it seems like this issue com from /libpymodules.so  but i don't know how can I add this
 
ImportError: dlopen failed: library "/data/user/0/org.gmail.gmail/files/app /libpymodules.so" not found
[apk_debug_log.txt](https://github.com/kivy/kivy/files/2129693/apk_debug_log.txt)
[log_level2.txt](https://github.com/kivy/kivy/files/2129694/log_level2.txt)

_Copied from original issue: kivy/kivy#5823_

**Comment by akshayaurora** [comment]
think this belongs in python-for-android

**Comment by froglenn** [comment]
I'm getting this error from Google Developer Console:

`10-12 04:50:15.649: I/python(12494): Android bootstrap done. __name__ is __main__
10-12 04:50:15.650: D/InteractionController(12494): clickNoSync (1108, 473)
10-12 04:50:15.673: I/python(12494): Opening libpymodules failed: dlopen failed: library "libpymodules.so" not found
10-12 04:50:15.693: I/python(12494): Traceback (most recent call last):
10-12 04:50:15.693: I/python(12494):   File "<string>", line 31, in <module>
10-12 04:50:15.694: I/python(12494):   File "/data/user/0/my.app/files/lib/python2.7/site-packages/pygame_sdl2/__init__.py", line 86, in <module>
10-12 04:50:15.694: I/python(12494):     from pygame_sdl2.error import *
10-12 04:50:15.694: I/python(12494): ImportError: dlopen failed: file offset for the library "/data/user/0/my.app/files/lib/python2.7/site-packages/pygame_sdl2/error.so" >= file size: 0 >= 0
10-12 04:50:15.694: I/python(12494): Run user program, change dir and execute main.py
`

**Comment by inclement** [comment]
Closing as we've moved away form using libpymodules.so, plus I think some issues with loading it were fixed anyway.
