### ISSUE TITLE
libpython2.7.so: is missing DT_SONAME using buildozer with latest VirtualBox VM for Android Buildozer (Version 2.0, released the 13 May 2017).

### ISSUE THREAD

**Issue by BillBridge** [kivy/python-for-android#1314]
I have setup a new VirtualBox VM for Android Buildozer (Version 2.0, released the 13 May 2017).
In this environment I wanted to build an APK for the KivyMD Kitchensink_demo (https://gitlab.com/kivymd/KivyMD) which runs fine on my Windows development environment and standalone build using PyInstaller.

The command: buildozer android debug produces an APK in the bin directory.
Running the APK on the device (Huawei P10) causes a crash and gives the following error log.

07-23 11:41:01.995 23581 23581 W linker  : /data/app/org.test.kivymd_kitchen_sink-1/lib/arm/libpython2.7.so: is missing DT_SONAME will use basename as a replacement: "libpython2.7.so"

07-23 11:41:02.001 23581 23581 W linker  : /data/data/org.test.kivymd_kitchen_sink/files/app/lib/python2.7/lib-dynload/_io.so: is missing DT_SONAME will use basename as a replacement: "_io.so"

07-23 11:41:02.003 23581 23581 W linker  : /data/data/org.test.kivymd_kitchen_sink/files/app/lib/python2.7/lib-dynload/unicodedata.so: is missing DT_SONAME will use basename as a replacement: "unicodedata.so"

07-23 11:41:02.005 23581 23581 W linker  : /data/data/org.test.kivymd_kitchen_sink/files/app/lib/python2.7/lib-dynload/_ctypes.so: is missing DT_SONAME will use basename as a replacement: "_ctypes.so"

**Comment by AndreMiras** [comment]
I think I've seen that before on Android 4. Which version are you running?

**Comment by BillBridge** [comment]
I am running Android Version 6.0

**Comment by BillBridge** [comment]
And this is the Buildozer.spec file:

`[app]

# (str) Title of your application
title = kivymd

# (str) Package name
package.name = kivymd_kitchen_sink

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
source.exclude_dirs = bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = kivy, hostpython2

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
requirements.source.kivymd = ../../kivymd

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
presplash.filename = %(source.dir)s/../../kivymd/images/kivymd_logo.png

# (str) Icon of the application
icon.filename = %(source.dir)s/../../kivymd/images/kivymd_logo.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = all

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
#osx.python_version = 3

# Kivy version to use
#osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (string) Presplash background color (for new android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (list) Permissions
#android.permissions = INTERNET

# (int) Android API to use
#android.api = 19

# (int) Minimum API required
#android.minapi = 9

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 9c

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = True

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (list) Android AAR archives to add (currently works only with sdl2_gradle
# bootstrap)
#android.add_aars =

# (list) Gradle dependencies to add (currently works only with sdl2_gradle
# bootstrap)
#android.gradle_dependencies =

# (str) python-for-android branch to use, defaults to stable
#p4a.branch = stable

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = armeabi-v7a

#
# Python for android (p4a) specific
#

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
`

**Comment by BillBridge** [comment]
Problem solved!
The crash is caused by the following statement:

import locale
locale.setlocale(category=locale.LC_ALL,locale="Dutch")

However, still might be an issue p4a?

**Comment by AndreMiras** [comment]
Thank you for sharing your findings, now I see that the logs you shared were only warnings ant not errors.
Yes it's still an issue and we should at least document the behaviour. The resolution could be to update the troubleshooting until we have a proper fix.
I didn't give it a try myself yet. But yes ideally we would have a simple scenario and the actual error message and stacktrace. We have the `locale.setlocale()` scenario, now I'd like the stack trace so we can document it.

**Comment by BillBridge** [comment]
I enclose the logcat. Search for:
07-23 11:41:03.630 23581 23612 I python  :    File "/home/kivy/Desktop/kivymd-test/demos/kitchen_sink/.buildozer/android/app/main.py", line 920, in <module>

07-23 11:41:03.631 23581 23612 I python  :    File "/home/kivy/Desktop/kivymd-test/demos/kitchen_sink/.buildozer/android/app/main.py", line 942, in KitchenSink

07-23 11:41:03.631 23581 23612 I python  :    File "/home/kivy/Desktop/kivymd-test/demos/kitchen_sink/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a/python2/python-install/lib/python2.7/locale.py", line 531, in setlocale

07-23 11:41:03.631 23581 23612 I python  :    File "/home/kivy/Desktop/kivymd-test/demos/kitchen_sink/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a/python2/python-install/lib/python2.7/locale.py", line 80, in setlocale

07-23 11:41:03.632 23581 23612 I python  :  ValueError: _locale emulation only supports "C" locale

07-23 11:41:03.681 23581 23612 I python  : Python for android ended.

[
[logcat.txt](https://github.com/kivy/python-for-android/files/2223349/logcat.txt)


](url)

**Comment by AndreMiras** [comment]
That's way better, thanks for the help!

**Comment by inclement** [comment]
Closing as not an issue, it doesn't seem to matter if this happens, and there seems to be no actual crash currently associated with it.
