### ISSUE TITLE
Crystax NDK size is larger than Android Studio + SDK + (regular) NDK + ... combined

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1319]
The extracted Crystax NDK size is larger than Android Studio + SDK + (regular) NDK + Emulator + SDK Tools combined. I literally can't use it right now because it doesn't seem to fit into the docker container on my system partition. Since it's not required for Python 2 either, isn't there a way you can get rid of this excessive requirement for Python 3 apps?

**Comment by inclement** [comment]
We have a general goal of getting a python3 build process working without Crystax, but there is not particular ETA for this.

You can probably safely delete sources/boost and sources/cxx-stl to save almost 4GB, and maybe some other things there as well, if it helps.

**Comment by JonasT** [comment]
No that doesn't help, because you can't do that before extracting it. Extracting it needs more than 15GB of disk space!

**Comment by AndreMiras** [comment]
Yes @JonasT  you can do that before extracting using the `--exclude` parameter of `tar` command, just like we do it in the Dockerfile:
https://github.com/kivy/python-for-android/blob/9bef536/Dockerfile#L60
