### ISSUE TITLE
Read & write to entire SD card is an unreasonable default permission for most games and basic UI applications

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1335]
Read & write to entire SD card is an unreasonable default permission for most games and basic UI applications. A game can easily just store savegames wherever it is supposed to store its own specific settings (other games do without sd card access just fine and offer savegames, so I assume this works) and a UI app that does whatever, maybe just provide a remote control UI for something, often will not need SD card access either.

Even for apps that have a good reason to write/read from anywhere, it makes a much more trustworthy impression to ask for this when an actual import/load/... button is pressed (where a user could even possibly decline), instead of just requiring this permission right from the start - which I assume is possible to do with `pyjnius`, at least in theory.

Therefore, I think `p4a` should be changed to package apps per default without this permissions. Also, until that happens, is there a way I can remove this permission manually?

**Comment by inclement** [comment]
I agree, there's already an issue about this [here](https://github.com/kivy/python-for-android/issues/1081).

**Comment by JonasT** [comment]
> You can edit the python-for-android code to remove the permission easily enough, for your own use.

Could you possibly add a switch for this? I don't check out python-for-android manually, I use a deployment script - so editing around in the source is something I'd rather avoid, because it complicates the deployment process that is already quite complicated...
