### ISSUE TITLE
python-for-android packages wrong manifest for ANDROIDAPI="19", doesn't include configChanges="...|screenSize" which leads to app crash on rotation

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1342]
python-for-android packages the wrong manifest for me for my specified ANDROIDAPI="19" version: the included `AndroidManifest.xml` specifies `android:configChanges="keyboardHidden|orientation` and missing "screenSize", which leads to app crash on rotation. When manually editing `/usr/local/lib/python3.6/dist-packages/pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml` to take out the conditional and hardcoding "screenSize" into the `android:configChanges=...` value, then it works. So it seems something is bugged with how that template is being handled.

To reproduce, try a `p4a` build line with `--requirements=python3crystax,pysdl2,sdl2 --orientation user --window` and any simple SDL2 code, e.g. the one in that comment here: https://github.com/kivy/python-for-android/issues/1338#issue-353901127

**Comment by shrugjam** [comment]
Should I just make a pull request to remove the condition in AndroidManifest.tmpl.xml? Because honestly, IMHO the already reasonably old API level 19 (and possibly more recent ones) failing so bad is a much bigger problem than that extremely ancient API level no longer working properly...

**Comment by JonasT** [comment]
This may or may not be caused by this issue: #1352 seems like in general, the whole handling of the minimum API version is just broken.

**Comment by JonasT** [comment]
Ok I am taking a wild guess here, but maybe this happens:

1. ANDROIDAPI="19" sets target API to 19, but doesn't change the minimum level
2. The minimum API appears to default to something low, maybe 12 or something even less, where `screenSize` in the manifest is not a valid option
3. With the API **target** level (not minimum level) 19, Android will possibly expect the app to set configChanges to include `screenSize` at runtime, but the p4a/kivy wrapper doesn't handle this at all. It probably assumes the manifest will take care of everything, which may not be possible with minlevel=`<superlow>` and targetlevel=19 in combination.

As a result, configChanges doesn't include `screenSize` when defining `ANDROIDAPI=19` and it crashes with `--orientation=user`. However, at no point p4a gives a warning about this, so this seems like a major oversight:

I suggest that either, 1. enabling orientation changes with that combination of minimum and target API level should just work, or 2. it should raise the minimum level automatically to something that works if it's not specified, or 3. `p4a` should abort with an error if that combination of target and minimum levels is used.

**Comment by JonasT** [comment]
Minimum target API level is 21 now so this is somewhat outdated / accidentally solved
