### ISSUE TITLE
build-tools below 25 will not add jars

### ISSUE THREAD

**Issue by zx013** [kivy/python-for-android#1345]
When I use build-tools below 25, buildozer will choose ant for build, but the android.add_jars option will not take effect. Then I check the code and found the reason. When I use android.add_jars option, jars will copy to src/main/libs but not the libs, so ant will not find the jars.

**Comment by AndreMiras** [comment]
can you tell if this is fixed via https://github.com/kivy/python-for-android/pull/1693 ?

**Comment by Julian-O** [comment]
@zx013: Still having the problem?
