### ISSUE TITLE
Bug or support request?

### ISSUE THREAD

**Issue by johnlarfour** [kivy/python-for-android#1346]
I post here but i don't know if is a bug or a support request. If it is not a bug I close this issue.
The problem is this: https://stackoverflow.com/questions/52058611/app-crash-with-kivy-and-bs4
I read on internet there are a lot of people there are this problem so, i don't know.
Sorry if I have not respected the rules

**Comment by inclement** [comment]
Closing as not really a bug, beautifulsoup4 needs a recipe but doesn't have one. It might work without one following @JonasT's recent additions though.

A beautifulsoup4 recipe would be welcome as a PR, but not something we are likely to dedicate any time to.
