### ISSUE TITLE
Fix/clean-up LDSHARED 

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#1360]
`LDSHARED` doesn't seem to be set in `PythonRecipe` leading to failing compilation in some scenarios.
The compilation may be failing because p4a would then pick up the system linker rather than the cross-compiler one.
For this reasons some recipes added that change in their `get_recipe_env()` method, like below:
```python
env['LDSHARED'] = env['CC'] + ' -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions'
```
As in last master commit 0dc7664 we have at least 17 of them:
```
$ grep -r "env\['LDSHARED'\] = env\['CC'\]" pythonforandroid/recipes/ | wc -l
17
```
 
In his PR JonasT tries to address it via `pythonforandroid/archs.py`, see https://github.com/kivy/python-for-android/pull/1357/files#diff-569e13021e33ced8b54385f55b49cbe6R115
This probably requires investigation to know where is the proper place to put it and then the pull request fixing it should also clean recipes overriding it in their `get_recipe_env()` method.

**Comment by JonasT** [comment]
By the way, similar issue: ```env['CFLAGS'] += ' -I{}/sources/python/{}/include/python/'.format(self.ctx.ndk_dir, self.ctx.python_recipe.version[0:3])```

Your greenlet recipe pull request does that, mine does, I've seen yet another do it - maybe this should be handled centrally as well?

**Comment by JonasT** [comment]
I added a pull request here: https://github.com/kivy/python-for-android/pull/1361 (still WIP, I'm building my app with it right now to see if things blow up)

**Comment by AndreMiras** [comment]
Even though https://github.com/kivy/python-for-android/pull/1361 is now merged, we still need to clean existing recipes to remove redundant `env['LDSHARED']` override before closing the issue.
I think it would be great to also verify everything is going OK at unit test level e.g. checking all recipes `get_recipe_env()` behaviour.
