### ISSUE TITLE
SSL/TLS is broken with Python 3: ImportError: missing module _ssl

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1372]
SSL/TLS is broken with Python 3: ImportError: missing module _ssl.

### Versions

* Python: python3crystax as needs to be used with p4a
* OS: docker image with Ubuntu LTS for building, ran on LineageOS 14.1
* Kivy: not used, p4a is git master from a few days ago
* Cython: not using cython

### Description

SSL/TLS breaks on import, gives `ImportError: missing module _ssl` - `openssl` as via the recipe is present and installed.

### buildozer.spec
not using bulldozer directly

### Logs

error happened in crystax_python/stdlib.zip/ssl.py line 98: `import ssl` -> `ImportError: No module named "_ssl"'

**Comment by AndreMiras** [comment]
Thanks for the clean/concise bug report. It's know and have some ongoing PR at least in https://github.com/kivy/python-for-android/pull/707, https://github.com/kivy/python-for-android/pull/1195 and https://github.com/kivy/python-for-android/pull/1217

**Comment by JonasT** [comment]
To anyone dropping by searching for TLS support:

- use `python3crystax` (until `python3` supports it, at least to my knowledge it doesn't yet)

- use this branch which is a continuously updated fork of python-for-android's bleeding edge master: https://github.com/JonasT/python-for-android/tree/tlsfix (I didn't create it myself, it's just #1217 on a branch I continuously rebase on p4a master to keep things working)

This should hopefully help other users out until p4a master finally supports TLS out of the box for python 3 applications.

**Comment by JonasT** [comment]
Now fixed on p4a master with regular `python3`, works out of the box!
