### ISSUE TITLE
error: kivy/graphics/texture.c: No such file or directory

### ISSUE THREAD

**Issue by nufe** [kivy/python-for-android#1384]
/mnt/h/MyPprjs# p4a apk --private ./ --package=org.example.myapp --name "My application" --version 0.1 --ndk-dir=/mnt/f/Software/crystax-ndk-10.3.2  --bootstrap=sdl2 --requirements=sdl2,python3crystax,kivy

building 'kivy.graphics.texture' extension
arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=19 -I/mnt/o/crystax-ndk-10.3.2/platforms/android-19/arch-arm -isysroot /mnt/o/crystax-ndk-10.3.2/platforms/android-19/arch-arm -I/root/.local/share/python-for-android/build/python-installs/unnamed_dist_34/include/python3.5 -DNDEBUG -g -fwrapv -O3 -Wall -I/mnt/o/crystax-ndk-10.3.2/sources/python/3.5/include/python -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=19 -I/mnt/o/crystax-ndk-10.3.2/platforms/android-19/arch-arm -isysroot /mnt/o/crystax-ndk-10.3.2/platforms/android-19/arch-arm -I/root/.local/share/python-for-android/build/python-installs/unnamed_dist_34/include/python3.5 -fPIC -Ikivy/include -Ikivy/include -I/usr/local/include/python3.7m -c kivy/graphics/texture.c -o build/temp.linux-x86_64-3.7/kivy/graphics/texture.o
arm-linux-androideabi-gcc: error: kivy/graphics/texture.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files

**Comment by nufe** [comment]
> On what version of p4a are you running? What operating system? Could you reply some of the important questions listed in the issue template?
> Is this all the log you're having or you cut some context? It seems rather small 🤔
> Also I don't recommend running it as root.

Sorry, it should be the reason for the Cython version.
pip3.5 install -I Cython==0.25.2

**Comment by inclement** [comment]
Closing as probably fixed, I didn't see anything like this recently.
