### ISSUE TITLE
Investigate Azure Pipelines

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#1400]
We're currently using Travis for continuous integration.
While things are working we have a very annoying issue, which is Travis not providing Docker layer caching, see https://github.com/travis-ci/travis-ci/issues/5358.
This means every single build will rebuild docker images from scratch ~15 minutes when it should take less than a minute if layer caching was properly implemented Travis side.
Other CI providers seem to provide solutions for it in their free tier, e.g. CircleCI, GitLab Pipelines, Azure Pipelines...
Apparently Azure also seems to provide up to 10 parallel builds when Travis offers 5.
Find out more https://azure.microsoft.com/en-us/services/devops/pipelines/
The goal of this task is to investigate and try at least other competitors to see how they perform compared to Travis in our environment.

**Comment by AndreMiras** [comment]
I already gave a try to Azure Pipeline in a branch of my fork. While the integration was pretty straight forward and parallel jobs are great (https://github.com/AndreMiras/python-for-android/pull/1), I didn't see any caching of previous builds. See build https://dev.azure.com/andremiras/andremiras/_build/results?buildId=14&view=logs
Since the agent seems to get provisioned every time from scratch cached images don't seem to be reusable.
Sources:
- https://github.com/Microsoft/vsts-tasks/issues/6439
- https://medium.com/@marcodesanctis2/a-build-and-release-pipeline-in-vsts-for-docker-and-azure-kubernetes-service-aks-41efc9a0c5c4

**Comment by misl6** [comment]
I guess that we're now fine with Github Actions and we can close this issue?

**Comment by AndreMiras** [comment]
Completely, thanks for the heads up, closing
