### ISSUE TITLE
pyjnius really should be version pinned.

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1415]
### Versions
latest git master of p4a, no matter what python/cython/kivy used

### Description

pyjnius isn't version pinned: 

https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/pyjnius/__init__.py#L10

This means even if I stay at a fixed commit of p4a master, I don't get reproducible builds and if someone breaks stuff in pyjnius like **right now** -> #1414 I might be stuck not being able to do a simple deployment of my application unless I happened to keep a previous full system image with a working combination of things.

This is bad for such a core component. If I stick on a p4a master at least all the core things should be guaranteed to work, because manually meddling around in recipes just to get back to an older version of e.g. pyjnius in an automated build chain is pretty annoying to do.

*Even if nobody ever tests the pin and the pin is updated to a broken version, this is a lot better than no pin.* (because in that case, everyone can just go back with their main p4a master clone, which is easy, instead of patching inside the recipes folder during the build to avoid broken pyjnius, which is hard and annoying.)

### buildozer.spec
not relevant
### Logs

not relevant

**Comment by JonasT** [comment]
Closing since it appears to be pinned now!

**Comment by KeyWeeUsr** [comment]
Ref https://github.com/kivy/python-for-android/pull/1426.
