### ISSUE TITLE
Python 3 recipe follow up issues

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1455]
The new Python 3 recipe (#1412) is in a fully working state, but there are a few important follow up issues to work through now:

- [x] Make python3 recipe use p4a's arch system as much as possible, including making p4a understand clang toolchains (and ideally at the same time try using clang for other recipes)
- [x] openssl recipe compatibilty
- [x] sqlite recipe compatibility
- [x] Fully optimize the zipped distribution size by removing unnecessary things (and making this customisable?)
- [x] Make the python3 build include ctypes, not sure why it doesn't build right now as it did in bpo-30386 #1465
- [x] Get a python3 CI test working #1456

**Comment by pmp-p** [comment]
>     * [ ]  Make the python3 build include ctypes, not sure why it doesn't build right now as it did in bpo-30386

setup.py won't always detect libffi of target when cross compiling, but now python3.7 - unlike the bpo - *need* a system ffi to build ctypes.

cf: https://bugs.python.org/issue31710

**Comment by pmp-p** [comment]
maybe a bug, i found that when using a python host 3.7.1+ ( some distributions have started shipping it ) 
the jinja2 from ./pythonforandroid/bootstraps/pygame/build/buildlib/jinja2.egg is seriously updated ( 3 errors due to py3 )

**Comment by inclement** [comment]
@pmp-p Thanks for the note, the pygame bootstrap is deprecated and has many issues like this, we may look to just remove it soon.

**Comment by inclement** [comment]
Follow up issues essentially complete thanks to various contributors :)
