### ISSUE TITLE
GC deadlock on subprocess

### ISSUE THREAD

**Issue by marecik16** [kivy/python-for-android#1461]
Hello community! Can you help me?
I have a strange problem with Python for Android and I have short demo

```python
from jnius import autoclass

import os
import signal
import multiprocessing
import time

def process():
    Runtime = autoclass("java.lang.Runtime")
    print("Starting GC...")
    Runtime.getRuntime().gc()
    print("GC done.")

print("STARTED")
while True:
    newProcess = multiprocessing.Process(target=process)
    newProcess.start()
    time.sleep(1)
    
    if newProcess.is_alive():
        print("      GC DEADLOCK!!!!????????")
        pid = newProcess.pid
        os.kill(pid, signal.SIGKILL)
    newProcess.join()
```
basically if I started a new python subprocess, then SOMETIMES the garbage collector freezes inside.
You can change the sleeping time in the above code and a result would be the same - some of the subprocesses never return from GC.
Tested with the new version of p4a & jnius, bootstrap=sdl2, python3crystax, arch=armeabi-v7a and a three complete different smartphones with Android 6/7/8

**Comment by marecik16** [comment]
Well, can you at least confirm my problem at your device?

**Comment by tito** [comment]
Android doesn't like any kind of fork. At least that was the case before, dunno if it has evolved since.
If you do Android, then go services and communicate between your app / services, don't use multiprocessing.

I never though to write or think that a such example would work :)
