### ISSUE TITLE
working: make: *** [Makefile:426: sharedmods] Error 139 

### ISSUE THREAD

**Issue by cTas0099** [kivy/python-for-android#1474]
hello, I did not find the answer to this problem. 
in #1297 the same problem, but there is no explicit solution

### Versions

* Python:3.7.1
* OS: Archlinux
* Kivy: 1.10.1
* python for android: 0.6.0

### Description

Command:
```sh
[user@revenge ~]$ p4a apk --private main4.py --name "Main4Kivy" --version 0.1 --bootstrap=sdl2 --requirements=kivy --debug
```

### Error

```
[DEBUG]:   	make: *** [Makefile:426: sharedmods] Error 139
Exception in thread background thread for pid 31600:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/make -j5

  STDOUT:
gcc -pthread -c -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -o Modules/config.o Modules/config.c
gcc -pthread -c -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes  -I. -IInclude -I./Include   -DPy_BUILD_CORE -DPYTHONPATH='":plat-linux4:lib-tk:lib-old"' \
	-DPREFIX='"/usr/local"' \
	-DEXEC_PREFIX='"/usr/local"' \
	-DVERSION='"2.7"' \
	-DVPATH='""' \
	-o Modules/getpath.o ./Modules/getpath.c


```

**Comment by tito** [comment]
It's explained here: https://github.com/kivy/python-for-android/issues/1297#issuecomment-418292032

Try using python3 recipes in your requirements. Or use a previous compiler. Or contribute to have Python2 recipes using 2.7.15 with all updates cross-platform patches.

**Comment by tito** [comment]
Actually, somebody is working for 2.7.15: https://github.com/kivy/python-for-android/pull/1460

**Comment by AndreMiras** [comment]
Basically you need to switch to Python3 or wait for the 2.7.15 PR to be merged, or else use @opacam fork directly.
If you have more questions, give it a try on Discord `#support` channel

**Comment by ZhangKuixun** [comment]
> Basically you need to switch to Python3 or wait for the 2.7.15 PR to be merged, or else use @opacam fork directly.
> If you have more questions, give it a try on Discord `#support` channel

[Use yours or report errors](https://github.com/kivy/python-for-android/issues/1538#issue-391981246)
