### ISSUE TITLE
Android app crashes on rotation to landscape

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#148]
My kivy app crashes when rotated from portrait to landscape via phone rotation with the 'orientation=sensors' option. An example logcat output is at https://gist.github.com/inclement/6245730

I've tested with another (much simpler) app and got the same behaviour, and tshirtman reports also seeing it.

**Comment by miohtama** [comment]
This happens to me too.

`orientation = all` in buildozer.spec. Rotating device crashes the application without very meaningful debug information. Buildozer default minapi settings.

Below is adb logcat.

    03-12 22:31:22.447  4346  4383 I ActivityManager: Config changes=480 {1.0 310mcc260mnc en_US ldltr sw411dp w683dp h387dp 420dpi nrml land finger -keyb/v/h -nav/h s.32}
    03-12 22:31:22.449  4346  5554 I InputReader: Reconfiguring input devices.  changes=0x00000004
    03-12 22:31:22.450  4346  5554 I InputReader: Device reconfigured: id=7, name='synaptics_rmi4_i2c', size 1080x1920, orientation 1, mode 1, display id 0
    03-12 22:31:22.464 30746 30762 I python  : [INFO              ] [Android     ] Must go into sleep mode, check the app
    03-12 22:31:22.465 30746 30762 I python  : [INFO              ] [Android     ] App paused, now wait for resume.
    03-12 22:31:22.474 30746 30746 W SDLSurface: onDestroy() called
    03-12 22:31:22.475 30746 30746 D SDLSurface: onDestroy() stop requested, wait for an event from the app
    03-12 22:31:22.477 30746 30762 I python  : [INFO              ] [Android     ] Android wants to close our app.
    03-12 22:31:22.478 30746 30762 I python  : [INFO              ] [Base        ] Leaving application in progress...
    03-12 22:31:22.504 29384 29384 D GeckoApplication: onConfigurationChanged: en_US, background: false
    03-12 22:31:22.504 29384 29384 D GeckoLocales: No selected locale. No correction needed.
    03-12 22:31:22.570 30746 30762 I python  : Python for android ended.
    03-12 22:31:22.571 30746 30762 I art     : System.exit called, status: 0
    03-12 22:31:22.572 30746 30762 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
    03-12 22:31:22.595  4346 17793 D GraphicsStats: Buffer count: 9
    03-12 22:31:22.595  4346  6180 I WindowState: WIN DEATH: Window{45f7fb5 u0 com.opensourcehacker.webkivy/org.renpy.android.PythonActivity}
    03-12 22:31:22.595  4346  6180 W WindowManager: Force-removing child win Window{1f6018f u0 SurfaceView} from container Window{45f7fb5 u0 com.opensourcehacker.webkivy/org.renpy.android.PythonActivity}
    03-12 22:31:22.602  4346 32119 W WindowManager: Failed looking up window
    03-12 22:31:22.602  4346 32119 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@c2bed16 does not exist
    03-12 22:31:22.602  4346 32119 W WindowManager:     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8736)
    03-12 22:31:22.602  4346 32119 W WindowManager:     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8727)
    03-12 22:31:22.602  4346 32119 W WindowManager:     at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1209)
    03-12 22:31:22.602  4346 32119 W WindowManager:     at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
    03-12 22:31:22.602  4346 32119 I WindowState: WIN DEATH: null
    03-12 22:31:22.611  4346  5774 I ActivityManager: Process com.opensourcehacker.webkivy:python (pid 30746) has died
    03-12 22:31:22.612  4346  5774 W ActivityManager: Force removing ActivityRecord{bdeffaf u0 com.opensourcehacker.webkivy/org.renpy.android.PythonActivity t8017}: app died, no saved state
    03-12 22:31:22.632  4346  5774 I ActivityManager: Config changes=480 {1.0 310mcc260mnc en_US ldltr sw411dp w411dp h659dp 420dpi nrml port finger -keyb/v/h -nav/h s.33}
