### ISSUE TITLE
onSensorChanged continuosly called during app execution

### ISSUE THREAD

**Issue by misl6** [kivy/python-for-android#1498]
### Versions

* Python: 3.7.1
* OS: Android
* Kivy: master
* Cython: 0.28.3

### Description

During app execution, org.libsdl.app.sdlsurface.onSensorChanged is called continuosly. (Profiled via apk profiling in android studio)

**Comment by inclement** [comment]
Does this have a measurable performance problem? I'm happy to believe it's wrong, but not really familiar with it.
One of the things on the todo list is to upgrade the java code to a newer SDL2, maybe that will fix it.
Thanks for the report!

**Comment by inclement** [comment]
I wonder if this still happens with SDL2.0.9.

**Comment by Julian-O** [comment]
@misl6: Is this still happening. Can it be closed?
