### ISSUE TITLE
App doesn't support pause mode' when using on_pause method

### ISSUE THREAD

**Issue by fr3nzy** [kivy/python-for-android#1518]
### Versions

* Python: 3.60
* OS: Ubuntu 18.04
* Kivy:1.10.1

### Description

Apk created using `p4a`, command used:

```
p4a apk --private $HOME/Documents/Code/Kivy/kivytest --package=org.example.myaasdqpp --name "My appliasacation" --version 0.1 --bootstrap=sdl2 --requirements=kivy,python3crystax,pyjnius,android,sdl2 --ndk-dir $HOME/Documents/Code/crystax-ndk-10.3.2 --android-api 28 --arch=armeabi-v7a
```

Whenever the home button is pressed or the screen is switched off, report for the app crash appears and according to the logs, python for android ends:

```
12-10 20:47:23.996  6150  6150 I python  : [INFO   ] [WindowSDL   ] App doesn't support pause mode, stop.
12-10 20:47:23.997  6150  6150 I python  : INFO:kivy:[WindowSDL   ] App doesn't support pause mode, stop.
12-10 20:47:23.998  6150  6150 I python  : [INFO   ] [Base        ] Leaving application in progress...
12-10 20:47:23.998  6150  6150 I python  : INFO:kivy:[Base        ] Leaving application in progress...
12-10 20:47:24.201  6150  6171 I python  : Python for android ended.
```
The back button does not mention `App doesn't support pause mode, stop.`, but ends right away.

### Code and Logs

```python
import kivy
kivy.require('1.10.1')

from kivy.app import App
from kivy.uix.relativelayout import RelativeLayout

class Root(RelativeLayout):
	def __init__(self):
		super().__init__()


class WhatToday(App):
	def build(self):
		 return Root()
	def on_pause(self):
		pass

WhatToday().run()
```

This occurs whilst using the crystax ndk and `sdl2` as the bootstrap. I am unable to run the android ndk or `pygame` to test as a comparison because both bring about errors that have no mention on the internet. Since using the crystax ndk and `sdl2` are the only ways I can successfully create an apk.

**Comment by jtoledo1974** [comment]
I believe on_pause should return True so that the app doesn't stop. See https://stackoverflow.com/questions/20719383/run-the-application-in-background

**Comment by jtoledo1974** [comment]
Having said that there is something really wrong with SDL2, as I've been able to check with python3:
See https://github.com/kivy/kivy/issues/6075. 
I understand this is a critical bug as it is basic functionality in the default configuration.
