### ISSUE TITLE
Hello, is there a Chinese document? It is still very difficult for me to read the document after using Google Translate.

### ISSUE THREAD

**Issue by zhushichuan** [kivy/python-for-android#1527]
Hello, is there a Chinese document? It is still very difficult for me to read the document after using Google Translate.

**Comment by Zen-CODE** [comment]
No, sorry. If you have any further questions, please post them in Kivy user group, not here.

https://groups.google.com/forum/#!forum/kivy-users

This area if for reporting proven problems or bugs.
