### ISSUE TITLE
No module named sh

### ISSUE THREAD

**Issue by ZhangKuixun** [kivy/python-for-android#1531]
I have a error:
> Traceback (most recent call last):
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/toolchain.py", line 11, in <module>
>     from pythonforandroid.build import DEFAULT_NDK_API, DEFAULT_ANDROID_API
>   File "/Users/zhangkuixun/pythonforandroid/pythonforandroid/build.py", line 10, in <module>
>     import sh
> ImportError: No module named sh

I tried to fix this error by installing `sh`, but when installing `sh`, I encountered `"download error"`

here is the download `sh` command output：
> $ sudo easy_install sh 
> Password:  
> Searching for sh
> Reading https://pypi.python.org/simple/sh/
> Download error on https://pypi.python.org/simple/sh/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
> Couldn't find index page for 'sh' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.python.org/simple/
> Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
> No local packages or download links found for sh
> error: Could not find suitable distribution for Requirement.parse('sh')

I use Mac, python 2.7

**Comment by Zen-CODE** [comment]
Try "sudo pip install sh"

Either way, this is not a python-for-android issue as such. If you still have problems, please post on issue of the kivy forums using the link below.

https://groups.google.com/forum/#!forum/kivy-users

**Comment by ZhangKuixun** [comment]
Thanks, Very thanks, like you @Zen-CODE
