### ISSUE TITLE
How to build other versions of ABI？

### ISSUE THREAD

**Issue by ZhangKuixun** [kivy/python-for-android#1535]
Sorry, I have a question.

After my successful build, there was only armeabi under the Lib folder. How to create other ABI so libraries? I want these ABI so libraries:'x86','x86_64','armeabi','armeabi-v7a','arm64-v8a'.
Can you generate so libraries for different ABIS by changing python's code? If you can, please tell me how to modify the code. I'm an Android developer, I don't know python, I changed several places and it didn't work.

**Comment by ZhangKuixun** [comment]
I know how to solve this problem.

**Comment by AndreMiras** [comment]
Well this is not a support platform for questions, but a bug tracker.
But in any case if you found the solution, you could write it down here before closing the ticket
