### ISSUE TITLE
How to build other ABI versions of "libcrypto.so" and "libssl.so"?

### ISSUE THREAD

**Issue by ZhangKuixun** [kivy/python-for-android#1536]
How to build other ABI versions of "libcrypto.so" and "libssl.so". I want to build these libraries corresponding to ABI:'x86','x86_64','armeabi','armeabi-v7a','arm64-v8a'. I looked up a lot of methods, but none of them succeeded. I used Mac, python3.7

**Comment by inclement** [comment]
Using the p4a arguments `--arch=x86` etc. should work. The available archs and their names are in https://github.com/kivy/python-for-android/blob/master/pythonforandroid/archs.py, although different arch targets don't get much testing and there may be issues with some recipes.
