### ISSUE TITLE
Failure to compile .py should cause exit

### ISSUE THREAD

**Issue by brousch** [kivy/python-for-android#156]
A failure to compile one of the .py files (like main.py) should cause the script to fail. Instead, the script continues on like everything is fine.

I think a fix is to change this line to subprocess.check_output. Then it can check the return code, report the error, and exit the script with an error.

https://github.com/kivy/python-for-android/blob/master/src/build.py#L80

**Comment by inclement** [comment]
I think p4a now fails properly in such scenarios.
