### ISSUE TITLE
Minor exclude extensions code simplification

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#1560]
This is a pretty minor code improvement to be tested. The idea is to simplify slightly the extension exclusion code. It was reported during code reviewing of https://github.com/kivy/python-for-android/pull/1537/files#r242658566
Since this code was already existing, but simply moved, I think it's fine to address it later.
Also when addressing check if there're other places to tackle.

**Comment by AndreMiras** [comment]
Fixed in https://github.com/kivy/python-for-android/commit/1a4830b7ddbb6d2f2d0fec0782f76545219b49b9 of #1537 will close if this ever get merged

**Comment by JonasT** [comment]
@AndreMiras can this be closed? Since #1537 was indeed merged
