### ISSUE TITLE
All the python functions can run on kivy

### ISSUE THREAD

**Issue by manhsv2017** [kivy/python-for-android#1567]
Can all of the Python functions work with Kivy, especially some GUIs for windows?

**Comment by JonasT** [comment]
What specifically have in mind? If you don't use external libraries or more obscure/platform-specific parts of the standard library (like, let's say, `curses` for terminal formatting) then everything should work, like the widgets you use on windows also work on Android. But e.g. if your own code expects certain file paths to be around that don't exist on android then you could have issues.

It really depends, but basically yes, your kivy UI should work the same on Android

**Comment by manhsv2017** [comment]
I see. Thanks for your reply

Vào CN, 13 thg 1, 2019 vào lúc 03:20 JonasT <notifications@github.com> đã
viết:

**Comment by JonasT** [comment]
@manhsv2017 is it ok if I close this for now? I'll do so, but I can reopen if there's anything else. also feel free to drop by on discord if you have questions
