### ISSUE TITLE
python2legacy - various warnings then no valid dependency graphs

### ISSUE THREAD

**Issue by hottwaj** [kivy/python-for-android#1582]
I have just tried to build my app using the new (post API 26) toolchain.  Unfortunately my app still needs to use pygame/sdl on android, so I saw in the docs that I need to use the python2legacy recipe

When I run P4A with the python2recipe selected, I get various warnings like this:

```
/home/jonathan/prog/src/p4a-2019/pythonforandroid/recipes/pyjnius/__init__.py:3: RuntimeWarning: Parent module 'pythonforandroid.recipes' not found while handling absolute import
  from pythonforandroid.patching import will_build
```

This happens for all recipes I have included in my build.

Finally, I get:

```
[ERROR]:   Build failed: Didn't find any valid dependency graphs. This means that some of your requirements pull in conflicting dependencies.
```

I guess that this is because some recipes depend on python2 (and not python2legacy)?

Thanks!

**Comment by homdx** [comment]
Hello.
You not show in issue .p4a file or command line parameters or/and requirements.txt

**Comment by AndreMiras** [comment]
Since #1582 was recently merged you could give it a try on master see if the problem is fixed.
e.g. via `buildozer android update`

**Comment by hottwaj** [comment]
Thanks, I will give that a try - and sorry for the lack of p4a cmd line parameters etc, my concern (which I wasn't clear on) was that the python2legacy route was not currently usable because of the recent overhaul

I will close for now and come back with anything specific that I have trouble with.

Cheers!
