### ISSUE TITLE
Travis conditional boostrap build support

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#1588]
Currently the Travis conditional build script only support the `sdl2` bootstrap. This is because [sdl2 the bootstrap is hardcoded](https://github.com/kivy/python-for-android/blob/12ac837/ci/rebuild_updated_recipes.py#L67).
It would be great if it could at least try to rebuild another bootstrap if it gets updated. That could be done using the same way we detect for a recipe update.

**Comment by Julian-O** [comment]
Travis no longer supported. Closing as Not Planned.
