### ISSUE TITLE
Support for NDK 19

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#1613]
I just tested with Android NDK 19 for which we'll need to build with clang only. This seemed to work fine when I tested some core recipes (exception libFFI, https://github.com/kivy/python-for-android/issues/1612). However, to accomplish that I hardcoded clang=True in Arch.get_env.

We should only need to add a simple check for what is available in the NDK when selecting an appropriate compiler. Probably we should switch to clang-by-default even on NDKs where we currently use gcc.

**Comment by misl6** [comment]
Fixed via #1722
