### ISSUE TITLE
numpy/opencv fails with latest p4a at runtime (import)

### ISSUE THREAD

**Issue by zworkb** [kivy/python-for-android#1678]
I was very happy to read that the opencv recipe was updated to version 4.0.1 and the build runs fine with python3, numpy and opencv, but when starting the app on android it gives the following error in logcat:

    I python  : Traceback (most recent call last):
    I python  :   File "/home/phil/dev/kivy/cvtest/.buildozer/android/app/main.py", line 1, in <module>
    I python  :   File "/home/phil/dev/kivy/cvtest/.buildozer/android/platform/build/build/python-installs/cvtest400/numpy/__init__.py", line 142, in <module>
    I python  :   File "/home/phil/dev/kivy/cvtest/.buildozer/android/platform/build/build/python-installs/cvtest400/numpy/add_newdocs.py", line 13, in <module>
    I python  :   File "/home/phil/dev/kivy/cvtest/.buildozer/android/platform/build/build/python-installs/cvtest400/numpy/lib/__init__.py", line 8, in <module>
    I python  :   File "/home/phil/dev/kivy/cvtest/.buildozer/android/platform/build/build/python-installs/cvtest400/numpy/lib/type_check.py", line 11, in <module>
    I python  :   File "/home/phil/dev/kivy/cvtest/.buildozer/android/platform/build/build/python-installs/cvtest400/numpy/core/__init__.py", line 26, in <module>

    I/python : ImportError: 
    I/python : Importing the multiarray numpy extension module failed.  Most
    I/python : likely you are trying to import a failed build of numpy.
    I/python : If you're working with a numpy git repo, try `git clean -xdf` (removes all
    I/python : files not under version control).  Otherwise reinstall numpy.
    I/python : Original error was: dlopen failed: library "libpython2.7.so" not found
    I/python : Python for android ended.

I ran the build with the master of buildozer and p4a (0c4cd1d732e6f461f780f62b84f9ca57b722f5b9) and python 3.5 

the requirements in buildozer.spec:

    requirements = kivy, android,  numpy

the rest was untouched after buildozer init

in the main.py it fails at:

    import numpy as np

I tried that on a device runnning Android 7.0 and another one with Android 5.1.1 with the same results

**Comment by AndreMiras** [comment]
In the requirements of your `buildozer.spec` please add `python3`

**Comment by zworkb** [comment]
@[AndreMiras](/AndreMiras) thanks for the hint. When compiling with the python3 requirement the build fails at compiling pyjnius:

    ...
    jnius/jnius.c: In function '__Pyx_ExceptionSave':
    jnius/jnius.c:46818:19: error: 'PyThreadState' has no member named 'exc_type'
         *type = tstate->exc_type;
                   ^
    jnius/jnius.c:46819:20: error: 'PyThreadState' has no member named 'exc_value'
         *value = tstate->exc_value;
    ...

I have cython 0.28.2 and tried with python3.5 and 3.7

**Comment by zworkb** [comment]
the problem was an old system-wide version of cython that interfered with the version installed in the virtualenv i was using, updating to cython 0.29 did the job
Thanks to @JonasT
