### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by PROuserR** [kivy/python-for-android#1694]
ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
I tried to install pbs but:EVEN
Requirement already satisfied: pbs
Running on windows 10 64-bit

**Comment by inclement** [comment]
I'm afraid python-for-android does not support windows. The dependency on sh is only the smallest of many changes it would need there.
