### ISSUE TITLE
AttributeError: 'java.io.File' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by Depaulicious** [kivy/python-for-android#170]
I noticed that Python for Android is giving this error when calling posixpath.join:

<pre>
I/python  (32288):  Traceback (most recent call last):
I/python  (32288):    File "/home/davideddu/karaokivy/.buildozer/android/app/main.py", line 631, in <module>
I/python  (32288):    File "/home/davideddu/karaokivy/.buildozer/android/app/main.py", line 137, in check_env
I/python  (32288):    File "/home/davideddu/karaokivy/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/posixpath.py", line 68, in join
I/python  (32288):  AttributeError: 'java.io.File' object has no attribute 'endswith'
</pre>

I think it's a problem inside Py4A, but I'm not sure.

I'm using buildozer to build the application.
##

**Comment by inclement** [comment]
Closing as this issue relates to the old toolchain which is no longer supported. Please open a new issue if you experience this problem with the current master branch.
