### ISSUE TITLE
Webview build can't find `SDL_setenv`.

### ISSUE THREAD

**Issue by dbrnz** [kivy/python-for-android#1702]
I'm attempting to build the Python3 webview test app from the `master` branch using NDK 19 and an arm64-v8a target. However linking `libmain.so` fails with `undefined reference to 'SDL_setenv'`.

I see [start.c](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/common/build/jni/application/src/start.c) references `SDL_setenv` in `Java_org_kivy_android_PythonActivity_nativeSetenv()` which is compiled because `BOOTSTRAP_NAME_WEBVIEW` is defined. Is it intended to call `SDL_setenv` given that `SDL.h` has not been included (since a webview build defines `BOOTSTRAP_USES_NO_SDL_HEADERS`)??

**Comment by AndreMiras** [comment]
Thanks for the report, you can now try on p4a master since @j-devel fixed the regression recently

**Comment by dbrnz** [comment]
Thanks!
