### ISSUE TITLE
Match official requestPermissions interface

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#1704]
The Android API for requesting runtime permission has the following signature:
```java
void requestPermissions (Activity activity,
                String[] permissions,
                int requestCode)
```
Currently via our `PythonActivity.java` class, we're providing:
```java
public void requestNewPermission(String permission)
```
See https://github.com/kivy/python-for-android/blob/02519cc/pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonActivity.java#L608
It would be great if our interface was also somewhat matching the official name/signature.

- official documentation [ActivityCompat#requestPermissions()](https://developer.android.com/reference/android/support/v4/app/ActivityCompat#requestPermissions(android.app.Activity,%20java.lang.String[],%20int))
- PR discussion https://github.com/kivy/python-for-android/pull/1528#discussion_r255345553

This would be a non-breaking change since we can keep our current `requestNewPermission()` method and just add the new `requestPermissions()` one.

**Comment by JonasT** [comment]
The `android` module, the only one that directly calls this, is bundled with p4a anyway (in an always-compatible version as a natural consequence). So why would there a need to keep the old signaure around?

**Comment by AndreMiras** [comment]
Yes that's also a true. Then at least the android permission module should still provide some backward compatible interface. Currently it's `def request_permission(permission):` and we should also have a `def request_permissions(permissions):`

**Comment by JonasT** [comment]
yeah for the android module it makes sense to keep both I suppose (`request_permission` and `request_permissions`). As for the strings, even the android module also already takes strings, the predefined constants are just for nicer code and don't need to be actually used

**Comment by AndreMiras** [comment]
Yes that's what I mean, it should take an array of string
