### ISSUE TITLE
python-for-android.readthedocs.io has problems updating, apparently

### ISSUE THREAD

**Issue by ghost** [kivy/python-for-android#1709]
It seems like python-for-android.readthedocs.io is for some reason failing to update itself. E.g. check this one out:

https://python-for-android.readthedocs.io/en/latest/apis/#accessing-android-apis (First headings: "Working on Android", "Accessing Android APIs")

vs.

https://github.com/kivy/python-for-android/blob/master/doc/source/apis.rst (First headings: "Working on Android", "Runtime permissions")

Since we've had quite a few things introduced lately (like runtime permissions), it'd be useful if it updated. Does someone happen to know how to make that happen or whom to contact about this?

**Comment by JonasT** [comment]
@inclement the docs seem to be newer now, was that a manual bump or can this ticket be closed and automatic updates work again?

**Comment by AndreMiras** [comment]
Yes I triggered it manually months ago. So we still need to investigate the automatic building

**Comment by misl6** [comment]
Just added a webhook that notifies RTD about changes.
Closing as fixed.
