### ISSUE TITLE
Null pointer when finding libraries

### ISSUE THREAD

**Issue by dbrnz** [kivy/python-for-android#1717]
I've successfully built the Webview test app for Python 3, NDK 19, API 24 and am now trying to get it to run -- starting the app gives "Attempting to get length of null array" when PythonActivity tries to load the application libraries.

I've traced this to ``addLibraryIfExists()``  in ``./pythonforandroid/bootstraps/common/build/src/main/java/org/kivy/android/PythonUtil.java`` where it appears that ``libsDir`` doesn't exist and so the ``files`` variable is set to null. I'm uncertain as to how paths values in the debugger relate to those in the FileExplorer, but the debugger has the library path as ``/data/user/0/com.pandq.test/lib`` yet File Explorer shows the libraries inside ``/data/app/com.pandq.test-1/lib/arm64``.  Is some form of versioning going on?

**Comment by j-devel** [comment]
This `libsDir` is issue is being addressed in #1701.

**Comment by inclement** [comment]
@dbrnz The PR #1701 that @j-devel linked has been merged, did that fix your issue?

Beyond that, maybe try NDK 17c instead of 19.

**Comment by dbrnz** [comment]
@inclement thanks, that did fix things. I'm all good with NDK 19 and Python 3, so closing.
