### ISSUE TITLE
ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

### ISSUE THREAD

**Issue by SwagatRanjit84** [kivy/python-for-android#1721]
After doing python-for-android recipes, its showing error even after installing pbs:
ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

**Comment by Towloo** [comment]
locate the python file that's giving the error and replace 'import sh' with:
import pbs
class Sh(object):
    def __getattr__(self, attr):
        return pbs.Command(attr)
sh = Sh()

That should solve the issue

**Comment by Towloo** [comment]
locate the python file that's giving the error and replace 'import sh' with:

```
import pbs
class Sh(object):
def **getattr**(self, attr):
return pbs.Command(attr)
sh = Sh()
```

That should solve the issue

**Comment by Towloo** [comment]
locate the python file that's giving the error and replace 'import sh' with:
```
import pbs
class Sh(object):
    def **getattr**(self, attr):
    return pbs.Command(attr)
sh = Sh()

```
That should solve the issue

**Comment by Towloo** [comment]
locate the python file that's giving the error and replace 'import sh' with:
```
import pbs
class Sh(object):
    def **getattr**(self, attr):
        return pbs.Command(attr)
sh = Sh()
```

That should solve the issue

**Comment by inclement** [comment]
I'm afraid we don't support windows.

**Comment by SwagatRanjit84** [comment]
@inclement Some users have done it on windows!! Dont close this issue

**Comment by MisterY** [comment]
@SwagatRanjit84, unfortunately they don't support Windows and, more importantly, they *don't want* to support Windows. Which is quite unfortunate as some of us spend most of their time on Windows machines. Maintaining a Linux VM is too cumbersome and Linux Subsystem now requires Windows Marketplace, which is disabled in some environments.
Once there is an idea that Windows may be supported in the future, should people start sending pull requests that make p4a work on both platforms (as both Python and Android SDK already do, paradoxically).
