### ISSUE TITLE
Android setup.py not working for windows

### ISSUE THREAD

**Issue by Towloo** [kivy/python-for-android#1726]
python-for-android/pythonforandroid/recipes/android/src/setup.py

This setup file is not working for windows; I'm running Windows 10 Pro with python 2.7 64 Bit. It is complaining of the environment variable ('ARCH') which is not found

**Comment by inclement** [comment]
I'm afraid we don't support running on windows, except that using the Windows Subsystem for Linux may work.

**Comment by inclement** [comment]
I'm afraid we don't support running on windows, except that using the Windows Subsystem for Linux may work. Please feel free to reopen this issue if it occurs on Linux, macOS, or WSL (in the latter case although we don't officially maintain support, it probably should work we'd rather not break it)
