### ISSUE TITLE
Problems with distibute.sh

### ISSUE THREAD

**Issue by i-zaitsev** [kivy/python-for-android#175]
I got error when command ./distribute.sh -m "kivy" was used:
# error Do not use this file, it is the result of a failed Cython compilation.

  ^
 error: command 'ccache' failed with exit status 1
## Error compiling Cython file:

...
        def **get**(self):
            w,h = self._width, self._height
            self.bind()
            data = py_glReadPixels(0, 0, w, h, GL_RGBA, GL_UNSIGNED_BYTE)
            self.release()
            return str(buffer(data))
##                             ^

kivy/graphics/fbo.pyx:391:29: undeclared name not builtin: buffer

I'm using cython 0.19.2.

**Comment by jtmorrisbytes** [comment]
What was the fix for this issue? I am having the same problem

**Comment by inclement** [comment]
If you have the same problem with python-for-android master, please create a new issue giving the full details. This issue is ancient and doesn't relate to modern p4a.

**Comment by jtmorrisbytes** [comment]
It was a similar issue for a completely different project. I just want to know how it was fixed because it seemed relevant to the issue I was having with cython. I am very new to cython so I dont yet know how to resolve types that arent builtins
