### ISSUE TITLE
App crashes using python3 and android's run_on_ui_thread

### ISSUE THREAD

**Issue by thegameguy** [kivy/python-for-android#1755]
I have ran into issues while deploying an app using python3 and run_on_ui_thread decorator in android module.

Thanks

**Comment by AndreMiras** [comment]
Thanks for the report, but that's not enough to debug or tell if it's an issue on p4a side.
We need a simple reproduction case, the log, the stack trace, the versions at minimum.
There's an issue template that should help filling the info
