### ISSUE TITLE
Update setuptools version

### ISSUE THREAD

**Issue by oshino-shinobu** [kivy/python-for-android#176]
Master branch of Kivy fails to compile with current version of setuptools:
ImportError: project/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/lib-dynload/_io.so: wrong ELF class: ELFCLASS32

Setting setuptools version to 1.2 in its recipe solved the problem for me.

**Comment by Cuuuurzel** [comment]
This kind of issues appears here and there regularly...
Is there a possibility to write a "standard" guide to solve this?

I've just got the same issues after adding plyer to buildozer.spec.

**Comment by akshayaurora** [comment]
@ecdsa had the same issue for him installing  cython using apt-get instead of pip helped fix  this.

**Comment by inclement** [comment]
I haven't seen this come up for a long time, and the new toolchain should certainly resolve it anyway, so I'll close this.
