### ISSUE TITLE
"--orientation fullUser" is not working

### ISSUE THREAD

**Issue by goffi-contrib** [kivy/python-for-android#1763]
### Versions

* Python: 2.7.15
* OS: Android 6.0
* Kivy: a95d67f
* Cython: 0.29.6

### Description

With P4A master (rev 84142eb) the `--orientation fullUser` argument is not working at all, the screen stay in portrait mode whatever the user-set orientation locking status is. The same result happens with `--orientation user`.

With `sensor` the orientation is working and moving according to sensor, but without obeying the user settings (which is the normal behaviour according to [Android documentation](https://developer.android.com/guide/topics/manifest/activity-element.html#screen)), so it can't be used as a replacement of `user` and `fullUser`.

This has been tested with the `sdl2` bootstrap.

### buildozer.spec

I've used P4A directly without buildozer.

### Logs

No logs, the app is not reacting at all to orientation change, with or without user locking.

**Comment by inclement** [comment]
Are you using Kivy master? If not, try that.

**Comment by goffi-contrib** [comment]
@inclement I was using the version of the recipe `a95d67f`.
I'm trying now with the latest commit of master (`c4d6894`), it's now working, but if I move to landscape mode and then lock the orientation, the app go back to portrait and crash a few seconds after. I don't think it's linked on the app itself. Anyway it's something for an other ticket, I'll test more and report this other issue later.

About the orientation, Kivy recipe should be updated.

Thanks for your feedback!
