### ISSUE TITLE
packaged python is built with IPv6 disabled

### ISSUE THREAD

**Issue by SomberNight** [kivy/python-for-android#1771]
Is there any reason for IPv6 being disabled?
https://github.com/kivy/python-for-android/blob/f16a66590c92bb57c69b214b2b69dfaa6dc1e0ed/pythonforandroid/recipes/python3/__init__.py#L37

**Comment by inclement** [comment]
I think I encountered a build error if I didn't add this, but it's probably something that can be fixed.

**Comment by SomberNight** [comment]
I've tested now and cannot see any issues.
Running https://github.com/SomberNight/python-for-android/commit/a607f4a446773ac0b0a5150171092b0617fbe670, and IPv6 works.
(note that I am not on up-to-date master but I don't think it makes a difference)

**Comment by inclement** [comment]
Thanks for the update!

**Comment by SomberNight** [comment]
To be clear, I meant IPv6 works when changing the referenced line (see https://github.com/SomberNight/python-for-android/commit/a607f4a446773ac0b0a5150171092b0617fbe670)

I don't believe it works on p4a master as-is.

**Comment by inclement** [comment]
Oh, okay. I'll leave this open then, but if you'd like to do a PR with the change I'll merge it as soon as the tests pass.

**Comment by AndreMiras** [comment]
Build was passing, I've merged it. Thanks for the report and PR :+1:
