### ISSUE TITLE
Python3 Numpy fails on np.save()

### ISSUE THREAD

**Issue by JohnBuckleyGitHub** [kivy/python-for-android#1776]
### Versions

* Python: 3.6 & 3.7 (I have tried both)
* OS: Ubuntu 18.10
* Kivy: 1.10
* Cython: 0.29.6

### Description

The command np.save(filename, numpy array) fails with the error:

File "/home/anon/.local/share/python-for-android/build/python-installs/vsbike/numpy/lib/npyio.py", line 521, in save
15867-16128/com.velosense.bikeano I/python: [WARNING] [2019-03-29 12|44|31.150] stderr:   File "/home/anon/.local/share/python-for-android/build/python-installs/vsbike/numpy/lib/format.py", line 604, in write_array
15867-16128/com.velosense.bikeano I/python: [WARNING] [2019-03-29 12|44|31.151] stderr: OSError: seeking file failed

 I can replicate this by simply calling:

import numpy as np
np.save('temp_file', np.array([1, 2, 3]))

However, if I use the compressed file version of save:

import numpy as np
np.savez_compressed('temp_file', np.array([1, 2, 3]))

I do not have the problem

### buildozer.spec

I am using p4a direct with the following command:

p4a apk --debug --dist_name=bikeAno  --bootstrap sdl2  --requirements=android,python3==3.7,kivy,plyer,numpy,boto3,botocore,urllib3,python-dateutil,jmespath,s3transfer  --arch armeabi-v7a   --name bike  --version 2.2  --package com.something.else  --android_api=28  --permission ACCESS_FINE_LOCATION  --permission ACCESS_COARSE_LOCATION  --permission INTERNET  --permission ACCESS_NETWORK_STATE  --add-jar android_antlib-restricted_4-15-0.jar  --add-jar channel.jar  --presplash splash.jpg  --icon Favicon-ExtraRounded.png  --orientation portrait  --wakelock  --color=always --private .
```


```

**Comment by johnbolia** [comment]
What is strange, is that it is failing on the seek() command, which is the same as this issue:
https://github.com/kivy/python-for-android/issues/1768

But that one only affects Python2

**Comment by misl6** [comment]
Since `numpy` recipe has been updated, does this issue is still reproducible on your side when using latest python-for-android `develop` version?
