### ISSUE TITLE
Background Service is killed when app is swiped (close by user)

### ISSUE THREAD

**Issue by brvier** [kivy/python-for-android#1783]
### Versions

* Python: 2.7
* OS: Android
* Kivy: master
* Cython: recommended
* Pythonforandroid: master

### Description

When you close a application, the service is also closed. This is an unexpected behaviors, as service should run in background,  and not be killed then restarted when you kill the app.

This happen as when you remove task from task list, the method onTaskRemoved of the service is also called.

**Comment by AndreMiras** [comment]
As far as I remember this is an Android feature. When the app is closed the service is also killed. Isn't it?
Quick googling lead me to:

- https://stackoverflow.com/q/42126979/185510
- https://stackoverflow.com/q/30525784/185510

**Comment by brvier** [comment]
No it's not a feature, it's badly coded. 

Take a look at kde connect source code for example. And how the app so works. Or automate, ifttt

**Comment by AndreMiras** [comment]
On KDE Connect seems to be using the `START_STICKY` bit. Unfortunately this is not yet working on the p4a implementation, see:

- https://github.com/kivy/python-for-android/pull/1374#issuecomment-421614772
- https://groups.google.com/forum/#!topic/kivy-users/1-zIEkI0snY
