### ISSUE TITLE
StartService in Android Oreo and More should use startForegroundService

### ISSUE THREAD

**Issue by brvier** [kivy/python-for-android#1785]
### Versions

* Python: 2.7
* OS: Android (API 28)
* Kivy: master
* Cython: recommendedone

### Description

On Android Oreo and more, Start service should use startForegroundService instead of startService

**Comment by brvier** [comment]
And also use notification channel for the permanent notification.

**Comment by JonasT** [comment]
I think this is implemented now on latest `develop` so it should work now! Please let me know if this isn't the case, I'll be happy to reopen the issue then
