### ISSUE TITLE
Crash at relaunch in pythonlib in SDL2Thread

### ISSUE THREAD

**Issue by brvier** [kivy/python-for-android#1787]
### Versions

* Python: 2.7
* OS: Android Oreo
* Kivy: master
* Cython: last prerered version 27.3

### Description

Swipe app from task list invoke onDestroy in SDLActivity.java

        // Now wait for the SDL thread to quit
        if (SDLActivity.mSDLThread != null) {
            try {
                SDLActivity.mSDLThread.join();
            } catch(Exception e) {
                Log.v(TAG, "Problem stopping thread: " + e);
            }
            SDLActivity.mSDLThread = null;

            //Log.v(TAG, "Finished waiting for SDL thread");
        }

        super.onDestroy();

        // Reset everything in case the user re opens the app
        SDLActivity.initialize();
 
But it s look like a thread never ends in my app or invoking service prevent activity to be deleted, so at relaunch the app crash with SDL2Thread in libpython

If i do a Process.killProcess(Process.myPid()); second launch don't crash....

I think all my threads should be ended, could it be a Clock.schedule_interval ?

**Comment by JonasT** [comment]
If the thread keeps running and it's related to `Clock.schedule_interval`, is this possibly a kivy issue?

**Comment by brvier** [comment]
Not sure which thread is running and why for the moment

**Comment by JonasT** [comment]
For what it's worth, I don't use kivy but I make very heavy use of threading, and I've never seen this happen. Of course it could still be a python-for-android issue, but it might be worth investigating kivy as well

Maybe add another thread and have it do this every few seconds? https://stackoverflow.com/questions/1032813/dump-stacktraces-of-all-active-threads Of course that will also break your shutdown but then at least you should see in the log what sort of threads are still running, if any

**Comment by brvier** [comment]
Or just my code ...

**Comment by inclement** [comment]
Just to be clear, `Clock.schedule_interval` does not involve threading. I'm not sure what is causing this problem.

**Comment by JonasT** [comment]
@inclement for what it's worth SDL2 2.0.9 stable has a remaining concurrency bug that can in theory cause crashes, but with the SDL2 dev version and even SDL_ANDROID_BLOCK_ON_PAUSE disabled (which makes everything a little more off the rails parallel) I haven't had any crashes or corruption with my app for weeks. I don't use kivy though, but at least as far as python-for-android is concerned it looks to me like it's possibly working corruption free (finally!) at leeast with SDL2 dev

**Comment by inclement** [comment]
@JonasT Thanks, I'm currently testing your SDL2 update PR with kivy

**Comment by JonasT** [comment]
Is this still an issue? Has there been anything new you found out @brvier ?

**Comment by brvier** [comment]
Too old
