### ISSUE TITLE
Keep track of coverage testing

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#1788]
Since we're trying to increase our testing coverage, we need to keep track of it.
This ticket is about investigating which solution to use and implement it.
In a first phase, we don't want to enforce a certain coverage, but at least have an overview of what we currently have and track how it evolves.

**Comment by opacam** [comment]
@AndreMiras, thanks to remind us this `coverage` thing, now I think that we already have it covered thanks to the pull request mentioned above, so I'm closing this issue :wink:, feel free to open it again if you think that we should discuss something
