### ISSUE TITLE
Compilation error, previously worked

### ISSUE THREAD

**Issue by spartero** [kivy/python-for-android#1846]
Today I had to update the python code of my app flask (it has only been the inclusion of a new html page) and I have not managed to compile the apk. I used to do it without problems.
I made a distclean buildozer, as I had read in other entries, but still giving errors

* Python: 3.6.7
* OS: neon 18.04
* Cython: 0.28.6

The configuration file is the same as the one previously obtained by the apk. I've even tried to generate a new configuration file.

```
I enclose the log in a file as it is too large

```
[error.txt](https://github.com/kivy/python-for-android/files/3268412/error.txt)

**Comment by AndreMiras** [comment]
Don't you have a syntax error in your source code?
```
[INFO]:    -> directory context /home/ubuntu/appsanelectric/.buildozer/android/platform/build/dists/myapp
Listing '/tmp/p4a-extra-env-d54v5ph0'...
Listing '/home/ubuntu/appsanelectric/.buildozer/android/app'...
Listing '/home/ubuntu/appsanelectric/.buildozer/android/app/_applibs'...
Compiling '/home/ubuntu/appsanelectric/.buildozer/android/app/main.py'...
***   File "/home/ubuntu/appsanelectric/.buildozer/android/app/main.py", line 113
    h = bbdd('cinta_aislante')https://github.com/kivy/python-for-android.git
                                  ^
SyntaxError: invalid syntax

Compiling '/home/ubuntu/appsanelectric/.buildozer/android/app/sitecustomize.py'...
```
Is it possible to share the source?

**Comment by spartero** [comment]
thanks for answering. I had not seen that error, I check my code. And I tell you something.

**Comment by spartero** [comment]
You had all the reason, had a part of the code that prevented the compilation of the apk. Although I still do not know why the app does not work on  [android 6 #1801](https://github.com/kivy/python-for-android/issues/1801)

**Comment by AndreMiras** [comment]
Thanks for keeping us updated
