### ISSUE TITLE
p4a build with NDK r18b: clang: error: unknown argument: '-mandroid' 

### ISSUE THREAD

**Issue by Fak3** [kivy/python-for-android#1853]
os: openSUSE Tumbleweed linux x64
p4a version: git master

I tried to build apk with command:
`
p4a apk --private /home/z/pproj/paradox_ssh/ --version=1.7 --bootstrap=sdl2 --local-recipes=./recipes --requirements=python3,kivy-async,openssl,sqlite3,pil,requests,sdl2,plyer --whitelist=./whitelist.txt --permission=CALL_PHONE --permission=INTERNET --orientation=portrait --package=org.spbelect.paradox2 --name="paradox2" --release 
`

* It should not matter here, but for clarity `kivy-async` is my customized recipe to grab https://github.com/matham/kivy/archive/async-support.zip branch

The build failed with error: 
```
configure: error: in `/home/u1/.local/share/python-for-android/build/other_builds/freetype/armeabi-v7a__ndk_target_19/freetype/builds/unix':
configure: error: C compiler cannot create executables
```

full p4a stdout: https://gist.github.com/Fak3/42ec4c772338ca359ae08cc9eeb332be

contents of ~/.local/share/python-for-android/build/other_builds/freetype/armeabi-v7a__ndk_target_19/freetype/builds/unix/config.log
https://gist.github.com/Fak3/1c65cc9476f326a0c3bf03d317b1eb9f

The suspect by quick googling is openssl recipe, which adds '-mandroid' flag, not recognized by clang. Although it is odd that the error occurs when building freetype.

**Comment by Fak3** [comment]
refs #1722

**Comment by inclement** [comment]
Thanks for the report. Are you able to try with NDK 17c, this is the most well tested configuration? I'm looking to update this in the near future.

**Comment by Fak3** [comment]
This error does not occur with ndk r17c

**Comment by Julian-O** [comment]
NDK minimum is now 25b. Closing as stale.

If the problem persists, please let us know
