### ISSUE TITLE
how do i support numba(a python module)

### ISSUE THREAD

**Issue by CSUTailorWu** [kivy/python-for-android#1865]
### Versions

* Python:2.7.12
* OS:ubuntu 16.04
* Kivy:1.10.1
* Cython:0.28.2

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?
First,I test example correct in my environment. then,I try to alter some data,hold good. Now,i want to test numba(a site-module),The APP crash
### buildozer.spec

Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by CSUTailorWu** [comment]
just easy to use numba

from numba import jit
@jit
def hello():
      return a

**Comment by lian2018** [comment]
No support for numba, DVM used in Android that using multithreading for acceleration. Whether it’s going to run on a multicore way or CUDA for GPU,it's not for Android when numba for LLVM. If you want to cross compliling numba for different platform configurations,that is not a good idea.
