### ISSUE TITLE
install recursive dependencies of pure python packages

### ISSUE THREAD

**Issue by Fak3** [kivy/python-for-android#1874]
Adding pure python package to requirements currently only installs this package, without its own dependencies. You have to flatten the list of recursive dependencies yourself, and provide them all as --requirements, which could be quite hard to do.

It would be a lot easier if p4a installed recursive deps by itself.

Possibly related: #1490

**Comment by inclement** [comment]
I think this is already 'fixed' if you use @JonasT's setup.py integration, but specifically wasn't rolled out by default because it's quite slow. Not sure if I've remembered that right though.

**Comment by inclement** [comment]
Closing as a duplicate of #1490.

**Comment by JonasT** [comment]
@Fak3 @inclement it is rolled out just not enabled by default, use `--use-setup-py` to use it. Details are here: https://python-for-android.readthedocs.io/en/latest/distutils/#have-p4a-apk-run-setup-py-replaces-requirements
