### ISSUE TITLE
get_bootstrap_from_recipes() result consistency

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#1875]
In https://github.com/kivy/python-for-android/pull/1872#discussion_r294949284 we realised get_bootstrap_from_recipes() was not always returning consistent result across setups.
This is an investigation task to determine if it's a bug or a feature and if it's a bug to fix it.

**Comment by AndreMiras** [comment]
Basically on my setup and in 0c9ef2e calling `list(Bootstrap().list_bootstraps())` returns the following: `['webview', 'sdl2', 'service_only', 'empty']` I guess for @opacam and Travis it returned something with "service_only" being first.

**Comment by JonasT** [comment]
@AndreMiras `listdir` depends on inode ordering and is not alphabetically sorted:
```python
    @classmethod
    def list_bootstraps(cls):
        '''Find all the available bootstraps and return them.'''
        forbidden_dirs = ('__pycache__', 'common')
        bootstraps_dir = join(dirname(__file__), 'bootstraps')
        for name in listdir(bootstraps_dir):
            if name in forbidden_dirs:
                continue
            filen = join(bootstraps_dir, name)
            if isdir(filen):
                yield name
```
I think a simple `sorted(listdir(bootstraps_dir))` may fix it and make it behave deterministically
