### ISSUE TITLE
main window jumps up and down

### ISSUE THREAD

**Issue by Fak3** [kivy/python-for-android#1876]
p4a version: develop branch

I have built simple kivy app with sdl2 backend, and it looks like window is changing height each 0.5 seconds from full screen to a bit smaller. So the whole app constantly jumps up and down.

adb log: https://gist.github.com/Fak3/ce144578c74762fc39f8f26c34590bb1

**Comment by Fak3** [comment]
Suspicious thing from the log, that right before I killed the app, it reported it's height slightly lower than device height:
V/SDL     (13995): Window size: 1080x1845
V/SDL     (13995): Device size: 1080x1920
But before that, after app is started, it reports that both are equal

**Comment by Fak3** [comment]
so the latest sdl2 from hg fixes this bug. The bad news is that it does not work with multisamples. So you have to disable it in kivy config:
```python
from kivy.config import Config
Config.set('graphics', 'multisamples', '0')
```

**Comment by inclement** [comment]
Any idea what has caused you to come across this issue? I don't think I've seen it mentioned before.

**Comment by Fak3** [comment]
It happens with any app if multisamples is enabled. I have reported in sdl bugtracker: https://bugzilla.libsdl.org/show_bug.cgi?id=4691

**Comment by Fak3** [comment]
i think it was introduced wit this commit: https://github.com/kivy/kivy/commit/e437dfc681bd774f6662c55a863041515ec2f3f0
but cant;t test it, as kivy from this time fails to start with error:
```
06-25 18:08:35.966 I/python  ( 5717):  Traceback (most recent call last):
06-25 18:08:35.966 I/python  ( 5717):    File "/home/z/pproj/paradox_dev/main.py", line 41, in <module>
06-25 18:08:35.966 I/python  ( 5717):    File "/home/z/pproj/paradox_dev/label.py", line 4, in <module>
06-25 18:08:35.966 I/python  ( 5717):    File "/home/u1/.local/share/python-for-android/build/python-installs/paradox/kivy/uix/label.py", line 286, in <module>
06-25 18:08:35.966 I/python  ( 5717):    File "/home/u1/.local/share/python-for-android/build/python-installs/paradox/kivy/core/text/__init__.py", line 90, in <module>
06-25 18:08:35.966 I/python  ( 5717):  ImportError: cannot import name 'USE_PANGOFT2' from 'kivy.setupconfig' (/data/data/org.spbelect.paradox2/files/app/_python_bundle/site-packages/kivy/setupconfig.pyc)
```

**Comment by Fak3** [comment]
Oh! When app is built with --window option, it behaves normally and does not jump. 
Also happens on pure SDL2 C apps, I have reported it upstream: https://bugzilla.libsdl.org/show_bug.cgi?id=4691

The key is to have both multisampling and SDL_WINDOW_FULLSCREEN flag.

**Comment by Julian-O** [comment]
Closing as no action required by p4a team.

If you disagree, please let us know.
