### ISSUE TITLE
Little but essential Typo 

### ISSUE THREAD

**Issue by JensGe** [kivy/python-for-android#1879]
Hi,
there is an important to fix Typo in
https://github.com/kivy/python-for-android/blob/e494c2567d898149edbee2063c7ad6e820f82297/pythonforandroid/recipes/android/src/android/permissions.py#L14

it should be changed to: `android.permission.ACCESS_FINE_LOCATION` (delete one s in permisssion)

You can use Pull Request #1880.

Greetings

**Comment by AndreMiras** [comment]
Thanks, fixed via 1bf002d
