### ISSUE TITLE
is recipe for the library "kivymd" available in p4a?

### ISSUE THREAD

**Issue by GUNASEKHAR333** [kivy/python-for-android#1893]
i created an apk file which uses "kivymd" library for the purpose of navigation drawer. The libraries used by me in the main.py are  kivy and kivymd only.The apk generated using buildozer is crashing on app launch on android. The requirements section in buildozer.spec file is "python3 ,kivy, kivymd". I want to know  whether p4a recipe for kivymd is available or not? please give a solution for the problem i am encountering.

**Comment by AndreMiras** [comment]
The `kivymd` lib doesn't need a recipe it's pure Python.
Try on Discord for support. Basically you can post your adb logcat there and ask for help
