### ISSUE TITLE
About TextInput, I can't type korean character. I only can type english.

### ISSUE THREAD

**Issue by meansoup** [kivy/python-for-android#1904]
### Versions
* Python: 3.5.2
* OS: ubuntu 16.04
* Kivy: 1.11.0
* Cython: 0.29.10

### Description

Simmilar issue with #1102 

Hello. I had make some app which has textinput & labels.
When I run the app in windows, it can show korean text label & I can type korean in textinput.
But, When I run the app in android, it also can show korean text label but I can't type korean in textinput. It just receive English.

I found simmilar issue(#1102 ) about TextInput font. (yes I already set the font_name)

Please kindly resolve this issue.
Or Please teach me how can I use non problem version build. with or without buildozer.

Thank you in advance.

**Comment by inclement** [comment]
Issue #1102  doesn't sound similar to your issue unless your keyboard presses are actually ignored.

Is your font correctly included in your apk?
