### ISSUE TITLE
please provide recipes for libraries dlib, easygui, Colormath , keras ,imutils

### ISSUE THREAD

**Issue by GUNASEKHAR333** [kivy/python-for-android#1906]
I am creating an android apk which uses above libraries. so please create recipes for above libraries as soon as possible.

**Comment by inclement** [comment]
I'm afraid we're unlikely to look at this actively, but contributions of these recipes would be welcome.

This may be hard or impractical though. In particular dlib is a big library that might need some hacking, Keras is the same but probably worse and may have many dependencies, and easygui seems to be a tkinter-based toolkit which doesn't work on Android anyway.
