### ISSUE TITLE
splash always loading 

### ISSUE THREAD

**Issue by FranciscoCarbonell** [kivy/python-for-android#1907]
i build app with bootstrap=webview, 
the application works perfect, but when I press the back button the splah comes back out and stays loaded. What I try is that this does not happen and that when you press the button to go back out of the application, is there any option to access the onResume methods ...? Is there any way to solve this problem?

**Comment by inclement** [comment]
It sounds like using the back button is closing hte app but failing to correctly open it again. This is probably some kind of bug. You can work around it by overriding the back button, e.g. as done [here](https://github.com/inclement/LazyBaduk/blob/master/nogo2/main.py#L66).
