### ISSUE TITLE
run_on_ui_thread crash

### ISSUE THREAD

**Issue by FranciscoCarbonell** [kivy/python-for-android#1908]
error output:

```
AttributeError : 'Wv' object has no attribute 'f2'

```
runable.py

```
def run_on_ui_thread(f):
    '''Decorator to create automatically a :class:`Runnable` object with the
    function. The function will be delayed and call into the Activity thread.
    '''
    def f2(*args, **kwargs):
        Runnable(f)(*args, **kwargs)
    return f2

```
python : 3.7.1
cyrhon: 0.28.6
Kivy: 1.10

**Comment by ocobacho** [comment]
Having the same problem. Solved by not using the decorator and just using a function.
`def run_ui_thread(f, *args, **kwargs):
    # args/kwargs to runnable was a bug, fixed in master
    Runnable(f)(args, kwargs)`

**Comment by inclement** [comment]
Closing as insufficiently reported. Please post a full runnable example if you're still having this issue.

**Comment by shashi278** [comment]
@ocobacho 
Get that `create_webview` out of the class instead of changing the decorator implementation and it'll work fine. Since you're using the decorator on a class method, it's searching for f2 within the class itself.

**Comment by lucasargento** [comment]
> @ocobacho
Could you please explain further?
having the same issue and i didnt get your solution.
im importing the ScreenWebView class from my main.py
thanks!

**Comment by lucasargento** [comment]
> Having the same problem. Solved by not using the decorator and just using a function.
> 
> ```
> def run_ui_thread(f, *args, **kwargs):
>     # args/kwargs to runnable was a bug, fixed in master
>     Runnable(f)(args, kwargs)
> ```

i know this issue is closed and its been a while, but could you please post your whole code on the solution? been tryng to implement it without success. thanks!

**Comment by kangpuru** [comment]
> > Having the same problem. Solved by not using the decorator and just using a function.
> > ```
> > def run_ui_thread(f, *args, **kwargs):
> >     # args/kwargs to runnable was a bug, fixed in master
> >     Runnable(f)(args, kwargs)
> > ```
> 
> i know this issue is closed and its been a while, but could you please post your whole code on the solution? been tryng to implement it without success. thanks!

Another solution is putting create_webview function outside the class. Because it likely trying to find the 'f2' inside Wv class.
```
from kivy.app import App
from jnius import autoclass
from kivy.clock import Clock
from android.runnable import run_on_ui_thread
from kivy.uix.widget import Widget

WebView = autoclass('android.webkit.WebView')
WebViewClient = autoclass('android.webkit.WebViewClient')
activity = autoclass('org.kivy.android.PythonActivity').mActivity

@run_on_ui_thread
def create_webview(self):
	webview = WebView(activity)
	webview.getSettings().setJavaScriptEnabled(True)
	wvc = WebViewClient();
	webview.setWebViewClient(wvc);
	activity.setContentView(webview)
	webview.loadUrl('https://google.com')


class Wv(Widget):
	def __init__(self, **kwargs):
		super().__init__(**kwargs)
		self.__functionstable__ = {}
		Clock.schedule_once(create_webview, 0)
	

class ServiceApp(App):
	def build(self):
		return Wv()
```

**Comment by JuditNugroho** [comment]
> > > Having the same problem. Solved by not using the decorator and just using a function.
> > > ```
> > > def run_ui_thread(f, *args, **kwargs):
> > >     # args/kwargs to runnable was a bug, fixed in master
> > >     Runnable(f)(args, kwargs)
> > > ```
> > 
> > 
> > i know this issue is closed and its been a while, but could you please post your whole code on the solution? been tryng to implement it without success. thanks!
> 
> Another solution is putting create_webview function outside the class. Because it likely trying to find the 'f2' inside Wv class.
> 
> ```
> from kivy.app import App
> from jnius import autoclass
> from kivy.clock import Clock
> from android.runnable import run_on_ui_thread
> from kivy.uix.widget import Widget
> 
> WebView = autoclass('android.webkit.WebView')
> WebViewClient = autoclass('android.webkit.WebViewClient')
> activity = autoclass('org.kivy.android.PythonActivity').mActivity
> 
> @run_on_ui_thread
> def create_webview(*args):
> 	webview = WebView(activity)
> 	webview.getSettings().setJavaScriptEnabled(True)
> 	wvc = WebViewClient();
> 	webview.setWebViewClient(wvc);
> 	activity.setContentView(webview)
> 	webview.loadUrl('https://google.com')
> 
> 
> class Wv(Widget):
> 	def __init__(self, **kwargs):
> 		super().__init__(**kwargs)
> 		self.__functionstable__ = {}
> 		Clock.schedule_once(create_webview, 0)
> 	
> 
> class ServiceApp(App):
> 	def build(self):
> 		return Wv()
> ```

hi i can run this but i can click back button in android. How can i detach this webview?. Thanks

**Comment by Sahil-pixel** [comment]
##i have this problem .on android 
I/python  (27183): [INFO   ] [Base        ] Start application main loop
I/python  (27183): [INFO   ] [Base        ] Leaving application in progress...
I/python  (27183):  Traceback (most recent call last):
I/python  (27183):    File "/home/sahil/app2/.buildozer/android/app/main.py", line 33, in <module>
I/python  (27183):    File "/home/sahil/app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/web/kivy/app.py", line 855, in run
I/python  (27183):    File "/home/sahil/app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/web/kivy/base.py", line 504, in runTouchApp
I/python  (27183):    File "/home/sahil/app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/web/kivy/core/window/window_sdl2.py", line 747, in mainloop
I/python  (27183):    File "/home/sahil/app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/web/kivy/core/window/window_sdl2.py", line 479, in _mainloop
I/python  (27183):    File "/home/sahil/app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/web/kivy/base.py", line 339, in idle
I/python  (27183):    File "/home/sahil/app2/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/web/kivy/clock.py", line 591, in tick
I/python  (27183):    File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
I/python  (27183):    File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
I/python  (27183):    File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
I/python  (27183):    File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
I/python  (27183):    File "/home/sahil/app2/.buildozer/android/app/main.py", line 13, in create_webview
I/python  (27183):    File "jnius/jnius_export_class.pxi", line 256, in jnius.jnius.JavaClass.__init__
I/python  (27183):    File "jnius/jnius_export_class.pxi", line 343, in jnius.jnius.JavaClass.call_constructor
I/python  (27183):    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
I/python  (27183):  jnius.jnius.JavaException: JVM exception occurred: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object re

**Comment by 5developer** [comment]
> Runnable(f)(args, kwargs)

can I show your code?

**Comment by 5developer** [comment]
whithout using decorator
