### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libffi.so.7" not found

### ISSUE THREAD

**Issue by Liujiangy1** [kivy/python-for-android#1924]
I put the libpython3.7m.so file and the libffi.so file in my android app, but the following happens:
I have put libffi.so in my android stduio, and I also configured my cmakelists.txt

java.lang.UnsatisfiedLinkError: dlopen failed: library "libffi.so.7" not found
         At java.lang.Runtime.loadLibrary0(Runtime.java:1016)
         At java.lang.System.loadLibrary(System.java:1657)

Is my way wrong?

**Comment by inclement** [comment]
I'm not really clear exactly what you've done, but it sounds like whatever it is it didn't result in the library being present and in the right place to get loaded by the app (if there was any code to load it at all).
