### ISSUE TITLE
JavaException: JVM exception occurred: Fail to connect to camera service

### ISSUE THREAD

**Issue by surbhicis** [kivy/python-for-android#1943]
JavaException: JVM exception occurred: Fail to connect to camera service

![Screenshot from 2019-07-30 18-13-31](https://user-images.githubusercontent.com/24718338/62132640-0dd35580-b2fb-11e9-9ac3-1eddcf2168ba.png)

**Comment by AndreMiras** [comment]
Yes this is because you need to ask for runtime permissions.

**Comment by surbhicis** [comment]
@AndreMiras I need ths workable for python 2  as my source code is in python2.7 I am using zbarcam repo for QR code scanner ,the runtime permission issue is fixed in p4a and zbarcam but the support for python2 permission issue is not there.

**Comment by AndreMiras** [comment]
Hi @surbhicis we don't have the resource to maintain Python2 in p4a.
Python2 is going officially unmaintained very soon https://pythonclock.org/
How about updating your code to be Python3 compatible?

**Comment by surbhicis** [comment]
@AndreMiras it will take month to accompalish and I spent year in making source code and if goes for converting it will take more time and I need to have my demo near ,I have implemented everything in kivy using p4a for python2 just QRCode scanner needed

**Comment by AndreMiras** [comment]
It actually takes us quite some efforts to maintain python2 compatibility, p4a is 15K lines of code. Maintaining Python2, slows down CI, can introduce bugs, slow down development and debugging process. Plus it's not fun for us to work with deprecated software. Keep in mind we're doing it in our free time.
If you're software is open source and you're lucky maybe people would help you in migrating to Python3 (things like this happen sometimes https://github.com/AndreMiras/GuyPS/pull/2).

**Comment by Julian-O** [comment]
Python2 is no longer supported. Closing as Not Planned.
