### ISSUE TITLE
How to overcome:? #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."

### ISSUE THREAD

**Issue by c0ntradicti0n** [kivy/python-for-android#1949]
I tried to package my app, that has a few dependencies, with buildozer and p4a a few times, but I run again and again into some errors. 

First I get an error, that <crypt.h> is not there. I found this workaround [https://github.com/kivy/python-for-android/issues/1575](https://github.com/kivy/python-for-android/issues/1575), that seems to work, because that brings me to the next error.
So I change the 
`~/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/pyconfig.h`
and comment the line with `#define HAVE_CRYPT_H 1` and come to:

The next error seems to complain, that my architecture doesn't fit. I don't know, if its the architecture of the NDK (linux x86_64), the compiling machine (linux x86_64) or the android target -- I assume, that is armeabi?  

I declared the dependencies for python for android in the config with: 
`--requirements=python3,kivy,regex,more_itertools,twisted`

Is that way correct or what I have to do more to get some dependencies compiled?
Is it true, that one needs to use python-for-android, when having some other dependencies as numpy instead of buildozer?
I used that pip archive for installing python for android. should I use the master branch instead?

I used Android SDK 28 and Android NDK r17c. These logs are:

`
$ p4a apk --log_level = 2
[INFO]:    Reading .p4a configuration
[WARNING]: --ndk-version is deprecated and no longer necessary, the value you passed is ignored
[WARNING]: $ANDROIDNDKVER is deprecated and no longer necessary, the value you set is ignored
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Getting Android API version from user argument: 29
[INFO]:    Available Android APIs are (28, 29)
[INFO]:    Requested API target 29 is available, continuing.
[INFO]:    Getting NDK dir from from user argument
[INFO]:    Found NDK revision 17.2.4988734
[INFO]:    Getting NDK API version (i.e. minimum supported API) from user argument
[INFO]:    Found virtualenv at /home/finn/CorpusCookApp/venv/bin/virtualenv
[INFO]:    ccache is missing, the build will not be optimized in the future.
[INFO]:    Found the following toolchain versions: ['4.9']
[INFO]:    Picking the latest gcc toolchain, here 4.9
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Found a single valid recipe set: ['constantly', 'hostpython3', 'incremental', 'libffi', 'more_itertools', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'six', 'pyjnius', 'regex', 'zope_interface', 'android', 'kivy', 'twisted']
[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name CorpusCook and requirements (python3, kivy, regex, more_itertools, twisted)
[INFO]:    Dist contains the following requirements as recipes: ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'six', 'pyjnius', 'regex', 'zope_interface', 'android', 'kivy', 'twisted']
[INFO]:    Dist will also contain modules (constantly, incremental, more_itertools) installed from pip
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Recipe build order is ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'six', 'pyjnius', 'regex', 'zope_interface', 'android', 'kivy', 'twisted']
[INFO]:    The requirements (constantly, incremental, more_itertools) were not found as recipes, they will be installed with pip.
[INFO]:    # Downloading recipes 
[INFO]:    Downloading hostpython3
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/hostpython3
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/hostpython3
[INFO]:    -> running basename https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    hostpython3 download already cached, skipping                                                                                                        
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading libffi
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/libffi
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/libffi
[INFO]:    -> running basename https://github.com/libffi/libffi/archive/v3.2.1.tar.gz
[INFO]:    libffi download already cached, skipping                                                                                                             
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading openssl
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/openssl
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/openssl
[INFO]:    -> running basename https://www.openssl.org/source/openssl-1.1.1.tar.gz
[INFO]:    openssl download already cached, skipping                                                                                                            
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading sdl2_image
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/sdl2_image
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/sdl2_image
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.tar.gz
[INFO]:    sdl2_image download already cached, skipping                                                                                                         
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading sdl2_mixer
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/sdl2_mixer
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/sdl2_mixer
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz
[INFO]:    sdl2_mixer download already cached, skipping                                                                                                         
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading sdl2_ttf
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/sdl2_ttf
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/sdl2_ttf
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    sdl2_ttf download already cached, skipping                                                                                                           
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading sqlite3
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/sqlite3
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/sqlite3
[INFO]:    -> running basename https://www.sqlite.org/2016/sqlite-amalgamation-3150100.zip
[INFO]:    sqlite3 download already cached, skipping                                                                                                            
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading python3
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/python3
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/python3
[INFO]:    -> running basename https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    python3 download already cached, skipping                                                                                                            
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading sdl2
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/sdl2
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/sdl2
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
[INFO]:    sdl2 download already cached, skipping                                                                                                               
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading setuptools
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/setuptools
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/setuptools
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/setuptools/setuptools-40.9.0.zip
[INFO]:    setuptools download already cached, skipping                                                                                                         
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading six
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/six
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/six
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
[INFO]:    six download already cached, skipping                                                                                                                
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading pyjnius
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/pyjnius
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/pyjnius
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/6553ad4.zip
[INFO]:    pyjnius download already cached, skipping                                                                                                            
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading regex
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/regex
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/regex
[INFO]:    -> running basename https://pypi.python.org/packages/d1/23/5fa829706ee1d4452552eb32e0bfc1039553e01f50a8754c6f7152e85c1b/re...(and 21 more)
[INFO]:    regex download already cached, skipping                                                                                                              
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading zope_interface
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/zope_interface
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/zope_interface
[INFO]:    -> running basename https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.3.tar.gz
[INFO]:    zope_interface download already cached, skipping                                                                                                     
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading android
[INFO]:    Skipping android download as no URL is set
[INFO]:    Downloading kivy
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/kivy
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/kivy
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.11.0.zip
[INFO]:    kivy download already cached, skipping                                                                                                               
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Downloading twisted
[INFO]:    -> running mkdir -p /home/finn/.local/share/python-for-android/packages/twisted
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/packages/twisted
[INFO]:    -> running basename https://github.com/twisted/twisted/archive/twisted-17.9.0.tar.gz
[INFO]:    twisted download already cached, skipping                                                                                                            
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    # Building all recipes for arch armeabi-v7a
[INFO]:    # Unpacking recipes
[INFO]:    Unpacking hostpython3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop                                               
[INFO]:    hostpython3 is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking libffi for armeabi-v7a
[INFO]:    -> running basename https://github.com/libffi/libffi/archive/v3.2.1.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/libffi/armeabi-v7a__ndk_target_21                                 
[INFO]:    libffi is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking openssl for armeabi-v7a
[INFO]:    -> running basename https://www.openssl.org/source/openssl-1.1.1.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/openssl/armeabi-v7a__ndk_target_21                                
[INFO]:    openssl is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking sdl2_image for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni                                              
[INFO]:    sdl2_image is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking sdl2_mixer for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni                                              
[INFO]:    sdl2_mixer is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking sdl2_ttf for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni                                              
[INFO]:    sdl2_ttf is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking sqlite3 for armeabi-v7a
[INFO]:    -> running basename https://www.sqlite.org/2016/sqlite-amalgamation-3150100.zip
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/sqlite3/armeabi-v7a__ndk_target_21                                
[INFO]:    sqlite3 is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking python3 for armeabi-v7a
[INFO]:    -> running basename https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21         
[INFO]:    python3 is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking sdl2 for armeabi-v7a
[INFO]:    -> running basename https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni                                              
[INFO]:    sdl2 is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking setuptools for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/setuptools/setuptools-40.9.0.zip
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/setuptools-python3/armeabi-v7a__ndk_target_21                     
[INFO]:    setuptools is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking six for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/six-python3/armeabi-v7a__ndk_target_21                            
[INFO]:    six is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking pyjnius for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/pyjnius/archive/6553ad4.zip
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/pyjnius-python3-sdl2/armeabi-v7a__ndk_target_21                   
[INFO]:    pyjnius is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking regex for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/d1/23/5fa829706ee1d4452552eb32e0bfc1039553e01f50a8754c6f7152e85c1b/re...(and 21 more)
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/regex-python3/armeabi-v7a__ndk_target_21                          
[INFO]:    regex is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking zope_interface for armeabi-v7a
[INFO]:    -> running basename https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.3.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/zope_interface-python3/armeabi-v7a__ndk_target_21                 
[INFO]:    zope_interface is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    -> running rm -rf /home/finn/.local/share/python-for-android/build/other_builds/android-python3-sdl2/armeabi-v7a__ndk_target_21/android
[INFO]:    -> running cp -a /home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/recipes/android/src /home/finn...(and 107 more)
[INFO]:    Unpacking kivy for armeabi-v7a
[INFO]:    -> running basename https://github.com/kivy/kivy/archive/1.11.0.zip
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/kivy-python3/armeabi-v7a__ndk_target_21                           
[INFO]:    kivy is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Unpacking twisted for armeabi-v7a
[INFO]:    -> running basename https://github.com/twisted/twisted/archive/twisted-17.9.0.tar.gz
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/twisted-python3/armeabi-v7a__ndk_target_21                        
[INFO]:    twisted is already unpacked, skipping
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    # Prebuilding recipes
[INFO]:    Prebuilding hostpython3 for armeabi-v7a
[INFO]:    hostpython3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding libffi for armeabi-v7a
[INFO]:    libffi has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for libffi[armeabi-v7a]
[INFO]:    libffi already patched, skipping
[INFO]:    Prebuilding openssl for armeabi-v7a
[INFO]:    openssl has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sdl2_image for armeabi-v7a
[INFO]:    sdl2_image has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_image[armeabi-v7a]
[INFO]:    sdl2_image already patched, skipping
[INFO]:    Prebuilding sdl2_mixer for armeabi-v7a
[INFO]:    sdl2_mixer has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for sdl2_mixer[armeabi-v7a]
[INFO]:    sdl2_mixer already patched, skipping
[INFO]:    Prebuilding sdl2_ttf for armeabi-v7a
[INFO]:    sdl2_ttf has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding sqlite3 for armeabi-v7a
[INFO]:    sqlite3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding python3 for armeabi-v7a
[INFO]:    python3 has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for python3[armeabi-v7a]
[INFO]:    python3 already patched, skipping
[INFO]:    Prebuilding sdl2 for armeabi-v7a
[INFO]:    sdl2 has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding setuptools for armeabi-v7a
[INFO]:    setuptools has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding six for armeabi-v7a
[INFO]:    six has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding pyjnius for armeabi-v7a
[INFO]:    pyjnius has no prebuild_armeabi_v7a, skipping
[INFO]:    Applying patches for pyjnius[armeabi-v7a]
[INFO]:    pyjnius already patched, skipping
[INFO]:    Prebuilding regex for armeabi-v7a
[INFO]:    regex has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding zope_interface for armeabi-v7a
[INFO]:    zope_interface has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/zope_interface-python3/armeabi-v7a__ndk_target_21/zope_interface
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Applying patches for zope_interface[armeabi-v7a]
[INFO]:    zope_interface already patched, skipping
[INFO]:    Prebuilding android for armeabi-v7a
[INFO]:    android has no prebuild_armeabi_v7a, skipping
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/android-python3-sdl2/armeabi-v7a__ndk_target_21/android
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Prebuilding kivy for armeabi-v7a
[INFO]:    kivy has no prebuild_armeabi_v7a, skipping
[INFO]:    Prebuilding twisted for armeabi-v7a
[INFO]:    twisted has no prebuild_armeabi_v7a, skipping
Should remove twisted tests etc. here, but skipping for now
[INFO]:    Applying patches for twisted[armeabi-v7a]
[INFO]:    twisted already patched, skipping
[INFO]:    # Building recipes
[INFO]:    Building hostpython3 for armeabi-v7a
[INFO]:    Skipping hostpython3 (3.7.1) build, as it has already been completed
[INFO]:    Building libffi for armeabi-v7a
[INFO]:    libffi said it is already built, skipping
[INFO]:    Building openssl for armeabi-v7a
[INFO]:    openssl said it is already built, skipping
[INFO]:    Building sdl2_image for armeabi-v7a
[INFO]:    Building sdl2_mixer for armeabi-v7a
[INFO]:    Building sdl2_ttf for armeabi-v7a
[INFO]:    Building sqlite3 for armeabi-v7a
[INFO]:    sqlite3 said it is already built, skipping
[INFO]:    Building python3 for armeabi-v7a
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/android-build
[WARNING]: Doing some hacky stuff to link properly
[INFO]:    -> running cp /home/finn/android/android-ndk-r17c/platforms/android-21/arch-arm/usr/lib/crtbegin_so.o ./
[INFO]:    -> running cp /home/finn/android/android-ndk-r17c/platforms/android-21/arch-arm/usr/lib/crtend_so.o ./
[WARNING]: lld not found, linking without it. Consider installing lld if linker errors occur.
[INFO]:    Activating flags for sqlite3
[INFO]:    Activating flags for libffi
[INFO]:    Activating flags for openssl
[INFO]:    <- directory context /home/finn/CorpusCookApp
[INFO]:    Building sdl2 for armeabi-v7a
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/bootstrap_builds/sdl2-python3/jni
[INFO]:    -> running ndk-build V=1
[INFO]:    <- directory context /home/finn/CorpusCookApp                                                                                                        
[INFO]:    Building setuptools for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    setuptools said it is already built, skipping
[INFO]:    Building six for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    six said it is already built, skipping
[INFO]:    Building pyjnius for armeabi-v7a
[INFO]:    Python package already exists in site-packages
[INFO]:    pyjnius said it is already built, skipping
[INFO]:    Building regex for armeabi-v7a
[INFO]:    regex apparently isn't already in site-packages
[INFO]:    Building compiled components in regex
[INFO]:    -> directory context /home/finn/.local/share/python-for-android/build/other_builds/regex-python3/armeabi-v7a__ndk_target_21/regex
[INFO]:    -> running python setup.py build_ext -v
           working: error: command 'arm-linux-androideabi-gcc' failed with exit status 1                                                                        Exception in thread background thread for pid 9813:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/sh-1.12.14-py3.6.egg/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/sh-1.12.14-py3.6.egg/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/sh-1.12.14-py3.6.egg/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/sh-1.12.14-py3.6.egg/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
running build_ext
building '_regex' extension
arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/finn/android/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/finn/android/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/finn/android/android-ndk-r17c/sysroot -I/home/finn/.local/share/python-for-android/build/python-installs/CorpusCook/include/python3.7 -DNDEBUG -g -fwrapv -O3 -Wall -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/finn/android/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/finn/android/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/finn/android/android-ndk-r17c/sysroot -I/home/finn/.local/share/python-for-android/build/python-installs/CorpusCook/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -I/home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build -c Python3/_regex.c -o build/temp.linux-x86_64-3.7/Python3/_regex.o
In file included from /home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include/Python.h:53:0,
                 from Python3/_regex.c:46:
/home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include/pyport.h:699:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  ^
Python3/_regex.c: In function 'basic_match':
Python3/_regex.c:13124:32: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
             try_body = changed && state->pattern->is_fuzzy || node->values[2] >
                                ^
Python3/_regex.c: In function 'do_best_fuzzy_match':
Python3/_regex.c:16855:77: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
                             if (state->total_errors < error_limit || i == 0 &&
                                                                             ^
error: command 'arm-linux-androideabi-gcc' failed with exit status 1

  STDERR:

Traceback (most recent call last):                                                                                                                              
  File "/home/finn/CorpusCookApp/venv/bin/p4a", line 10, in <module>
    sys.exit(main())
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/toolchain.py", line 1183, in main
    ToolchainCL()
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/toolchain.py", line 666, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/toolchain.py", line 152, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/toolchain.py", line 205, in build_dist_from_args
    args, "ignore_setup_py", False
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/build.py", line 557, in build_recipes
    recipe.build_arch(arch)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/recipe.py", line 883, in build_arch
    self.build_compiled_components(arch)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/recipe.py", line 895, in build_compiled_components
    _env=env, *self.setup_extra_args)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/pythonforandroid/logger.py", line 178, in shprint
    for line in output:
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/sh-1.12.14-py3.6.egg/sh.py", line 863, in next
    self.wait()
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/sh-1.12.14-py3.6.egg/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/finn/CorpusCookApp/venv/lib/python3.6/site-packages/sh-1.12.14-py3.6.egg/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
running build_ext
building '_regex' extension
arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/finn/android/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/finn/android/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/finn/android/android-ndk-r17c/sysroot -I/home/finn/.local/share/python-for-android/build/python-installs/CorpusCook/include/python3.7 -DNDEBUG -g -fwrapv -O3 -Wall -DANDROID -fomit-frame-pointer -D__ANDROID_API__=21 -mandroid -isystem /home/finn/android/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -I/home/finn/android/android-ndk-r17c/sysroot/usr/include/arm-linux-androideabi -isysroot /home/finn/android/android-ndk-r17c/sysroot -I/home/finn/.local/share/python-for-android/build/python-installs/CorpusCook/include/python3.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -I/home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build -c Python3/_regex.c -o build/temp.linux-x86_64-3.7/Python3/_regex.o
In file included from /home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include/Python.h:53:0,
                 from Python3/_regex.c:46:
/home/finn/.local/share/python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include/pyport.h:699:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  ^
Python3/_regex.c: In function 'basic_match':
Python3/_regex.c:13124:32: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
             try_body = changed && state->pattern->is_fuzzy || node->values[2] >
                                ^
Python3/_regex.c: In function 'do_best_fuzzy_match':
Python3/_regex.c:16855:77: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
                             if (state->total_errors < error_limit || i == 0 &&
                                                                             ^
error: command 'arm-linux-androideabi-gcc' failed with exit status 1

  STDERR:

`

**Comment by opacam** [comment]
Seeing the log you posted and your comments, it seems that regex's recipe it fails to compile. I tried to test it with our testapp `setup_testapp_python3_sqlite_openssl` (adding `regex` to requeriments) and it fails, complaining about missing header `crypt.h` as you mentioned...

This is usually solved by setting the recipe's class attribute: `call_hostpython_via_targetpython = False`.

I created a a pull request which fixes this issue and also upgrades regex's recipe to latests version (PR #1958). 

@c0ntradicti0n, thanks to report this issue :smile:, btw, I suggest you that you try again with the posted solution in mentioned PR...because I tried with arch `armeabi-v7a` and `arm64-v8a` for python3 without further issues, so the errors you mention shouldn't appear...
