### ISSUE TITLE
buildozer apk build problem

### ISSUE THREAD

**Issue by DevKrkita** [kivy/python-for-android#195]
i am trying to build .apk with buildozer, i get the error  # Command failed: ./distribute.sh -m "kivy"

how can i fix it?
```
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Preparing build
# Check requirements for android
# Install platform
# Apache ANT found at /home/devkirkita/.buildozer/android/platform/apache-ant-1.8.4
# Android SDK found at /home/devkirkita/.buildozer/android/platform/android-sdk-21
# Android NDK found at /home/devkirkita/.buildozer/android/platform/android-ndk-r9
# Android packages already installed.
# Check application requirements
# Compile platform
# Command failed: ./distribute.sh -m "kivy"
```

**Comment by fccoelho** [comment]
I am having the same issue as @DevKrkita. I am running Kivy 1.9.0 dev and have checked the permissions on .buildozer. I have cython 0.21.2 installed

**Comment by kloro2006** [comment]
thanks buildozer folks for yr great work!

my question: how long shd the "Compile platform" segment take? it's been running for about 1.5 an hour. i'm on Lenovo t400 with dual core processor at, i think, ~2.5GHZ.

regards

**Comment by macmittereder** [comment]
I'm still getting the "Command failed: ./distribute.sh -m "kivy" -d "appname" " error, has anyone found a fix yet?

**Comment by inclement** [comment]
This is a generic error, if you can't fix it then please post it on the kivy-users or python-for-android mailing lists, with the full verbose log.
