### ISSUE TITLE
dlopen failed: library "../../../../src/main/jniLibs/armeabi-v7a/libpython3.7m.so" not found

### ISSUE THREAD

**Issue by Liujiangy1** [kivy/python-for-android#1954]
I want to run python in my android project, I put libpython3.7m.so into my android stduio, this problem occurs, but libffi, libsqlite3, libcrypto1.1, libssl1.1 are fine, only libpython3 .7m.so will appear when loading: dlopen failed: library "../../../../src/main/jniLibs/armeabi-v7a/libpython3.7m.so" not found
I guess python-for-android modified the path, but I looked at the source and found no reason.

**Comment by inclement** [comment]
I don't understand what you're describing, under what circumstances do you get this error?
