### ISSUE TITLE
Can not Find on Google Play or Buy Premium

### ISSUE THREAD

**Issue by EndUserGames** [kivy/python-for-android#1974]
I can't seem to find your app anymore on Google Play and I've been looking for announcement to at least say why.
I bought the premium version and wish to use it (I had a keyboard phone that could run it, but now I rely on 2 phones, my Samsung S6 on Android 6MM & Sony Ecrisson Xperia Pro on Android 5LP).
So I type on hardkeys then send to phone that can run it.

I have the free version. but can't buy premium version on SGH-S6 6MM Phone.
Please Link to at least a Premium Version or way to restore purchases.

I got a Python Arsenal for my ideas
- Blender 2.79: For Blender Game Engine [No Coding], 3D Editing & Animation
- BornCG Tutorials: Easy & Simple to use Blender
- Panda3D  1.10.2 SDK & Tutor.pdf: Make Panda3D Games to port to Cub3D
- Cub3D Premium: For Panda3D
   + Doesn't seem to work on ICS, and doesn't run script on or render properly on phones w/Tegra2 
   + When I was trying to Re-make a similar Color Effect to Blender's Cycles Render, I discovered GLSL
- 4.1.2 ICS Keyboard Phone on Android 5 LP Rom: For Jotting, Python IDLEs, etc
  + If I had the Money, I would have bought a F(x) Tec Pro1 or Unihertz Titan
  + Qpython3: To practise simple Python Coding
  + Sololearn Python3.6 ScreenShots: Learn/Practise Python offline
- Prisma3D: To make draft 3D Models on the go then Export to OBJ to edit in Blender
- Pydroid3: Easy/Advance Python IDLE to use
- Python 3.6 IDLE: The same Python Version your Cub3D App is based
- Tutorials on Tkinter UI, more for Python, etc

All I need is Cub3D for Samsung S6

**Comment by AndreMiras** [comment]
What are you talking about :thinking: 
There's no such thing as free or premium version here
