### ISSUE TITLE
[question]Python for android no longer supports Error ! 

### ISSUE THREAD

**Issue by unkn513** [kivy/python-for-android#1978]
Hi / 
i have a problem after running 
buildozer android debug

`Build failed: python-for-android no longer supports running under Python 2. Either upgrade to Python 3.4 or higher (recommended), or revert to python-for-android 2019.07.08. Note that you *can* still target Python 2 on Android by including python2 in your requirements.
 Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3crystax,kivy,python3 --arch armeabi-v7a --copy-libs --color=always --storage-dir="/root/Desktop/OnlyforTest/untitled123/.buildozer/android/platform/build" --ndk-api=21
 ENVIRONMENT:
`

my p4a version is : 2019.08.09.1.dev0
how can i solve this issue ? 
i try to install p4a with pip and pip3 and installed with no error and clean. 

but how can i change the requirements from p4a ? 
in last line i see this error to : 

 Buildozer failed to execute the last command
The error might be hidden in the log above this error
 Please read the full log, and search for it before
 raising an issue with buildozer itself.
 In case of a bug report, please add a full log with log_level = 2

Tnx for your time.

**Comment by unkn513** [comment]
hi again 
i try to reinstall all package. 
but hat error still showing. 

any advice ?

**Comment by tshirtman** [comment]
Uninstall with pip, make sure it's only installed with pip3.

**Comment by unkn513** [comment]
> Uninstall with pip, make sure it's only installed with pip3.

hi tnx for your answer. 
can u tell me how can i uninstal python for android ? 
when i use p4a command. its work. 
but i cant uninstall it.

**Comment by tshirtman** [comment]
`pip uninstall python-for-android`

repeat until it says it's not installed.

then install again, but with pip3 instead of pip.
`pip3 install python-for-android`

if you use a virtualenv, make sure it's a python3 virtualenv.

**Comment by unkn513** [comment]
> `pip uninstall python-for-android`
> 
> repeat until it says it's not installed.
> 
> then install again, but with pip3 instead of pip.
> `pip3 install python-for-android`
> 
> if you use a virtualenv, make sure it's a python3 virtualenv.

tnx again. 
dude itry uninstall with pip, pip2, pip3 
and all done. 
but after installing with pip3 with your command. 
and run the buildozer android debug 

i see that error again. 
[ERROR]:   Build failed: python-for-android no longer supports running under Python 2. Either upgrade to Python 3.4 or higher (recommended), or revert to python-for-android 2019.07.08. Note that you *can* still target Python 2 on Android by including python2 in your requirements.

**Comment by tshirtman** [comment]
sorry, i missed that you used buildozer, in this case, you can just uninstall python-for-android, buildozer installs its own version anyway. I guess the solution is to use python3 to install buildozer as well, (so same thing, uninstall with pip2, then install with pip3).

**Comment by unkn513** [comment]
> sorry, i missed that you used buildozer, in this case, you can just uninstall python-for-android, buildozer installs its own version anyway. I guess the solution is to use python3 to install buildozer as well, (so same thing, uninstall with pip2, then install with pip3).

tnx MR.  i try ,then post result here .

**Comment by unkn513** [comment]
> sorry, i missed that you used buildozer, in this case, you can just uninstall python-for-android, buildozer installs its own version anyway. I guess the solution is to use python3 to install buildozer as well, (so same thing, uninstall with pip2, then install with pip3).

hi again. 
i try to uninstall what ever u said. 
and buildozer made one file with python-for-android name. 
anyway. , i dont have p4a installed on kali adter removing from pip3. 

but after enter that command (buildozer android debug)
my first error still show! 

any advice?

**Comment by tshirtman** [comment]
buildozer will automatically install the ndk and sdk as needed, if you get the aidl error, please use this command.
```
    ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;29.0.0"
```
as documented here https://buildozer.readthedocs.io/en/latest/installation.html#aidl-not-found-please-install-it

**Comment by unkn513** [comment]
> buildozer will automatically install the ndk and sdk as needed, if you get the aidl error, please use this command.
> 
> ```
>     ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;29.0.0"
> ```
> 
> as documented here https://buildozer.readthedocs.io/en/latest/installation.html#aidl-not-found-please-install-it

Hi again. 
dude i removed it the 29.0.2 build tools from sdk. 
and installed 29.0.0 with your command. 

and i use buildozer android debug. then automatically build tools updated to 29.0.2 again ! 
and aidl error return. 

here is full error : 
 ```
Run '/root/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "build-tools;29.0.2"'
 Cwd /root/.buildozer/android/platform/android-sdk
[=======================================] 100% Unzipping... android-10/lib64/lib
 Check that aidl can be executed
Search for Aidl
 Run '/root/.buildozer/android/platform/android-sdk/build-tools/29.0.2/aidl'
 Cwd None
 Aidl cannot be executed

```
any idea ?

**Comment by unkn513** [comment]
my problem isnt solve/ but i use windows instead linux and work well. 
good luck

**Comment by Arsh1219** [comment]
> `pip uninstall python-for-android`
> 
> repeat until it says it's not installed.
> 
> then install again, but with pip3 instead of pip. `pip3 install python-for-android`
> 
> if you use a virtualenv, make sure it's a python3 virtualenv.

Thanks buddy.
