### ISSUE TITLE
Leverage Docker image caching

### ISSUE THREAD

**Issue by AndreMiras** [kivy/python-for-android#2009]
The idea would be to speed up docker build (currently 10 minutes) by using the `--cache-from` flag.
Thing is we also need to `docker push` our successful builds ourselves as the DockerHub autobuild seems to mess up with `COPY` command leading to 100% cache bust when using this image.

**Comment by Julian-O** [comment]
@AndreMiras: Is this still an issue?

**Comment by AndreMiras** [comment]
We haven't solved it in p4a, but I think it's better documented in stackoverflow now.
https://stackoverflow.com/questions/54574821/docker-build-not-using-cache-when-copying-gemfile-while-using-cache-from
Also it's probably not critical and could be closed
