### ISSUE TITLE
Auto-correct / word suggestion does not work with Swiftkey/Samsung keyboard

### ISSUE THREAD

**Issue by mjuchno** [kivy/python-for-android#2010]
### Versions

* buildozer = 0.39
* Kivy = 1.11.1
* Cython = 0.29.13
* p4a = master
* SDK/NDK = default (commented out in buildozer.spec)

### Devices & keyboards:

* Samsung S7 (8.0.0), LG Stylo 4 (8.1.0)
* Samsung Keyboard, Swiftkey

### Description

When editing `TextInput` word suggestion tab does not show above Swiftkey/Samsung keyboard
Swipe dos not work as well (path shows up on Samsung keyboard but no word shows up).
Google Voice input works fine.
Setting `keyboard_suggestions` to True (which is suppose to be True by default) does nothing.

As Kivykeyboardtester-0.5-debug.apk by @inclement  gives exactly the same behavior I wonder whether it is my phone/keyboard fault or I do something wrong, or something is wrong with SDK2 (sorry if this was reported earlier).
I get the same behavior in the new Kivy Launched and when I build an apk.
I remember having the same issue about a year ago (and it was reason to stop playing with kivy). I remember that old Kivy Launcher (based on pygame and python2?) was working fine.
I would appreciate any hints.

**Comment by Franccisco** [comment]
The reason you're not getting suggestions is here:

https://github.com/kivy/python-for-android/blob/2610330cfca7f43d2fa69e175f4b9c3d09338680/pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/SDLActivity.java#L2005

[TYPE_TEXT_VARIATION_VISIBLE_PASSWORD](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_VARIATION_VISIBLE_PASSWORD) shows a keyboard for password fields. That's why you don't see suggestions, even if ```keyboard_suggestions``` is set to True.

Removing that input type should fix your issue, but as mentioned in https://github.com/kivy/python-for-android/pull/2015, a bug similar to the swipe one appears.

**Comment by mjuchno** [comment]
This is great! Thanks!
The bug you mentioned appears. I will continue replying to the pull thread you linked.

**Comment by Franccisco** [comment]
You're welcome. There's something I want to add:
At the time I'm posting this, ```keyboard_suggestions``` shouldn't work as expected, because it is not linked properly to any keyboard behavior. That said, if you turn ```keyboard_suggestions``` to False, you will see suggestions anyway.
We can keep the conversation in the PR then.

**Comment by mannutheman3** [comment]
May

> The reason you're not getting suggestions is here:
> 
> https://github.com/kivy/python-for-android/blob/2610330cfca7f43d2fa69e175f4b9c3d09338680/pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/SDLActivity.java#L2005
> 
> [TYPE_TEXT_VARIATION_VISIBLE_PASSWORD](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_VARIATION_VISIBLE_PASSWORD) shows a keyboard for password fields. That's why you don't see suggestions, even if `keyboard_suggestions` is set to True.
> 
> Removing that input type should fix your issue, but as mentioned in #2015, a bug similar to the swipe one appears.
> 
> P.S: You may want to see [this](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_AUTO_COMPLETE) and [this](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_AUTO_CORRECT).
How do I Remove that input ? please tell

**Comment by Saad5400** [comment]
> The reason you're not getting suggestions is here:
> 
> https://github.com/kivy/python-for-android/blob/2610330cfca7f43d2fa69e175f4b9c3d09338680/pythonforandroid/bootstraps/sdl2/build/src/main/java/org/libsdl/app/SDLActivity.java#L2005
> 
> [TYPE_TEXT_VARIATION_VISIBLE_PASSWORD](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_VARIATION_VISIBLE_PASSWORD) shows a keyboard for password fields. That's why you don't see suggestions, even if `keyboard_suggestions` is set to True.
> 
> Removing that input type should fix your issue, but as mentioned in #2015, a bug similar to the swipe one appears.
> 
> P.S: You may want to see [this](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_AUTO_COMPLETE) and [this](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_AUTO_CORRECT).

what about buildozer

**Comment by misl6** [comment]
Fixed via #2692

**Comment by Neizvestnyj** [comment]
Does not work with Microsoft SwiftKey (kivy: 2.2.0)

**Comment by brvier** [comment]
Swiftkey is end of life.
