### ISSUE TITLE
Support for androidx

### ISSUE THREAD

**Issue by tito** [kivy/python-for-android#2020]
[AndroidX](https://developer.android.com/jetpack/androidx)  is a new set of libraries that replaces the old Android "supports" libraries, and more.

We don't use supports libraries directly (if i recall correctly), but to activate `androidx` package, it requires a new file named `gradle.properties` with:

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by misl6** [comment]
It's starting to be quite a priority, in order to support the latest features on Google Play Services.

**Comment by RobertFlatt** [comment]
`gradle.properties` is an extra file we don't have to generate.
This can be implemented in `bootstraps/common/build/templates/build.tmpl.gradle`

Insert this block as the last item in the android{} block:
```
   ext {
      useAndroidX=true
      enableJetifier=true
   }
```
And if like me you are using "androidx.core.content.FileProvider", in buildozer.spec add:
 `  android.gradle_dependencies = "androidx.core:core:1.3.2"`

Other androidx classes may be in other packages https://maven.google.com/web/index.html

**This requires android.api=28  or greater**

I have I have used this to build and run an app implementing Android's file sharing feature.
I have not seen any side effects yet!

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/python-for-android/pull/2385
