### ISSUE TITLE
Missing javaclass when using able with previously working recipe

### ISSUE THREAD

**Issue by HelaFaye** [kivy/python-for-android#2041]
### Versions

* Python: Latest Python3
* OS: Android 8.1.0
* Kivy: Latest Kivy
* Cython: Latest Cython

### Description

I'm trying to use able to use BLE on android and getting an error about a missing javaclass (org/able/BLE). This commit was working a few days ago: https://github.com/b3b/able/commit/a9bf90dc4fafb952f10546f682c75b9d66e60be3

Test code here: https://github.com/b3b/able/tree/master/testapps/bletest
My code is here: https://github.com/slinger360/NineRiFt-Lite

### buildozer.spec

Command:

buildozer -v android release
and 
buildozer android debug
(they produce the same result)

Spec file:

https://github.com/slinger360/NineRiFt-Lite/blob/master/packaging/android-arm32/buildozer.spec
https://github.com/slinger360/NineRiFt-Lite/blob/master/packaging/android-arm64/buildozer.spec

### Logs

No error during build

**Comment by AndreMiras** [comment]
Could you share your build log?
