### ISSUE TITLE
p4a (2019.10.6) project build file management

### ISSUE THREAD

**Issue by Ham-Merhead** [kivy/python-for-android#2045]
### Versions

* Python: 3.7
* OS:   Android 10
* Kivy:  1.11.1
* Cython:  0.29.13

NDK r19c  
I use 19c because 19b is not available at 
https://developer.android.com/ndk/downloads/older_releases
SDK 29

### Description
Three issues with project build file management, these are I think new with 2019.10.6:

1) If I edit main.py  the change is not included in the apk unless I first delete main.pyc

2) "--clean_bulds" option does not appear to work, but "--clean_all" works

3) If I have two projects, both NDK 19c and SDK 29 
    First project builds and runs
    Second project build but fails with SDL Error (see image)
    p4a clean_all
    Second project builds and runs
    First project build but fails with same SDL Error 

![Screenshot_20191223-144340](https://user-images.githubusercontent.com/34464649/71390055-db284300-25a2-11ea-8b26-d371ca76ee66.png)

### buildozer.spec

Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by AndreMiras** [comment]
Could you share your `buildozer.spec` file? It looks like you're missing `python3` in your requirements

**Comment by Ham-Merhead** [comment]
Toggling between two apps each with their own .p4a 
The build of the second app (whichever that is) always fails as above
"p4a clean_all"   clears issue, till next build pair.
"p4a clean_dists" does not clear the issue

The two .p4a
```
--dist_name=fl
--private .
--package=com.fishes.fl
--name Fl
--requirements=python3,kivy
--arch=arm64-v8a
--permission INTERNET
--orientation sensor
--icon chart.png
--presplash chart.jpg
--sdk_dir /home/bobf/androidtools/sdk
--ndk_dir /home/bobf/androidtools/android-ndk-r19c
--android_api 29
--ndk-api 21
--version 0.3.35
```

```
--dist_name=rays
--private .
--package=com.fishes.rays
--name Rays
--requirements=python3,kivy
--arch=arm64-v8a
--orientation sensor
--sdk_dir /home/bobf/androidtools/sdk
--ndk_dir /home/bobf/androidtools/android-ndk-r19c
--android_api 29
--ndk-api 21
--version 0.0.0



```

**Comment by hvitis** [comment]
![image](https://user-images.githubusercontent.com/17104239/78193335-9140da00-747a-11ea-82ca-1d0af9049627.png)


Try with python older than 3.7
