### ISSUE TITLE
Hadi

### ISSUE THREAD

**Issue by hadisniper** [kivy/python-for-android#2048]
### Versions

* Python:
* OS:
* Kivy:
* Cython:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### buildozer.spec

Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by tshirtman** [comment]
looks like this was a mistake, there is no relevant information in here, please open a new issue if you found a bug.
