### ISSUE TITLE
Scraping web pages with javascript

### ISSUE THREAD

**Issue by szkr145** [kivy/python-for-android#2052]
### Versions

* Python: 3.7
* OS: Android 9
* Kivy: 1.11.1
* Cython: 0.29.14

### Description

I'm trying to scrap some information from webpage but it crashes my app.
I'm using requests_html to render webpage with javascript with it.(i need javascript render)
Is it any alternative for requests_html that work on android?
On pc it is working fine.

**Comment by hymancheng** [comment]
same question. 
someone?

**Comment by 4n1k1** [comment]
requests_html is using chromium (via pyppeteer) for rendering pages. Thus to make it work on android it also needs to be packaged as a dependency to you APK. But to package it you need to compile it for android. It's all doable but is definitely out of scope of python-for-android project.

It's more about how to make android more like linux PC if we think about "somewhat proper" implementation.
