### ISSUE TITLE
SDL Error: Error Could not load any libpythonXXX.so

### ISSUE THREAD

**Issue by chavarinbonbyn** [kivy/python-for-android#2056]
### Versions
* Python: 3.6.9
* OS: Ubuntu 18.04.3 LTS
* Kivy: 1.11.0
* Cython: 0.29.7
* Buildozer: 1.0
* Android: 7.1.2

### Description
This issue is related (but not fixed by) to  #1142. 

If one changes the default string at builddozer.spec:

# (str) Package name
package.name = myapp   (THIS ONE)

To anything else than "myapp", for example:

# (str) Package name
package.name = my_app

Even tough the app is build and no errors are shown, the following error appears on the app when opening (thus the app does not work):

SDL Error: Error Could not load any libpythonXXX.so

### buildozer.spec
Command:
buildozer -v android debug deploy run

Spec file:
*** Everything is the same but package.name***

[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = my_app

### Logs
There are no errors shown in the logs.

**Comment by Ham-Merhead** [comment]
See also 
https://github.com/kivy/buildozer/issues/1010
https://github.com/kivy/python-for-android/issues/2045

**Comment by robertpfeiffer** [comment]
I sometimes get this too

**Comment by chavarinbonbyn** [comment]
Which kivy version includes the fix ?

**Comment by Ham-Merhead** [comment]
Thank you, for addressing the issue.
@chavarinbonbyn FYI, the fix is currently only in the 'develop' branch of p4a (not kivy)
