### ISSUE TITLE
How to create my app name automatically on usb connect

### ISSUE THREAD

**Issue by marcets** [kivy/python-for-android#2071]
I'm working on android 9 and I am able to save my txt file on my usb by using this path:
 ``/storage/external_SD/Android/data/com.your.app.name/files``. Where ``external_SD`` changes in different vendors. 

When I connect my usb, a folder Android/data is automatically create but I don't see my app name in it. I have to create manually my app_name/files to be able to save my txt file.

My question is simple: It is possible to automatically create my app name/files directly on my buildozer spec, python code or AndroidManifest.xml

Reference:
pull request #1528
I can confirm that here.
Path that does work is ``/storage/external_SD/Android/data/com.your.app.name/files`` on my lollipop device.
Where ``external_SD`` changes in different vendors. 
Also it seem that latter Nugat threre was an API added for this but I don't have a device to test.

_Originally posted by @guysoft in https://github.com/kivy/python-for-android/pull/1528#issuecomment-455890500_

**Comment by smaudet** [comment]
I think you are a bit confused. You are conflating several issues here. buildozer has nothing to do with usb.

Android app paths are a different issue...

It is unclear what you mean by 'create my app name automatically'. You create your app name when you create your app. No usb is involved. This is not a help forum. This is for reporting issues or bugs with buildozer.

**Comment by marcets** [comment]
The problem is I am not allow (permisson denied) to create a folder in android/data. I tried os.mkdir function but it doesn't work. For example, I have to use my PC to create my app name folder on my usb flash drive first  and then I'm able to save my text file on usb with my kivy app.

When you mount an usb flash drive on Andoird 9 device via an usb-C connector, you will have an Android/data that is automatically create with some app folder in it. So I just want to add my app name folder to avoid several step for the user of my app.

I will close this issue because your are right, it is not really an issue from pythonforandroid.

**Comment by marcets** [comment]
I solve my problem by adding this to my code.

```
from jnius import autoclass, cast
import os


Environment = autoclass('android.os.Environment')

def _get_activity():
    """
    Retrieves the activity from `PythonActivity` fallback to `PythonService`.
    """
    PythonActivity = autoclass('org.kivy.android.PythonActivity')
    activity = PythonActivity.mActivity
    if activity is None:
        # assume we're running from the background service
        PythonService = autoclass('org.kivy.android.PythonService')
        activity = PythonService.mService
    return activity


def usb_storage_path():
    """ Locate the android/data built-in path. When a media is mount,
        it will automatically create and App-specific folder in android/data.
        Returns directory path to storage.
    """
    activity = _get_activity()
    currentActivity = cast('android.app.Activity', activity)
    context = cast('android.content.ContextWrapper',
                   currentActivity.getApplicationContext())
    file_p = cast('java.io.File', context.getExternalFilesDir(None))
    return os.path.normpath(os.path.abspath(
        file_p.getAbsolutePath().replace("/", os.path.sep)))


usb_storage_path = usb_storage_path()
print(f'usb_storage_path: {usb_storage_path}')
```

Maybe it can be add to python-for-android/pythonforandroid/recipes/android/storage.py
