### ISSUE TITLE
How to add a native Python package for kivy?

### ISSUE THREAD

**Issue by wwtghx** [kivy/python-for-android#2089]
Now, I want to add one of the following native Python packages for kivy:
    pytorch 
    keras
    tensorflow
And , What can I do?

Thanks~

**Comment by hvitis** [comment]
buildozer init
nano buildozer.spec
```
# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,pytorch,keras,tensorflow,kivy
```

**Comment by Ham-Merhead** [comment]
This is not going to work.
pytorch
keras
tensorflow
are not written in Python, and there are no recipes for compiling their C/C++/Fortran  for Android.

Calling these "native Python" is wishful thinking ;)

**Comment by AndreMiras** [comment]
Yes basically you would need to create a recipe for them https://python-for-android.readthedocs.io/en/latest/recipes/
