### ISSUE TITLE
Why advise us to use Python2???

### ISSUE THREAD

**Issue by BornForFever** [kivy/python-for-android#2090]
In your documentation, Python2 is listed in the installation dependencies. But why??? Python2 is **out of date** and **no longer** maintained. In addition, according to a [survey](https://www.jetbrains.com/research/python-developers-survey-2017/#python-3-adoption) carried out by Python Software Fundation and JetBrains, there are **3 times** as many pythoners who are using Python3 as those using Python2. Isn't it a little inappropriate to advise us to use Python2?

**Comment by 4n1k1** [comment]
I think what you mention is just docs being outdated. Python for android and Kivy both support Python 3. I think I've seen somewhere around that even 3.8 is supported.

**Comment by AndreMiras** [comment]
Definitely, actually we strongly discourage using Python2. Pull requests to update the documentation are always welcome :smile:

**Comment by BornForFever** [comment]
Sorry for misundersranding.😄

**Comment by AndreMiras** [comment]
If you saw a place where we were advising for Python 2, could you please create a pull request or maybe share where it is?

**Comment by BornForFever** [comment]
In the quickstart documentation. But I had just made a pull request. 😄

**Comment by AndreMiras** [comment]
Thanks!
