### ISSUE TITLE
No Python 3 Support

### ISSUE THREAD

**Issue by stephenmac7** [kivy/python-for-android#210]
Kivy, but not python-for android (nor buildozer) has python 3 support.

**Comment by FeralBytes** [comment]
Python 3 syntax is now possible. See [here](https://github.com/kivy/python-for-android/issues/322).

**Comment by inclement** [comment]
I'm going to close this in favour of the technical discussion at https://github.com/kivy/python-for-android/issues/484 (and that, to be clear, p4a should at least be runnable under python3 now).
