### ISSUE TITLE
Error occured while building the aplication using buildozer

### ISSUE THREAD

**Issue by neel004** [kivy/python-for-android#2104]
### Versions

* Python: 3.7.5
* OS: Ubuntu19 64-bit
* Kivy: 1.11.1
* Cython: 0.29.15

### Description
I am trying to build my application using buildozer in one of my virtualenv , while running command
" buildozer android debug " 
normally it should builde and debug application but instead of it ,
i'm getting command failed:
error 
### buildozer.spec

Command:

buildozer android debug

Spec file:

[buildozer.txt](https://github.com/kivy/python-for-android/files/4396830/buildozer.txt)

### Logs
start.c:3:
/home/neel/Downloads/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3-libffi-openssl-sqlite3/armeabi-v7a__ndk_target_21/python3/Include/Python.h:8:10: fatal error: 
      'pyconfig.h' file not found
#include "pyconfig.h"
         ^~~~~~~~~~~~
1 error generated.
make: *** [/home/neel/Downloads/.buildozer/android/platform/build-armeabi-v7a/build/bootstrap_builds/sdl2-python3/obj/local/armeabi-v7a/objs/main/start.o] Error 1

  STDERR:

[error.txt](https://github.com/kivy/python-for-android/files/4396832/error.txt)

**Comment by AndreMiras** [comment]
You truncated the log a bit too short. Could you share the complete log as this could help to come up with a fix later.
This looks like we're not linking the header path. I think this file should be copied over however.
Anyway maybe for now if you `apt install libpython3.7-dev` that would help. Also make sure to have it matched in your buildozer recipes, maybe try with `requirements = kivy,hostpython3==3.7.1,python3==3.7.1`

**Comment by AndreMiras** [comment]
I confirm I could reproduce the issue doing the `python3` recipe build with `buildozer` within a venv.
First build led me to a previous error https://github.com/kivy/python-for-android/issues/2060 and second build led me to this. So yes there's something going on with buildozer within venv it seems. My recommendation until it's fixed is to install buildozer outside the venv.
```sh
pip3 install --user buildozer
```
And update your path to match:
```sh
PATH=$PATH:~/.local/bin
```
