### ISSUE TITLE
Version bump for zeroconf to 0.25.4

### ISSUE THREAD

**Issue by mikevlz** [kivy/python-for-android#2107]
### Versions

it's all about p4a and module version, other things do not matter.

### Description

I tried to build a mobile application to work with zeroconf-enabled devices. I've got it almost working. 
The problem with python-zeroconf is that it is too old. It has a recipe with zeroconf-0.17.4, while the most recent is 0.25.4. There is a problem with that old version - i get services(devices) discovered, but can not get any additional info except the service(device) name. Moreover, Android OS does nto resolve mdns host names, so I know, there is a device with some name, but can't get it's IP-address.

I said myself, that I'm lucky enough, and changed the version string and requirements in the recipe for zeroconf module, After that I've rebuilt my application and checked the result. With the new version everything works fine, I get all info about devices, that I need.
Newer version doesn't depend on "**netifaces**", but it depends on "**ifaddr**" and "**typing**". 
Also it is ***NOT COMPATIBLE with python 2.7.***

Please, have a look at this module. May be there should be an option to use the newer version with python3.5+, while keeping older version for compatibility with python 2.7

**Comment by AndreMiras** [comment]
I think the compatibility with Python2 can go, it's not like we want to maintain it.
Pull requests for an updated recipe are welcome :)

**Comment by mikevlz** [comment]
Hello, Andre, wanted PRs? Here is one https://github.com/kivy/python-for-android/pull/2128 ;)

**Comment by mikevlz** [comment]
Since PR is merged, I think we can close this issue
