### ISSUE TITLE
openssl 1.1.1 has moved, recipe fails

### ISSUE THREAD

**Issue by Ham-Merhead** [kivy/python-for-android#2119]
Several users have reported openssl downloading as an empty file.

It appears the version in the recipe openssl==1.1.1 has moved to https://www.openssl.org/source/old/1.1.1
The location in the recipe https://www.openssl.org/source/   contains openssl==1.1.1f

As a workaround I was able to build 1.1.1f  as shown here
https://groups.google.com/d/msg/kivy-users/F0WJb8TXQBg/PwGwOFdxBAAJ

If this is permanent or a temporary openssl.org server issue I can't guess.

**Comment by thica** [comment]
Can confirm it, buildozer fails for me as well for the same reason

**Comment by moridinamael** [comment]
I would also add that if you attempt to build python3 via toolchain.py, the recipe attempts to install openssl via https://www.openssl.org/source/openssl-1.0.2k.tar.gz which is 404 address. This seems to mean the current recipe for building python3 is nonfunctional by default.

**Comment by AndreMiras** [comment]
This is solved in `p4a.branch = develop` via https://github.com/kivy/python-for-android/pull/2118
