### ISSUE TITLE
Build failed: Couldn't find executable for CC

### ISSUE THREAD

**Issue by srajith** [kivy/python-for-android#2146]
[ERROR]:   Build failed: Couldn't find executable for CC. This indicates a problem locating the /home/r4j/app/android-ndk-r19c/toolchains/llvm/prebuilt/linux-i686/bin/clang executable in the Android NDK, not that you don't have a normal compiler installed. Exiting.
# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy,requests --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/r4j/app/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     _LXSESSION_PID = '1604'
#     XDG_CONFIG_HOME = '/home/r4j/.config'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     TERMINATOR_UUID = 'urn:uuid:3018c182-39bc-4d79-8f1f-c326d383c4d4'
#     XDG_MENU_PREFIX = 'lxde-'
#     LANG = 'en_IN'
#     GDM_LANG = 'en_US'
#     DISPLAY = ':0'
#     QT_STYLE_OVERRIDE = 'gtk'
#     OLDPWD = '/home/r4j'
#     GTK_OVERLAY_SCROLLING = '0'
#     COLORTERM = 'truecolor'
#     XDG_VTNR = '7'
#     SSH_AUTH_SOCK = '/tmp/ssh-QWiOblEvKv4K/agent.1604'
#     MANDATORY_PATH = '/usr/share/gconf/Lubuntu.mandatory.path'
#     XDG_SESSION_ID = 'c2'
#     XDG_GREETER_DATA_DIR = '/var/lib/lightdm-data/r4j'
#     USER = 'r4j'
#     DESKTOP_SESSION = 'Lubuntu'
#     GOPATH = '/home/r4j/.go/'
#     DEFAULTS_PATH = '/usr/share/gconf/Lubuntu.default.path'
#     QT_QPA_PLATFORMTHEME = 'lxqt'
#     PWD = '/home/r4j/app'
#     HOME = '/home/r4j'
#     SSH_AGENT_PID = '1784'
#     QT_ACCESSIBILITY = '1'
#     XDG_SESSION_TYPE = 'x11'
#     QT_PLATFORM_PLUGIN = 'lxqt'
#     XDG_DATA_DIRS = '/etc/xdg/lubuntu:/usr/share/gdm:/var/lib/menu-xdg:/usr/share/Lubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop'
#     TERMINATOR_DBUS_NAME = 'net.tenshu.Terminator20x154d881c'
#     XDG_SESSION_DESKTOP = 'Lubuntu'
#     TERMINATOR_DBUS_PATH = '/net/tenshu/Terminator2'
#     TERM = 'xterm-256color'
#     SHELL = '/bin/bash'
#     VTE_VERSION = '5202'
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     XDG_CURRENT_DESKTOP = 'LXDE'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     XDG_SEAT = 'seat0'
#     SHLVL = '1'
#     LANGUAGE = 'en_US'
#     GDMSESSION = 'Lubuntu'
#     LOGNAME = 'r4j'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:abstract=/tmp/dbus-kVdJWVkgH6,guid=3e7964f2ada580b4212a58a15e9d234a'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     XAUTHORITY = '/home/r4j/.Xauthority'
#     GOBIN = '/home/r4j/.go/bin'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session0'
#     XDG_CONFIG_DIRS = '/etc/xdg/lubuntu:/etc/xdg/xdg-Lubuntu:/etc/xdg'
#     PATH = '/home/r4j/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/r4j/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/r4j/.go/bin:/home/r4j/.local/bin/'
#     PS1 = '\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]$ '
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     _ = '/usr/local/bin/buildozer'
#     PACKAGES_PATH = '/home/r4j/.buildozer/android/packages'
#     ANDROIDSDK = '/home/r4j/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/r4j/app/android-ndk-r19c'
#     ANDROIDAPI = '27'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by Ham-Merhead** [comment]
--ndk-api=21
try 19b or 19c

**Comment by srajith** [comment]
hey thanks ive figured out i ran it on a 64 bit machine it worked
