### ISSUE TITLE
[moved] pyo files are not being recreated by ./build.py in python for android

### ISSUE THREAD

**Issue by aspidites** [kivy/python-for-android#216]
moved from [kivy/kivy](https://github.com/kivy/kivy/issues/1961)

originally reported by @blissGitHub:

    I wrote the app on desktop and tested it.
    It worked fine.
    So I then compiled it through the ubuntu vm provided by kivy.
    Initially the pyo files were created.  After I realised that the code changes I've been making is not     
    being applied in p4a, I decided to delete the pyo files.
    After that I did the ./distribute.sh -m "kivy" and then did the ./build.py....
    this time however the .pyo files were not recreated and eventually I found out that my apk crashes.
    So I had to manually create it through:
    "python -O -m compileall /path/to/files"

    Then ran ./build.py  again....this time it worked......

**Comment by inclement** [comment]
I haven't seen this come up again, so I'll close as probably fixed. Please raise it again if it recurs.
