### ISSUE TITLE
specify python version

### ISSUE THREAD

**Issue by pythonisgreaterthanr** [kivy/python-for-android#2203]
Hello, I was wondering how you specify what version of python3 you want to use. I have some code that only runs on 3.7 and when I use --requirements python3 it installs python 3.8. Is their a way to change this or is it determined by the version of python already installed on the machine

note: I am new to GitHub so if this is the wrong place to post this please just let me know and redirect me to the right spot

**Comment by mzakharocsc** [comment]
```requirements = hostpython3==3.7.1,python3==3.7.1, kivy, etc```

**Comment by pythonisgreaterthanr** [comment]
thank you for the help
