### ISSUE TITLE
running python 3.6

### ISSUE THREAD

**Issue by pythonisgreaterthanr** [kivy/python-for-android#2204]
I was trying to do --requirements=python3.6 and it gave me an error stating that no version satisfies that requirement. Is their any way to create a python3.6 recipe as I found 3.7 and 3.8 will not work for my current use.

**Comment by AndreMiras** [comment]
You need to match an existing version https://www.python.org/downloads/ e.g. `python3==3.6.10`. You also need to do the same for `hostpython3==3.6.10`.
By the way for support questions ask on the support channels on Discord
