### ISSUE TITLE
apk size growing

### ISSUE THREAD

**Issue by Ham-Merhead** [kivy/python-for-android#2207]
### Versions

* Python:  3.8.2
* OS:   Win10/WSL/Ubuntu20.04
* Kivy: 1.11.1
* Cython: 0.29.17

### Description
Building "Hello World" in an empty directory:

buildozer init        
buildozer android debug

Results in an apk that is 28MB

p4a 2020.4.29 (NDK 19c, SDK 29, armeapi-v7a ) also gives 28MB
p4a 2020.4.29 (NDK 19c, SDK 29, arm64-v8a ) gives 21MB

Not long ago this was 12MB 

Is 28MB the new normal?

### buildozer.spec

Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build ouput containing the error
```

**Comment by AndreMiras** [comment]
Yes there's is already a recent bug created for it. Basically the app is now built with debug symbols turned on by default. We're working on updating this behaviour

**Comment by Ham-Merhead** [comment]
@AndreMiras 
( I get that this is still develop and not master)
Are 32bit and 64bit apks back to 12+-1 MB?
Is this the default behavior for  `p4a apk  ` and  `buildozer android debug` ?

**Comment by AndreMiras** [comment]
Yes exactly this is in develop and it's the default behaviour

**Comment by Ham-Merhead** [comment]
@AndreMiras 
Thanks, what size should we expect for a minimal app?
With 'master' (so pre changes) I currently have:
```
-rw-rw-rw- 1 bobf bobf 26641790 May 25 19:05 myapp__arm64-v8a-0.1-arm64-v8a-debug.apk
-rw-rw-rw- 1 bobf bobf 20604779 May 25 19:04 myapp__arm64-v8a-0.1-arm64-v8a-release-unsigned.apk
-rw-rw-rw- 1 bobf bobf 28404714 May 25 16:42 myapp__armeabi-v7a-0.1-armeabi-v7a-debug.apk
-rw-rw-rw- 1 bobf bobf 22180441 May 25 18:51 myapp__armeabi-v7a-0.1-armeabi-v7a-release-unsigned.apk

```

**Comment by AndreMiras** [comment]
I haven't tried, give it a go on develop and you tell me :smile: 
The CI build artifact of last develop build is between 18M and 20M, even though the app is not really minimal

**Comment by Ham-Merhead** [comment]
Why didn't I think of trying develop?!  ;)
Minimal app, I get a nice, 13MB or so.
Thank you.
```
-rw-rw-rw- 1 bobf bobf 13555979 May 26 12:49 myapp__arm64-v8a-0.1-arm64-v8a-debug.apk
-rw-rw-rw- 1 bobf bobf 12989887 May 26 12:50 myapp__arm64-v8a-0.1-arm64-v8a-release-unsigned.apk
-rw-rw-rw- 1 bobf bobf 13282813 May 26 13:04 myapp__armeabi-v7a-0.1-armeabi-v7a-debug.apk
-rw-rw-rw- 1 bobf bobf 12937257 May 26 13:03 myapp__armeabi-v7a-0.1-armeabi-v7a-release-unsigned.apk
```
