### ISSUE TITLE
Compile for x86 on MacOS

### ISSUE THREAD

**Issue by hoba87** [kivy/python-for-android#2215]
### Versions

* Python: 3.8.2
* OS: MacOS 10.14.6
* Kivy: 1.11.1
* Cython: 0.29.19
* python-for-android 2020.4.29.dev0

### Description

I want to compile an app for android to execute in the emulator in MacOS. Compiling for Android is failing on stage "Building pyjnius for x86". 

### buildozer.spec

Command:
```sh
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

p4a apk --arch x86 --dist_name sk --private . --package=com.hb.sk --name sk --version 0.5 --bootstrap sdl2 --requirements=python3,kivy --sdk-dir ~/.buildozer/android/platform/android-sdk/ --ndk-dir ~/.buildozer/android/platform/android-ndk-r19c --android-api "27"
```

### Logs

> [INFO]:    Building pyjnius for x86
> [INFO]:    jnius apparently isn't already in site-packages
> [INFO]:    Cythonizing anything necessary in pyjnius
> [INFO]:    -> directory context /Users/user/.python-for-android/build/other_builds/pyjnius-sdl2/x86__ndk_target_21/pyjnius
> [INFO]:    -> running python3 -c import sys; print(sys.path)
> [INFO]:    Trying first build of pyjnius to get cython files: this is expected to fail                                               
> [INFO]:    -> running python3 setup.py build_ext -v
>            working: error: command '/Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llv...(and 61 more)  Exception in thread background thread for pid 78927:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/user/repositories/venv38/lib/python3.8/site-packages/sh.py", line 1662, in wrap
>     fn(*args, **kwargs)
>   File "/Users/user/repositories/venv38/lib/python3.8/site-packages/sh.py", line 2606, in background_thread
>     handle_exit_code(exit_code)
>   File "/Users/user/repositories/venv38/lib/python3.8/site-packages/sh.py", line 2304, in fn
>     return self.command.handle_command_exit_code(exit_code)
>   File "/Users/user/repositories/venv38/lib/python3.8/site-packages/sh.py", line 877, in handle_command_exit_code
>     raise exc
> sh.ErrorReturnCode_1: 
> 
>   RAN: /Users/user/.python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v
> 
>   STDOUT:
> warning: [options] bootstrap class path not set in conjunction with -source 1.7
> 1 warning
> running build_ext
> building 'jnius' extension
> creating build
> creating build/temp.macosx-10.14-x86_64-3.8
> creating build/temp.macosx-10.14-x86_64-3.8/jnius
> /Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -target i686-linux-android21 -fomit-frame-pointer -march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -target i686-linux-android21 -fomit-frame-pointer -march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32 -I/Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include -DANDROID -D__ANDROID_API__=21 -I/Users/user/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/i686-linux-android -I/Users/user/.python-for-android/build/python-installs/skullking/include/python3.8 -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac/include -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac/include/linux -I/Users/user/.python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include -I/Users/user/.python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build -c jnius/jnius.c -o build/temp.macosx-10.14-x86_64-3.8/jnius/jnius.o
> clang: error: no such file or directory: 'jnius/jnius.c'
> clang: error: no input files
> error: command '/Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang' failed with exit status 1
> 
> 
>   STDERR:
> 
>                                                                                                                                      
> [INFO]:    pyjnius first build failed (as expected)
> [INFO]:    Running cython where appropriate
> [INFO]:    Cythonize jnius/jnius.pyx
> [INFO]:    -> running python3 -m Cython.Build.Cythonize ./jnius/jnius.pyx
> [INFO]:    -> running python3 setup.py build_ext -v                                                                                  
>            working: error: command '/Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llv...(and 61 more)  Exception in thread background thread for pid 78938:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/user/repositories/venv38/lib/python3.8/site-packages/sh.py", line 1662, in wrap
>     fn(*args, **kwargs)
>   File "/Users/user/repositories/venv38/lib/python3.8/site-packages/sh.py", line 2606, in background_thread
>     handle_exit_code(exit_code)
>   File "/Users/user/repositories/venv38/lib/python3.8/site-packages/sh.py", line 2304, in fn
>     return self.command.handle_command_exit_code(exit_code)
>   File "/Users/user/repositories/venv38/lib/python3.8/site-packages/sh.py", line 877, in handle_command_exit_code
>     raise exc
> sh.ErrorReturnCode_1: 
> 
>   RAN: /Users/user/.python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v
> 
>   STDOUT:
> warning: [options] bootstrap class path not set in conjunction with -source 1.7
> 1 warning
> running build_ext
> building 'jnius' extension
> /Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -target i686-linux-android21 -fomit-frame-pointer -march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -target i686-linux-android21 -fomit-frame-pointer -march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32 -I/Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include -DANDROID -D__ANDROID_API__=21 -I/Users/user/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/i686-linux-android -I/Users/user/.python-for-android/build/python-installs/skullking/include/python3.8 -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac/include -I/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/javac/include/linux -I/Users/user/.python-for-android/build/other_builds/hostpython3/desktop/hostpython3/Include -I/Users/user/.python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build -c jnius/jnius.c -o build/temp.macosx-10.14-x86_64-3.8/jnius/jnius.o
> jnius/jnius.c:10775:19: warning: assigning to 'jchar *' (aka 'unsigned short *')
>       from 'const jchar *' (aka 'const unsigned short *') discards qualifiers
>       [-Wincompatible-pointer-types-discards-qualifiers]
>   ...= (__pyx_v_j_env[0])->GetStringChars(__pyx_v_j_env, __pyx_v_j_string, NULL);
>      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> jnius/jnius.c:49914:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:50078:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:50177:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:50284:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:50409:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:50576:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:50757:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:50918:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:51062:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:51251:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:51370:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:51631:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:51777:3: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>   0, /*tp_print*/
>   ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> jnius/jnius.c:57920:5: warning: 'tp_print' is deprecated
>       [-Wdeprecated-declarations]
>     0,
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 
>       'tp_print' has been explicitly marked deprecated here
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
>     ^
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 
>       expanded from macro 'Py_DEPRECATED'
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
>                                                      ^
> 15 warnings generated.
> creating build/lib.macosx-10.14-x86_64-3.8
> creating build/lib.macosx-10.14-x86_64-3.8/jnius
> /Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -target i686-linux-android21 -fomit-frame-pointer -march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32 -shared -L/Users/user/.python-for-android/build/libs_collections/skullking/x86 -L/Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/android-build -lpython3.8m -L/Users/user/.python-for-android/build/libs_collections/skullking/x86 -L/Users/user/.python-for-android/build/libs_collections/skullking -L/Users/user/.python-for-android/build/bootstrap_builds/sdl2/obj/local/x86 -target i686-linux-android21 -fomit-frame-pointer -march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32 -I/Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include -DANDROID -D__ANDROID_API__=21 -I/Users/user/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/i686-linux-android -I/Users/user/.python-for-android/build/python-installs/skullking/include/python3.8 build/temp.macosx-10.14-x86_64-3.8/jnius/jnius.o -Llibs/None -lSDL2 -llog -o build/lib.macosx-10.14-x86_64-3.8/jnius/jnius.cpython-38-darwin.so
> /Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: build/temp.macosx-10.14-x86_64-3.8/jnius/jnius.o: relocation R_386_GOTOFF against preemptible symbol __pyx_module_is_main_jnius__jnius cannot be used when making a shared object
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> error: command '/Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang' failed with exit status 1
> 
> 
>   STDERR:
> 
> [INFO]:    STDOUT (last 20 lines of 185):                                                                                            
> 	                                                     ^	
> jnius/jnius.c:57920:5: warning: 'tp_print' is deprecated	
>       [-Wdeprecated-declarations]	
>     0,	
>     ^	
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/cpython/object.h:260:5: note: 	
>       'tp_print' has been explicitly marked deprecated here	
>     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);	
>     ^	
> /Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include/pyport.h:515:54: note: 	
>       expanded from macro 'Py_DEPRECATED'	
> #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))	
>                                                      ^	
> 15 warnings generated.	
> creating build/lib.macosx-10.14-x86_64-3.8	
> creating build/lib.macosx-10.14-x86_64-3.8/jnius	
> /Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -target i686-linux-android21 -fomit-frame-pointer -march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32 -shared -L/Users/user/.python-for-android/build/libs_collections/skullking/x86 -L/Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/android-build -lpython3.8m -L/Users/user/.python-for-android/build/libs_collections/skullking/x86 -L/Users/user/.python-for-android/build/libs_collections/skullking -L/Users/user/.python-for-android/build/bootstrap_builds/sdl2/obj/local/x86 -target i686-linux-android21 -fomit-frame-pointer -march=i686 -mtune=intel -mssse3 -mfpmath=sse -m32 -I/Users/user/.python-for-android/build/other_builds/python3/x86__ndk_target_21/python3/Include -DANDROID -D__ANDROID_API__=21 -I/Users/user/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/i686-linux-android -I/Users/user/.python-for-android/build/python-installs/skullking/include/python3.8 build/temp.macosx-10.14-x86_64-3.8/jnius/jnius.o -Llibs/None -lSDL2 -llog -o build/lib.macosx-10.14-x86_64-3.8/jnius/jnius.cpython-38-darwin.so	
> /Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: build/temp.macosx-10.14-x86_64-3.8/jnius/jnius.o: relocation R_386_GOTOFF against preemptible symbol __pyx_module_is_main_jnius__jnius cannot be used when making a shared object	
> clang: error: linker command failed with exit code 1 (use -v to see invocation)	
> error: command '/Users/user/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang' failed with exit status 1
> [INFO]:    STDERR:
> 	
> [INFO]:    COMMAND:
> cd /Users/user/.python-for-android/build/other_builds/pyjnius-sdl2/x86__ndk_target_21/pyjnius && /Users/user/.python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py build_ext -v
> 
> [WARNING]: ERROR: /Users/user/.python-for-android/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 failed!

**Comment by C1em** [comment]
I got exactly the same issue with:
- Python: 3.7.0
- OS: MacOS 10.14.5
- Kivy: 1.11.1
- Cython: 0.28.2
- python-for-android 2020.06.02

Also building for ARM works as expected it's just for x86.

**Comment by davizucon** [comment]
Yes, same here:

Kivy: 2.0.0
pyjnius: 1.3.0
Cython: 0.29.19
OS: 10.15.7
Python : 3.8

**Comment by Rizzist** [comment]
hopefully someone has found a solution. ARM Works, but x86 and x86_64 does not

Kivy: 2.1.0
pyjnius: 1.4.2
Cython: 0.29.19
OS: 12.4
Python: 3.9.9

**Comment by misl6** [comment]
The issue seems fixed in the recently released `python-for-android` and `buildozer` versions, feel free to re-open the issue if it persists on your side, after the upgrade.

PS: Feel free to join us on [Discord](https://chat.kivy.org)
