### ISSUE TITLE
error for package apk

### ISSUE THREAD

**Issue by MichaelJackson380** [kivy/python-for-android#223]
I write a small app using kivy,and it runs on my computer and Android's Kvlauncher successfully.But when I try to package it into an apk,errors come.I use the testdrive ,the vbox image downloaded from the official site.I just do as the docs say.But when I use build.py,failed.then I tryed buildozer,also failed.there is the output.............................................Updated project.properties
Updated local.properties
----------
build.xml: Failed to find version-tag string. File must be updated.
In order to not erase potential customizations, the file will not be automatically regenerated.
If no changes have been made to the file, delete it manually and run the command again.
If you have made customizations to the build process, the file must be manually updated.
It is recommended to:
	* Copy current file to a safe location.
	* Delete original file.
	* Run command again to generate a new file.
	* Port customizations to the new file, by looking at the new rules file
	  located at <SDK>/tools/ant/build.xml
	* Update file to contain
	      version-tag: custom
	  to prevent file from being rewritten automatically by the SDK tools.
----------
Updated file ./proguard-project.txt
It seems that there are sub-projects. If you want to update them
please use the --subprojects parameter.
Listing /home/kivy/android/python-for-android/dist/default/private ...
Listing /home/kivy/android/python-for-android/dist/default/private/include ...
Listing /home/kivy/android/python-for-android/dist/default/private/include/python2.7 ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7 ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/bsddb ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/compiler ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/config ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/distutils ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/distutils/command ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/email ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/email/mime ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/encodings ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/hotshot ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/importlib ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/json ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/lib-dynload ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/logging ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/multiprocessing ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/multiprocessing/dummy ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/plat-linux3 ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/pydoc_data ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/PIL ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/jnius ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/adapters ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/audio ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/camera ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/clipboard ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/gl ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/image ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/spelling ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/text ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/video ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/core/window ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/data ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/data/fonts ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/data/glsl ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/data/images ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/data/keyboards ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/data/logo ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/effects ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/ext ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/extras ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/graphics ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/input ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/input/postproc ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/input/providers ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/lib ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/lib/gstplayer ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/lib/osc ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/lib/vidcore_lite ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/modules ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/network ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/storage ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/kivy/uix ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/threads ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/sqlite3 ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/sqlite3/test ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/unittest ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/wsgiref ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/xml ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/xml/dom ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/xml/etree ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/xml/parsers ...
Listing /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/xml/sax ...
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/libpymodules.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/include/python2.7/pyconfig.h
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python27.zip
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/README
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/PIL.pth
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/surface.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/midi.pyo
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/compat.pyo
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/mouse.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/transform.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/joystick.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/pkgdata.pyo
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/image.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/key.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/constants.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/sysfont.pyo
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/colordict.pyo
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/surflock.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/display.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/pygame.ico
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/color.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/cursors.pyo
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/mask.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/base.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/_arraysurfarray.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/rect.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/imageext.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/fastevent.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/time.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/pygame_icon.tiff
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/overlay.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/font.so
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/sprite.pyo
assets/private.mp3: /home/kivy/android/python-for-android/dist/default/private/lib/python2.7/site-packages/pygame/rwobject.so
assets/private.mp3: /home/kivy/android/python-for-android/d......................................................................................[0m[1;34m# Check configuration tokens[0m
[0m[1;34m# Ensure build layout[0m
[0m[1;34m# Check configuration tokens[0m
[0m[1;34m# Preparing build[0m
[0m[1;34m# Check requirements for android[0m
[0m[1;34m# Install platform[0m
[0m[1;34m# Apache ANT found at /home/kivy/.buildozer/android/platform/apache-ant-1.8.4[0m
[0m[1;34m# Android SDK found at /home/kivy/android/android-sdk-linux[0m
[0m[1;34m# Android NDK found at /home/kivy/android/android-ndk-r8c[0m
[0m[1;34m# Android packages already installed.[0m
[0m[1;34m# Check application requirements[0m
[0m[1;34m# Check garden requirements[0m
[0m[1;31m# Command failed: virtualenv-2.7 --python=python2.7 ./venv[0m

**Comment by FeralBytes** [comment]
This seems like a Buildozer issue not p4a.
@MichaelJackson380: in the buildozer.spec set log_level to equal 2. Then post back with an updated log.

**Comment by inclement** [comment]
Closing as inactive, please raise it again if the issue recurs.
