### ISSUE TITLE
Build failed for Pillow recipe when targeting x86_64 arch

### ISSUE THREAD

**Issue by misl6** [kivy/python-for-android#2259]
### Checklist

- [x] the issue is indeed a bug and not a support request
- [x] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [x] I have a short, runnable example that reproduces the issue
- [x] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [x] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: python3.8
- OS: Ubuntu 20.04
- Kivy: master
- Cython: 0.29.17
- OpenJDK: 1.8.0_252

### Description

Building the `Pillow` recipe for x86_64 arch fails

### buildozer.spec

Command:
```sh
buildozer android release
```

Spec file:
```
# (int) Android API to use
android.api = 28

# (int) Minimum API required. You will need to set the android.ndk.api to be as low as this value.
android.minapi = 23

# (int) Android SDK version to use
android.sdk = 26

# (str) Android NDK version to use
android.ndk = 19b

# (int) Android NDK API to use (optional). This is the minimum API your app will support.
android.ndk_api = 23

....
# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86
android.arch = x86_64
.....
# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = openssl, python3, kivy==master, android, ....., libiconv, libzbar, Pillow, pyzbar, zbarcam, xcamera
```

### Logs

```
    self.build_extensions()
  File "setup.py", line 597, in build_extensions
    raise RequiredDependencyException(f)
__main__.RequiredDependencyException: zlib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 807, in <module>
    raise RequiredDependencyException(msg)
__main__.RequiredDependencyException: 

The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html
```

The bug also appears here: https://github.com/kivy/python-for-android/pull/2257

**Comment by 83-p** [comment]
If arch is x86_64, the NDK library path will be /usr/lib64. Pillow recipes need to change `ndk_lib_dir = join(self.ctx.ndk_platform, 'usr', 'lib')` to `ndk_lib_dir = join(self.ctx.ndk_platform, 'usr', 'lib64')`.
Please change `zlib_lib_path = join(self.ctx.ndk_platform, 'usr', 'lib')` to `zlib_lib_path = join(self.ctx.ndk_platform, 'usr', 'lib64')` for the Python3 recipe.
Other recipes also need to check the NDK library path.

**Comment by akshayaurora** [comment]
Fixed in develop branch.
