### ISSUE TITLE
OSX build error if more than one pure-python module

### ISSUE THREAD

**Issue by alanjds** [kivy/python-for-android#226]
`distribute.sh` is creating a bad `requirements.txt` in OSX if multiple pure-python modules are provided:
```
./distribute.sh -m "kivy pygments requests"
(...)
Create a requirement file for pure-python modules
Install pure-python modules via pip in venv
Downloading/unpacking requestsnpygments (from -r requirements.txt (line 1))
```
Because of this: http://stackoverflow.com/q/6111679/798575

I changed the [line 723](https://github.com/kivy/python-for-android/blob/ec8d54b3844dbeab18dba3f2f23c7bf68045083d/distribute.sh#L723) manually from:
```
    try echo "$PYMODULES" | try sed 's/\ /\n/g' > requirements.txt
```

to 
```
    try echo "$PYMODULES" | try sed 's/\ /\
/g' > requirements.txt
```

and worked. Is this an acceptable patch on all platforms?

**Comment by inclement** [comment]
Fixed in the new toolchain, and possibly in the old one. Thanks for reporting it.
