### ISSUE TITLE
How to hiding Android keyboard in kivy?

### ISSUE THREAD

**Issue by onsunsl** [kivy/python-for-android#2268]
### Versions

- Python:  Python3.6.8
- OS: Ubuntu
- Kivy: 1.11.1
- Cython: 0.29.1
- OpenJDK: 1.8

### Description

I have implemented a small numeric keyboard myself. The Android soft keyboard will pop up automatically when TextInput gets the focus, and I need to only respond to a custom keyboard or an external physical keyboard. How can I hide the Android soft keyboard? 
Thank all

**Comment by obfusk** [comment]
It [looks](https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/android/src/android/_android.pyx#L233) like you should be able to use `android.hide_keyboard()`.

**Comment by shijiqing** [comment]
> @onsunsl Have you hidden the keyboard?
