### ISSUE TITLE
`future_builtins` shouldn't be blacklisted

### ISSUE THREAD

**Issue by oprypin** [kivy/python-for-android#228]
So I started my Kivy application on Android, only to have it crash right after the loading screen.
To my great surprise, the cause of the problem was:

```
from future_builtins import *
```

As I later found out, this is because the module is blacklisted.

This module is very useful for making Python 2 ~~bearable~~ behave more like Python 3  and it makes single-codebase 2.x+3.x compatibility easy. It is also very small (_future_builtins.c_ is 3.0 KiB and _future_builtins.so_ is 7.5 KiB).
I think it should not be blacklisted.
##

**Comment by FeralBytes** [comment]
Although I agree. [This issue](https://github.com/kivy/python-for-android/issues/322) has details to help you use Python 3 syntax.

**Comment by inclement** [comment]
This was never blacklisted under SDL2, and I've removed it from the old pygame backend too.
