### ISSUE TITLE
System.currentTimeMillis() returns a negative number

### ISSUE THREAD

**Issue by jtoledo1974** [kivy/python-for-android#229]
From Kivy Remote Shell

>>> from jnius import autoclass
>>> System = autoclass('java.lang.System')
>>> System.currentTimeMillis()
-1605849459

It is supposed to be a long integer

**Comment by inclement** [comment]
Do you (or anyone else) know if this is still an issue? I guess it's a pyjnius problem anyway, not something to change in p4a.

**Comment by brentpicasso** [comment]
I just noticed this fetching the time value from android.location.Location - getTime() returns a negative value when calling from python. Using latest pyjnius.
