### ISSUE TITLE
verify downloads using sha256?

### ISSUE THREAD

**Issue by obfusk** [kivy/python-for-android#2294]
Most recipe downloads use https -- but some use http! -- which should provide reasonable security for most scenarios.
But IMHO best practice would be to verify sha256 hashes "just in case". And always for for http downloads!

I'm not sure how to handle the case where the user specifies a different version yet.
Might be good to have a mapping of (historical) versions to shasums instead of only the sum for the latest version?

(This would replace the current -- seldomly used -- md5sum.)

**Comment by AndreMiras** [comment]
Thank you for bringing it to the discussion.
I think we're better of simply moving all the remaining http to https

**Comment by obfusk** [comment]
>  I think we're better of simply moving all the remaining http to https

FYI: the official [`libxml2` site](http://xmlsoft.org) doesn't have working https. Downloading from [gitlab](https://gitlab.gnome.org/GNOME/libxml2/-/tags) or [github](https://github.com/GNOME/libxml2/releases) should work though.

**Comment by AndreMiras** [comment]
Shame on them, yes I'd definitely go for gitlab/github then

**Comment by fuzzyTew** [comment]
#2351

**Comment by fuzzyTew** [comment]
#2351 has been merged; `sha256sum` may work in recipes now.
