### ISSUE TITLE
Integrating ads in P4A

### ISSUE THREAD

**Issue by SonofPoseidon1982** [kivy/python-for-android#2295]
I have written an android app in Python. I used Google admob (Kivmob), but my account got suspended due to some breach of service (Not intentional on my part). I'm thinking of using unity or some other source of advertising. My question is, could I place these ads in my Python app with pyjnius? Are there stability issues and what is best option for future advertising in my app?

**Comment by tshirtman** [comment]
This is not a bug report, but a support/help request, please ask for such things in the support channels, thanks
