### ISSUE TITLE
Reportlab bitbucket link is not working anymore

### ISSUE THREAD

**Issue by marcets** [kivy/python-for-android#2310]
Since august, bitbucket for reporlab is not working anymore (see link in reportlab recipe __init__.py). I'm not an expert with recipes, but I think that we need to updated the url link with github mirror: https://github.com/MrBitBucket/reportlab-mirror/.

possible solution:
to change in __init__.py:
```
    version = 'c088826211ca'
    url = 'https://bitbucket.org/rptlab/reportlab/get/{version}.tar.gz'
```

to:
```
    version = '???' #I don't know the version in bitbucket
    url = 'https://github.com/MrBitBucket/reportlab-mirror/ReportLab_{version}.tar.gz'
```

**Comment by marcets** [comment]
It seems to work with those 2 lines in __init__.py.
```
    version = '3_3_0'
    url = 'https://github.com/MrBitBucket/reportlab-mirror/archive/ReportLab_{version}.tar.gz'
```

**Comment by marcets** [comment]
Maybe a better solution (directly from source):

```
    version = 'fe660f227cac'
    url = 'https://hg.reportlab.com/hg-public/reportlab/archive/{version}.tar.gz'
```

**Comment by AndreMiras** [comment]
Thank you for the report. Please feel free to make a pull request
