### ISSUE TITLE
C extension overlap

### ISSUE THREAD

**Issue by kived** [kivy/python-for-android#232]
All of the C extensions are combined into one library, to get around the Android `dlopen()` limit. However, this causes issues when you have modules in C extensions with the same name.

For example, if you have two C extensions `a` and `b`, and they have modules `a.mod` and `b.mod`, the application will not work. Both extensions will produce a file `mod.so`, and will be copied into the same directory and so one will overwrite the other. I did some testing by putting each package/recipe's output in its own directory, but that has issues as well. The C extension modules have an init function which is not namespaced - it will be called `init_mod()` in both modules, so the functions overlap when added to the same library.

I'm not really sure what a good fix is for this, I just wanted to make sure that it's a known issue.

**Comment by inclement** [comment]
I'm going to close this, since skipping biglink is now well supported, although modifying the symbols to prevent clashes might still be nice.
