### ISSUE TITLE
Cannot run Py4A APKs on Android x86

### ISSUE THREAD

**Issue by brousch** [kivy/python-for-android#233]
APKs created by python-for-android fail immediately when running on Android x86. This blog post may offer a solution http://danilogiulianelli.blogspot.fr/2013/01/how-to-build-python-4-android-for-x86.html

Android x86 images and installers can be found at http://www.android-x86.org/download

**Comment by inclement** [comment]
Closing in favour of https://github.com/kivy/python-for-android/issues/492 (which will also be fixed shortly).
