### ISSUE TITLE
Buildozer ValueError: specify a path with --storage-dir

### ISSUE THREAD

**Issue by annouoos** [kivy/python-for-android#2331]
My path is correct `~/kivy` just nothing else .. But when I building apk I had this problem ValueError: storage dir path cannot contain spaces, please specify a path with --storage-dir

The report : 

`File "/root/kivy/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 173, in setup_dirs                                                       raise ValueError('storage dir path cannot contain spaces, please '                                          ValueError: storage dir path cannot contain spaces, please specify a path with --storage-dir                    # Command failed: /bin/python3 -m pythonforandroid.toolchain create --dist_name=rial.cool --bootstrap=sdl2 --requirements=python3,kivy,kivymd --arch armeabi-v7a, arm64-v8a, x86, x86_64 --copy-libs --color=always --storage-dir="/root/kivy/.buildozer/android/platform/build-armeabi-v7a, arm64-v8a, x86, x86_64" --ndk-api=21 --ignore-setup-py                                                     # ENVIRONMENT:                                          #     PWD = '/root/kivy'                                #     HOME = '/root'                                    #     LANG = 'C.UTF-8'                                  #     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'                                                     #     LESSCLOSE = '/bin/lesspipe %s %s'                 #     TERM = 'xterm-256color'                           #     LESSOPEN = '| /bin/lesspipe %s'                   #     SHLVL = '1'                                       #     PATH = '/root/.buildozer/android/platform/apache-ant-1.9.4/bin:/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games'          #     _ = '/usr/local/bin/buildozer'                    #     OLDPWD = '/root'                                  #     PACKAGES_PATH = '/root/.buildozer/android/packages'                                                       #     ANDROIDSDK = '/root/.buildozer/android/platform/android-sdk'                                              #     ANDROIDNDK = '/root/.buildozer/android/platform/android-ndk-r19c'                                         #     ANDROIDAPI = '27'                                 #     ANDROIDMINAPI = '21'                              #                                                       # Buildozer failed to execute the last command          # The error might be hidden in the log above this error # Please read the full log, and search for it before    # raising an issue with buildozer itself.               # In case of a bug report, please add a full log with log_level = 2`

Where is Wrong if my project in `~/kivy` ?
The path is very short .. No spaces in `kivy`
Please HELP !!

**Comment by annouoos** [comment]
The spaces were in buildozer.spec file  : delete the architect between them (arm,x86,)

**Comment by dahmadjid** [comment]
i have the same error, can you clarify what spaces u deleted?

**Comment by SL-Pirate** [comment]
I guess the error message explains the error exactly
In my case it was the path to my current working folder
my main.py,something.kv,buildozer.spec and all other addidtitional folders were on /home/slpirate/Desktop/py projects/kivys
The problem was at "py projects". changed the folder name to "py_projects" and everything was fine.

**Comment by inclement** [comment]
To be fair, this _is_ a bug with some level of the stack, spaces in filenames should work okay. I don't know if this is buildozer/p4a anticipating a failure in the Android tools, or if they do it wrong themselves, though.

**Comment by Shashankh001** [comment]
> I guess the error message explains the error exactly In my case it was the path to my current working folder my main.py,something.kv,buildozer.spec and all other addidtitional folders were on /home/slpirate/Desktop/py projects/kivys The problem was at "py projects". changed the folder name to "py_projects" and everything was fine.

Thanks!!! This worked
