### ISSUE TITLE
Easily reproducible crash accessing Context constants

### ISSUE THREAD

**Issue by jtoledo1974** [kivy/python-for-android#235]
The following code crashes the remote shell (as it does on my app, as well)

from jnius import autoclass
PythonActivity = autoclass('org.renpy.android.PythonActivity')
activity = PythonActivity.mActivity
activity.POWER_MANAGER

It should return the string "power", as defined in the the Context class android API

I've checked it crashes as well when accessing WIFI_POWER, for instance. I suspect it's the same for other constants.
##

**Comment by FeralBytes** [comment]
When it crashes, what does adb logcat produce? I think it is probably a permission issue. Or after researching you may have the wrong object POWER_MANAGER should be POWER_SERVICE at least according [android.app.Activity](http://developer.android.com/reference/android/app/Activity.html) Even [android.content.Context](http://developer.android.com/reference/android/content/Context.html#POWER_SERVICE) does not define POWER_MANAGER.
Also WIFI_POWER should be [WIFI_SERVICE](http://developer.android.com/reference/android/content/Context.html#WIFI_SERVICE).

**Comment by FeralBytes** [comment]
This should be closed.
