### ISSUE TITLE
./distribute.sh -u option doesn't work

### ISSUE THREAD

**Issue by trivedigaurav** [kivy/python-for-android#236]
It simply prints the usage on the terminal:

Usage:   ./distribute.sh [options]

  -d directory           Name of the distribution directory
  -h                     Show this help
  -l                     Show a list of available modules
  -m 'mod1 mod2'         Modules to include
  -f                     Restart from scratch (remove the current build)
  -x                     display expanded values (execute 'set -x')

For developers:
  -u 'mod1 mod2'         Modules to update (if already compiled)

**Comment by FeralBytes** [comment]
Please close if the above command works.

**Comment by trivedigaurav** [comment]
It doesn't work as it is specified in usage but is functional. Closing.
