### ISSUE TITLE
build.gradle 'compile' depreciated

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/python-for-android#2362]
Enhancement request:

`bootstraps/common/build/templates/build.tmpl.gradle`

Uses a _depreciated_ keyword `compile` in the dependencies block.

`compile` will be removed and replaced with `implementation` in Gradle 7

 https://tomgregory.com/gradle-implementation-vs-compile-dependencies/

**Comment by obfusk** [comment]
Seems to be fixed by #2234.

**Comment by misl6** [comment]
Agree with @obfusk .

@RobertFlatt looks fine also on your side? We can close this one?

**Comment by RobertFlatt** [comment]
Agree
