### ISSUE TITLE
Android 10 storage permission denied 

### ISSUE THREAD

**Issue by Sahil-pixel** [kivy/python-for-android#2364]
I have build a app which is saving file into android sdcard (internal memory ) ..i have put all required permission in buildozer and 
android.permissions = INTERNET,ACCESS_NETWORK_STATE,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
and i have take permission from user using android module ....

which is working fine on android 8 and android 5.1
 
but in Android 10 showing permission denied ..but i have given all permission ..

**Comment by RobertFlatt** [comment]
Usage questions should be addressed to the user group
https://groups.google.com/g/kivy-users
