### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by everydaysayhello** [kivy/python-for-android#2366]
when I set android sdk path,it has an error.
input:p4a sdk_tools --sdk-dir '$HOME/Android/sdk/platforms/android-27' tool
[ERROR]:   Build failed: Asked to build for armeabi architecture with API 27, but API 21 or greater does not support armeabi.
can you help me?thank you very much!

**Comment by RobertFlatt** [comment]
buildozer.spec probably answers the question: 

```
# (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
android.arch = armeabi-v7a
```

**Comment by everydaysayhello** [comment]
Thank you very much!

**Comment by everydaysayhello** [comment]
> buildozer.spec可能会回答以下问题：
> 
> ```
> # (str) The Android arch to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
> android.arch = armeabi-v7a
> ```

Thank you very much!
