### ISSUE TITLE
Switch from .sh to pythonic toolchain

### ISSUE THREAD

**Issue by techtonik** [kivy/python-for-android#238]
There is a problem with using this project on Windows, because it uses non-cross-platform shell scripts. It will make porting easier if shell scripts are replaced with Python.

**Comment by inclement** [comment]
The p4a revamp switched to a pythonic toolchain, though it won't help on windows unless someone works out how to make the build work there (and removes hardcoded unix shell assumptions, but that part shouldn't be hard).
