### ISSUE TITLE
Does Kivy supports SDK 30?

### ISSUE THREAD

**Issue by UltraBurstXD** [kivy/python-for-android#2411]
Hi,
I'm considering use Kivy in my projects, but I don't know if it supports API Level 30, which is minimum requirement now in [play store deployment](https://developer.android.com/distribute/best-practices/develop/target-sdk).

**Comment by obfusk** [comment]
Relevant bits from that link:

> Starting in **August 2021**, new apps will need to:
**Publish with the Android App Bundle format.**
Use Play Asset Delivery or Play Feature Delivery to deliver assets or features that exceed download size of 150MB. Expansion files (OBBs) will no longer be supported for new apps.
**Target API level 30** (Android 11) or above and adjust for behavioral changes.

> Starting in **November 2021**, app updates will be required to **target API level 30** or above and adjust for behavioral changes in Android 11. Existing apps that are not receiving updates are unaffected and can continue to be downloaded from the Play Store.

So it's not actually a requirement *yet*.

**Comment by UltraBurstXD** [comment]
They extended time, it was postponed in last year to give devs more time to migrate their code to newer API's.

**Comment by obfusk** [comment]
I ran some quick tests (building with sdk 30, running on android 10):

* a simple "hello world" kivy app seems to work fine
* my webview app works, but `_load.html` doesn't (permission denied)

**Comment by UltraBurstXD** [comment]
Alright, I'll take look.
