### ISSUE TITLE
Use Debian's Python packages for ARM instead of cross-compiling?

### ISSUE THREAD

**Issue by venthur** [kivy/python-for-android#242]
(Full disclosure: I'm Debian Developer and maintainer of python-kivy package in Debian)

When you call `distribute.sh -m "foo"` you basically download and compile a Python library "foo", like `pip install foo` would do, except that you cross-compile it for ARM and not for your architecture right? 

Is it, in principle, possible to use compiled python libraries from Debian's ARM architecture instead of compiling them yourself? The Debian packages usually come with architecture specific patches if needed, are well maintained and tested. Plus: you could use a lot more packages out of the box, compared to the recipes available in python-for-android.

This would also make the compiling part much easier and less error prone.

If you want to try, you can download the python-kivy package for ARM here (scroll down until you see the table with the different architectures): https://packages.debian.org/sid/python-kivy
##

**Comment by inclement** [comment]
I'm sorry that this issue got missed, I've only more recently focused on p4a and noticed it.

I'm not sure how plausible it is to use Debian''s ARM architecture, but I'll add it to my list of things to try.

**Comment by btatlisu** [comment]
how can ı block and spam you
19:02, 6 декабря 2015 пользователь Alexander Taylor <notifications@github.com> написал:
	
		I'm sorry that this issue got missed, I've only more recently focused on p4a and noticed it.
		
		I'm not sure how plausible it is to use Debian''s ARM architecture, but I'll add it to my list of things to try.

**Comment by inclement** [comment]
@btatlisu Are you getting emails about all the python-for-android updates? If so, probably you need to check your github settings.

**Comment by inclement** [comment]
Closing as not an active issue.
