### ISSUE TITLE
Bug in the keyboard event listener

### ISSUE THREAD

**Issue by Neizvestnyj** [kivy/python-for-android#2423]
- Python: 3.8
- OS: android
- Kivy: 2.0.0, master
- Cython: 0.29.19
- OpenJDK: 8

When I click on the input field, the event handler that is declared in the _init_ method stops working (events like 'back') , but if I switching focus away from the whole app, then back again, the handler starts working until I click on the text field again.

All this I tested with:
**api:** _27, 28, 29, 30_
**ndk:** _19b, 19c, 20b, 21e_
**p4a branch:** _develop, master, release-2019.06.06, release-2020.06.02_

`p4a.bootstrap = sdl2`
`android.arch = armeabi-v7a`, `arm64-v8a`

**Code:**  https://pastebin.com/RJH6abdG

https://user-images.githubusercontent.com/40869738/108220548-e562b480-7147-11eb-97c9-211828d2bffd.mp4

**Comment by RobertFlatt** [comment]
Well you didn't get an answer there https://github.com/kivy/kivy/issues/7374
So I suppose it doesn't hurt to try here ;)

However I think nobody understands what is going on as shown by:

https://github.com/kivy/python-for-android/issues/1903
https://github.com/kivy/kivy/issues/6686
https://github.com/spesmilo/electrum/issues/6276
https://github.com/kivy/kivy/issues/7375

**Comment by Neizvestnyj** [comment]
@RobertFlatt Yes, most likely the problem is with **p4a**, or rather with **sdl**, and the bug is old, and not related to Google, they are doing well

**Comment by RobertFlatt** [comment]
Months later, I think this  may be due to the event listener not returning a boolean,
https://github.com/kivy/python-for-android/blob/develop/doc/source/apis.rst#handling-the-back-button

**Comment by Neizvestnyj** [comment]
> Months later, I think this may be due to the event listener not returning a boolean,
> https://github.com/kivy/python-for-android/blob/develop/doc/source/apis.rst#handling-the-back-button

For my example, this did not solve the problem. But now `suggestions` works.
`requirements = kivy==master`
`p4a.branch = develop`

**Comment by Neizvestnyj** [comment]
Hi everyone, has this bug been fixed yet?

**Comment by Neizvestnyj** [comment]
Fixed in `kivy==master` (2.2.0dev0)
