### ISSUE TITLE
Travis CI misconfigured?

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/python-for-android#2428]
Checks for pull request https://github.com/kivy/python-for-android/pull/2385 Fail in continuous-integration/travis-ci/pr 
Errors appear unrelated to the PR which previously passed.
```
error: Can not find Rust compiler
The command "python3.7 -m pip install pyOpenSSL" failed and exited with 1 during .
Your build has been stopped.

```
https://travis-ci.org/github/kivy/python-for-android/jobs/759936932
https://travis-ci.org/github/kivy/python-for-android/jobs/759936933

**Comment by AndreMiras** [comment]
Most likely just fixed in develop via https://github.com/kivy/python-for-android/pull/2422

**Comment by RobertFlatt** [comment]
Thanks, a sync with develop fixed it.
