### ISSUE TITLE
where is 'main.py' ?

### ISSUE THREAD

**Issue by everydaysayhello** [kivy/python-for-android#2441]
I want to know  Where is the 'main.py' packed? I use P4A to generate projects that I don't want to modify 'main.py' every time  when the code has to be regenerated.Can you help me?Thank you very much.

**Comment by RobertFlatt** [comment]
https://github.com/kivy/python-for-android/blob/develop/doc/source/troubleshooting.rst#unpacking-an-apk

That what you needed to know? Please close.
