### ISSUE TITLE
Android permissions not working on Android 10

### ISSUE THREAD

**Issue by Axentiev** [kivy/python-for-android#2444]
I am creating a regular application for android
When I add lines
from android.permissions import request_permissions, Permission
request_permissions([Permission.READ_EXTERNAL_STORAGE, Permission.WRITE_EXTERNAL_STORAGE])
to my code and
android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE
to my buildozer.spec
Permissions are requested, issued, but in the logs:
"Permission denied "/sdcard/Android/data/*MyFolderName*" "
And app crashes
I ran the app on two devices

Mint Cinnamon
Android 10
Python 3.8.1
Kivy 1.9.1
Cython 0.29.19

**Comment by inclement** [comment]
In target API 29+ the WRITE_EXTERNAL_STORAGE permission no longer does anything.

In target API 29 you can revert to the old behaviour by putting `android:requestLegacyExternalStorage="true"` in your AndroidManifest.xml, in the application tag.

This does not affect your ability to write to the app-specific directory in external storage, you always have permission for that. The path to that directory can be obtained as described [in the documentation](https://python-for-android.readthedocs.io/en/latest/apis/#storage-paths). I'm not clear if this is what you are trying.

If this does not explain your permissions failure, please give full details (ideally a minimal runnable example) of what you're attempting to do.
