### ISSUE TITLE
Apk file built by buildozer is large in comparision to other apks

### ISSUE THREAD

**Issue by ayuzzh** [kivy/python-for-android#2473]
(Note: I am week in English so if any mistakes are found just ignore them.) 

I have built some Android apps using Kivy Framework and I observed that the apk files are very large in size as compared to the apks built using Android Studio. 
I know that Python is Interpreter language and requires Python Virtual machine to execute on any device.

For this problem I think I have found a solution i.e.,
1. An app store would be created and all the apps written in Kivy Framework could be released in this App store. This app store creates a folder in "/sdcard" as "/sdcard/.kivy" and in that folder all the standard libraries and python interpreter will be compiled and stored . As all libraries and python is already present. there is no need pack apks with Python libraries.
2. If the app is installed in a device where the kivy app store not installed. Then the app should download the libraries and place them in the folder "/sdcard/.kivy" so that other Kivy apps could use the same.

**Comment by misl6** [comment]
Duplicated of https://github.com/kivy/python-for-android/issues/202
