### ISSUE TITLE
Python compilation error: LXMLRecipe' object has no attribute 'ndk_include_dir'

### ISSUE THREAD

**Issue by excepterror** [kivy/python-for-android#2493]
### Checklist

- [x] the issue is indeed a bug and not a support request
- [x] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [x] I have a short, runnable example that reproduces the issue
- [x] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [ ] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: 3.8.10
- OS: Ubuntu 20.04
- Kivy: master
- Cython: 0.29.21
- OpenJDK: 13

### Description

Recipe doesn't build due to the the compilation error as 'ndk_include_dir' is not an attribute for :cls: LXMLRecipe(). Fix is simple: In line 55, `ndk_include_dir = self.ctx.ndk_include_dir`. I am not aware if this issue is present in other recipes too. Thanks!  

### buildozer.spec

Command:
```sh
buildozer android debug

**Comment by misl6** [comment]
Fixed via #2495
