### ISSUE TITLE
pydantic compiling in Buildozer with 'crypt.h' file not found

### ISSUE THREAD

**Issue by ngochien1990** [kivy/python-for-android#2507]
Dear python-for-android community,

I try to install pydantic by buuldozer the following error messages appear. I have checked other similar issues--'crypt.h' file not found--and do the suggested solutions, but the problem still occurs.

I really appreaciate your advices

-----
from pythonforandroid.recipe import PythonRecipe

class PydanticRecipe(PythonRecipe):
    version = '1.8.2'
    url = 'https://github.com/samuelcolvin/pydantic/archive/refs/tags/v{version}.zip'
    depends = ['setuptools']
    python_depends = ['Cython', 'devtools', 'email-validator', 'dataclasses', 'typing-extensions', 'python-dotenv']
    call_hostpython_via_targetpython = False

recipe = PydanticRecipe()
-----

Logcat:

[INFO]:    Building pydantic for armeabi-v7a
[INFO]:    pydantic apparently isn't already in site-packages
[INFO]:    Installing pydantic into site-packages
[INFO]:    -> directory context /home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pydantic/armeabi-v7a__ndk_target_21/pydantic
[INFO]:    -> running python3 setup.py install -O2 --root=/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-ar...(and 67 more)
           working: error: command '/home/hien/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang' failed with exit status 1 Exception in thread background thread for pid 91779:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hien/.local/lib/python3.8/site-packages/sh.py", line 1637, in wrap
    fn(*rgs, **kwargs)
  File "/home/hien/.local/lib/python3.8/site-packages/sh.py", line 2561, in background_thread
    handle_exit_code(exit_code)
  File "/home/hien/.local/lib/python3.8/site-packages/sh.py", line 2265, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/hien/.local/lib/python3.8/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py install -O2 --root=/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/leansixsigmamethods --install-lib=.

  STDOUT:
running install
running build
running build_py
running build_ext
building 'pydantic.__init__' extension
/home/hien/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O3 -DANDROID -D__ANDROID_API__=21 -I/home/hien/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/arm-linux-androideabi -I/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/leansixsigmamethods/include/python3.8 -fPIC -I/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c pydantic/__init__.c -o build/temp.linux-x86_64-3.8/pydantic/__init__.o
In file included from pydantic/__init__.c:16:
/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/Python.h:44:10: fatal error: 
      'crypt.h' file not found
#include <crypt.h>
         ^~~~~~~~~
1 error generated.
error: command '/home/hien/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang' failed with exit status 1

  STDERR:

Traceback (most recent call last):                                                                                                                                     
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 1276, in <module>
    main()
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 725, in __init__
    getattr(self, command)(args)
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 153, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/toolchain.py", line 212, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/build.py", line 580, in build_recipes
    recipe.build_arch(arch)
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 962, in build_arch
    self.install_python_package(arch)
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/recipe.py", line 978, in install_python_package
    shprint(hostpython, 'setup.py', 'install', '-O2',
  File "/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/python-for-android/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/home/hien/.local/lib/python3.8/site-packages/sh.py", line 911, in next
    self.wait()
  File "/home/hien/.local/lib/python3.8/site-packages/sh.py", line 841, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/hien/.local/lib/python3.8/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build/python3 setup.py install -O2 --root=/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/leansixsigmamethods --install-lib=.

  STDOUT:
running install
running build
running build_py
running build_ext
building 'pydantic.__init__' extension
/home/hien/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O3 -DANDROID -D__ANDROID_API__=21 -I/home/hien/.buildozer/android/platform/android-ndk-r19c/sysroot/usr/include/arm-linux-androideabi -I/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/leansixsigmamethods/include/python3.8 -fPIC -I/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include -I/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/native-build -c pydantic/__init__.c -o build/temp.linux-x86_64-3.8/pydantic/__init__.o
In file included from pydantic/__init__.c:16:
/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/hostpython3/desktop/hostpython3/Include/Python.h:44:10: fatal error: 
      'crypt.h' file not found
#include <crypt.h>
         ^~~~~~~~~
1 error generated.
error: command '/home/hien/.buildozer/android/platform/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang' failed with exit status 1

  STDERR:

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=leansixsigmamethods --bootstrap=sdl2 --requirements=python3,kivy==2.0.0rc1,certifi,spacy,thinc,numpy,pydantic --arch armeabi-v7a --copy-libs --color=always --storage-dir="/home/hien/myapps_archives/LSSmethodAssistant/.buildozer/android/platform/build-armeabi-v7a" --ndk-api=21
# ENVIRONMENT:
#     SHELL = '/bin/bash'
#     SESSION_MANAGER = 'local/hien-VirtualBox:@/tmp/.ICE-unix/1801,unix/hien-VirtualBox:/tmp/.ICE-unix/1801'
#     QT_ACCESSIBILITY = '1'
#     COLORTERM = 'truecolor'
#     XDG_CONFIG_DIRS = '/etc/xdg/xdg-ubuntu:/etc/xdg'
#     XDG_MENU_PREFIX = 'gnome-'
#     GNOME_DESKTOP_SESSION_ID = 'this-is-deprecated'
#     LC_ADDRESS = 'es_ES.UTF-8'
#     GNOME_SHELL_SESSION_MODE = 'ubuntu'
#     LC_NAME = 'es_ES.UTF-8'
#     SSH_AUTH_SOCK = '/run/user/1000/keyring/ssh'
#     XMODIFIERS = '@im=ibus'
#     DESKTOP_SESSION = 'ubuntu'
#     LC_MONETARY = 'es_ES.UTF-8'
#     SSH_AGENT_PID = '1753'
#     GTK_MODULES = 'gail:atk-bridge'
#     PWD = '/home/hien/myapps_archives/LSSmethodAssistant'
#     LOGNAME = 'hien'
#     XDG_SESSION_DESKTOP = 'ubuntu'
#     XDG_SESSION_TYPE = 'x11'
#     GPG_AGENT_INFO = '/run/user/1000/gnupg/S.gpg-agent:0:1'
#     XAUTHORITY = '/run/user/1000/gdm/Xauthority'
#     GJS_DEBUG_TOPICS = 'JS ERROR;JS LOG'
#     WINDOWPATH = '2'
#     HOME = '/home/hien'
#     USERNAME = 'hien'
#     IM_CONFIG_PHASE = '1'
#     LC_PAPER = 'es_ES.UTF-8'
#     LANG = 'en_US.UTF-8'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
#     XDG_CURRENT_DESKTOP = 'ubuntu:GNOME'
#     VTE_VERSION = '6003'
#     GNOME_TERMINAL_SCREEN = '/org/gnome/Terminal/screen/9344cd87_7e2e_4ea4_bd4f_282231725965'
#     INVOCATION_ID = 'a2296db47f04468b8e99570656b711be'
#     MANAGERPID = '1537'
#     GJS_DEBUG_OUTPUT = 'stderr'
#     LESSCLOSE = '/usr/bin/lesspipe %s %s'
#     XDG_SESSION_CLASS = 'user'
#     TERM = 'xterm-256color'
#     LC_IDENTIFICATION = 'es_ES.UTF-8'
#     LESSOPEN = '| /usr/bin/lesspipe %s'
#     USER = 'hien'
#     GNOME_TERMINAL_SERVICE = ':1.168'
#     DISPLAY = ':0'
#     SHLVL = '1'
#     LC_TELEPHONE = 'es_ES.UTF-8'
#     QT_IM_MODULE = 'ibus'
#     LC_MEASUREMENT = 'es_ES.UTF-8'
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     LC_TIME = 'es_ES.UTF-8'
#     JOURNAL_STREAM = '8:35589'
#     XDG_DATA_DIRS = '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
#     PATH = '/home/hien/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/hien/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/hien/Library/Python/3.7/bin'
#     GDMSESSION = 'ubuntu'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     LC_NUMERIC = 'es_ES.UTF-8'
#     _ = '/home/hien/.local/bin/buildozer'
#     OLDPWD = '/home/hien/myapps_archives'
#     PACKAGES_PATH = '/home/hien/.buildozer/android/packages'
#     ANDROIDSDK = '/home/hien/.buildozer/android/platform/android-sdk'
#     ANDROIDNDK = '/home/hien/.buildozer/android/platform/android-ndk-r19c'
#     ANDROIDAPI = '29'
#     ANDROIDMINAPI = '21'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by fabianpx** [comment]
Hi, getting the same error when trying to install pydantic, as a dependency for spacy- was this ever resolved?

**Comment by ConnerLabs** [comment]
Same here too
