### ISSUE TITLE
Full control of the AndroidManifest.xml [$20]

### ISSUE THREAD

**Issue by vidplace7** [kivy/python-for-android#255]
Allow for full control over the contents of the AndroidManifest.xml.

This is crucial to allow developers to limit devices that can install their APKs, for instance, [apps that require BLE](https://developer.android.com/guide/topics/connectivity/bluetooth-le.html#permissions) using the <uses-feature> tag.

Perhaps allow for custom XML to be passed to the build script, or add new fields for each XML tag.
##

**Comment by kamathln** [comment]
+1 for re-opening

We can definitely pass along the manifest as a element tree or something. Recipes and such can play around with the element tree adding and modifying nodes.

**Comment by daytipper1989** [comment]
> You can overwrite templates/AndroidManifest.tmpl.xml on your own. There is also a manifest extras option inside that template near the bottom. If you want a buildozer option to make it easier to overwrite the template in its entirety, you would need to file the bug on buildozer. I'm pretty sure there should already be options for including the manifest extras.

When I overwrite the AndroidManifest.tmpl.xml, it is regenerated everytime I deploy and my changes are lost. Why is this happening with me? any idea? please help.
