### ISSUE TITLE
Is there a way to build smaller apks?

### ISSUE THREAD

**Issue by chaiwa-berian** [kivy/python-for-android#2553]
> Hi! I am sorry, but there is no simple way to make it smaller.
> 
> Usually, it's not very critical for apks to weigh 15 megabytes. Many apps on the Internet weigh 10-20 MB.
> 
> You can try to ask your question on [Buildozer](https://github.com/kivy/buildozer) or [Python-for-android](https://github.com/kivy/python-for-android) repositories (buildozer uses p4a for building apk, so it's better to ask p4a).
> 
> Also, you should know that p4a unpacks your code and standard library code on the first run. You may want to see the full app's size after running.

Thanks.

_Originally posted by @chaiwa-berian in https://github.com/ArtemSBulgakov/buildozer-action/issues/13#issuecomment-1039565599_

**Comment by misl6** [comment]
Duplicated of: https://github.com/kivy/python-for-android/issues/202
