### ISSUE TITLE
Webview app fail to startup.

### ISSUE THREAD

**Issue by Prashanth-BC** [kivy/python-for-android#2559]
### Checklist

- [x] the issue is indeed a bug and not a support request
- [x] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [ ] I have a short, runnable example that reproduces the issue
- [ ] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [ ] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python:3.8.10
- OS: Ubuntu
- Kivy:
- Cython: 0.29.28
- OpenJDK: 13.0.7

### Description
Webview application failed to start with flask as the server.
This is due the depencies of flask on itsdangerous and itsdangerous is unable to find the name json hence the application fails to start with the following exception.
    ImportError: cannot import name 'json' from itsdangerous
This issue needs to fixed by upgrading the version of the flask the recipie. 
I have tested with the modified reciepe with the latest version of flask and found that application works after the fix.

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/python-for-android/pull/2560
