### ISSUE TITLE
Python file is not converted to bytecode when building apk

### ISSUE THREAD

**Issue by MohsenHassani** [kivy/python-for-android#257]
Hello guys,

For using RESTful API, I had to install and use `requests` package.

So, for building the app, I had to do:
./distribute.sh -m "kivy requests==2.1.0 urllib3"

After making and installing the app, it would not open on my HTC.
Debugging it using `adb logcat` I noticed an error related to my problem:
SyntaxError: Non-ASCII character '\xa3' in file when function returns...
in the file:
/data/data/a.b.c/files/lib/python2.7/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py

Taking a look at the packages within the path, I noticed all files have the extension `pyo` but this one was in `py`. I changed the extension to `pyo` and it solved my problem. The app opened successfully.

So I guess there is a bug or something with the converter for not distributing it in `pyo`?

**Comment by inclement** [comment]
I haven't seen this come up more, so I'll close it as not reproducible. If anyone gets the problem again, especially if it can be reproduced, feel free to raise it again.
