### ISSUE TITLE
"Could Not Extract Public Data"  Needs very explicit instructions or feedback to the user

### ISSUE THREAD

**Issue by knappador** [kivy/python-for-android#260]
This issue is KILLING our app store ratings in cases where SD Cards are full, internal memory is full, or the USB is in mass storage mode etc etc.

It looks like PythonActivity.java just says "could not extract public data" or "could not extract private data" and doesn't give any feedback at all.

I'm going to start by creating some popups and then trying to separate the different causes so that we can display a different message for each cause to at least tell users what the problem is.  Bad error messages cause one-star ratings.  We can't have this.  I'm going to fix it, and please tell me what you know!

^^
##

**Comment by misl6** [comment]
Public data is not supported anymore.
See: https://github.com/kivy/python-for-android/issues/363
