### ISSUE TITLE
ffmpeg recipe for 23b build fails

### ISSUE THREAD

**Issue by RobertFlatt** [kivy/python-for-android#2608]
### Checklist

- [ x] the issue is indeed a bug and not a support request
- [ x] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [ ] I have a short, runnable example that reproduces the issue
- [ x] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [ x] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: 3.10.4
- OS: Ubuntu 22.04
- Kivy: 2.1
- Cython: 0.29.19
- OpenJDK: 17

### Description

Buildozer 1.4.0.dev0
p4a.branch = develop
android.archs = armeabi-v7a

`buildozer android debug`

`ffmpeg recipe` build fails, `strip not found`.

```
INSTALL doc/examples/Makefile
INSTALL libavdevice/libavdevice.so
STRIP   install-libavdevice-shared
/bin/sh: 1: arm-linux-androideabi-strip: not found
make: *** [ffbuild/library.mak:104: install-libavdevice-shared] Error 127
```

**Comment by misl6** [comment]
Hi @RobertFlatt!

I guess https://github.com/kivy/python-for-android/pull/2586 fixes it. Did you had a chance to test the changes?

**Comment by RobertFlatt** [comment]
p4a.fork=misl6
p4a.branch = fix/build-platform-on-m1

ffmpeg builds OK  :)

**But** now ffpyplayer Cython fails, new issue or run with it here?
Log below.

I notice the Cython egg is `3.0.0 for py3.9`
So this is not the platform's installed Cython version, it is p4a's copy,

Any suggestions?

```
  RAN: /usr/bin/python3 '-cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main());' ./.eggs/Cython-3.0.0a10-py3.9.egg/Cython/Utility/TestCyUtilityLoader.pyx

  STDOUT:
/home/bobf/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/bobf/ex/share_receive_example/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/ffpyplayer-openssl/armeabi-v7a__ndk_target_21/ffpyplayer/.eggs/Cython-3.0.0a10-py3.9.egg/Cython/Utility/TestCyUtilityLoader.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
########## TestCyUtilityLoader ##########
#@requires: OtherUtility

test {{cy_loader}} impl
    ^
------------------------------------------------------------

.eggs/Cython-3.0.0a10-py3.9.egg/Cython/Utility/TestCyUtilityLoader.pyx:4:5: Syntax error in simple statement list
```

**Comment by misl6** [comment]
> @misl6 p4a.fork=misl6 p4a.branch = fix/build-platform-on-m1
> 
> ffmpeg builds OK :)
> 
> **But** now ffpyplayer Cython fails, new issue or run with it here? Log below.
> 
> I notice the Cython egg is `3.0.0 for py3.9` So this is not the platform's installed Cython version, it is p4a's copy,
> 
> Any suggestions?
> 
> ```
>   RAN: /usr/bin/python3 '-cimport sys; from Cython.Compiler.Main import setuptools_main; sys.exit(setuptools_main());' ./.eggs/Cython-3.0.0a10-py3.9.egg/Cython/Utility/TestCyUtilityLoader.pyx
> 
>   STDOUT:
> /home/bobf/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/bobf/ex/share_receive_example/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/ffpyplayer-openssl/armeabi-v7a__ndk_target_21/ffpyplayer/.eggs/Cython-3.0.0a10-py3.9.egg/Cython/Utility/TestCyUtilityLoader.pyx
>   tree = Parsing.p_module(s, pxd, full_module_name)
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> ########## TestCyUtilityLoader ##########
> #@requires: OtherUtility
> 
> test {{cy_loader}} impl
>     ^
> ------------------------------------------------------------
> 
> .eggs/Cython-3.0.0a10-py3.9.egg/Cython/Utility/TestCyUtilityLoader.pyx:4:5: Syntax error in simple statement list
> ```

Looks like a separate issue to me, but I may have a clear idea of the root cause of the issue.

I will be back to you shortly.

**Comment by misl6** [comment]
@RobertFlatt FYI: I've just added a commit on #2586 that should fix the issue: https://github.com/kivy/python-for-android/pull/2586/commits/4f7d8e61b736eb63dbc215b0f1ffd969755db034.

**Comment by RobertFlatt** [comment]
@misl6 Builds and runs 😀Thank you.
