### ISSUE TITLE
compile error: sys/timeb.h not found

### ISSUE THREAD

**Issue by victorlee129** [kivy/python-for-android#261]
It seems that in the android-ndk-r10, the file timeb.h is removed, which leads to a compiling failure.
Has no idea of how to fix it besides downloading a r9 version of ndk...

P.S.: And in r10, the API dir has been changed into Android-L from Android-14 or so, which I made a link to solve the problem.

Thanks for any suggestion.

**Comment by Samureus** [comment]
The error message that appears is:

```make
ccache arm-linux-androideabi-gcc -DANDROID -mandroid  -fomit-frame-pointer --sysroot /home/samo/Dev/android-ndk-r10d/platforms/android-21/arch-arm -fno-strict-aliasing -DANDROID -mandroid  -fomit-frame-pointer --sysroot /home/samo/Dev/android-ndk-r10d/platforms/android-21/arch-arm -DNDEBUG   -I. -IInclude -I./Include  -fPIC -DPy_BUILD_CORE  -I/home/samo/Dev/python-for-android/build/python-install/include -c ./Modules/zlibmodule.c -o Modules/zlibmodule.o
./Modules/timemodule.c:31:23: fatal error: sys/timeb.h: No such file or directory
 #include <sys/timeb.h>
                       ^
compilation terminated.
make: *** [Modules/timemodule.o] Error 1
```
Which is required here:

https://github.com/python/cpython/blob/2.2/Modules/timemodule.c#L28

but not in the latest version, there seems to be a workaround here:

https://github.com/python/cpython/blob/2.7/Modules/timemodule.c#L919

After checking /android-ndk-r10d/platforms/android-21/arch-arm/usr/include/sys/, timeb.h is indeed missing in API 21, but it's available in API 19 and lower. This looks like a bad combination of the latest API and Python 2.7.2.

**Comment by franciscod** [comment]
same here on api 21!

**Comment by inclement** [comment]
This should be fixed by the linked PR.
