### ISSUE TITLE
USB permission

### ISSUE THREAD

**Issue by robotixdevteam** [kivy/python-for-android#2611]
Is it possible to create an app in kivy which communicates with arduino through serial communication? I know that i have to give USB permission to android.How to give the usb permission and communicate between kivy app and arduino?

**Comment by misl6** [comment]
Before using the USB APIs, a runtime permission should be requested: https://developer.android.com/guide/topics/connectivity/usb/host#permission-d

On `python-for-android`, you can use:
```
from android.permissions import request_permissions, Permission
request_permissions([Permission.WRITE_EXTERNAL_STORAGE])
```
to request the required permissions during runtime.

See: https://github.com/kivy/python-for-android/blob/8ab7c950618ebc3bf4c2afddbc4a416b8bf325d1/doc/source/apis.rst#runtime-permissions for additional info.
