### ISSUE TITLE
Feature Request: Give more access to the android project folder inside of the dist folder

### ISSUE THREAD

**Issue by kengoon** [kivy/python-for-android#2614]
Android has been changing a lot of things in their API and that gives real headache to Frameworks like Kivy. Accessing files in android 11 and later proves to be a pain process. You have to add some file provider tag in the Manifest file and add extra xml to code to the res/xml folder of the android project. The buildozer and P4A provides a way we can add extra xml code in the Manifest file but that is limited and you can't add tags like the <provider> tag in `android.extra_manifest_xml` argument. Also you don't even have access to add files into the `res` folder of the andorid project. This whole thing boils down to you going through the stress of opening the .buildozer cache file and swinging around until you get to the android project folder.

This is a real issue for developers(mostly newbies)  who have not done anything related to android before and know nothing of Java, and to those who clearly understands the android development process itself, finds it a bit stressful moving through the .buildozer cache file to manipulate some files

I propose that extra arguments should be provided so that developers using the buildozer tool to build their app can easily manipulate and add any file in any folder inside of the android project folder without needing to go through the above mentioned procedure.

Thanks In Advance

**Comment by misl6** [comment]
Hi @kengoon !

Now the `res` folder is highly-customizable thanks to PR #2684 (which has been merged this morning, and also have a related PR on `buildozer` the expose the functionality, here: https://github.com/kivy/buildozer/pull/1513 )

**Comment by Julian-O** [comment]
Closing as complete.
