### ISSUE TITLE
touchtracer not working

### ISSUE THREAD

**Issue by victorlee129** [kivy/python-for-android#262]
I copied the example out and use buildozer and python-for-android to build the apk with ndk r9c and api 15.
However, the app runs a 'loading' screen and then crushes.
Here is the logcat, omitted all python extracts(which has no failure)

I/python  ( 2242): extracting include/
I/python  ( 2242): extracting include/python2.7/
I/python  ( 2242): extracting include/python2.7/pyconfig.h
I/python  ( 2242): extracting touchtracer.kv
I/python  ( 2242): extracting icon.png
I/python  ( 2242): extracting sitecustomize.pyo
I/python  ( 2242): extracting particle.png
I/python  ( 2242): extracting main.pyo
W/ResourceType( 2242): No package identifier when getting value for resource number 0x00000000
W/dalvikvm( 2242): threadid=11: thread exiting with uncaught exception (group=0x4163b498)
E/AndroidRuntime( 2242): FATAL EXCEPTION: Thread-20079
E/AndroidRuntime( 2242): java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:   174 cannot locate 'signal'...
E/AndroidRuntime( 2242): 
E/AndroidRuntime( 2242):        at java.lang.Runtime.loadLibrary(Runtime.java:370)
E/AndroidRuntime( 2242):        at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime( 2242):        at org.renpy.android.PythonActivity.run(PythonActivity.java:250)
E/AndroidRuntime( 2242):        at java.lang.Thread.run(Thread.java:856)
W/ActivityManager(  529):   Force finishing activity org.test.myapp/org.renpy.android.PythonActivity

Thanks in advance.

**Comment by inclement** [comment]
I'm not sure if this is still an issue, but I havent' seen it come up so I'll close it for now, especially with the major toolchain changes since then.
