### ISSUE TITLE
--private clobers /data/data/[package name]/files directory

### ISSUE THREAD

**Issue by knappador** [kivy/python-for-android#263]
The default behavior when upgrading packages is not to clobber directories or delete files that aren't included in the APK, however, this is in effect what happens when updating using --private.  It's wrong and I'm trying to figure out where we clobber this directory.  AssetExtract.java looks like it's supposed to be working since mkdirs doesn't clobber directories by default.

This is definitely -not- correct in terms of how the rest of Android application development works.  I'm investigating a solution because I have live APK's out there that will lose data on update if I don't fix this =)
##

**Comment by denys-duchier** [comment]
#350 implements this fix using `__kivy_root__` as the name of the subdirectory
