### ISSUE TITLE
[Question] Java Files

### ISSUE THREAD

**Issue by jhay06** [kivy/python-for-android#2646]
Hi , This is not an issue but a question 

I'm just wondering, where can i find these 3 files with arrow from the source of python-for-android 
![image](https://user-images.githubusercontent.com/5191437/182003253-4fb8433e-9a47-4da2-9837-9eaec73176ee.png)

the 2 files without arrow is located on the templates bootstrap , but the 3 i can't find it on the templates , where does p4a get the files and add it on its project ? i don't know if it is p4a files or maybe it is related on the buildozer . 

I just want to modify those files before building it so i can save it on my own github workspace . thanks

**Comment by misl6** [comment]
See:

https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android
