### ISSUE TITLE
[Question] Pip SSL ?

### ISSUE THREAD

**Issue by jhay06** [kivy/python-for-android#2649]
Any way to skip SSL verification of pip from python for android ?   pip from python4android packages has issue on newer macos monterey , even openssl exist both 1.1 and version 3.0.2

**Comment by misl6** [comment]
Hi @jhay06,

Skipping SSL verification is something that should only be done as a last resort and is not supported directly via `python-for-android`.

Instead, we can check why `python-for-android` is failing to find `openssl` on your setup.

Can you post a full log?

**Comment by jhay06** [comment]
actually im getting the same error on buildozer python-for-android and kivy-ios toolchain.py   

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/certifi/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/certifi/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL modu... (1381 more, please see e.stdout)


i already have both openssl1.1 and openssl3 and also i added on its path , but im still getting the same error ,


wil send the logs im getting with buildozer python4android

**Comment by jhay06** [comment]
okay got this working by cleaning homebrew packages and reinstall everything in homebrew arch x86_64 ,
