### ISSUE TITLE
Sticky services

### ISSUE THREAD

**Issue by mscansian** [kivy/python-for-android#267]
Shouldn't the PythonService class be a little bit more flexible? Right now it's only possible to create a foreground service with a notification. If a developer wants, for instance, to create a sticky service without "On going" notifications, it's not possible.

I think it would be nice to change the start_service() in PythonActivity (and of course PythonService) to be able to do this kind of stuff easily.

Have you guys already thought this through?

**Comment by FeralBytes** [comment]
I solved this problem. In your service you just need to put your service in the background; but remember now it can be killed to recliam memory.
Here is the code that goes in your service/main.py:
```python
from jnius import autoclass
Service = autoclass('org.renpy.android.PythonService').mService
Service.stopForeground(True)
```
Here is the Java Documentation for that call: http://developer.android.com/reference/android/app/Service.html#stopForeground%28boolean%29

**Comment by FeralBytes** [comment]
Also Wiki Article: https://github.com/kivy/kivy/wiki/Background-Service-using-P4A-android.service

**Comment by inclement** [comment]
The new p4a toolchain has more flexible service support.
