### ISSUE TITLE
Touch input causes big slowdown ( from get_keyboard_height ) - can use 12% to 30%+ of cpu before even passing to kivy

### ISSUE THREAD

**Issue by chozabu** [kivy/python-for-android#268]
This is the function in question https://github.com/kivy/python-for-android/blob/master/recipes/android/src/android/_android.pyx#L174

profile of moving 1 finger for most of the time while profiling: http://chozabu.net/autopush/boardz-android-12-09-14-2135.profile ~12% total cpu usage by get_keyboard_height 

profile of moving ~5 fingers for most of the time while profiling: http://chozabu.net/autopush/5fingers.profile ~30% total cpu usage by get_keyboard_height 

It looks like eventes are issued by android when the keyboard changes - this would be a good time to cache the keyboard height:
ref - http://stackoverflow.com/a/18992807/445831

**Comment by akshayaurora** [comment]
Thanks to kived I just found out the real reason for the slowdown on touch input, `onGlobalLayout` Listener on the Java side was being called and triggered gettign keyboard height on every key, touch, movement.

Checking for height inside the layout listener and sending the key to kivy only when there is a height different solve the issue of keyboard_height being triggered again and again.

closed via 52e1861ca58657324a9f5452b1c91aaeca3963f3

**Comment by chozabu** [comment]
Hooray! Nice one!
