### ISSUE TITLE
[ERROR]:   Build failed: Asked to compile for no Archs, so failing.

### ISSUE THREAD

**Issue by e-lunev** [kivy/python-for-android#2685]
p4a apk --private $HOME/code/myapp --package=org.example.myapp --name "My application" --version 0.1 --bootstrap=sdl2 --requirements=python3,kivy

[WARNING]: prerequisites.py is experimental and does not support all prerequisites yet.
[WARNING]: Please report any issues to the python-for-android issue tracker.
[ERROR]:   Build failed: Asked to compile for no Archs, so failing.

**Comment by misl6** [comment]
Hi @e-lunev !

We may have missed to update something in the docs, but `--arch =xxxx` (or multiple ones) is mandatory.

**Comment by e-lunev** [comment]
what is meant by xxxx

**Comment by misl6** [comment]
> what is meant by xxxx

See: https://python-for-android.readthedocs.io/en/latest/commands/#distribution-arguments

**Comment by e-lunev** [comment]
[ERROR]:   Build failed: Android SDK dir was not specified, exiting.

**Comment by e-lunev** [comment]
p4a --sdk-dir=/home/kali/Android/Sdk/

don't work

**Comment by RobertFlatt** [comment]
Consider using Buildozer https://github.com/kivy/buildozer/blob/master/docs/source/installation.rst it is a wrapper around p4a that handles the Google tools for you.

**Comment by nheffelman** [comment]
I added this to my p4a apk command along with all the requirements 
--arch=arm64-v8a --arch=armeabi-v7a
