### ISSUE TITLE
Error When I set android.api = 31

### ISSUE THREAD

**Issue by Tan837** [kivy/python-for-android#2696]
I tried to convert my kivy app to (aab):

when setting ( android.api = 30 ) It does not cause any problems
but play store asked me ( android.api >= 31 )

And when I changed android.api to 31 there was a problem with ( gradlew failed! )

"""
[WARNING]: ERROR: /content/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/dists/app/gradlew failed!
"""

I've attached the full log.

[full log.txt](https://github.com/kivy/python-for-android/files/9882303/full.log.txt)

**Comment by misl6** [comment]
Hi @Tan837 !

Can you also post your `buildozer.spec` ?

**Comment by misl6** [comment]
This is the relevant part of the log:
```
/content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/soccerlineup/src/main/AndroidManifest.xml:27:7-31:18 Error:
android:exported needs to be explicitly specified for element <receiver#com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver>.
Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
```

Looks like you need to update `com.google.firebase:firebase-ads:10.2.0` to a newer version.

**Comment by Tan837** [comment]
@misl6 I tried a build with com.google.firebase:firebase-ads:21.3.0 and the build still fails, I've attached the full log please take a look.
[build failed.txt](https://github.com/kivy/python-for-android/files/9883551/build.failed.txt)

**Comment by SnKhor974** [comment]
@misl6 what is the latest version of it?

**Comment by SnKhor974** [comment]
@misl6 thanks so much, i set the version to 12.0.1 and it works! u made my day :)
