### ISSUE TITLE
ModuleNotFoundError: No module named 'android'

### ISSUE THREAD

**Issue by Sz3rs** [kivy/python-for-android#2697]
### Checklist

- [ + ] the issue is indeed a bug and not a support request
- [ + ] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [ + ] I have a short, runnable example that reproduces the issue
- [ ] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [ ] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: 3.9.8 and 3.7.5
- OS: Macos X (arm64)
- Kivy: latest
- OpenJDK: latest

### Description

I run:
`pip3 install python-for-android`
Result: _Successfully installed appdirs-1.4.4 pep517-0.6.0 python-for-android-2022.9.4 pytoml-0.1.21 sh-1.14.3 toml-0.10.2_

And try:
python3
>>> import android
**ModuleNotFoundError: No module named 'android'**

**Comment by RobertFlatt** [comment]
https://github.com/Android-for-Python/Android-for-Python-Users#no-module-named-android
