### ISSUE TITLE
Can't build with all modules

### ISSUE THREAD

**Issue by anjiro** [kivy/python-for-android#27]
`./distribute.sh -m "android chipmunk ffmpeg hostpython jpeg kivy libxml2 libxslt lxml openssl pil\
 png pycrypto pygame pyopenssl pyqrcode python sdl setuptools sqlite3 twisted txws wokkel zope"`

eventually yields

`./distribute.sh: line 45: /home/dan/android/python-for-android/build/python-install/bin/python.host: No such file or directory`

Full build log at http://pastebin.com/a8HmFGjz

**Comment by erm3nda** [comment]
@phlax saved my day, adding sqlite3 before hostpython2 in dependancies worked.
`# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = kivy, sqlite3, hostpython2`
