### ISSUE TITLE
[proposed feature-request] Lacking psutil recipe

### ISSUE THREAD

**Issue by yves-surrel** [kivy/python-for-android#2707]
### Versions

- Python: 3.9
- OS: MacOS 11.7
- Kivy: 2.1.0
- Cython:
- OpenJDK:

### Description

A recipe for `psutil` used to exist (see #157 , May 27, 2014). The simplest one I tried to create:
```
from pythonforandroid.recipe import PythonRecipe


class PsutilRecipe(PythonRecipe):
    version = "5.9.3"
    url = f'https://github.com/giampaolo/psutil/archive/refs/tags/release-{version}.tar.gz'
    depends = ["setuptools"]
    site_packages_name = 'psutil'
    call_hostpython_via_targetpython = False


recipe = PsutilRecipe()
```
and I have no knowledge of how to amend it (no skill about gcc compiling, linking etc.)

**Comment by RobertFlatt** [comment]
Android is not POSIX compliant. 

I think the interesting question about psutil is how much of it's functionality would be available from within an Android app?

**Comment by yves-surrel** [comment]
It is possible to have an operative `psutil` in Pydroid3, so it could be possible to have psutil compiled properly...?

**Comment by yves-surrel** [comment]
Actually, in my App, `psutil` was required by `ipykernel`. I specified `ipykernel==5.5.5` in `buildozer.spec` which does not require `psutil`. So for my purpose, the problem is solved. But it may be useful to others, although @RobertFlatt answer is quite relevant.

**Comment by Julian-O** [comment]
No-one currently needs a recipe and it is unclear that it would be useful anyway. Closing as Not Planned.
