### ISSUE TITLE
Update kivy app that's already published on google play store.

### ISSUE THREAD

**Issue by Tan837** [kivy/python-for-android#2709]
I recently published my kivy app on google play store, I have a update that I want to release, I have the apps keystore and the certificate, how do I do this? There'a no document about this topic.

**Comment by misl6** [comment]
Hi @Tan837 !

An update is just a new release with a different version number. Then everything else in the process is exactly the same as the first release. (At least on `python-for-android` and `buildozer` side, on Google Play is a little bit different, but that topic should be covered in Google Play docs)

If you need some help, feel free to reach out on our [Discord](https://chat.kivy.org) chat.
