### ISSUE TITLE
buildozer -v android debug

### ISSUE THREAD

**Issue by xiaolinpeter** [kivy/python-for-android#2711]
when i run the buildozer -v android debug in Ubuntu(Ubuntu 20.04, is the win10+wsl subsystem), the error as follw
![image](https://user-images.githubusercontent.com/27184803/205497707-7fd600ab-a49f-400d-ad0f-a3b543a1e6c4.png)
![image](https://user-images.githubusercontent.com/27184803/205497726-44f82039-befd-407e-bf6c-5c4e676660d0.png)

I hope someone give me suggestion, thank you very much

**Comment by RobertFlatt** [comment]
Please direct support questions to the user groups.

The log shows two of these issues are potential problems 
https://github.com/Android-for-Python/Android-for-Python-Users#non-deterministic-behavior

If you still have a problem ask here https://discord.gg/F5EZh8PD
