### ISSUE TITLE
Setting `android:screenOrientation` via `--orientation` has no effect when targeting API 31

### ISSUE THREAD

**Issue by misl6** [kivy/python-for-android#2724]
### Checklist

- [x] the issue is indeed a bug and not a support request
- [x] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [x] I have a short, runnable example that reproduces the issue
- [x] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [x] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: Any
- OS: Any
- Kivy: Any
- Cython: Any
- OpenJDK: Any

### Description

`python-for-android` made possible to set the activity `android:screenOrientation` via `--orientation` argument.
Unfortunately, when targeting API 31 and above, on Android 12 and above, this attribute is ignored, as the activity will run in multi-window mode.

From [Android Docs:](https://developer.android.com/guide/topics/manifest/activity-element#screen)
> android:screenOrientation
The orientation of the activity's display on the device. The system ignores this attribute if the activity is running in [multi-window mode](https://developer.android.com/guide/topics/ui/multi-window).

On Android 12, the multi-window mode is the standard behavior, and additionally:

> On large screens (sw >= 600dp), the platform supports all apps in multi-window mode regardless of app configuration. If [resizeableActivity="false"](https://developer.android.com/guide/topics/manifest/application-element#resizeableActivity), the app is put into compatibility mode when necessary to accommodate display dimensions.

> On small screens (sw < 600dp), the system checks an activity’s [minWidth](https://developer.android.com/reference/android/content/pm/ActivityInfo.WindowLayout#attr_android:minWidth) and [minHeight](https://developer.android.com/reference/android/content/pm/ActivityInfo.WindowLayout#attr_android:minHeight) to determine whether the activity can run in multi-window mode. If [resizeableActivity="false"](https://developer.android.com/guide/topics/manifest/application-element#resizeableActivity), the app is prevented from running in multi‑window mode regardless of minimum width and height.

So, `resizeableActivity="false"`might be great to handle some specific configurations, but is not meant to be a solution for that.
Also, users may want to take advantage of such a feature. (Since the vastly majority of Apps now support multi-window mode)

### But we still want to force a specific orientation, when the app is not in multi-window mode:

Setting `KIVY_ORIENTATION` to a supported SDL configuration, (`Portrait`, `LandscapeRight`, ...) will force the App to keep the selected orientation, even if the device gets rotated.

So, as a quick workaround:

```python
import os

os.environ["KIVY_ORIENTATION"] = "Portrait"
```

In a near future:
We should advise users that `--orientation` has no effect anymore, and we should think about a (cross-platform?) migration plan.

**Comment by RobertFlatt** [comment]
Its a little more complicated. I tested on Pixel5, Android13, api 31

 - Buildozer.spec `orientation` sets the presplash orientation, and sets the app orientation to "all".
 - `os.environ["KIVY_ORIENTATION"]` sets the app orientation, but does **not** set the presplash orientation.
 - "LandscapeRight" and "LandscapeLeft" are switched according these definitions https://wiki.libsdl.org/SDL2/SDL_HINT_ORIENTATIONS
 - "PortraitUpsideDown" is interpreted as "Portrait"
 - Multiple orientations are a white space separated list. 
 - The special case "All" is surprisingly specified with "LandscapeLeft Portrait" or "LandscapeRight Portrait" (or no specification).
 - "All" behavior includes the otherwise unavailable "PortraitUpsideDown" 
 
 I updated this https://github.com/Android-for-Python/Android-for-Python-Users#orientation to reflect the issue.

**Comment by misl6** [comment]
Fixed via https://github.com/kivy/python-for-android/pull/2739

**Comment by sunnyking** [comment]
FYI, we had this issue with target api 30 as well as running on android 10
```
# (int) Target Android API, should be as high as possible.
android.api = 30

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait
```
We can confirm that p4a version 2023.01.28 fixed this issue for us.
