### ISSUE TITLE
there is an issue with playing video from URL on the latest p4a releases

### ISSUE THREAD

**Issue by cryptoone** [kivy/python-for-android#2744]
the latest p4a release always fails , when trying to play a video from a url.
the app simply crashes; with no real useful log; 

the same code works flawlessly on p4a = v2022.09.04
but when using p4a = master or developer in buildozer; the app keeps crashing when trying to load the video

**Comment by misl6** [comment]
Hi @cryptoone ,
Filtering by PID, you should be able to see something more into the logcat.

Otherwise, can you please post a small reproducible code snipped + the video source?
Also, can you share some more info about your device? (Vendor / Model / Android version)

**Comment by Julian-O** [comment]
No response. Closing as can't repro.
