### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by GODIMONGO** [kivy/python-for-android#2749]
PS C:\Users\Gdjsb> pip install python-for-android
Collecting python-for-android
  Using cached python_for_android-2023.2.10-py3-none-any.whl (524 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: colorama>=0.3.3 in c:\users\gdjsb\appdata\local\programs\python\python311\lib\site-packages (from python-for-android) (0.4.6)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting pep517
  Using cached pep517-0.13.0-py3-none-any.whl (18 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting packaging
  Using cached packaging-23.0-py3-none-any.whl (42 kB)
Collecting sh<2.0,>=1.10
  Using cached sh-1.14.3.tar.gz (62 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Gdjsb\AppData\Local\Temp\pip-install-v8ne6yd3\sh_4ff44ff1d1034e88ba2fa9570d7551c1\setup.py", line 5, in <module>
          import sh
        File "C:\Users\Gdjsb\AppData\Local\Temp\pip-install-v8ne6yd3\sh_4ff44ff1d1034e88ba2fa9570d7551c1\sh.py", line 37, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
PS C:\Users\Gdjsb>

**Comment by RobertFlatt** [comment]
On Windows p4a only runs under WSL, Also it is easier to use Buildozer.

This forum is for development issues, not usage issues.
If you have any further usage questions, please use the user groups
https://discord.gg/TshtbsFg
https://groups.google.com/g/kivy-users
