### ISSUE TITLE
distribute fails to build flask or sqlite3 : Error: libpymodules.so - no input files

### ISSUE THREAD

**Issue by ToddG** [kivy/python-for-android#275]
1. Building 'Flask' fails...

``` bash
./distribute.sh -m 'Flask'
```

http://pastebin.com/spDBqp3M

``` bash
./distribute.sh -m 'Flask' -C
```

http://pastebin.com/ErJfVKGs
1. As a double-check, I also tried building something for which there is a recipe, sqlite3...

``` bash
./distribute.sh -m 'sqlite3'
```

``` bash
./distribute.sh -m 'sqlite3' -C
```

http://pastebin.com/um0WaL5t
1. The common error seems to be:

``` bash
Biglink create [...]/p4a3/build/libs/libpymodules.so library
Biglink arguments:
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
```
1. Using the -C compilation flag fails with
   http://pastebin.com/yMQj4HQx

Here, the common error is:

``` bash
Copy python distribution
./distribute.sh: line 769: /media/RHINO/data/projects/p4a3/build/python-install/bin/python.host: No such file or directory
Copy libs
Copy java files from various libs
cp: cannot stat ‘/media/RHINO/data/projects/p4a3/build/java/*’: No such file or directory
Fill private directory
cp: cannot stat ‘python-install/include/python2.7/pyconfig.h’: No such file or directory
```

Note, I'm on master:

``` bash
commit a1fbc8259b6bf5831c6c10f9aad88e2cc3680fdd
Author: Mathieu Virbel <mat@kivy.org>
Date:   Tue Sep 30 16:13:20 2014 +0200

    fix django compilation. closes #231 
```

I cannot seem to reproduce it, but I was able to build Flask. I had fiddled with building other things (kivy, for example) and then, in the same p4a clone directory, running distribute again to get it to build Flask. I even moved the run_pymodules_install before the run_prebuild step... that actually makes sense to me, and seemed to work, too. But I'll admit, I do not fully understand distribute.sh yet...

``` bash
function run() {
    check_build_deps
    run_prepare
    run_source_modules
    run_get_packages
        run_pymodules_install  ## my change
    run_prebuild
    run_build
    run_biglink
    run_postbuild
    run_distribute
    info "All done !"
}
```

**Comment by franciscod** [comment]
+1 to what ToddG said!
