### ISSUE TITLE
Cannot install Python-for-Android

### ISSUE THREAD

**Issue by excelant100** [kivy/python-for-android#2754]
Everytime I launch pip install python-for-android,  get an error. Basically I cannot install it which is obvious.

The logs:
`(venv) C:\Users\Alienware\PycharmProjects\TesseractPlayground>pip install python-for-android
Collecting python-for-android
  Using cached python_for_android-2023.2.10-py3-none-any.whl (524 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pep517
  Using cached pep517-0.13.0-py3-none-any.whl (18 kB)
Requirement already satisfied: packaging in c:\users\alienware\pycharmprojects\tesseractplayground\venv\lib\site-packages (from python-for-android) (21.3)
Collecting sh<2.0,>=1.10
  Using cached sh-1.14.3.tar.gz (62 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Alienware\AppData\Local\Temp\pip-install-shciiecb\sh_6ed78a7e3bda46acac5362f9729eb0cf\setup.py", line 5, in <module>
          import sh
        File "C:\Users\Alienware\AppData\Local\Temp\pip-install-shciiecb\sh_6ed78a7e3bda46acac5362f9729eb0cf\sh.py", line 37, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by PythonLaboratory** [comment]
python-for-android not intended for use on Windows
