### ISSUE TITLE
https://code.videolan.org not available

### ISSUE THREAD

**Issue by aleReimondo** [kivy/python-for-android#2758]
### Description

Tried to build my app (with a minor change of orientation in spec) and got an error during building becasue it tried to download Libx264 from site at https://code.videolan.org that is not available at time of this bug report.
The prior recipe version download the library from other site.

### buildozer.spec
requirements = kivy, android, cymunk ,ffpyplayer,ffpyplayer_codecs

**Comment by misl6** [comment]
Hi @aleReimondo !

Does the issue still persist on your side?

I've just tried to download the file and I do not encounter any issue.
```bash
mirko@Mirkos-MacBook-Pro /tmp % curl https://code.videolan.org/videolan/x264/-/archive/5db6aa6cab1b146e07b60cc1736a01f21da01154/x264-5db6aa6cab1b146e07b60cc1736a01f21da01154.zip --output tst.zip  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1083k  100 1083k    0     0  1365k      0 --:--:-- --:--:-- --:--:-- 1373k
```

**Comment by aleReimondo** [comment]
Now the file can be downloaded from here too.

**Comment by DexerBR** [comment]
This has been happening to me for a few days now.
