### ISSUE TITLE
[JVM]: FLAG_IMMUTABLE or FLAG_MUTABLE is required when a PendingIntent is created

### ISSUE THREAD

**Issue by PythonLaboratory** [kivy/python-for-android#2759]
### Description

When I try to send a notification via the `plyer` library, I get an error

> JVM exception occurred: com.test.test.testservice: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

I tried to install `android.api = 30` (in buildozer.spec), but it didn't change anything

**If someone knows how to work around this problem by sending a notification, for example via `jnius`, then please tell me.**

### Version
python-for-android: master

**Comment by RobertFlatt** [comment]
Plyer is great if it works, But if not, IMHO walk away (nobody here will like that)

I don't know if it will help you but as an alternative look at this https://github.com/Guhan-SenSam/Android-Notification-in-Python
