### ISSUE TITLE
Fail installation

### ISSUE THREAD

**Issue by ocrock** [kivy/python-for-android#2764]
When trying installation found this issue : 

Collecting python-for-android
  Using cached python_for_android-2023.2.10-py3-none-any.whl (524 kB)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: colorama>=0.3.3 in c:\users\fu094usb\documents\mon_projet\social-auth-kivy\.venv\lib\site-packages (from python-for-android) (0.4.6)
Collecting pep517
  Using cached pep517-0.13.0-py3-none-any.whl (18 kB)
Collecting sh<2.0,>=1.10
  Using cached sh-1.14.3.tar.gz (62 kB)
  Preparing metadata (setup.py) ... error             
  error: subprocess-exited-with-error                 
                                                      
  × python setup.py egg_info did not run successfully.
  │ exit code: 1                                            
  ╰─> [8 lines of output]                                   
      Traceback (most recent call last):                    
        File "<string>", line 36, in <module>               
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\FU094USB\AppData\Local\Temp\pip-install-003t2egn\sh_6e9aa773570c4d9d892cd79e5a45ec22\setup.py", line 5, in <module>
          import sh
        File "C:\Users\FU094USB\AppData\Local\Temp\pip-install-003t2egn\sh_6e9aa773570c4d9d892cd79e5a45ec22\sh.py", line 37, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kuzeyron** [comment]
In order to use python-for-android you need a Unix system to compile apps with. No one have ported python-for-android for Windows.
But there are other ways you can do and that is to use WSL2 or VirtualBox on your Windows machine.
