### ISSUE TITLE
buildozer/p4a.prerequisites: enable automation build with no questions asked.

### ISSUE THREAD

**Issue by cederom** [kivy/python-for-android#2778]
* I am using buildozer for build automation.
* On a clean macOS environment not all prerequisites are installed.
* It would be nice to have option to enable automation so no questions are asked and the process does not require human interaction.

**Comment by RobertFlatt** [comment]
Reading buildozer.spec is time well spent.
```
# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
# android.accept_sdk_license = False
```

**Comment by Julian-O** [comment]
Closing as it isn't clear what action is required by p4a team.

**Comment by AndreMiras** [comment]
I think no action is required, as @RobertFlatt pointed out, there's an option to automatically accept the licence.
And if `sdkmanager` is used manually, then it's possible to use the `yes` command like so: `yes | $(ANDROID_SDK_HOME)/tools/bin/sdkmanager --sdk_root=$(ANDROID_SDK_HOME) --licenses > /dev/null`
