### ISSUE TITLE
BroadcastReceiver broken in service

### ISSUE THREAD

**Issue by multplx** [kivy/python-for-android#278]
Hi I have a kivy app with an activity and a service.

In service/main.py I have:
- from android.broadcast import BroadcastReceiver
  Up to last week this was working fine. It is now throwing the error:
- ''NoneType' object has no attribute 'getWindow''.
  flagged to _android.pyx line 178.
  I believe this is being caused by this change:
- https://github.com/kivy/python-for-android/commit/3345c66dcabf3555b57a50b8fb77657e6a6d5711
  and maybe get_keyboard_height() is now being called more than it was.

Can a change be made so that get_keyboard_height() is not called when in a service?
Or is there some change I can make in my code to accomodate this commit?
##

**Comment by tshirtman** [comment]
This has been confirmed to work recently enough, closing.
