### ISSUE TITLE
Feature Request: Add Python `3.11` support

### ISSUE THREAD

**Issue by DexerBR** [kivy/python-for-android#2798]
Looking forward to benefiting from the performance improvements of python 3.11 on Android, this is a feature request to add support for it in python-for-android.

**Comment by misl6** [comment]
This is certainly something we want to add in the near future. 😀

Hopefully, in the next few weeks, we will find out the majority of issues with current recipes on Python 3.10 (E.g https://github.com/kivy/python-for-android/pull/2800). This will help us to identify and migrate any outdated recipe, giving us the most possible clean path when upgrading to Python 3.11

**Comment by DexerBR** [comment]
Thank you @misl6! Sounds like a good plan!

**Comment by RobertFlatt** [comment]
> This will help us to identify and migrate any outdated recipe,

Oops, I read this and went a little crazy, 23 new issues.

**Comment by DexerBR** [comment]
> > This will help us to identify and migrate any outdated recipe,
> 
> Oops, I read this and went a little crazy, 23 new issues.

🤯

**Comment by misl6** [comment]
> > This will help us to identify and migrate any outdated recipe,
> 
> Oops, I read this and went a little crazy, 23 new issues.

Love that. I see there's something that likely will not need a recipe anymore, will triage the issues today.

**Comment by FeodorFitsner** [comment]
Are you going to add Python 3.11 to https://github.com/kivy/kivy-ios too?
