### ISSUE TITLE
Path commands on readme and official-website-toolchain don't seem to work

### ISSUE THREAD

**Issue by DeRobyJ** [kivy/python-for-android#281]
Hello,
I'd like to use python to program android apps, and I'm trying to install all the programs needed to do that in Ubuntu... since yesterday.
I've spent two hours yesterday and all today afternoon in trying to apply these two guides:
- http://python-for-android.readthedocs.org/en/latest/toolchain/#introduction
- https://github.com/kivy/python-for-android/blob/master/README.rst

I'll list all my problems
Official website introduction guide:
- #prerequisites VirtualBox suggestion links to the general kivy page: I actually downloaded kivy for ubuntu, but the Note wanted me to download a file that was at the bottom of the page.

But let's not use a virtual machine, also because I didn't have it working and I don't want to deal with virtual machines (I've installed VirtualBox, imported the image downloaded, got the boot screen, started Ubuntu and then the vm crashes)

- SDK/NDK: I didn't know that API8 was to download inside the SDK, so I've spent a lot of time searching for a download of the "API8"
I know that someone who is going to write for android should know how it works, but the thing is: I actually tried to install Android Studio and the Eclispe plugin for Android before, and yet I didn't remember what an API is.

And these were the readthedocs site problems only.

Now let's see what I couldn't do: PATH.

After some researches, I got to know how PATH works in Ubuntu (I knew what was on Windows, but I couldn't find it on Ubuntu at first)
And  I've learned that writing 
echo $PATH
on the terminal will tell me my current path variables.
Now let's try adding the path needed for the guides.
Apart from the fact that the two guides ask me to write different things (r7 vs r8b and "Also, you must configure you’re PATH to add the android binary:" is missing in the README).

These commands were uneffective: the terminal didn't say anything after I wrote the commands (and having checked all was wrote correctly. I did it 10 times today).
So I tried to double check with echo $PATH and nothing is added.
I've done other searches about how to add path, and the commads seem to be right for http://unixhelp.ed.ac.uk/environment/env3ab.html
wrong for other sites, like http://www.cyberciti.biz/faq/set-environment-variable-linux/ (but even the "set" command is not what they say, so maybe they're referring to something different)

Before understanding that my PATH was unchanged by all the commands I did, I actually tried to go for the #usage section.
".distribute.sh" is to download through "git clone git://github.com/kivy/python-for-android", but the official website introduction guide actually never said to download python-for-android. This made me lose an hour or two, because I didn't find the github page of kivy before.

Then of course I had to stop: here is where I found out about missing PATHs.

Could you please help me with my PATH and then write all the information needed in both guides?
Thank you very much in advance.

[note: in case it is not clear yet, I'm not a pro Linux user, nor I'm a programmer, nor I have good experience with terminals]

**Comment by inclement** [comment]
I'm closing this as probably outdated with the new toolchain, please raise it again if you still have the problem, though for problems like this you might be better off on the mailing lists.

**Comment by btatlisu** [comment]
Please blok meSent from EX Mail for iOS19:18, 6 декабря 2015 пользователь Alexander Taylor <notifications@github.com> написал:Closed #281.

**Comment by dessant** [comment]
@btatlisu, click on 'Not watching' in the watch menu at the top of the page, we can't do anything about this, you were the one who subscribed.
