### ISSUE TITLE
kivy cant load image in requesturl android

### ISSUE THREAD

**Issue by jabarmajidi** [kivy/python-for-android#2832]
I want to get images from my site using UrlRequest and API to display them in Kivy. this code The codes I wrote work correctly in Windows and Linux, but in Android it gives me a black picture. In fact, it cannot load the photo

this is my codes:

home_page.py:

    from kivymd.uix.screen import MDScreen
    from kivy.network.urlrequest import UrlRequest

    class HomePage(MDScreen):

        def on_enter(self):
            self.free_courses()

        def free_courses(self):
            data = UrlRequest('my api')
            data.wait(delay=0.5)
            for course in data.result:
                self.ids.free_courses.add_widget(FreeCourses(
                    image=course.get('app_image'),
                    title=course.get('category_name')))

home_page.kv:

    <FreeCourses>
        size_hint: None, None

        MDRelativeLayout:
            size_hint: None, None
            size: 100, 100
            FitImage:
                source: root.image
                size_hint: None, None
                size: 100, 80
                radius: [10,]
                pos_hint: {'center_x':0.5, 'center_y': 0.6}

**Comment by kuzeyron** [comment]
[Support question -> Kivy@Discord]
Sounds like you are missing the INTERNET permission in the spec file.

**Comment by jabarmajidi** [comment]
this is in buildozer.spec
andriod.permissions = android.permission .INTERNET, (name=android.permission.WRITE_STORAGE;maxSdkVersion=18)

**Comment by kuzeyron** [comment]
Just `android.permissions = android.permission.INTERNET` should be fine. The other part looks to be an example to be used without the parentheses. Then you should probably clean the old cached data with `buildozer appclean`.

**Comment by jabarmajidi** [comment]
i run buildozer appclean. not it rais this error:
in case of a bug report, lease add a full log with log_leve = 2

**Comment by kuzeyron** [comment]
Please share the entire `buildozer.spec`. How recent is your buildozer version?

**Comment by RobertFlatt** [comment]
@jabarmajidi 
That one line is not sufficient for anybody to help you
https://github.com/Android-for-Python/Android-for-Python-Users#if-buildozer-fails-to-compile
