### ISSUE TITLE
not installing on windows 10

### ISSUE THREAD

**Issue by sameermahajan** [kivy/python-for-android#2836]
### Checklist

- [X ] the issue is indeed a bug and not a support request
- [X] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [X ] I have a short, runnable example that reproduces the issue
- [ X] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [X ] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python: 3
- OS: Windows 10
- Kivy: NA
- Cython: NA
- OpenJDK: NA

### Description

When I try to install

$pip install python-for-android

on Windows 10, I get an error of:

ModuleNotFoundError: No module named 'fcntl'

When I lookup fcntl, it does not seem to exist for Windows

**Comment by RobertFlatt** [comment]
See the Buildozer install instructions 
https://github.com/kivy/buildozer/blob/master/docs/source/installation.rst#android-on-windows-10-or-11
