### ISSUE TITLE
scipy with kivy

### ISSUE THREAD

**Issue by isa5456** [kivy/python-for-android#2861]
¿Is it possible to use scipy with kivy?

Because I have tried to use https://github.com/mzakharo/android-gfortran/releases but I don't know if I have to do something more because it fails:

[DEBUG]:        -- Android: Targeting API '21' with architecture 'arm', ABI 'armeabi-v7a', and processor 'armv7-a'
[DEBUG]:        -- The Fortran compiler identification is unknown
[DEBUG]:        arm-linux-androideabi-gfortran: error trying to exec 'cc1': execvp: No such file or directory
[DEBUG]:        -- Android: Selected unified Clang toolchain
[DEBUG]:        -- The C compiler identification is Clang 9.0.9
[DEBUG]:        -- Check for working Fortran compiler: /home/isabel/.buildozer/android/platform/android-ndk-r21e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gfortran
[DEBUG]:        -- Check for working Fortran compiler: /home/isabel/.buildozer/android/platform/android-ndk-r21e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gfortran  -- broken
[DEBUG]:        CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestFortranCompiler.cmake:45 (message):
[DEBUG]:          The Fortran compiler
[DEBUG]:   
[DEBUG]:            "/home/isabel/.buildozer/android/platform/android-ndk-r21e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gfortran"
[DEBUG]:   
[DEBUG]:          is not able to compile a simple test program.

Thank you in advance!

**Comment by isa5456** [comment]
> ¿Is it possible to use scipy with kivy?
> 
> Because I have tried to use https://github.com/mzakharo/android-gfortran/releases but I don't know if I have to do something more because it fails.

Thank you in advance

**Comment by misl6** [comment]
Is possible, see:
https://github.com/kivy/python-for-android/pull/2370
https://github.com/kivy/python-for-android/pull/2615

For support questions, please refer to our support channels. 😀
