### ISSUE TITLE
Question: how to write a recipe to download and install(coz build fail) a wheel package directly?

### ISSUE THREAD

**Issue by riflemanl** [kivy/python-for-android#2878]
### Checklist

- [ ] the issue is indeed a bug and not a support request
- [ ] issue doesn't already exist: https://github.com/kivy/python-for-android/issues
- [ ] I have a short, runnable example that reproduces the issue
- [ ] I reproduced the problem with the latest development version (`p4a.branch = develop`)
- [ ] I used the grave accent (aka backticks) to format code or logs when appropriated

### Versions

- Python:
- OS:
- Kivy:
- Cython:
- OpenJDK:

### Description

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### buildozer.spec

Command:
```sh
// REPLACE ME: buildozer command ran? e.g. buildozer android debug
// Keep the triple grave accent (aka backquote/backtick) to have the code formatted
```

Spec file:
```
// REPLACE ME: Paste your buildozer.spec file here
```

### Logs

```
// REPLACE ME: Paste the build output containing the error
// Keep the triple grave accent (a.k.a. backquote/backtick) to have the code formatted
```

**Comment by RobertFlatt** [comment]
Usage questions should be directed to the user groups, this forum is for development issues.

It is not clear that the resolution implied in the question addresses the issue in the question.

When you post to the user groups provide the info referenced here:
https://github.com/Android-for-Python/Android-for-Python-Users#if-buildozer-fails-to-compile
And clarify what it is about "a wheel" that addresses the issue.

**Comment by riflemanl** [comment]
hi, Robert, my problem is actually a development issue, coz I've tried to use original torch recipe to build torch package for android arm, but it built out an x86_64 version package. So after some investigation I found pypi provided a prebuilt arm version wheel package already, I should not need to build it again, so, I issued a question above how to use that arm wheel directly, skip the setup/build problem, thanks a lot.
