### ISSUE TITLE
Fix sqlalchemy recipe

### ISSUE THREAD

**Issue by o-murphy** [kivy/python-for-android#2882]
Fix sqlalchemy build errors and bump sqlalchemy from 1.3.3 to 2.0+.

**Comment by misl6** [comment]
Hi @o-murphy , is this a feature request?

**Comment by o-murphy** [comment]
> Hi @o-murphy , is this a feature request?

No, it's request to up to date library build recipe

**Comment by BaccanoMob** [comment]
> Fix sqlalchemy build errors and bump sqlalchemy from 1.3.3 to 2.0+.

I agree with this since sqlalchemy total revamp to 2.0 and it fully differs from 1.4.

**Comment by o-murphy** [comment]
Does it support both major varsions 1.x and 2.x, today?
