### ISSUE TITLE
shared libs builds with 32 bit arch instaead of 64 bit

### ISSUE THREAD

**Issue by o-murphy** [kivy/python-for-android#2888]
### Versions

- Python: 10
- OS: Android
- Kivy: 2.2.1

### Description
After commit [https://github.com/kivy/python-for-android/commit/4d50d7d883bb6313f37c22402ecfaefa689bbbed](https://github.com/kivy/python-for-android/commit/4d50d7d883bb6313f37c22402ecfaefa689bbbed
) shared libs of cpython modules builds with 32 bit arch instaead of 64 bit

**Comment by RobertFlatt** [comment]
I was *unable* to replicate this with

```
android.archs = arm64-v8a
p4a.branch = develop
```

**Comment by misl6** [comment]
Hi @o-murphy , can you please add some more info about it ?

Is the `hostpython3` or the `python3` impacted (or both)?

If you're using `buildozer`, can you please attach your `buildozer.spec` file?
If you're using `python-for-android`, without the aid of `buildozer`, can you please post your full `p4a` cmd?
Are you running the toolchain on Linux or macOS ?

**Comment by o-murphy** [comment]
> Hi @o-murphy , can you please add some more info about it ?
> 
> Is the `hostpython3` or the `python3` impacted (or both)?
> 
> If you're using `buildozer`, can you please attach your `buildozer.spec` file? If you're using `python-for-android`, without the aid of `buildozer`, can you please post your full `p4a` cmd? Are you running the toolchain on Linux or macOS ?

Now i'm testing it, i think it not depend by last commit, issue is occuring in random run on CI build via github workflow, some builds fails to launch cause this error, but buildozer.spec and .yml was not changed between commit

**Comment by Julian-O** [comment]
There wasn't enough information provided to repro.

Closing as can't repro, but if the problem persists (after clearing caches and installing latest), please let us know with full debug logs.
