### ISSUE TITLE
App is crashing with Pyrebase4

### ISSUE THREAD

**Issue by wish-rohitv** [kivy/python-for-android#2893]
requirements = requirements = python3,kivy, pyrebase4, gcloud, googleapis-common-protos, protobuf, httplib2, pyparsing, oauth2client, pyasn1, pyasn1-modules, rsa, pycryptodome, python-jwt, jws, requests, certifi, chardet, idna, urllib3, requests-toolbelt , jwcrypto, cryptography, deprecated, wrap

log error -

![image](https://github.com/kivy/python-for-android/assets/126248971/a32e0a84-40ed-4301-b39d-a74161fa3094)

**Comment by Samael-TLB** [comment]
Follow the requirements stated here : https://github.com/Android-for-Python/Android-for-Python-Users#pyrebase4

Seems like you have spelt the last dependency wrong it should be `wrapt` and not `wrap`. 
Try with this and may be you can share about the results.

**Comment by wish-rohitv** [comment]
> Follow the requirements stated here : https://github.com/Android-for-Python/Android-for-Python-Users#pyrebase4
> 
> Seems like you have spelt the last dependency wrong it should be `wrapt` and not `wrap`. Try with this and may be you can share about the results.

thank but you are too late, i had also followed this documentation very carefully, may be now it have been updated

**Comment by Samael-TLB** [comment]
I see... Did you manage to solve this in some other way?
Or else we can consider this issue to be solved and may be you can choose to close it.

**Comment by wish-rohitv** [comment]
yeah i left pyrebase4 but issue is not solved, you should inspect this yourself the problem
