### ISSUE TITLE
aar file does not import properly in version v2023.09.16

### ISSUE THREAD

**Issue by amir0241** [kivy/python-for-android#2894]
when is use buildozer to make android apk file it gives me Could not find :libv2ray:. Required by: project : in version v2023.09.16 but when i use previous version of p4a everything is very normal and give me my apk file

**Comment by JohnBuckleyGitHub** [comment]
I think this is an issue in v2023.09.16

I had an operating script importing 'support-v4-24.1.1.aar' in v2023.05.21

After updating to v2023.09.16, the build would fail as the file could not be found.

One thing worth noting is that the paths in p4a for --add-aar have always been different from --add-jar. Meaning that if the files were in the same directory, --add-aar needed the full path while --add-jar used the relative path.

I have tried both path styles in v2023.09.16 and could not get a build to work. It does seem that the full path style is needed, however it fails on the gradle build.

**Comment by Julian-O** [comment]
@JohnBuckleyGitHub Please take it to Discord.

**Comment by Ivanking741245** [comment]
> 我認為這是 v2023.09.16 中的問題
> 
> 我有一個在 v2023.05.21 中導入“support-v4-24.1.1.aar”的操作腳本
> 
> 更新到v2023.09.16後，由於找不到文件，建置會失敗。
> 
> 值得注意的一件事是 p4a 中 --add-aar 的路徑始終與 --add-jar 不同。這意味著如果檔案位於同一目錄中，--add-aar 需要完整路徑，而 --add-jar 使用相對路徑。
> 
> 我在 v2023.09.16 中嘗試了兩種路徑樣式，但無法建立工作。似乎確實需要完整路徑樣式，但是它在 gradle 建置上失敗了。
> 
> 回滾到 v2023.05.21 後，它可以再次運行。

How should I change the version to v2023.05.21 in buildozer.spec?Thanks.
