### ISSUE TITLE
Kivy app crashes on startup

### ISSUE THREAD

**Issue by 0Beshoy** [kivy/python-for-android#2895]
I have been trying to fix this for days and haven't seen a similar issue , could anybody help ?

10-13 22:02:34.604  1645  1710 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.downtunes/files/app/.kivy/logs/kivy_23-10-13_6.txt
10-13 22:02:34.604  1645  1710 I python  : [INFO   ] [Kivy        ] v2.2.1
10-13 22:02:34.604  1645  1710 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
10-13 22:02:34.604  1645  1710 I python  : [INFO   ] [Python      ] v3.10.10 (main, Oct 13 2023, 16:30:34) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0
10-13 22:02:34.604  1645  1710 I python  : [INFO   ] [Python      ] Interpreter at ""
10-13 22:02:34.604  1645  1710 I python  : [INFO   ] [Logger      ] Purge log fired. Processing...
10-13 22:02:34.604  1645  1710 I python  : [INFO   ] [Logger      ] Purge finished!
10-13 22:02:34.605  1645  1710 I python  : [INFO   ] [KivyMD      ] 1.1.1, git-Unknown, 2023-10-08 (installed at "/data/user/0/org.test.downtunes/files/app/_python_bundle/site-packages/kivymd/__init__.pyc")
10-13 22:02:34.607  1645  1710 I python  : [INFO   ] [Factory     ] 190 symbols loaded
10-13 22:02:34.885  1645  1710 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
10-13 22:02:34.903  1645  1710 I python  : [INFO   ] [Text        ] Provider: sdl2
10-13 22:02:35.024  1645  1710 I python  : [INFO   ] [Window      ] Provider: sdl2
10-13 22:02:35.048  1645  1710 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
10-13 22:02:35.052  1645  1710 I python  : [INFO   ] [GL          ] Backend used <sdl2>
10-13 22:02:35.053  1645  1710 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@0615.0 (GIT@5a00bbd4b7, I0f5aa60515, 1673930385) (Date:01/16/23)'>
10-13 22:02:35.053  1645  1710 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
10-13 22:02:35.053  1645  1710 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 730'>
10-13 22:02:35.053  1645  1710 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
10-13 22:02:35.053  1645  1710 I python  : [INFO   ] [GL          ] Texture max size <16384>
10-13 22:02:35.053  1645  1710 I python  : [INFO   ] [GL          ] Texture max units <16>
10-13 22:02:35.088  1645  1710 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
10-13 22:02:35.090  1645  1710 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
10-13 22:02:35.299  1645  1710 I python  : [INFO   ] [GL          ] NPOT texture support is available
10-13 22:02:35.305  1645  1710 I python  : [WARNING] Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x785216cba0>" has been set, it will be removed in a future version
10-13 22:02:35.305  1645  1710 I python  : [WARNING] Deprecated property "<BooleanProperty name=keep_ratio>" of object "<kivy.uix.image.Image object at 0x785216cba0>" was accessed, it will be removed in a future version
10-13 22:02:35.441  1645  1710 I python  : [WARNING] [Base        ] Unknown <android> provider
10-13 22:02:35.441  1645  1710 I python  : [INFO   ] [Base        ] Start application main loop
10-13 22:02:36.350  1823  1823 F DEBUG   :   NOTE:   /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/_event.so
10-13 22:02:36.350  1823  1823 F DEBUG   :   NOTE:   /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-13 22:02:36.350  1823  1823 F DEBUG   :   NOTE:   /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.350  1823  1823 F DEBUG   :   NOTE:   /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/vbo.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #05 pc 000000000000ac70  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/vbo.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #06 pc 00000000000143b4  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #07 pc 0000000000008280  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #08 pc 00000000000122a0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #09 pc 0000000000011ae0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #10 pc 0000000000014b54  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #11 pc 000000000001607c  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #12 pc 0000000000008280  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #13 pc 00000000000122a0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #14 pc 0000000000011ae0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #15 pc 0000000000008280  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #16 pc 00000000000122a0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #17 pc 0000000000011ae0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #18 pc 0000000000014b54  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #19 pc 0000000000008280  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #20 pc 00000000000122a0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #21 pc 0000000000011ae0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #22 pc 0000000000014b54  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #23 pc 0000000000008280  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #24 pc 00000000000122a0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #25 pc 0000000000011ae0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #26 pc 0000000000014b54  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #27 pc 0000000000008280  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/compiler.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #28 pc 00000000000122a0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #29 pc 0000000000011ae0  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #30 pc 0000000000014b54  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #31 pc 000000000001607c  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #32 pc 0000000000020968  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/graphics/instructions.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #33 pc 0000000000172a2c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #34 pc 000000000023914c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #35 pc 0000000000234f5c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (_PyEval_EvalFrameDefault+9272)
10-13 22:02:36.351  1823  1823 F DEBUG   :       #36 pc 0000000000232a04  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #37 pc 000000000016bbd8  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #38 pc 0000000000025c34  /data/data/org.test.downtunes/files/app/_python_bundle/site-packages/kivy/_event.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #39 pc 0000000000172670  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #40 pc 000000000023914c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #41 pc 0000000000234f5c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (_PyEval_EvalFrameDefault+9272)
10-13 22:02:36.351  1823  1823 F DEBUG   :       #42 pc 0000000000232a04  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #43 pc 000000000023914c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #44 pc 0000000000234f5c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (_PyEval_EvalFrameDefault+9272)
10-13 22:02:36.351  1823  1823 F DEBUG   :       #45 pc 0000000000232a04  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #46 pc 000000000023914c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #47 pc 0000000000234f5c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (_PyEval_EvalFrameDefault+9272)
10-13 22:02:36.351  1823  1823 F DEBUG   :       #48 pc 0000000000232a04  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #49 pc 000000000023914c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #50 pc 0000000000234a40  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (_PyEval_EvalFrameDefault+7964)
10-13 22:02:36.351  1823  1823 F DEBUG   :       #51 pc 0000000000232a04  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #52 pc 000000000023914c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #53 pc 0000000000234f5c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (_PyEval_EvalFrameDefault+9272)
10-13 22:02:36.351  1823  1823 F DEBUG   :       #54 pc 0000000000232a04  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so
10-13 22:02:36.351  1823  1823 F DEBUG   :       #55 pc 000000000023294c  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (PyEval_EvalCode+104)
10-13 22:02:36.351  1823  1823 F DEBUG   :       #56 pc 0000000000279044  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (_PyRun_SimpleFileObject+1188)
10-13 22:02:36.351  1823  1823 F DEBUG   :       #57 pc 00000000002798ec  /data/app/~~fU8Y461gBdvP6ClZQXIU-g==/org.test.downtunes-a0xcLPR0gR8UsK0osqVMfQ==/lib/arm64/libpython3.10.so (PyRun_SimpleFileExFlags+60)

**Comment by misl6** [comment]
Hi @0Beshoy !

Can you please share your requirements and a minimal reproducible example?

**Comment by 0Beshoy** [comment]
i solved it by replacing kivymd in the  buildozer.spec requirments with  https://github.com/kivymd/KivyMD/archive/master.zip , for more info check : https://github.com/kivymd/KivyMD/blob/master/README.md#how-to-fix-a-shader-bug-on-an-android-device , https://github.com/Android-for-Python/Android-for-Python-Users#kivymd
