### ISSUE TITLE
doc/macos/jdk: invalid brew install command provided.

### ISSUE THREAD

**Issue by cederom** [kivy/python-for-android#2896]
Hello world :-)

Documentation [1] for latest and develop gives invalid OpenJDK command on macOS with brew. AdoptOpenJDK8 is abandoned. Modern Buildozer/P4A uses OpenJDK17 anyways. Please update :-)

[1] https://python-for-android.readthedocs.io/en/latest/quickstart/

**Comment by Julian-O** [comment]
If it wasn't fixed before #2923, it has been now.

**Comment by cederom** [comment]
TANK U @Julian-O :-)
