### ISSUE TITLE
error in your VM Image after ./distribute.sh -m kivy

### ISSUE THREAD

**Issue by LittleBuster** [kivy/python-for-android#291]
building 'kivy.graphics.svg' extension
ccache arm-linux-androideabi-gcc -mandroid -fomit-frame-pointer --sysroot /home/kivy/android/android-ndk-r8c/platforms/android-14/arch-arm -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -mandroid -fomit-frame-pointer --sysroot /home/kivy/android/android-ndk-r8c/platforms/android-14/arch-arm -fPIC -I/home/kivy/android/android-ndk-r8c/platforms/android-14/arch-arm/usr/include -I/home/kivy/android/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/svg.c -o build/temp.linux-i686-2.7/kivy/graphics/svg.o
kivy/graphics/svg.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 error: command 'ccache' failed with exit status 1

**Comment by btc-babydev** [comment]
I'm also getting the "error: command 'ccache' failed with exit status 1" issue when executing ./distribute.sh -m "kivy"

I'm using the latest VM package from http://kivy.org/#download which uses Ubuntu 12.10.  I've tried upgrading & downgrading cython, updating dependencies according as per the included Readme, and have tried starting from scratch multiple times.  Some direction would be greatly appreciated.

**Comment by akshayaurora** [comment]
the vm has been updated.
