### ISSUE TITLE
How to get real file path from uri 

### ISSUE THREAD

**Issue by USER4247** [kivy/python-for-android#2911]
Hi , I am using send receive example to get files into my app , although I have modded the example so my app can accept any type of file instead of only videos . I checked the code behind send share , it seems like the code copies files to cache . I am implementing a file sharing system in my app so I need real file path to keep track of files that were unloaded so user must not reupload same copies but I cant  get real file path from uri . I will provide modded code if needed . 

for example , uri is somewhat like this content://some stuff , but I want /storage/emulated/0/ like path when receiving files

**Comment by DisDoh** [comment]
The modded code is always needed, for example I would need it. Could you please share your get_real_path_from_uri?
