### ISSUE TITLE
ReadTheDocs version is unclear.

### ISSUE THREAD

**Issue by Julian-O** [kivy/python-for-android#2920]
At the time of writing, [python-for-android v2023.09.16](https://github.com/kivy/python-for-android/releases/tag/v2023.09.16) has been released.

I want to read the documents for that version.

When visiting https://python-for-android.readthedocs.io/ the default version is "latest". Other versions include "v2022.12.20" and earlier, and develop.

The "latest" version has no indicator whether it is 2023.09.16, or v2022.12.20 or master or develop or something else.  So reading it I can't be comfortable that it truly is the documentation that belongs to the release I am using.

Include a version or date in the latest document and/or include a duplicate set of documentation with the latest release number included, so readers can be confident.

**Comment by misl6** [comment]
https://python-for-android.readthedocs.io/en/develop/ the develop version now shows the version name on top left.

When a new `python-for-android` release will be performed, the `latest` version will be automatically updated accordingly.
