### ISSUE TITLE
Update documentation copyright

### ISSUE THREAD

**Issue by Julian-O** [kivy/python-for-android#2921]
Kivy has been under MIT license since [2013](https://github.com/kivy/python-for-android/commit/f2dbfb3db44bb03ea35980fe2d1ca2b2ee748999)

However, the [documentation reports on each page](https://python-for-android.readthedocs.io/en/latest/quickstart/):

> © Copyright 2015, Alexander Taylor 

I can see the name appearing in the code in a couple of places, but I can't see how it is getting sucked up into the documentation.

Remove Alexander's name and replace it with Kivy Team or similar.

**Comment by tcaduser** [comment]
A copyright is not a license.

Software licenses are not always the best for documentation.

I would like to suggest considering a Creative Commons license that protects the rights of the authors and the project:
https://chooser-beta.creativecommons.org/

**Comment by Julian-O** [comment]
> A copyright is not a license.

True. However, Mr Taylor is not the sole copyright owner of the communal work that has lots of contributors. This copyright statement is inaccurate, and this should change. 

> I would like to suggest considering a Creative Commons license 

Please do that in a separate issue. Changing a license is a major pain, and getting sufficient support will require a major campaign. Changing a copyright notice is a trivial edit, and doesn't need to wait.

**Comment by Julian-O** [comment]
> I can't see how it is getting sucked up into the documentation.

The reason for that is this was [fixed just under a week ago](https://github.com/kivy/python-for-android/commit/609ad2d61c242d8856c4d5d3bd4d4e7b8950b65c), but we haven't seen the new documents generated yet.

Closing as stale.

**Comment by misl6** [comment]
FYI: https://python-for-android.readthedocs.io/en/develop/ shows the updated version
