### ISSUE TITLE
Feature Request: Pymssql

### ISSUE THREAD

**Issue by tsiens** [kivy/python-for-android#2936]
Versions
Python:3.10
OS:Linux
Description
Is that possible that nice people can generate a recipe for Pymssql? Thank you so much in advance. 
I am unable to construct the recipe myself.
Alternatively, other methods can be provided to connect to the SQL Server database

**Comment by Julian-O** [comment]
I have never tried [pytds](https://github.com/denisenkom/pytds) but it may be an alternative.
