### ISSUE TITLE
Add  pdf2docx library recipe

### ISSUE THREAD

**Issue by alihassan143** [kivy/python-for-android#2941]

**Comment by Julian-O** [comment]
As with https://github.com/kivy/kivy-ios/issues/883 - why do you think a recipe is needed for this pure python package?

**Comment by alihassan143** [comment]
this can help to create custom converter for. the app

**Comment by akshayaurora** [comment]
All pure python packages can be specified in buildozer.spec as a requirement or directly with kivy-ios or p4a. There is no need for a separate recipe.
