### ISSUE TITLE
please add uvloop to recipes!

### ISSUE THREAD

**Issue by cweilouis** [kivy/python-for-android#2997]
please add uvloop to recipes! uvloop is a fast, drop-in replacement of the built-in 'asyncio' event loop. This has greatly improved the performance of our project. We urgently need it.  please! 🙏🙏🙏
uvloop url: https://github.com/MagicStack/uvloop/tree/master

**Comment by T-Dynamos** [comment]
Here it is: https://github.com/kivy/python-for-android/pull/2998!
