### ISSUE TITLE
ctypes module not loaded

### ISSUE THREAD

**Issue by aoncorici** [kivy/python-for-android#301]
I have tried to use dtls which is using ctypes from Python. The first behaviour was that ctypes was not included. I found a promising fix at: https://bitbucket.org/Nodrev/kivy-python-for-android-with-ctypes/commits/30948f20cef489dba165b3b33aefccbb5f400b84#chg-recipes/python/recipe.sh

but now it complains that:/python-for-android_old/build/python-install/lib/python2.7/ctypes/**init**.py", line 10, in <module>
I/python  ( 9805):  ImportError: No module named _ctypes

Anyone has an idea why?

**Comment by paddywwoof** [comment]
@aoncorici trying to get a project working on android and run into this issue. I've made the mods you point to, in the files (not using openssl stuff so not done second part)
However I'm still getting no _ctypes error. I'm re-running distribute.sh and build.py.. do I need to do something else to force python ctypes to be re-compiled using the changed malloc.h?

**Comment by aoncorici** [comment]
Dear paddywwoof, I am not sure if you already made the steps from the bitbucket project (https://bitbucket.org/Nodrev/kivy-python-for-android-with-ctypes/commits/30948f20cef489dba165b3b33aefccbb5f400b84#chg-recipes/python/recipe.sh). Then you can take a look at the cross compiling log and check what is the error. if you put only  python in the distribute line you will get less logs than usual. If there is any error during cross compiling then the ctypes.so will not be created. Unfortunately the process does not stop if a subcomponent is not compiling, the developer has to dig into the log.
In the end you should see the _ctypes.so in $BUID_python/build/lib.linux-x86_64-2.7, then you can try to add the lines:  
cd $BUILD_python
try cp -a build/lib.linux-x86_64-2.7/_ctypes*.so $LIBS_PATH

in the python recipe to copy the library to dist/default/private/lib/python2.7/lib-dynload.

Then you can add in PythonService.java the line referring to ctypes:
try {
                 System.load(getFilesDir() + "/lib/python2.7/lib-dynload/libcrypto.so.1.0.0");
                 System.load(getFilesDir() + "/lib/python2.7/lib-dynload/libssl.so.1.0.0");
                 System.load(getFilesDir() + "/lib/python2.7/lib-dynload/_ctypes.so");
} catch(UnsatisfiedLinkError e) {
}

**Comment by paddywwoof** [comment]
Hi

thanks for getting back so quickly.

On Mon, January 12, 2015 12:59 pm, aoncorici wrote:
> Dear paddywwoof, I am not sure if you already made the steps from the
> bitbucket project
> (https://bitbucket.org/Nodrev/kivy-python-for-android-with-ctypes/commits
> /30948f20cef489dba165b3b33aefccbb5f400b84#chg-recipes/python/recipe.sh).

yes I had made those changes to the three files.

> Then you can take a look at the cross compiling log and check what is the
> error. if you put only  python in the distribute line you will get less
> logs than usual.

I then ran
$ ./distribute.sh -m "python" > ~/kivy/pi3dtest/log.txt
does this do the cross compiling?

> If there is any error during cross compiling then the
> ctypes.so will not be created.

attached is the log.txt file. I can't really see any errors but it does
say on line 30 that it skipped build_python. Anyway there's no sign of
_ctypes.so in $BUID_python/build/lib.linux-x86_64-2.7

> Unfortunately the process does not stop if
> a subcomponent is not compiling, the developer has to dig into the log. In
> the end you should see the _ctypes.so in
> $BUID_python/build/lib.linux-x86_64-2.7, then you can try to add the
> lines:
> cd $BUILD_python try cp -a build/lib.linux-x86_64-2.7/_ctypes*.so
> $LIBS_PATH
>
>
> in the python recipe to copy the library to
> dist/default/private/lib/python2.7/lib-dynload.
>
> Then you can add in PythonService.java the line referring to ctypes:
> try { System.load(getFilesDir() +
> "/lib/python2.7/lib-dynload/libcrypto.so.1.0.0");
> System.load(getFilesDir() + "/lib/python2.7/lib-dynload/libssl.so.1.0.0");
>  System.load(getFilesDir() + "/lib/python2.7/lib-dynload/_ctypes.so");
> } catch(UnsatisfiedLinkError e) {
> }
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kivy/python-for-android/issues/301#issuecomment-6956599
> 9
[34;01mCheck build dependencies for Ubuntu[39;49;00m
[34;01mCheck enviromnent[39;49;00m
[30;01mSDK located at /home/jill/.buildozer/android/platform/android-sdk-21[39;49;00m
[30;01mNDK located at /home/jill/.buildozer/android/platform/android-ndk-r9c[39;49;00m
[30;01mNDK version is r9c[39;49;00m
[30;01mAPI level set to 14[39;49;00m
[34;01mCheck mandatory tools[39;49;00m
[34;01mDistribution will be located at /home/jill/buildozer/.buildozer/android/platform/python-for-android/dist/default[39;49;00m
[31;01mThe distribution /home/jill/buildozer/.buildozer/android/platform/python-for-android/dist/default already exist[39;49;00m
[31;01mPress a key to remove it, or Control + C to abort.[39;49;00m
[34;01mEntering in ARM environment[39;49;00m
[30;01mCompiler found at /home/jill/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc[39;49;00m
[30;01mPATH is /home/jill/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/bin/:/home/jill/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/:/home/jill/.buildozer/android/platform/android-ndk-r9c:/home/jill/.buildozer/android/platform/android-sdk-21/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games[39;49;00m
[34;01mLeaving ARM enviromnent[39;49;00m
[30;01mRead python recipe[39;49;00m
[30;01mModule python depend on hostpython[39;49;00m
[30;01mRead hostpython recipe[39;49;00m
[34;01mModules changed to hostpython python[39;49;00m
[34;01mPure-Python modules changed to [39;49;00m
[34;01mRun get packages[39;49;00m
[30;01mDownload package for hostpython[39;49;00m
[30;01mModule hostpython already downloaded[39;49;00m
[30;01mDownload package for python[39;49;00m
[30;01mModule python already downloaded[39;49;00m
[34;01mRun prebuild[39;49;00m
[30;01mCall prebuild_hostpython[39;49;00m
[30;01mCall prebuild_python[39;49;00m
[34;01mRun build[39;49;00m
[30;01mSkipped build_hostpython[39;49;00m
[30;01mSkipped build_python[39;49;00m
[34;01mEntering in ARM environment[39;49;00m
[30;01mCompiler found at /home/jill/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc[39;49;00m
Biglink create /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/libs/libpymodules.so library
Biglink arguments:
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/joystick.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/fastevent.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/cdrom.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/surflock.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/rwobject.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/time.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/pixelarray.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/overlay.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/imageext.so.o
 -lsdl_image
 -lpng
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/draw.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/surface.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/mask.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/base.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/_android.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/mouse.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/_imagingft.so.o
 -lfreetype
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/rect.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/_arraysurfarray.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/font.so.o
 -lsdl_ttf
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/event.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/image.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/_imaging.so.o
 -ljpeg
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/key.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/transform.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/constants.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/color.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/_imagingmath.so.o
 -L/home/jill/buildozer/.buildozer/android/platform/python-for-android/src/obj/local/armeabi
 -L/home/jill/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/lib
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/gfxdraw.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/display.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/_android_sound.so.o
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/bufferproxy.so.o
 -L/home/jill/buildozer/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/
 -lz
 -lsdl
 /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/objects/_android_billing.so.o
 -lm
 -L/home/jill/buildozer/.buildozer/android/platform/python-for-android/build/libs
 -Llibs/armeabi
 -L/home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib
 -llog
 -lpython2.7
[34;01mLeaving ARM enviromnent[39;49;00m
[34;01mRun postbuild[39;49;00m
[30;01mCall postbuild_hostpython[39;49;00m
[30;01mCall postbuild_python[39;49;00m
[34;01mRun pymodules install[39;49;00m
[30;01mNo pymodules to install[39;49;00m
[34;01mRun distribute[39;49;00m
[30;01mCreate initial layout[39;49;00m
[30;01mCopy default files[39;49;00m
[30;01mCopy python distribution[39;49;00m
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/bin ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/include ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7 ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/include/python2.7/pygame ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/pkgconfig ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7 ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/bsddb ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/bsddb/test ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/compiler ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/config ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/ctypes ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/ctypes/macholib ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/ctypes/test ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/distutils ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/distutils/command ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/email ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/email/mime ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/encodings ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/hotshot ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/idlelib ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/idlelib/Icons ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/importlib ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/json ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/lib-dynload ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/lib2to3 ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/lib2to3/fixes ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/lib2to3/pgen2 ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/logging ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/multiprocessing ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/multiprocessing/dummy ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/plat-linux3 ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/pydoc_data ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/PIL ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/android ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/compat ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/core ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/core/include ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/core/include/numpy ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/core/lib ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/core/lib/npy-pkg-config ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/core/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/core/tests/data ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/command ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/fcompiler ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/mingw ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/f2py_ext ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/f2py_ext/src ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/f2py_ext/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/f2py_f90_ext ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/f2py_f90_ext/include ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/f2py_f90_ext/src ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/f2py_f90_ext/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/gen_ext ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/gen_ext/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/pyrex_ext ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/pyrex_ext/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/swig_ext ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/swig_ext/src ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/distutils/tests/swig_ext/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/doc ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/docs ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/docs/usersguide ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/src ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/tests/src ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/tests/src/array_from_pyobj ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/tests/src/assumed_shape ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/tests/src/kind ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/tests/src/mixed ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/f2py/tests/src/size ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/fft ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/fft/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/lib ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/lib/benchmarks ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/lib/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/linalg ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/linalg/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/ma ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/ma/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/matrixlib ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/matrixlib/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/numarray ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/numarray/include ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/numarray/include/numpy ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/oldnumeric ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/oldnumeric/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/polynomial ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/polynomial/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/random ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/random/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/testing ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/testing/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/numpy/tests ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d/constants ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d/event ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d/loader ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d/shaders ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d/shape ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d/sprite ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d/util ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pi3d/util/icons ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pygame ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pygame/threads ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/pyxlib ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/sqlite3 ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/unittest ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/wsgiref ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/xml ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/xml/dom ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/xml/etree ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/xml/parsers ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/xml/sax ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/share ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/share/man ...
Listing /home/jill/buildozer/.buildozer/android/platform/python-for-android/build/python-install/share/man/man1 ...
[30;01mCopy libs[39;49;00m
[30;01mCopy java files from various libs[39;49;00m
[30;01mFill private directory[39;49;00m
[30;01mReduce private directory from unwanted files[39;49;00m
[30;01mStrip libraries[39;49;00m
[34;01mEntering in ARM environment[39;49;00m
[30;01mCompiler found at /home/jill/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc[39;49;00m
[34;01mLeaving ARM enviromnent[39;49;00m
[34;01mAll done ![39;49;00m

**Comment by paddywwoof** [comment]
sorry that attachment turned itself into a long post! 

Seems that an -f argument to distribute.sh was needed
