### ISSUE TITLE
Upgrade Pillow recipe to a version newer than 8.4.0

### ISSUE THREAD

**Issue by kuzeyron** [kivy/python-for-android#3019]
Please upgrade the Pillow recipe to a version newer than 8.4.0.
While trying out two different versions (9.5.0 and 10.3.0) I'm getting following error:
```
.buildozer/android/platform/python-for-android/pythonforandroid/recipes/Pillow/patches/fix-setup.patch

  STDOUT:
patching file setup.py
Hunk #1 succeeded at 124 (offset -1 lines).
Hunk #2 FAILED at 411.
patch unexpectedly ends in middle of line
Hunk #3 FAILED at 471.
2 out of 3 hunks FAILED -- saving rejects to file setup.py.rej
```

That's when having `Pillow==9.5.0` or `Pillow==10.3.0` in the requirements.

The problem with the `8.4.0` is that it's old and obsolete. There are problems with BMP files which is rendering black images (fixed on version 9.x..). It's probably doing the same with other formats other than Jpeg and PNG. With `8.4.0` I'm also getting errors that `webp` isn't included.

I hope this problem will be solved as soon as possible!

**Comment by tcaduser** [comment]
Hi,

You need to analyze how the patchfile interacts with 8.4.0 and then create
a new patch for the version you want to try:
https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/Pillow/patches/fix-setup.patch

You then need to make sure that using a new version of Pillow doesn't break
any of the packages depending on it:

matplotlib/__init__.py:    depends = ['kiwisolver', 'numpy', 'pillow',
'setuptools', 'freetype']

Regards,

Juan
