### ISSUE TITLE
Bug with android.p4a_whitelist in buildozer.spec file.

### ISSUE THREAD

**Issue by MohsenHassani** [kivy/python-for-android#302]
Hello guys,

I needed to use `unittest` for `raven`, so I added it to `android.p4a_whitelist`. After compilation and installing the `apk` file, the application would get closed because there was an error: not being able to import 'unittest'.
For solving the problem, with help of tshirtman in IRC I included 'unittest/*' in the file:
my_project/.buildozer/android/platform/python-for-android/dist/<name_of_my_project>/whitelist.txt

So I guess the during compilation procedure Buildozer ignores android.p4a_whitelist in spec file.

**Comment by FeralBytes** [comment]
So isn't this a bug with Buildozer then and not p4a? Opened issue [here](https://github.com/kivy/buildozer/issues/180) and I recommend this issue be closed as it is not an issue with p4a.

**Comment by tito** [comment]
This has already been fixed in https://github.com/kivy/buildozer/commit/b17a0ef6c13033ff58db84e9e88ee5d1eb1c223c
