### ISSUE TITLE
Numpy failing on development branch

### ISSUE THREAD

**Issue by JohnBuckleyGitHub** [kivy/python-for-android#3021]
### Versions

- Python: 3.11.5
- OS: Ubuntu 20.04
- Kivy: 2.3.0
- Cython: 0.29.37
- OpenJDK: 17.0.10
- Found NDK version 25b

### Description

Build p4a.branch = develop with numpy is failing with error below

No buildozer.
Run directly from python-for-android

* This builds ok with python-for-android==2024.01.21
* I get the failure below with latest development.
* I have also tried p4a.commit 33e1b460c11ae3cbf59e8842b6edf7627bc68a47 which also fails, but with a different error.

The intent was to get a build of numpy with pydantic > 2.0. 
The build from commit  33e1b460c11ae3cbf59e8842b6edf7627bc68a47 works in creating a pydantic 2.7, but does not work with numpy. Addition of numpy does not fail on build, but resulting application contains working numpy but is missing pydantic-core.

Addition or removal of pydantic on p4a.branch = development did not seem to affect numpy build failure behaviour.

All failures were tested with an uninstall of previous python-for-android, new python-for-android install and ```p4a clean_all``` before build.

Command:
```
p4a apk --debug --version=2.4.20669 --dist_name=nimbus --bootstrap sdl2  --requirements=libffi,android,python3==3.11.5,kivy==2.3.0,plyer,requests,openssl,certifi,numpy,pydantic,typing_extensions,annotated-types --arch arm64-v8a --name NIMBUS --package aero.streamlines.nimbus --android_api=31 --permission ACCESS_FINE_LOCATION --permission INTERNET  --permission ACCESS_NETWORK_STATE --permission REQUEST_INSTALL_PACKAGES --add-jar app/appjars/android_antlib-restricted_4-15-0.jar --add-jar app/appjars/channel.jar --enable-androidx --depend androidx.core:core:1.3.2 --presplash app/images/Streamlines_Splash.jpg --icon app/images/ic_launcher_round.png --orientation portrait --wakelock --window --color=always --private ~/app/
```

### Logs

```
<   File "/home/anon/.local/share/python-for-android/build/other_builds/hostpy
  thon3/desktop/hostpython3/Lib/importlib/resources/__init__.py", line 3, in
  <module>
<     from ._common import (
<   File "/home/anon/.local/share/python-for-android/build/other_builds/hostpy
  thon3/desktop/hostpython3/Lib/importlib/resources/_common.py", line 3, in
  <module>
<     import tempfile
<   File "/home/anon/.local/share/python-for-
  android/build/other_builds/hostpython3/desktop/hostpython3/Lib/tempfile.py",
  line 45, in <module>
<     from random import Random as _Random
<   File "/home/anon/.local/share/python-for-
  android/build/other_builds/hostpython3/desktop/hostpython3/Lib/random.py",
  line 49, in <module>
<     from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as
  _ceil
< ModuleNotFoundError: No module named 'math'
```

**Comment by T-Dynamos** [comment]
@JohnBuckleyGitHub Please attach the full log.

**Comment by T-Dynamos** [comment]
@JohnBuckleyGitHub I remembered something, do you have `patchelf` (apt install patchelf)  installed on your system?

If not, install it and retry building.

**Comment by JohnBuckleyGitHub** [comment]
patchelf fixes the numpy error.
