### ISSUE TITLE
freetype recipe cannot download

### ISSUE THREAD

**Issue by grekichi** [kivy/python-for-android#3031]
Hi there !

Today suddenly I cannot download "freetype" recipe. (buildozer stopped)
Yesterday I could download.

I checked their recipe contents, and I guess it is not working download server ? or some trouble ? 

So I switched download url for my local folder's recipe as follows,
(this is "[freetype site](https://freetype.org/download.html)"'s another recommendation)

current: [https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.gz](https://download.savannah.gnu.org/releases/freetype/freetype-2.10.1.tar.gz)

new: [https://sourceforge.net/projects/freetype/files/freetype2/2.10.1/freetype-2.10.1.tar.gz](https://sourceforge.net/projects/freetype/files/freetype2/2.10.1/freetype-2.10.1.tar.gz)

If you need, check this and study c/measures.

For your information.

**Comment by manikrishnaamarthi** [comment]
Did you got any method or solution for the above error?

**Comment by grekichi** [comment]
I try to modify freetype recipe by myself.
You should try too.
Take a look this [https://github.com/kivy/python-for-android/blob/develop/doc/source/recipes.rst](https://github.com/kivy/python-for-android/blob/develop/doc/source/recipes.rst)

**Comment by grekichi** [comment]
Site recoverded.

**Comment by manikrishnaamarthi** [comment]
yaa but now coming another error "ModuleNotFoundError: No module named 'math'"  and i have given these requirements
android.api = 33

android.minapi = 24

android.ndk_api = 24

**Comment by T-Dynamos** [comment]
@manikrishnaamarthi Please install patchelf (`apt install patchelf`) and build again.

**Comment by manikrishnaamarthi** [comment]
Thank you ......
