### ISSUE TITLE
Command ./distribute.sh -m "openssl pil kivy" results in error: command 'ccache' failed with exit status 1

### ISSUE THREAD

**Issue by jamesgaddum** [kivy/python-for-android#306]
building 'kivy.graphics.svg' extension
ccache arm-linux-androideabi-gcc -mandroid -fomit-frame-pointer --sysroot /home/kivy/android/android-ndk-r8c/platforms/android-14/arch-arm -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -mandroid -fomit-frame-pointer --sysroot /home/kivy/android/android-ndk-r8c/platforms/android-14/arch-arm -fPIC -I/home/kivy/android/android-ndk-r8c/platforms/android-14/arch-arm/usr/include -I/home/kivy/android/python-for-android/build/python-install/include/python2.7 -c kivy/graphics/svg.c -o build/temp.linux-i686-2.7/kivy/graphics/svg.o
kivy/graphics/svg.c:1303: error: expected specifier-qualifier-list before 'arrayobject'
kivy/graphics/svg.c: In function '__pyx_pf_4kivy_8graphics_3svg_3Svg___init__':
kivy/graphics/svg.c:9839: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:9839: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:9851: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:9851: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:9871: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:9871: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:9871: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:9872: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:9967: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_points'
kivy/graphics/svg.c:9977: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'circle_points'
kivy/graphics/svg.c:9989: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:9989: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:9989: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:9990: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:10006: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:10006: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:10006: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:10007: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:10018: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'anchor_x'
kivy/graphics/svg.c:10028: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'anchor_y'
kivy/graphics/svg.c:10066: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:10066: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:10066: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:10067: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:10077: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c: In function '__pyx_pf_4kivy_8graphics_3svg_3Svg_8anchor_y___set__':
kivy/graphics/svg.c:10445: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'anchor_y'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_parse_element':
kivy/graphics/svg.c:12834: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'circle_points'
kivy/graphics/svg.c:12898: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'circle_points'
kivy/graphics/svg.c:13040: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'circle_points'
kivy/graphics/svg.c:13104: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'circle_points'
kivy/graphics/svg.c:13192: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:13243: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_parse_path':
kivy/graphics/svg.c:13611: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:13611: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:13710: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:13731: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:13762: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:13762: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:13762: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:13763: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14240: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_cx'
kivy/graphics/svg.c:14249: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_cy'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_new_path':
kivy/graphics/svg.c:14654: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14654: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14654: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14655: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_close_path':
kivy/graphics/svg.c:14698: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14729: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14729: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14729: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14730: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_set_position':
kivy/graphics/svg.c:14825: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:14839: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_arc_to':
kivy/graphics/svg.c:15208: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'circle_points'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_curve_to':
kivy/graphics/svg.c:15355: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_points'
kivy/graphics/svg.c:15374: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:15429: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:15429: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:15429: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:15430: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:15440: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:15464: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_points'
kivy/graphics/svg.c:15468: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_points'
kivy/graphics/svg.c:15561: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:15576: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_cx'
kivy/graphics/svg.c:15585: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_cy'
kivy/graphics/svg.c:15603: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:15620: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:15632: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_end_path':
kivy/graphics/svg.c:15769: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:15790: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_push_mesh':
kivy/graphics/svg.c:16196: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_push_strip_mesh':
kivy/graphics/svg.c:16696: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:16706: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:16706: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:16739: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:16739: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:16739: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:16740: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:16750: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:16750: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c: In function '__pyx_f_4kivy_8graphics_3svg_3Svg_push_line_mesh':
kivy/graphics/svg.c:17351: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c: In function '__pyx_pf_4kivy_8graphics_3svg_3Svg_9gradients___get__':
kivy/graphics/svg.c:18231: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:18232: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c: In function '__pyx_pf_4kivy_8graphics_3svg_3Svg_9gradients_2__set__':
kivy/graphics/svg.c:18260: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:18260: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:18260: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:18261: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c: In function '__pyx_pf_4kivy_8graphics_3svg_3Svg_9gradients_4__del__':
kivy/graphics/svg.c:18286: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:18286: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:18286: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:18287: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c: In function 'get_memview_MemoryView_5array_7memview___get__':
kivy/graphics/svg.c:19953: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:19953: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '__pyx_array_new':
kivy/graphics/svg.c:20261: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:20261: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '__pyx_memoryview_is_slice':
kivy/graphics/svg.c:21422: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:21422: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '__pyx_memoryview_MemoryView_10memoryview_16is_c_contig':
kivy/graphics/svg.c:23568: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:23568: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '__pyx_memoryview_MemoryView_10memoryview_18is_f_contig':
kivy/graphics/svg.c:23633: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:23633: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '__pyx_memoryview_new':
kivy/graphics/svg.c:23851: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:23851: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '_unellipsify':
kivy/graphics/svg.c:24039: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:24039: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:24194: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:24194: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:24260: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:24260: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '__pyx_memoryview_fromslice':
kivy/graphics/svg.c:26277: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c:26277: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '__pyx_tp_new_4kivy_8graphics_3svg_Svg':
kivy/graphics/svg.c:28999: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:29000: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:29001: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:29002: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:29003: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c: In function '__pyx_tp_dealloc_4kivy_8graphics_3svg_Svg':
kivy/graphics/svg.c:29015: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:29015: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:29015: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:29016: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:29016: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:29016: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:29017: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:29017: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:29017: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:29018: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:29018: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:29018: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:29019: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:29019: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:29019: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c: In function '__pyx_tp_traverse_4kivy_8graphics_3svg_Svg':
kivy/graphics/svg.c:29045: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:29046: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:29048: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:29049: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:29051: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:29052: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:29054: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:29055: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:29057: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:29058: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c: In function '__pyx_tp_clear_4kivy_8graphics_3svg_Svg':
kivy/graphics/svg.c:29085: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:29086: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'loop'
kivy/graphics/svg.c:29088: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:29089: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'gradients'
kivy/graphics/svg.c:29091: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:29092: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'bezier_coefficients'
kivy/graphics/svg.c:29094: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:29095: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'line_texture'
kivy/graphics/svg.c:29097: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c:29098: error: 'struct __pyx_obj_4kivy_8graphics_3svg_Svg' has no member named 'last_mesh'
kivy/graphics/svg.c: In function 'initsvg':
kivy/graphics/svg.c:33513: warning: dereferencing type-punned pointer will break strict-aliasing rules
kivy/graphics/svg.c: In function '__Pyx_RaiseTooManyValuesError':
kivy/graphics/svg.c:33954: warning: format '%zd' expects type 'signed size_t', but argument 3 has type 'Py_ssize_t'
kivy/graphics/svg.c: In function '__Pyx_RaiseNeedMoreValuesError':
kivy/graphics/svg.c:33960: warning: format '%zd' expects type 'signed size_t', but argument 3 has type 'Py_ssize_t'
kivy/graphics/svg.c: In function '__Pyx_RaiseArgtupleInvalid':
kivy/graphics/svg.c:34211: warning: format '%zd' expects type 'signed size_t', but argument 5 has type 'Py_ssize_t'
kivy/graphics/svg.c:34211: warning: format '%zd' expects type 'signed size_t', but argument 7 has type 'Py_ssize_t'
kivy/graphics/svg.c: In function '__Pyx_BufFmt_ProcessTypeChunk':
kivy/graphics/svg.c:34761: warning: format '%zd' expects type 'signed size_t', but argument 3 has type 'long int'
kivy/graphics/svg.c:34761: warning: format '%zd' expects type 'signed size_t', but argument 4 has type 'long int'
kivy/graphics/svg.c: In function '__Pyx_GetBufferAndValidate':
kivy/graphics/svg.c:35002: warning: format '%zd' expects type 'signed size_t', but argument 3 has type 'Py_ssize_t'
kivy/graphics/svg.c:35002: warning: format '%zd' expects type 'signed size_t', but argument 6 has type 'long int'
kivy/graphics/svg.c: In function '__Pyx_ValidateAndInit_memviewslice':
kivy/graphics/svg.c:35104: warning: format '%zu' expects type 'size_t', but argument 3 has type 'Py_ssize_t'
 error: command 'ccache' failed with exit status 1
kivy@kivy-VirtualBox:~/android/python-for-android$

**Comment by sepeliry** [comment]
I have the same problem.

**Comment by arboss** [comment]
You need to install a new (but not too new) version of cython. I used 0.20.1.

    sudo pip install -I https://pypi.python.org/packages/source/C/Cython/Cython-0.20.1.tar.gz

then check your installed version

    cython --version

and try again.

**Comment by Skarlso** [comment]
I can't believe how frakking difficult this is. And their OWN distributed VM isn't working either. 

I was looking for an alternative to build Android apps, since I think that the Java apps are overly complicated, but damn, was I wrong if ever.

**Comment by tito** [comment]
Cython 0.22 cannot be used due to a bug in their side. We added check / warning mesasge into our setup.py to prevent it.

**Comment by lancewoo** [comment]
Great! Thanks  to arboss! 
It's OK to use Cython 0.20.1.

**Comment by kronenpj** [comment]
For what it's worth, this is still a problem with cython-0.23. I've worked around it using
`pip install --user -I https://pypi.python.org/packages/source/C/Cython/Cython-0.20.1.tar.gz`
and setting `PATH=$HOME/.local/bin:${PATH}` for these builds.

**Comment by inclement** [comment]
@kronenpj Are you using the new toolchain?

**Comment by kronenpj** [comment]
For some reason, I have never been able to get the new toolchaint to work. So maybe I'm actually having larger problems than this, but... No, it's the old toolchain.
`$ more .buildozer/android/platform/python-for-android/.git/config 
[core]
...
[remote "origin"]
        url = https://github.com/kivy/python-for-android.git
        fetch = +refs/heads/old_toolchain:refs/remotes/origin/old_toolchain
`

**Comment by zoltan-fedor** [comment]
Still a problem with cython-0.24.1
