### ISSUE TITLE
Unable to use <gstreamer> as loader!

### ISSUE THREAD

**Issue by brunoqc** [kivy/python-for-android#31]
I'm trying to play a mp3 on a Nexus one (2.3.7).

I get `Unable to use <gstreamer> as loader!` when the application starts and I get `Unable to found a loader for </mnt/sdcard/test.mp3>` when I try to play the mp3.

I saw on the google group that there was a fix for a similar problem : https://groups.google.com/forum/?fromgroups#!searchin/kivy-users/gstreamer/kivy-users/dbO-9_aprRo/37mlQCSsjGEJ

**Comment by FeralBytes** [comment]
I think this has been resolved for awhile, recommend closing it. Also isn't' that technically a kivy/kivy issue?
