### ISSUE TITLE
Build errors on OSX 10.10

### ISSUE THREAD

**Issue by DrMoriarty** [kivy/python-for-android#311]
Hello, I'm trying to build my project for android on osx yosemite and have a lot of errors during python compilation.
There is full build log: https://gist.github.com/DrMoriarty/d19c273d10bc444d3f9b
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11) (MacPorts llvm-gcc42 2336.11_1)

I noticed errors Unknown value '10.10' of -mmacosx-version-min and decided to update gcc.
Than I tried to install gcc 4.9.2 and compile pyhton with it, but no lucky. Full log: https://gist.github.com/DrMoriarty/a4c40c08edcc67f08141
gcc version 4.9.2 (MacPorts gcc49 4.9.2_1) 
Could anybody help me?
##

**Comment by tito** [comment]
Ref #321

**Comment by inclement** [comment]
Closing as this issue relates to the old toolchain which is no longer supported. Please open a new issue if you experience this problem with the current master branch.
