### ISSUE TITLE
Python Service multiple instances

### ISSUE THREAD

**Issue by aoncorici** [kivy/python-for-android#329]
Dear all,

Is is possible to have multiple PythonService instances when they are built inside different packages.

**Comment by FeralBytes** [comment]
Please close this issue and I will talk to you about it on the original issue.
Duplicate [Issue](https://github.com/kivy/python-for-android/issues/270).

**Comment by aoncorici** [comment]
Dear all,

I got scared too early. The answer is yes: you can have multiple Python for android/Kivy applications running at the same time when the package name building the apk is different.
