### ISSUE TITLE
After installing the Pillow does not compile the project. (Mac OS)

### ISSUE THREAD

**Issue by duhanov** [kivy/python-for-android#332]
After installing the Pillow (pip install pillow) does not compile the project. (Mac OS)

>
>
>
Entering in ARM environment
Compiler found at /Users/maksimduhanov/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin//arm-linux-androideabi-gcc
/Users/maksimduhanov/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: freetype: no archive symbol table (run ranlib)
/Users/maksimduhanov/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: png: no archive symbol table (run ranlib)
/Users/maksimduhanov/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: jpeg: no archive symbol table (run ranlib)
/Users/maksimduhanov/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: z: no archive symbol table (run ranlib)
collect2: error: ld returned 1 exit status
Biglink create /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/libs/libpymodules.so library
Biglink arguments:
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/_android.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/_android_billing.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/_android_sound.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/_arraysurfarray.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/_event.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/_imaging.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/_imagingft.so.o
 -lfreetype
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/_imagingmath.so.o
 -L/opt/local/lib
 -L/Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/src/obj/local/armeabi
 -L/Users/maksimduhanov/.buildozer/android/platform/android-ndk-r9c/platforms/android-14/arch-arm/usr/lib
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/base.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/buffer.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/bufferproxy.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/c_opengl_debug.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/cdrom.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/color.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/compiler.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/constants.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/context.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/context_instructions.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/display.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/draw.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/event.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/fastevent.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/fbo.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/font.so.o
 -lsdl_ttf
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/gfxdraw.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/gl_instructions.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/image.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/imageext.so.o
 -lsdl_image
 -lpng
 -ljpeg
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/instructions.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/jnius.so.o
 -Llibs/armeabi
 -llog
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/joystick.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/key.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/mask.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/mouse.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/opengl.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/opengl_utils.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/overlay.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/pixelarray.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/properties.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/rect.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/rwobject.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/shader.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/stencil_instructions.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/surface.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/surflock.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/texture.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/time.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/transform.so.o
 -L/Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/src/obj/local/armeabi/
 -lz
 -lsdl
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/transformation.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/vbo.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/vertex.so.o
 /Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/objects/vertex_instructions.so.o
 -L/Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/libs
 -L/Users/maksimduhanov/Projects/kivy/test/.buildozer/android/platform/python-for-android/build/python-install/lib
 -lGLESv2
 -lpython2.7
 -lm

**Comment by tito** [comment]
Dunno how you actually installed Pillow, this is not supported in Python for android :(
