### ISSUE TITLE
ctypes.py and _ctypes.so are not available

### ISSUE THREAD

**Issue by olymk2** [kivy/python-for-android#333]
Seems quite a few libraries require _ctypes.so to be available i have found a few reported by others and in my case freetype requires it.

seems there are reports of people getting it to work (I have not managed myself yet) here are some links i have found.

Patch here
https://groups.google.com/forum/?hl=en#!searchin/python-android/ctypes/python-android/vDaaJXNYz_A/eazMVI-DQSYJ

related issue here 
https://github.com/kivy/python-for-android/issues/301

and another attempt here
https://bitbucket.org/Nodrev/kivy-python-for-android-with-ctypes/commits/30948f20cef489dba165b3b33aefccbb5f400b84#chg-recipes/python/recipe.sh

I have been trying myself but i dont seem to get a ctypes.so file created, my attempt is here but i am unsure about what i am doing :p
https://github.com/olymk2/python-for-android/tree/feature/ctypes

Would be good to see this one patch an dbuilding.

**Comment by tito** [comment]
@olymk2 Great progress on your branch, i'm waiting your PR :)

**Comment by olymk2** [comment]
i am hoping to put one in soon using this PR https://github.com/olymk2/python-for-android/pull/1

it seems to build the ctypes.so file and place it in ../libs/armeabi/_ctypes.so as i expect how ever running on an android tablet i am still getting.

.buildozer/android/app/_applibs/freetype/__init__.py", line 19, in <module>
.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/ctypes/__init__.py", line 10, in <module>
ImportError: No module named _ctypes
Python for android ended.
System.exit called, status: 0

when i try to use a library that requires ctypes in this case freetype i still get

so i am not sure if there is something else i need todo after the .so file exists i have put in the PythonService.java file to load the library.

does anyone have any ideas ? i could put it in for a pr now because it does build the .so file.

**Comment by tito** [comment]
the libs in libs are more "system" lib, not python extension.

Either the _ctypes.so is biglinked with libpython.so, or it's separated in the ctypes/_ctypes.so directory, same on desktop.

**Comment by olymk2** [comment]
okay, i will try again later see if i can figure out if its creating a folder for ctypes or if its being biglinked.

its quite difficult to spot whats going on as the build process chucks out so much content.

thanks for the tip

**Comment by olymk2** [comment]
Created a dead basic repo to test python imports, link here if its usefull to any one https://github.com/olymk2/buildozer-test-imports

**Comment by olymk2** [comment]
just an update with progress i can see ctypes is created and placed in the path below.

/opt/buildozer/testappimports/.buildozer/android/platform/python-for-android/dist/testappimports/private/lib/python2.7/lib-dynload/_ctypes.so

_ctypes.so is 168.1 kB in /testappimports/private/lib/python2.7/lib-dynload/_ctypes.so

but still no joy, i did manage to patch out all errors i could see during the build process i am wondering if i have something else going wrong some where

**Comment by olymk2** [comment]
Okay this may actually be working i just built my test project wondering if i have some cruft left on my system perhaps the clean is not fully clearing everything away.

going to blow away the build on my main program later and see if it works anyone fancy trying the above to see if it works, if you use the test project be aware it builds the project in /opt/buildozer so change or take that out of the spec file.

**Comment by GeoRW** [comment]
Hi, I tried this and it worked! 
_ctypes.so was built correctly and included in android package.
-rwxr-xr-x 1 georw georw 485084 Apr  4 15:58 _ctypes.so

I applied the patch from:
 https://groups.google.com/forum/?hl=en#!searchin/python-android/ctypes/python-android/vDaaJXNYz_A/eazMVI-DQSYJ
as well as fix for malloc.h:
In the file: android-ndk-r9d/platforms/android-14/arch-arm/usr/include/malloc.h have the line: extern size_t malloc_usable_size(void*); //instead of (const void*)

All compiled well, and it's working on Android.
Regards

**Comment by olymk2** [comment]
@GeoRW I have a PR in for these changes, you will find that although it compiles you can not import any libraries because ctypes does not know where to look.

There is a simple fix for that also in this branch https://github.com/kivy/python-for-android/pull/343 if you have tested from this branch may be worth commenting hopefully we can get it merged :)

**Comment by GeoRW** [comment]
well, I can use the compiled library in Android without any issues. no need to patch util.py in my case. I'm loading libwebp.so when using https://github.com/expobrain/python-webm which requires ctypes. Don't know much about C and the whole build process, but happy to make this working for my project. Cheers.

**Comment by GeoRW** [comment]
ok, tried the patches at https://github.com/kivy/python-for-android/pull/343 on clean environment and all workes fine without a need to patch malloc.h in NDK. ctypes library is compiled and packaged correctly. Cheers

**Comment by tito** [comment]
Ctypes is now part of python-for-android!

**Comment by smpsupply** [comment]
Hello all, I tried to compile with buildozer and python-2.7.2 is downloaded. I tried to follow the solution provided here but I found the recipe is different. After finish build, _ctypes still doesn't appear in the folder. My environment is MacOS 10.13.4. Hope someone can help. Thanks.
