### ISSUE TITLE
Failed to build pure Python module included after `twisted`

### ISSUE THREAD

**Issue by jasonxunxu** [kivy/python-for-android#337]
When including a pure Python module like `rsa` right after `twisted`:
```bash
./distribute.sh -m "twisted rsa kivy" -d "test"
```

Building would eventually fail with following error:
```
Run pymodules install
We want to install: rsa
Check if /usr/local/bin/virtualenv is present
Check if a virtual environment already exists
Installing virtualenv
New python executable in venv/bin/python2.7
Also creating executable in venv/bin/python
Installing setuptools, pip...done.
Running virtualenv with interpreter /usr/bin/python2.7
Create a requirement file for pure-python modules
Install pure-python modules via pip in venv
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Collecting rsa (from -r requirements.txt (line 2))
  Using cached rsa-3.1.4.tar.gz
  setuptools must be installed to install from a source distribution
```

It is quite strange as `setuptools` was clearly already installed in venv.

**Comment by jasonxunxu** [comment]
It turns out that the `twisted` recipe (and maybe some other recipes) changed `PYTHONPATH`:
```bash
export PYTHONPATH=$SITEPACKAGES_PATH:$BUILDLIB_PATH
```
which was then mistakenly picked up by venv, leading to the missing `setuptools`.

Virtualenv should be setup with no `PYTHONPATH`, a PR wil follow.

**Comment by FeralBytes** [comment]
Were you running P4A in a venv, or are you talking about the venv that P4A creates it's self? I am sure it is the case but just confirm that your PR #338 does actually remedy the issue without causing any side effects?

**Comment by jasonxunxu** [comment]
I was talking about the venv created by P4A. AFAIK PR #338 fixed the issue, and I haven't observed side effects so far.

**Comment by kived** [comment]
Can you test that #320 fixes this? Similar problems happen between recipe builds as well, and your fix wouldn't help that.

**Comment by FeralBytes** [comment]
@jasonxunxu did you ever test #320 as requested by kived?

**Comment by tito** [comment]
We'll assume it does. Please reopen if the case still happen.
