### ISSUE TITLE
Error In building kivy android on Mac OSX

### ISSUE THREAD

**Issue by ktitan123** [kivy/python-for-android#340]
Hello
I am getting the following error while building app using
buildozer android debug

make: *** [Python/mactoolboxglue.o] Error 1
make: *** Waiting for unfinished jobs....
# Command failed: ./distribute.sh -m "kivy" -d "'myapp'"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error

**Comment by tito** [comment]
We added more message information to prevent raising issue without valuable information. Attach the whole log, system information, anything that we can use for debugging. 

If you don't know what to show, show everything, not the thing you think it will be enough. :)
