### ISSUE TITLE
does this matter ? arm-linux-androideabi-gcc: error: kivy/graphics/opengl.c: No such file or directory

### ISSUE THREAD

**Issue by olymk2** [kivy/python-for-android#362]
I often notice this failing during a build everything compiles and builds and kivy works fine regardless but it looks like quite a major failure even though everything works out.

just thought i would report it incase its significant :)

building 'kivy.graphics.opengl' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/kivy
creating build/temp.linux-x86_64-2.7/kivy/graphics
arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/oly/.buildozer/android/platform/android-ndk-r9d/platforms/android-14/arch-arm -DNDEBUG -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/oly/.buildozer/android/platform/android-ndk-r9d/platforms/android-14/arch-arm -fPIC -I/home/oly/.buildozer/android/platform/android-ndk-r9d/platforms/android-14/arch-arm/usr/include -I/home/oly/repos/testing/enable-ctypes/build/python-install/include/python2.7 -c kivy/graphics/opengl.c -o build/temp.linux-x86_64-2.7/kivy/graphics/opengl.o
arm-linux-androideabi-gcc: error: kivy/graphics/opengl.c: No such file or directory
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
 error: command 'arm-linux-androideabi-gcc' failed with exit status 1

**Comment by kived** [comment]
That is expected. The recipe runs setup.py once, knowing it will fail, then
runs Cython on all the files and runs setup.py again.

**Comment by olymk2** [comment]
good to know, though i do wonder about that, seems wrong that we even need a second attempt at compiling when the params look identical to the first attempt.
