### ISSUE TITLE
bulldozer and distribute.sh

### ISSUE THREAD

**Issue by idarek92** [kivy/python-for-android#364]
My distribute.sh file crashes on my mac running 10.10.2. Lines 286, 400, and 401: 
```
./distribute.sh: line 286: lsb_release: command not found
Check build dependencies for 
Avoid check build dependencies, unknow platform 
Check environment
SDK located at /Users/Darek/.buildozer/android/platform/android-sdk-21
NDK located at /Users/Darek/.buildozer/android/platform/android-ndk-r9c
NDK version is r9c
API level set to 14
Check NDK location
Check mandatory tools
Distribution will be located at /dist/pongTest
The distribution /dist/pongTest already exist
Press a key to remove it, or Control + C to abort.

./distribute.sh: line 400: /src/default.properties: No such file or directory
./distribute.sh: line 401: /src/local.properties: No such file or directory
cp: /src/blacklist.txt: No such file or directory
```

**Comment by tito** [comment]
This can happen if your default shell is not bash. Ensure it's the case?

**Comment by vrescobar** [comment]
Hi that there is happening me on MacOSX, the shell is bash and the example... a bare hello world which works on desktop.

**Comment by macmittereder** [comment]
I'm also having this problem with a bare hello world application

**Comment by ryansehrlich** [comment]
Hi all, this happend to me too. What you need to do is change your default shell to bash. http://osxdaily.com/2012/03/21/change-shell-mac-os-x/

Hope this helps

ps. Kivy devs your software is fantastic

**Comment by ryansehrlich** [comment]
I'm also having this problem. My Default shell is bash, and I followed all the steps. Help please

**Comment by inclement** [comment]
Not sure what caused this, though it may be fixed now, please raise the issue in the mailing lists if you get this problem.

**Comment by EpicSoftworks** [comment]
```
NDK version is r9c
API level set to 14
Check NDK location
Check mandatory tools
Distribution will be located at /dist/pongTest
The distribution /dist/pongTest already exist
Press a key to remove it, or Control + C to abort.

./distribute.sh: line 400: /src/default.properties: No such file or directory
./distribute.sh: line 401: /src/local.properties: No such file or directory
cp: /src/blacklist.txt: No such file or directory
```

I had error messages along these lines. I discovered that you get the same error message when a folder has spaces in the name along in your project's path. I didn't see that answer in here and this was a good help. The spaces in path don't get escaped so they break buildozer in the process.

My folder was the following wich failed:
`/media/rob/DEV/Untitled Folder/myTestApp`

Then i moved my project folder to this and worked:
`/media/rob/DEV/myTestApp`
