### ISSUE TITLE
Enable armeabi-v7a-hard

### ISSUE THREAD

**Issue by directrix1** [kivy/python-for-android#366]
I've been trying to build using armeabi-v7a-hard, by setting the ARCH in distribute.py . I'm doing this to use the hard float ABI to try and extract a bit better floating point performance out of Kivy animations. It seems to work pretty well in general, except sometimes projects either don't honor the arch or they try to explicitly link with the m library instead of m_hard. Would love a little help with this.

**Comment by directrix1** [comment]
To get it working, I just set the CFLAGS and LDFLAGS to the appropriate values and added "--with-libm=' -lm_hard '" to the python recipe's config lines. Here is what I set in distribute.py if anyone cares.

**Comment by tito** [comment]
This could be done, but first we need to analysis what phone works/don't work with this flag, and how we can support previous generation if needed.

**Comment by inclement** [comment]
With a --arch option fully implemented in the new toolchain, I'm going to close this. We'd probably accept a PR to the old toolchain if anyone wants to do it.
