### ISSUE TITLE
p4a crashes under ARC

### ISSUE THREAD

**Issue by cbenhagen** [kivy/python-for-android#367]
Error output and hello world program used can be found [here](https://gist.github.com/cbenhagen/c948c9059a32c67c6301#file-gistfile1-txt).

More about ARC:
https://developer.chrome.com/apps/getstarted_arc
##

**Comment by tito** [comment]
Thanks for providing the log. I just discover ARC, didn't knew this at all. I have no idea  about the error behind, and why it would crash. Anyway, this is not a platform we are currently supporting. As ARC is still in Beta, it might even be an issue on their side as well.

**Comment by inclement** [comment]
Closing for lack of interest in ARC.
