### ISSUE TITLE
Build a release so this can be included in F-Droid

### ISSUE THREAD

**Issue by robinpaulson** [kivy/python-for-android#369]
I have asked [1] for this to be included in F-Droid [2], a free software catalogue of applications for Android. To do so, it would be best to have a release, could you tag a suitable commit as a release please?

[1] https://f-droid.org/forums/topic/python-on-android/#post-15679
[2] https://f-droid.org/

**Comment by inclement** [comment]
Isn't F-Droid a catalogue of android apps? P4A isn't an android application, but a tool for making apks.

**Comment by robinpaulson** [comment]
OK, sure. I think I've got horribly confused somewhere.... my bad. Suggestions welcome for a Python interpreter which runs on Android, which is what I'm actually looking for.

**Comment by inclement** [comment]
Such a thing is provided by QPython.
