### ISSUE TITLE
android app crash on screen rotation

### ISSUE THREAD

**Issue by sladinji** [kivy/python-for-android#379]
[This commit](https://github.com/kivy/python-for-android/commit/aa38c6b99544439dfe08792477341f01d4d116ea#diff-f181688cd9c24982672c7a922a429f70R18) makes my app crash on screen rotation. In  src/templates/AndroidManifest.tmpl.xml line 32 : 

...{% if **android_api** >= 13 %}|screenSize{% endif %}"
...{% if args.**min_sdk_version** >= 13 %}|screenSize{% endif %}"

should be : 
{% if args.**sdk_version** >= 13 %}|screenSize{% endif %}"

if we want to keep the same behavior. Otherwise, app with auto rotating screen will now crash on rotation if "android.minapi" in buildozer.spec is not set to at least 13.
...{% if args.**sdk_version** >= 13 %}|screenSize{% endif %}"

**Comment by denys-duchier** [comment]
indeed setting android.minapi=13 fixes the issue for me.

**Comment by WSember** [comment]
I've been having the same issue, and setting android.minapi=13 also fixed it for me.

I'm on Android 5.0.2.

**Comment by kived** [comment]
This is fixed in #382.
