### ISSUE TITLE
building harfbuzz with freetype support symbol errors

### ISSUE THREAD

**Issue by olymk2** [kivy/python-for-android#381]
Hoping some one can help me out i have spent quite a bit of time on this and not progressed.

```
I/python  ( 8605):  OSError: dlopen failed: cannot locate symbol "hb_ft_font_create" referenced by "libfreetype.so"...
```

From googling around it sounds like this means those methods are not available in the built .so file.

however I can inspect the built files  with objdump

```
objdump -TC libharfbuzz.so | grep hb_font_create
00013208 g    DF .text  000000ac hb_font_create
000132b4 g    DF .text  000000c0 hb_font_create_sub_font

objdump -TC libfreetype.so | grep hb_ft
00000000      D  *UND*  00000000 hb_ft_font_create
```

I wonder if its a case of freetype cant find harfbuzz to call the method perhaps ? 
but i am delving deeper and deeper out of my knowledge level with this stuff.

any one able to lend a hand or offer some things to try ?

you can see my current branch here https://github.com/kivy/python-for-android/pull/378
##

**Comment by tito** [comment]
I guess freetype know about harfbuzz and use a function declared into the harfbuzz. But Harfbuzz don't know about freetype and don't compile the needed method.

It might be due to a invalid set of flags / ordering during the compilation maybe ?

**Comment by olymk2** [comment]
you might be right, i am still trying to figure this out when i get some time as its stopping me progressing with my app.

I have tried various different flags and different orderings, but i am stabbing around in the dark quite a bit :/

**Comment by olymk2** [comment]
I have created a simple gist which will throw the error when loading freetype.

https://gist.github.com/olymk2/d5801d9e1df0459625a3

My current progress is below, i believe it may need the nostdinc option, i believe its building against local libraries but i can convince it to work with nostdinc option.

https://github.com/kivy/python-for-android/pull/378

the buildozer.spec file i am using has a hard coded py4a folder so if you use that update it.

**Comment by inclement** [comment]
The harfbuzz recipe has changed a lot since this was created, please reopen if it's still a current issue causing a problem.
