### ISSUE TITLE
Android app crashing when ended and on_stop is not executed

### ISSUE THREAD

**Issue by mrhubbs** [kivy/python-for-android#384]
My app is crashing when I end it and the code in on_stop is not being run.  The logcat shows the error:

I/ActivityManager(  777): Killing 13468:crown.test.test:python/u0a241 (adj 9): remove task
E/audit   ( 1832): type=1701 msg=audit(1432319840.786:234): auid=4294967295 uid=10241 gid=10241 ses=4294967295 subj=u:r:untrusted_app:s0 pid=13468 comm="est.test:python" reason="memory violation" sig=11

This crash message looks somewhat similar to the one I was getting from [this issue](https://github.com/kivy/python-for-android/issues/379):

E/audit   ( 1832): type=1701 msg=audit(1432320584.076:236): auid=4294967295 uid=10241 gid=10241 ses=4294967295 subj=u:r:untrusted_app:s0 pid=15912 comm="est.test:python" reason="memory violation" sig=11
I/ActivityManager(  777): Process crown.test.test:python (pid 15912)(adj 0) has died(69,329)

The fix for that issue doesn't help this issue.
##

**Comment by kived** [comment]
Please provide a full log of your application run, and try with the most recent version of p4a.

**Comment by WSember** [comment]
I've re-run with the most recent p4a and am experiencing the same problem.  See the log [here](https://gist.github.com/WSember/1f8929dfbc7e101dfb95).  The error messages seems to be on lines 812-813.

The application is very simple:

```python
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
         return Button(text='hello')

    def on_pause(self):
        print('pausing')
        return True

    def on_stop(self):
         print('goodbye !!!!!! . . . . ')
         return True

if __name__ == '__main__':
    TestApp().run()
```

**Comment by inclement** [comment]
I think this doesn't happen any more. It can be reopened if necessary.
