### ISSUE TITLE
Does not build on OSX

### ISSUE THREAD

**Issue by 0xABC** [kivy/python-for-android#387]
Running:

    ./distribute.sh -m openssl

I get (after some time):

    Leaving ARM environment
    ./distribute.sh: line 669: $envrestore: ambiguous redirect
    grep: option requires an argument -- f
    usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    	[-e pattern] [-f file] [--binary-files=value] [--color=when]
    	[--context[=num]] [--directories=action] [--label] [--line-buffered]
    	[--null] [pattern] [file ...]
    Entering in ARM environment
    Compiler found at /Users/markprosser/Library/Android/ndk//toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin//arm-linux-androideabi-gcc
    Biglink create /private/tmp/p/python-for-android/build/libs/libpymodules.so library
    Biglink arguments:
    arm-linux-androideabi-gcc: fatal error: no input files
    compilation terminated.

**Comment by tito** [comment]
@kived ?

**Comment by kived** [comment]
`mktemp` works differently on OS X, which I did not know when adding that feature. There was a PR (#344) which fixed usage on OS X, which was previously merged, but I ended up reverting it (#349) because it broke Linux builds. I asked the author of that PR to make it work on both Linux and OS X, but that never happened.

I don't have access to OS X and can't test it, otherwise I'd fix it myself.

**Comment by 0xABC** [comment]
I tried the patch from that pull request, but I still get:

    Leaving ARM environment
    Entering in ARM environment
    Compiler found at /Users/markprosser/Library/Android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin//arm-linux-androideabi-gcc
    Biglink create /private/tmp/p/python-for-android/build/libs/libpymodules.so library
    Biglink arguments:
arm-linux-androideabi-gcc: fatal error: no input files
    compilation terminated.

**Comment by 0xABC** [comment]
Just tried on an Ubuntu machine and I get a very similar error

**Comment by kived** [comment]
Ubuntu is my primary platform, I can assure you that p4a works there. You **must** include kivy in the module list when you build your distribution. And that is a different issue than the original issue, which is with the envsave/envrestore functionality.

**Comment by 0xABC** [comment]
@kived I was not including kivy.  When I change to running:

    ./distribute.sh -f -m openssl kivy

I'm getting the same error...

**Comment by kived** [comment]
The module list needs to be a single argument:

`./distribute.sh -f -m 'openssl kivy'`

**Comment by 0xABC** [comment]
@kived thanks!  I think I'm most of the way there.  Getting "Error compiling Cython file" several times now, followed by:

    kivy/graphics/vbo.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
     error: command 'ccache' failed with exit status 1

Could it be my cython is a bad version?

**Comment by kived** [comment]
If you are using Cython 0.22, then yes. :) This will be the case if you installed via pip, in which case you can run `sudo pip install -I Cython==0.21.2` to fix it.

**Comment by 0xABC** [comment]
Thanks!  Got it working.
