### ISSUE TITLE
Ctypes still not found [$50]

### ISSUE THREAD

**Issue by kiamming** [kivy/python-for-android#397]
Hi,

Thanks for all the contributions to kivy.

I am trying to run buildozer on a kivy programme but I encounter the following error whose full log is:
https://gist.github.com/anonymous/efd06c9d2eca760ae1a5

I have ran buildozer android clean but buildozer -v android debug still gives me the ctypes error which I thought was solved in a previous merge.

Please help!

**Comment by dan-klasson** [comment]
Did you try to delete your `.buildozer` folders in your home and project folder?

**Comment by kiamming** [comment]
I deleted the `.buildozer` folder in my project folder before re-running `buildozer -v android debug`. Should I also delete the `.buildozer` folder in the home folder?

**Comment by dan-klasson** [comment]
I would try that yes.

**Comment by kiamming** [comment]
Here's what I did:
- delete both `.buildozer` folders in home and project directory
- run `buildozer android clean`
- run `buildozer -v android debug`

However, there is still a ctypes error...

Not sure if the issue is with me using Ubuntu 14 in a Virtual Machine to run buildozer...

Downloading Ubuntu 12 now to try.

Any more advice is welcome!

**Comment by guitarical** [comment]
I had a similar error. Ended up just needing to make sure the .android folder in my  home directory had "read & write" access. If that doesn't work, you can also try pulling the python for android, android SDK, and android NDK packages out of the .buildozer folder in your home directory and putting them in a folder that does not require "sudo" access. You can then specify the path to all three in your buildozer.spec file

**Comment by kiamming** [comment]
Tried all advice but nothing seemed to work.

In the end I decided to use a physical machine instead of a virtual machine, but still running Ubuntu 14.04 LTS. Finally managed to build the .apk! Thanks!
