### ISSUE TITLE
gstreamer recipe

### ISSUE THREAD

**Issue by rnixx** [kivy/python-for-android#400]
Hi,

gstreamer provides binaries for android (and ios) here http://gstreamer.freedesktop.org/download/

What needs to be done to include a gstreamer recipe and make it work with p4a?

**Comment by tito** [comment]
I don't think that would be a good idea at all. Libavconv.a is itself about 80MB, and so, you'll be limited by the maximum size of an APK: 50MB. (We don't support OBB extension files too).

Generally, use ffpyplayer recipes (that uses ffmpeg). If you need to add more codecs, edit the ffmpeg2 recipes according to your need :)

Ref: https://github.com/kivy/python-for-android/blob/master/recipes/ffmpeg2/recipe.sh#L45

**Comment by rnixx** [comment]
OK, probably the same applies to https://github.com/kivy/kivy-ios/issues/145. Closing that one as well.

**Comment by stuaxo** [comment]
The apk size has risen to 100MB so it could be interesting to revisit ?

**Comment by zoolyka** [comment]
Would be nice to have gstreamer inside kivy apps on android too. Now APK sizes does not really an issue.

**Comment by EternityForest** [comment]
+1 for revisiting this.   Gstreamer is *the* most flexible media toolkit I've seen, despite it's ability to be a PITA.  There are so many things that are doable with it, which can only be done from scratch otherwise.

**Comment by alanlivio** [comment]
+1 for revisiting this
