### ISSUE TITLE
ctypes callback function SIGSEGV

### ISSUE THREAD

**Issue by jerrys208** [kivy/python-for-android#401]
Hi,

i have a python-ctypes-c program that run well at ubuntu and i port it to the android based on 'python-for-android'. but i get SIGSEGV when the program call back from C to python.

1. my python code:
```
def py_cb(p1):
    print("just cb")
module = load_library("xxxx.so")
CFUN = CFUNCTYPE(None, c_int)
cb = CFUN(py_cb)
module.test_cb(cb)
```
2. my c code:
```
typedef void (*py_cb)(int p1);
const void test_cb(py_cb cb)
{
    cb(1)
}
```
can anyone help? many thanks!

**Comment by tito** [comment]
If you're doing Python in C, then you must learn about C-API in Python. You cannot do what you're doing, as `py_cb`is a Python function, and there is no "typedef" possible for it.

I suggest you to learn the C-API, or use a simpler way (Cython).
Here is some documentation: https://docs.python.org/2/extending/extending.html#calling-python-functions-from-c

**Comment by tito** [comment]
Sorry,

**Comment by tito** [comment]
Could you share the traceback / segfault trace ?

**Comment by inclement** [comment]
I'll close this as inactive, please reopen (or maybe better, raise it on the mailing lists) if you'd still like help.
