### ISSUE TITLE
numpy fails to build 

### ISSUE THREAD

**Issue by dl1ksv** [kivy/python-for-android#409]
Numpy fails to build with a lot of error messages like

/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: npymath: no archive symb
ol table (run ranlib)
/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: npysort: no archive symb
ol table (run ranlib)
/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: hidden symbol 'introsele
ct_bool' is not defined locally
/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: hidden symbol 'aintrosel
ect_bool' is not defined locally
/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: hidden symbol 'introsele
ct_byte' is not defined locally
/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: hidden symbol 'aintrosel
ect_byte' is not defined locally
/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: hidden symbol 'introsele
ct_ubyte' is not defined locally
/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: hidden symbol 'aintrosel
ect_ubyte' is not defined locally

System info:

SDK located at /opt/android-sdk-update-manager/
NDK located at /opt/android-ndk
NDK version is r9
API level set to 16

Compiler found at /opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
PATH is /opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/bin/:/opt/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/:/opt/android-ndk:/opt/a
ndroid-sdk-update-manager//tools:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.2:/usr/local/gnuradio/bin:/opt/android-sdk-update-manager/tools:/opt/android-sdk-u
pdate-manager/platform-tools:/usr/games/bin

**Comment by inclement** [comment]
I'm closing this since some fixes since then have probably resolved the problem. Please open another issue with full information about it if not.
