### ISSUE TITLE
PIL does not compile with freetype2 support

### ISSUE THREAD

**Issue by GeoRW** [kivy/python-for-android#413]
PIL is not compiled with freetype2 support with current recipe:

<pre>
--------------------------------------------------------------------
PIL 1.1.7 SETUP SUMMARY
--------------------------------------------------------------------
version       1.1.7
platform      linux3 2.7.2 (default, Jul  9 2015, 09:27:04)
              [GCC 4.8.4]
--------------------------------------------------------------------
*** TKINTER support not available
--- JPEG support available
--- ZLIB (PNG/ZIP) support available
*** FREETYPE2 support not available
*** LITTLECMS support not available
--------------------------------------------------------------------
</pre>

Changing the CFLAGS path solved the issue for me:
-   export CFLAGS="$CFLAGS -I$JNI_PATH/png -I$JNI_PATH/jpeg -I$JNI_PATH/freetype/include/freetype"
-   export CFLAGS="$CFLAGS -I$JNI_PATH/png -I$JNI_PATH/jpeg -I$JNI_PATH/freetype"

<pre>
--------------------------------------------------------------------
PIL 1.1.7 SETUP SUMMARY
--------------------------------------------------------------------
version       1.1.7
platform      linux3 2.7.2 (default, Jul  9 2015, 09:56:49)
              [GCC 4.8.4]
--------------------------------------------------------------------
*** TKINTER support not available
--- JPEG support available
--- ZLIB (PNG/ZIP) support available
--- FREETYPE2 support available
*** LITTLECMS support not available
--------------------------------------------------------------------
</pre>

##

**Comment by GeoRW** [comment]
Actually, it compiles with FREETYPE2 support, when I upgrade freetype library in src/jni/freetype to 2.4.0. Then it works with the original recipe.
However I needed to go few months of commits back as there's another problem with manipulating images -> they get screwed up by PIL. I suspect, it's due to changes in jpeg library. I will try to figure out which commit caused this.

**Comment by inclement** [comment]
Closing as out of date, the PIL and now pillow recipes have changed since then and may no longer have the issue.
