### ISSUE TITLE
[revamp] - Darwin patches applied on Linux

### ISSUE THREAD

**Issue by thopiekar** [kivy/python-for-android#423]
Well, I think it was just set link this during testing the code. I does not affect me, but I read that while browsing the code.

```
if uname()[0] == 'Linux':
  self.apply_patch(join('patches', 'fix-configure-darwin.patch'))
  self.apply_patch(join('patches', 'fix-distutils-darwin.patch'))
```

https://github.com/kivy/python-for-android/blob/revamp/pythonforandroid/recipes/python2/__init__.py#L38

**Comment by inclement** [comment]
This is fixed in master now, thanks for reporting it.
