### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/home/username/code/kivy/examples/demo/touchtracer'

### ISSUE THREAD

**Issue by Kasramvd** [kivy/python-for-android#424]
I got this error : 

    OSError: [Errno 2] No such file or directory: '/home/username/code/kivy/examples/demo/touchtracer'

After running the following command  : 

    ./build.py --package org.test.touchtracer --name touchtracer \--version 1.0 --dir  ~/code/kivy/examples/demo/touchtracer debug
 
I read similar issues but seems this is a new one, is it because of bad installation of kivy? also if after this error I run the following command : 

    adb install bin/touchtracer-1.0-debug.apk

I will raise this error : 

    can't find 'bin/touchtracer-1.0-debug.apk' to install

**Comment by dl1ksv** [comment]
I think the path to the touchtracer example ist wrong.
You can check it by
find . -name touchtracer

On my system I get

./python-install/share/kivy-examples/demo/touchtracer

**Comment by Kasramvd** [comment]
@dl1ksv  Yes that was the problem thanks, some times the simplicity becomes a problem :)
