### ISSUE TITLE
[revamp] --android_api is ignored on SDL2 bootstrap

### ISSUE THREAD

**Issue by alanjds** [kivy/python-for-android#425]
*.properties files needed to be set manually for now. Defaults to android-12

**Comment by inclement** [comment]
Thanks for reporting this, it's a known issue but good to have reported here, and thanks for testing the revamp branch.

I'll get to fixing this eventually, but if anyone is interested it might also be a fairly simple fix for someone to add to the new toolchain.

**Comment by str4d** [comment]
With #446 merged, I think this can be closed?

**Comment by alanjds** [comment]
Nice. Thanks @str4d.
