### ISSUE TITLE
Android app crashes on screen rotation if android.minapi < 13

### ISSUE THREAD

**Issue by Alamot** [kivy/python-for-android#430]
My android app crashes on Rotation on Android 4.1.1, if android.minapi < 13. It used to work with android.minapi = 8, but last night, I run a 'buildozer clean', so the buildozer downloaded a new version python-for-android. I have tested it with both kivy-1.9.0 and kivy-1.9.1-dev. I thought this problem had been solved recently. Or not?
##

**Comment by inclement** [comment]
APIs below about 19 are no longer supported at all, so closing (plus this is probably fixed anyway).
