### ISSUE TITLE
SQLite gets compiled without Full Text Search (FTS3) support

### ISSUE THREAD

**Issue by matphysrin** [kivy/python-for-android#431]
Hello! I'm trying to make my classical music database app run on Android, but I'm struggling with the full text search (FTS) support in the `sqlite3` library. On my Mac and Ubuntu boxes, as well as on Android using Python with SL4A, SQLite is by default compiled with the FTS support turned on. Not so within py4a. As it is a very handy feature and I'm not aware of any drawbacks of turning the support on, I believe it should be allowed in py4a as well.

According to [the official SQLite documentation](https://www.sqlite.org/fts3.html#section_2) the FTS support gets turned on by setting the preprocessor flags `-DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS` at compilation.

According to [this](http://stackoverflow.com/questions/13323655/controlling-compiler-flags-in-the-android-ndk) and [this](http://stackoverflow.com/questions/16473845/android-ndk-how-to-specify-different-cflags-to-different-platform-using-androi) sites, I've tried myself adding these flags into the `python-for-android/src/jni/sqlite3/Android.mk` file, by adding the lines

```
APP_CFLAGS += -DSQLITE_ENABLE_FTS3
APP_CFLAGS += -DSQLITE_ENABLE_FTS3_PARENTHESIS
```

or the same with `LOCAL_CFLAGS` instead of `APP_CFLAGS`. With no success so far, though. Apparently I don't really see deeper under the hood to be able to make it work.

In case you agree that the FTS support turned on is desirable, could you please look into this? Thanks in advance!
##

**Comment by inclement** [comment]
Haven't looked into this but just a comment: have you checked the sl4a source (I think it's OSS?)? That might be a useful check to see how they set the CFLAGS. If it's the same as you (which does look reasonable), perhaps there is another issue in what you've done.

**Comment by matphysrin** [comment]
Thanks for the prompt reply! No, that didn't occur to me, I shall have a look into the SL4A code.

**Comment by AndreMiras** [comment]
I think this was enabled long ago with https://github.com/kivy/python-for-android/pull/672 and https://github.com/kivy/python-for-android/pull/936
