### ISSUE TITLE
pylibpd failes to compile

### ISSUE THREAD

**Issue by Stocarson** [kivy/python-for-android#434]
Probably due to the old recipe (2013) the distribute script fails to compile pylibpd.
I've noticed that in the pylibpd recipe setup.py build and install are executed before
compiling the libpd itself.
In addition to this the distribute script cannot download any of the libpd submodules.
This because the script download the .zip version of the repo and github does not include
submodules using this kind of download.
Using git to clone the repository would fix the problem, by adding the
"git submodule init" and "git submodule update" commands.

**Comment by inclement** [comment]
Presumably fixed by https://github.com/kivy/python-for-android/pull/433 - thanks!
