### ISSUE TITLE
[revamp] toolchain.py ignores recipes with errrors

### ISSUE THREAD

**Issue by thopiekar** [kivy/python-for-android#440]
Had an typo error in my recipe and toolchain.py just ignored this error.
It resumed to install it via pip.

My expected behaviour is that toolchain.py should halt and print the traceback of the failing import.

**Comment by inclement** [comment]
This should be fixed by https://github.com/kivy/python-for-android/commit/5986ed671681473300f5ad06df914a8aaee10bb4
