### ISSUE TITLE
[revamp] p4a silently fails if --private is not absolute

### ISSUE THREAD

**Issue by str4d** [kivy/python-for-android#448]
This one tripped me up for a while, because the documentation (both master and revamp) was not clear on where the entry point to the Python code should go. But eventually I discovered that if `--private` is given a relative path (on Linux), it silently fails: `assets/private.mp3` is successfully built without any of the app code, resulting in an APK that installs but doesn't start.

Either `--private` should be extended to support relative paths, or the documentation should say they aren't supported, and `p4a` should fail loudly.

**Comment by inclement** [comment]
This is just a bug, relating to how p4a switches directory contexts - it holds the correct directory for relative path resolution in a variable but doesn't always correctly apply it. Thanks for reporting it.

**Comment by inclement** [comment]
This should be fixed with https://github.com/kivy/python-for-android/commit/5986ed671681473300f5ad06df914a8aaee10bb4

**Comment by inclement** [comment]
(Oops, wrong issue)

**Comment by inclement** [comment]
This should be fixed by https://github.com/kivy/python-for-android/commit/dfc8ab3c2c2c44d38c4b9ba7ad219f6947cbd0e6
