### ISSUE TITLE
Unable to use the crypt lib.

### ISSUE THREAD

**Issue by tshirtman** [kivy/python-for-android#45]
Needed for ssh key authentication for kivy-remote-shell.

started work in https://github.com/kivy/python-for-android/tree/libcrypt but still non functional.

**Comment by FeralBytes** [comment]
Kivy-Remote-Shell now works and a [Pycrypto](https://github.com/kivy/python-for-android/tree/master/recipes/pycrypto) recipe exists. 
Recommend this gets closed.
