### ISSUE TITLE
Creating Widgets

### ISSUE THREAD

**Issue by rubik** [kivy/python-for-android#46]
Currently it's not possible to create widgets but only applications. Is it planned for the future?

**Comment by nlsn** [comment]
I'm curious about this. Has anything happened on this subject in the past couple years?

**Comment by tshirtman** [comment]
No, it needs somebody wanting it enough to really try.

**Comment by FeralBytes** [comment]
Probably should be implemented via Buildozer though right? Since it already handles the manifest.

**Comment by waynew** [comment]
Anyone have any pointers? Is it just the manifest? Where would we look for more info about the manifests?

**Comment by inclement** [comment]
I'm not sure Kivy widgets would be possible, since I don't think they support opengl. The tool could support a widget bootstrap that possibly used python, but that relies entirely on someone making such a bootstrap - it's not a particular goal of the project so I'll close thi.
