### ISSUE TITLE
Foreground Kivy application stopped if phone locked via power button

### ISSUE THREAD

**Issue by Mystic-Mirage** [kivy/python-for-android#462]
Device: Gigabyte GSmart Roma R2 Plus
Android: 4.4.2

If my application is foreground and I press the power button my application stopped by android.

adb log:

> I/python  ( 7168): [INFO              ] [Android     ] Must go into sleep mode, check the app
> I/python  ( 7168): [INFO              ] [Android     ] App paused, now wait for resume.
> I/python  ( 7168): [INFO              ] [Android     ] Android wants to close our app.
> I/python  ( 7168): [INFO              ] [Base        ] Leaving application in progress...
> I/python  ( 7168): Python for android ended.
> I/python  ( 7237): Starting audio thread

If I minimize my application via home button before lock this is not happen.

Other Kivy applications from Play Market (Touch Tracer, 2048) not affected with this issue.
##

**Comment by RaoulX** [comment]
i was having the same issue on my SGS 4, but managed to get it sorted by setting in buildozer.spec:
android.minapi = 14

also tested minapi 13, and that worked as well.

**Comment by inclement** [comment]
Issue is stale and I haven't seen any other reports like this, so probably fixed.
