### ISSUE TITLE
The SDL2 bootstrap can't make a Kivy Launcher

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#468]
As in the title, the SDL2 bootstrap doesn't have any code to make a Kivy Launcher APK. It should be quite easy to add it just by looking at the way the pygame bootstrap does it, but the work needs doing.

The launcher could also be a separate bootstrap, but there might then be a lot of code duplication. Maybe there is another way to resolve this though.
##

**Comment by KeyWeeUsr** [comment]
ref #891 so that it's closed later ^^
