### ISSUE TITLE
Missing dependency in quickstart?

### ISSUE THREAD

**Issue by Chiel92** [kivy/python-for-android#476]
Today I followed the instructions on http://inclem.net/files/p4a_revamp_doc/quickstart.html#quickstart to install python-for-android on my Ubuntu machine.
At first, when creating a distribution, I got the error `IOError: Couldn't find a virtualenv executable, you must install this to use p4a.`

After running `pip2 install virtualenv` this was solved, but I couldn't find this dependency in the instructions. Is it missing? If so, I'd be happy to provide a PR fixing this.

**Comment by inclement** [comment]
Fixed by 358c91f1a5377c35ccece81dc9aa36f755515b5f. Thanks for reporting it.
