### ISSUE TITLE
Allow scaling of the presplash image to device resolution

### ISSUE THREAD

**Issue by fabiankreutz** [kivy/python-for-android#481]
The presplash image is not scaled to fullscreen and no configuration option allows anything but the default behaviour.
The code resides currently in SDLSurfaceView.java and a diff that (fixed) scales the image while keeping the ratio is

```
815,816c816,823
<             float mx = ((float)mWidth / bitmap.getWidth()) / 2.0f;
<             float my = ((float)mHeight / bitmap.getHeight()) / 2.0f;
---
>             float mx, my;
>             if (bitmap.getWidth() < bitmap.getHeight()) {
>                 mx = 0.5f;
>                 my = (float)bitmap.getHeight() / bitmap.getWidth() / 2.0f;
>             } else {
>                 mx = (float)bitmap.getWidth() / bitmap.getHeight() / 2.0f;
>                 my = 0.5f;
>             }
```

**Comment by inclement** [comment]
Nice fix. If you (or anyone else) would like to contribue it to p4a, feel free to make a pull request - it would be ideal to combine it with a command line option controlling which mode (pixel perfect or scaled) is used.

**Comment by fabiankreutz** [comment]
So this issue can be closed, right?

**Comment by inclement** [comment]
Yes, I just didn't get to it.
