### ISSUE TITLE
freshly built old_toolchain crashes  with 'cannot locate symbol "_Py_asinh"'

### ISSUE THREAD

**Issue by cbenhagen** [kivy/python-for-android#487]
```
11-10 19:59:28.007 29073 29093 W linker  : /data/app/ch.kamerawerk.pool-2/lib/arm/libpython2.7.so: is missing DT_SONAME will use basename as a replacement: "libpython2.7.so"
11-10 19:59:28.010 29073 29093 E AndroidRuntime: FATAL EXCEPTION: Thread-11691
11-10 19:59:28.010 29073 29093 E AndroidRuntime: Process: ch.kamerawerk.pool:python, PID: 29073
11-10 19:59:28.010 29073 29093 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Py_asinh" referenced by "/data/app/ch.kamerawerk.pool-2/lib/arm/libpython2.7.so"...
11-10 19:59:28.010 29073 29093 E AndroidRuntime:    at java.lang.Runtime.loadLibrary(Runtime.java:372)
11-10 19:59:28.010 29073 29093 E AndroidRuntime:    at java.lang.System.loadLibrary(System.java:1076)
11-10 19:59:28.010 29073 29093 E AndroidRuntime:    at org.renpy.android.PythonActivity.run(PythonActivity.java:254)
11-10 19:59:28.010 29073 29093 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:818)
11-10 19:59:28.014  2257  6942 W ActivityManager:   Force finishing activity ch.kamerawerk.pool/org.renpy.android.PythonActivity
```
##

**Comment by cbenhagen** [comment]
He seems to have had the same or a similar problem.
https://stackoverflow.com/questions/33216132/cannot-locate-symbol-pow-referenced-by-libpython2-7-so

I might have to add that i built the toolchain using the latest buildozer.

**Comment by snaderi** [comment]
I've encountered the same issue (exact same stack trace). I've got cython 0.20.1 and buildozer 0.30 on osx 10.10.5. Any ideas?

**Comment by sot-iris** [comment]
same issue here, working with cython 0.20 buildozer 0.30 and osx 10.10.4

**Comment by BallisticPain** [comment]
I'm having the same issue here. I used Python 2.7.11, bulldozer 0.32. I just used mostly default settings... I changed to portrait only mode. I set log level to 2. The application is crashing the moment I try to run it.

Thoughts?
Anyone else actually get around this?

**Comment by kennedyshead** [comment]
Same problem here python 3.5.2 buildozer 0.32 log_level 2 landscape

**Comment by GitLark** [comment]
Same problem here.  I'm disappointed that I could not run hello world or the snake tutorial on my phone after ten hours of kivy & bulldozer. Why are these math functions missing?

Workarounds:
 * Install Kivy Launcher on the phone. Figure out how to move files to the correct place.
 * Don't use Mac. I have not tried Ubuntu but it could work.

I installed kivy yesterday. I'm not confident that my python3 installation did not interfere. Many of the other python-related libraries were installed in what seems like a random order over the past few months, so perhaps the versions are all jumbled up.

Mac OS X El Capitan 10.11.6. Python 2.7.12, Kivi2 (Python 2.7.10), Bulldozer 0.32. Samsung S6.  Android 6.0.1.

**Comment by inclement** [comment]
Closing as this issue relates to the old toolchain which is no longer supported. Please open a new issue if you experience this problem with the current master branch.

(This issue should definitely be fixed in the current version).
