### ISSUE TITLE
error when execute p4a in line from urlparse import urlparse

### ISSUE THREAD

**Issue by amru-rosyada** [kivy/python-for-android#488]
I am using python 3.5, error when execute p4a on toolchain.py

error :
on import expression 'from urlparse import urlparse'

I fixed it with adding try catch when importing it, for compatibility reason:
try:
    from urlparse import urlparse
except ImportError:
    from urllib.parse import urlparse

Regards,

**Comment by inclement** [comment]
Thanks, I've applied your fix to the master branch.
