### ISSUE TITLE
compiler problem with gcc >= 4.8

### ISSUE THREAD

**Issue by dl1ksv** [kivy/python-for-android#489]
compiling python2 with gcc >= 4.8 results in alot of warnings like:

............... -o Python/ast.o Python/ast.c
In file included from Include/Python.h:126:0,
                 from Python/ast.c:6:
Include/modsupport.h:27:1: warning:  **'PyArg_ParseTuple' is an unrecognized format function type [-Wformat]**

You can see a discussion of this topic 

https://bugzilla.redhat.com/show_bug.cgi?id=927358

To fix use this patch:

    --- Python-2.7.2/configure.orig 2015-06-24 17:47:39.181473779 +0200
    +++ Python-2.7.2/configure      2015-06-24 17:48:31.646173137 +0200
    @@ -5731,7 +5731,7 @@
       { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether gcc supports ParseTuple __format__" >&5
     $as_echo_n "checking whether gcc supports ParseTuple __format__... " >&6; }
     save_CFLAGS=$CFLAGS
    -  CFLAGS="$CFLAGS -Werror"
    +  CFLAGS="$CFLAGS -Werror -Wformat"
       cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */

**Comment by inclement** [comment]
Does this patch cause any problems for older gcc versions? We could just apply it every time if so.

Thanks!

**Comment by dl1ksv** [comment]
I tried to use 4.6 with this patch and got no errors.

**Comment by inclement** [comment]
Looks like it's probably good then. If you or anyone else would like to contribute a PR, I'll look at merging it, otherwise I'll add it when I get time.

**Comment by inclement** [comment]
Closing as fixed by the linked PR.
