### ISSUE TITLE
verbose output

### ISSUE THREAD

**Issue by dl1ksv** [kivy/python-for-android#490]
If I run
    python -v
I get more verbose output. This is helpfull to debug import statements.

Is there a way to get more verbose output on android, too ?

**Comment by inclement** [comment]
You'd want to first check if this can be somehow enabled from within python, this would be easiest.

Other than that, you could modify the C initialisation code to either manually change the argv and add the -v (at https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/pygame/build/jni/application/src/start.c#L58, or similar for other bootstraps or the old toolchain), or possibly try to find the python C api calls to enable it and add them instead. This might be fiddly though.

If you have a specific problem, feel free to post it on the normal channels. There also should be nothing too special about Android, with python code either installed to site-packages (in which case it's in the path and should be fine) or in your local directory structure which is copied exactly and so relative imports should be the same.
