### ISSUE TITLE
Recipes depending on external modules don't work

### ISSUE THREAD

**Issue by proy87** [kivy/python-for-android#520]
I'm struggling with using numpy as external dependency.
This question describes the issue in details:

https://groups.google.com/forum/#!topic/python-android/nKgzviS6YpA

Matplotlib doesn't "see" numpy.
##

**Comment by inclement** [comment]
Sorry, I missed this issue originally, I think I misread it. Could you give full details of what you're trying and what goes wrong?

**Comment by proy87** [comment]
Everything is written. I try to install Matplotlib, but buildozer doesn't see numpy.

**Comment by inclement** [comment]
By 'install matplotlib' you mean build it with python-for-android? What recipe are you using? Where did you get it?

**Comment by proy87** [comment]
I use this recipe: http://stackoverflow.com/questions/30295886/matplotlib-compilation-recipe-for-python-for-android

"install matplotlib" means build with python-for-android

**Comment by inclement** [comment]
This issue is probably stale, but for general information there is no currently supported matplotlib recipe. The linked one might work, but would need translating to the current toolchain.
