### ISSUE TITLE
import sh module problem

### ISSUE THREAD

**Issue by PalashGore** [kivy/python-for-android#540]
Python 3.5. Windows 8.1
While trying to install python-for -android this happens.
![capture](https://cloud.githubusercontent.com/assets/16311436/11829648/05bf754c-a36c-11e5-9960-82c5914bfbc9.JPG)

**Comment by tito** [comment]
And https://pypi.python.org/pypi/pbs is no longer supported. Excellent.

**Comment by inclement** [comment]
python-for-android won't actually work on windows anyway.

**Comment by kived** [comment]
As @inclement said, p4a isn't supported on Windows, and there are no plans to add such support. You can build APKs using a virtual machine, and we provide one for this purpose. The VM includes p4a as well as buildozer, a tool which eases the process of building your app.

[Kivy Android VM Instructions](http://kivy.org/docs/guide/packaging-android-vm.html#kivy-android-vm)

**Comment by PalashGore** [comment]
Thank you @inclement  @kived.
