### ISSUE TITLE
native code in kivyAndroid, possible?

### ISSUE THREAD

**Issue by MichaelPython** [kivy/python-for-android#542]
hello, i am quite comfortable with python and kivy. but one thing that i worry about is, i need to do a lot of calculation in my program, while kivy android doesnt provide ctypes for now (v1.90). so i have to write all code in python? when will kivy android have ctypes?
i read something about renderscript on android. can kivy support renderscript? such as through pyjnius?
thanks.

**Comment by akshayaurora** [comment]
Why not just write your native code as c then simply make it into a recipe? like all the other recipes out there use Cython...,  use existing libs like Numpy for faster number crunching that already have a recipe.

**Comment by MichaelPython** [comment]
sorry i dont know about recipe, nor have i used cython,numpy. currently i am using kivy launcher on android. i write python code in an text editor then run the file with kivy launcher, very convenient to use. but i dont compile app yet. do you mean to compile my own module? or anything else? what tools do i need ?

**Comment by inclement** [comment]
ctypes does work on Android.

**Comment by MichaelPython** [comment]
yes i mean the launcher(ctypes not working). my kivy launcher was downloaded from kivy.org download page.
