### ISSUE TITLE
Window.softinput_mode/TextInput - Window moves up/down when switching softinput_mode to 'below_target'/'resize'

### ISSUE THREAD

**Issue by rafalo1333** [kivy/python-for-android#544]
When the Window's softinput_mode is set to 'below_target' or 'resize', the Window size and position is not correct after requesting keyboard with textinput/restartting the app after first launch.

Example app code:

https://gist.github.com/rafalo1333/5484ebdba49203074114

App UI on initial launch:

![screenshot_2016-01-01-19-33-37](https://cloud.githubusercontent.com/assets/7304986/12071805/b0c2cb5a-b0bf-11e5-9736-2a9f2050828c.png)

App UI when keyboard was requested (look at the bar under the TextInput widget:

![screenshot_2016-01-01-19-33-47](https://cloud.githubusercontent.com/assets/7304986/12071811/c7f2febc-b0bf-11e5-9218-4aba8b905416.png)

App UI after hiding keyboard/resetting the app (look at the bar under the TextInput):

![screenshot_2016-01-01-19-33-53](https://cloud.githubusercontent.com/assets/7304986/12071814/e18858d6-b0bf-11e5-99f7-ed35b1dcd548.png)

With the Window.softinput_mode set to 'resize', things are going even uglier.

It could be related to https://github.com/kivy/python-for-android/pull/483 PR.

It should be fixed as right now Kivy TextInputs are unusable on Android.

**Comment by inclement** [comment]
According to the other issues linked, this should be fixed in master.
