### ISSUE TITLE
ccache compilation issues?

### ISSUE THREAD

**Issue by hottwaj** [kivy/python-for-android#550]
Hey guys, the new ccache compilation route causes me issues... I haven't tried to step through the code to see exactly what's going on but have included some error messages below in case you can spot anything obvious...  

My problem is that i get an error when linking a bunch of compiled c++ ".o" files for one of the packages I'm including in my android distribution.

The P4A call I'm using to set off compilation looks like this:

```
python -m pythonforandroid.toolchain apk --private /home/hottwaj/prog/src/testapp --package=org.hottwaj.testapp --name="testapp" --version=0.2 --requirements=sdl,python2,audiostream,my_cpp_lib --dist_name=testapp
```

The command executed by P4A that's going wrong looks like this:

```
/usr/bin/ccache -lm -L/home/hottwaj/.local/share/python-for-android/build/libs_collections/testapp/armeabi-L/home/hottwaj/.local/share/python-for-android/build/libs_collections/testapp -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/hottwaj/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/hottwaj/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/sdl/include -I/home/hottwaj/.local/share/python-for-android/build/bootstrap_builds/pygame/jni/sdl_mixer  ... BIG LIST OF .o FILES ... -L/home/hottwaj/.buildozer/android/platform/android-ndk-r9c/sources/cxx-stl/stlport/libs/armeabi-v7a -L/home/hottwaj/.local/share/python-for-android/build/other_builds/python2/armeabi/python2/python-install/lib -lstlport_shared -llog -lpython2.7 -o my_linked_so_file_thing.so -fexceptions -frtti -fPIC -shared
```

The error message is:

```
/usr/bin/ccache: invalid option -- 'l'
```

If I roll back to before the ccache changes were made, e.g. https://github.com/kivy/python-for-android/commit/9916cb56f3b8a92eaff1f3f944ab9f2b49931b1e then I don't have this problem anymore...

Other calls to ccache that I can see were executed by P4A look like this - but the problem call above is missing the gcc part - is that the cause?

```
/usr/bin/ccache arm-linux-androideabi-gcc
```

Thanks
##

**Comment by inclement** [comment]
That cause looks plausible to me, maybe we have to be more careful passing the build command somewhere. Thanks for reporting it, hopefully we can fix it quickly.

**Comment by hottwaj** [comment]
Cool, thanks!

**Comment by inclement** [comment]
I haven't come across this, despite doing a lot of compilation. Do you think it is related to audiostream or your particular cpp lib?

**Comment by hottwaj** [comment]
Not sure - I'll have another go at testing this when I can and will get
back to you.  Thanks

**Comment by kived** [comment]
Please run your build with `--debug` and post the output of the failed recipe. If the failed recipe is your cpp lib recipe, please post that recipe as well.

**Comment by AndreMiras** [comment]
I think I actually saw that and other weird things with `audiostream` too while working on #1382.
I'll come back to it when I'm done with conditional builds.

**Comment by hottwaj** [comment]
Sorry for never coming back on this.  I ended up writing some custom code to disable ccache for a couple of my own cython recipes.  Closing for now as seems like it might have just been me...  Thanks!
