### ISSUE TITLE
Extending the launcher

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/python-for-android#565]
It's not an issue, but I have an ideas which would bring more comfort into coding on the road with Kivy Launcher, as I mostly code on mobile. Maybe a good features for Kivy 2.0?
1. extend the launcher to a simple text editor capable of showing & running the code right as it is
2. open a possibility to "share" a file from another app into the launcher - file from internet as more browsers have an option to share this and that
3. allow to run inspector the simple way - button for example

I tried to do the editor, though with kivy. It wasn't effective as the editor itself was running python and running the script would require to run another python on the phone, ie storage&battery killer. Haven't found a way how to do it within one running python.
##

**Comment by inclement** [comment]
We'd be happy to extend the launcher, but I suspect it isn't a priority for any of the kivy developers right now. If you'd like to try some of these changes though, we'd be happy to accept them.

**Comment by Julian-O** [comment]
This belongs as a feature request on the new version of the Launcher (which is not in a healthy state right now)

Closing as won't fix in p4a.
