### ISSUE TITLE
Can't load library "libPVROCL.so"

### ISSUE THREAD

**Issue by AndreMPCosta** [kivy/python-for-android#594]
The phone is a ThL W100, with JellyBean(4.2.1).

The app runs fine on Lollipop (another devices), but this problem is probably device related.

Here's the logcat (regarding Python).

http://pastebin.com/rBUqZKsj

Full logcat:

http://pastebin.com/HyNDZK5j

Device info:
build.board: bird89_wet_a_jb2
build.bootloader: unknown
build.brand: ThL
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: bird89_wet_a_jb2
build.display: ThL.W100.130912.JBV2.QHD.EN.COM.V01.8P32_V01_MT6589
build.fingerprint: ThL/bird89_wet_a_jb2/bird89_wet_a_jb2:4.2.1/JOP40D/1378960373:user/test-keys
build.hardware: mt6589
build.host: yuanhao-desktop
build.id: JOP40D
build.manufacturer: ThL
build.model: W100
build.product: bird89_wet_a_jb2
build.radio: unknown
build.serial: 0123456789ABCDEF
build.tags: test-keys
build.time: 1378960541000
build.type: user
build.user: root
version.codename: REL
version.incremental: eng.root.1378960373
version.release: 4.2.1
version.sdk_int: 17

Another device:

Logcat:

http://pastebin.com/haW5idMP
##

**Comment by inclement** [comment]
Closing as maybe fixed, certainly not a common issue, can be reopened if necessary.
