### ISSUE TITLE
Local recipe dir is not returned by get_recipe_dir()

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#613]
If a local recipe requests its directory with self.get_recipe_dir() a non-existent recipe dir is returned on the root recipe path of p4a.
##

**Comment by brussee** [comment]
Additionally ```self.get_recipe('boost', self.ctx).recipe_dir``` returns ```./boost/``` instead of the actual path.

**Comment by AndreMiras** [comment]
Thanks for the report this has been fixed in https://github.com/kivy/python-for-android/pull/1276
