### ISSUE TITLE
OpenSSL 1.0.2e outdated (replaced by 1.0.2f)

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#614]
A new version has been published today. The recipe no longer can download version 1.0.2e.

Does ```disable-solver.patch``` still apply?

**Comment by kived** [comment]
It's `disable-sover.patch`, and yes. Android won't let you install libs with so versions like libcrypto.so.1.0.2. That patch makes disables the so versioning so you end up with libcrypto.so. The patch could need updating, but the patching has to happen.

Even if there is a new version, the old version will not go away. It will still be downloadable. However, I cannot connect to www.openssl.org at all - so it seems like this is probably just a web server issue.

**Comment by brussee** [comment]
It appears that both affected lines have shifted 2 lines down.

Why is there --- openssl/Makefile and +++ b/Makefile I expected +++ openssl/Makefile there?

The website is slow for me, probably overloaded.

**Comment by kived** [comment]
Because I name the second directory `b` when generating patches. The directory name doesn't matter, as patches will be applied with `-p1` which will strip the first component from the path.

**Comment by brussee** [comment]
I understand. Please review PR #615
