### ISSUE TITLE
Unintended rollback patches

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#632]
Applying a patch from a recipe with
```
self.apply_patch(join(self.get_recipe_dir(), 'use-soname.patch'), arch.arch)
```

Results every other build in an unintended rollback:

```
Reversed (or previously applied) patch detected!  Assuming -R.
```

**Comment by inclement** [comment]
Currently you should manually track whether the patch has already been applied, or use the `patches` attribute of the recipe to set the patches (in which case this is done, and the patches applied, automatically). If any existing recipe doesn't do this (are you looking at openssl?), it's a bug.

**Comment by kived** [comment]
The patch in the openssl recipe is applied to files generated by the Configure script, which is why it runs unconditionally. Any patches applied via the `patches` class attribute are tracked and will only be applied once.

**Comment by brussee** [comment]
The patches can only be applied after a certain step in the recipe. When exactly are the patches = [] applied?

Yes, as a matter of fact I took the openssl recipe as an example.

**Comment by kived** [comment]
They are applied directly following `prebuild_arch`.

**Comment by brussee** [comment]
> The patches can only be applied after a certain step in the recipe.
Ah, but the patches that are affected by the rollback actually can and should go in the patches = [].
Thanks!
