### ISSUE TITLE
First label not rendered on android

### ISSUE THREAD

**Issue by tshirtman** [kivy/python-for-android#64]
Using the following code
https://gist.github.com/4072912
```
from kivy.uix.label import Label
from kivy.app import App


class MyApp(App):
    def build(self):
        #Label()
        return Label(text='test')


if __name__ == '__main__':
    MyApp().run()
```
result in a completly blank app, in my python-for-android distribution, but works fine on desktop, if i uncomment the `Label()` call, the app works correctly.

**Comment by inclement** [comment]
I just tried this again with the SDL2 bootstrap, and it worked, so I guess I'll close this as resolved.
