### ISSUE TITLE
Unable to find libpython2.7.so on older versions of Android

### ISSUE THREAD

**Issue by kmonson** [kivy/python-for-android#645]
When I try to run my APK on older versions of Android (<4.x) I'm getting a crash with this error: "Cannot load library: link_image[1936]:   106 could not load needed library 'libpython2.7.so' for 'libmain.so' (load_library[1091]: Library 'libpython2.7.so' not found)"

I'm using the new python-for-android toolchain and buildozer master both checked out a few days ago.

I get a popup on the device that says it's an "SDL Error"

logcat: http://pastebin.com/f3zg91ja
buildozer spec: http://pastebin.com/WCbU96TM
buidozer log: http://pastebin.com/negsytP7

Tested on a Kindle Fire HD (3.x fails), LG Volt (4.4 Works), and a Samsung phone running Android 2.3.x (fails).

Both failing devices worked before I switched to the new toolchain.

**Comment by nokianhunter** [comment]
On Android 4.0.4 I get the same "SDL Error" with default .spec.

**Comment by kived** [comment]
Did you install the new app over an old version? Try clearing the app data from Settings->Applications, then uninstall and reinstall the app.

**Comment by nokianhunter** [comment]
Unfortunately that didn't help.

**Comment by kmonson** [comment]
I tried that as well and it didn't help.

**Comment by kived** [comment]
@kmonson Please try with this testing branch on my fork: https://github.com/kived/python-for-android/tree/fix-libs-pre-kitkat

**Comment by kmonson** [comment]
Sure thing. I try to get to it tonight.

**Comment by kmonson** [comment]
You, sir, are a gentleman and a scholar. 

It now works on my Kindle HD. It will be some time before I can try it on Android 2.3 but I'm guessing it will work there as well. If it does not I will let you know.

**Comment by nokianhunter** [comment]
Thank you very much. Now it works on Android 4.0.4.
Had to delete my temporary files in ~/.local/share/python-for-android first.

**Comment by kmonson** [comment]
I was able to load it onto android 2.3 and it worked.

**Comment by dfrison01** [comment]
Hi!
I really am a noob on this. So would greatly appreciate any help:
I'm trying to apply @kived 's "fix-libs-pre-kitkat" repo (by cloning it and setting buildozer "p4a.source_dir" to the downloaded/extracted folder), yet I get a strange error that I can not understand when trying to "buildozer android update" or "buildozer android debug". As follows:

'''
Install platform
Run 'pip install -q --user '
Cwd None
ERROR: You must give at least one requirement to install (see "pip help install")
Command failed: pip install -q --user
'''

Any suggestions? Trying to compile for Android 4.0.4 (buildozer 0.34, sdk20 with api 19, py2.7 and crystax)
Thx guys!

**Comment by JDevPy** [comment]
I have the same problem.. anyone??
