### ISSUE TITLE
App crash on resume with new tool chain

### ISSUE THREAD

**Issue by kmonson** [kivy/python-for-android#646]
After I switched to the new toolchain my app now crashes when resuming with the error:

"java.lang.RuntimeException: Unable to start activity ComponentInfo{edword.test.edword/org.kivy.android.PythonActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first."

I get a popup that says the application has stopped. I hit OK and the application restarts.

logcat: http://pastebin.com/tXEkfPy6 (had to trim for size, everything important should be there)
buildozer spec: http://pastebin.com/WCbU96TM
buidozer log: http://pastebin.com/negsytP7

Tested on an LG Volt (Android 4.4)

**Comment by inclement** [comment]
@kived @tito Is this the crashing issue I've seen mentioned on #kivy-dev, or is that fixed?

**Comment by kmonson** [comment]
I was asking about it on #kivy-dev last night.

**Comment by kived** [comment]
No, that crashing issue was due to bad locking (one thread held the GIL while waiting on another lock, and that code which released that lock needed the GIL to do so).

**Comment by tito** [comment]
Could that be the case if the image can't be found for loading screen?

**Comment by kmonson** [comment]
That would be weird. It starts cold just fine.

**Comment by kmonson** [comment]
@inclement It doesn't look like anything pushed since then has anything to do with this problem, but I'll try pulling all changes and building from clean environment when I get home just to be sure.

**Comment by kmonson** [comment]
I did a pull and ran it from clean environment. Got this error:

[INFO]:    The selected bootstrap is sdl2
[INFO]:    # Creating dist with sdl2 bootstrap
[INFO]:    Dist will have name edword and recipes (pyopenssl, cryptography, pyasn1, apsw, ndg_httpsclient, kivy)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kyle/edword/python-for-android/pythonforandroid/toolchain.py", line 711, in <module>
    main()
  File "/home/kyle/edword/python-for-android/pythonforandroid/toolchain.py", line 708, in main
    ToolchainCL()
  File "/home/kyle/edword/python-for-android/pythonforandroid/toolchain.py", line 323, in __init__
    getattr(self, args.command)(unknown)
  File "/home/kyle/edword/python-for-android/pythonforandroid/toolchain.py", line 105, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/home/kyle/edword/python-for-android/pythonforandroid/toolchain.py", line 139, in build_dist_from_args
    ctx.prepare_bootstrap(bs)
  File "pythonforandroid/build.py", line 476, in prepare_bootstrap
    self.bootstrap.prepare_build_dir()
  File "pythonforandroid/bootstrap.py", line 95, in prepare_build_dir
    self.build_dir)
  File "pythonforandroid/logger.py", line 150, in shprint
    logger.info('{}{}'.format(shorten_string(string, columns - 12),
  File "pythonforandroid/logger.py", line 101, in shorten_string
    if not isinstance(string, unistr):
NameError: global name 'unistr' is not defined
# Command failed: python -m pythonforandroid.toolchain create --dist_name=edword --bootstrap=sdl2 --requirements=pyopenssl,cryptography,pyasn1,apsw,ndg_httpsclient,kivy --arch armeabi-v7a

**Comment by kmonson** [comment]
Ok, the error in my previous comment was fixed in 7881a0ba34ac7ac93ac9cfbbe88236c4233d2871.

**Comment by kmonson** [comment]
I rebuilt this and now it seems to work just fine. Thanks for your patience.
