### ISSUE TITLE
Check presence of main.py during build time

### ISSUE THREAD

**Issue by dessant** [kivy/python-for-android#656]
_From @miohtama on February 26, 2016 21:24_

Now it is possible to create an APK without a valid Python entry point. In this case the application just quickly flashes, then closes.

If the developer makes a mistake with packaging and main.py doesn't end up in the APK the application startup does not give any meaningful error message. For novice users it might be difficult to spot the error from adb logs.

_Copied from original issue: kivy/buildozer#298_

**Comment by dessant** [comment]
This should probably be addressed in p4a directly.

**Comment by dessant** [comment]
_From @miohtama on February 26, 2016 22:39_

Gotcha. Please point me forward to another project if this a wrong issue tracker.

**Comment by dessant** [comment]
I'll port it for you. :wink:

**Comment by inclement** [comment]
This would be fixed by https://github.com/kivy/python-for-android/pull/698.
