### ISSUE TITLE
will_build does not work as expected

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#657]
```
if will_build('snappy'):
```
is not equivalent to
```
if 'snappy' in recipe.ctx.recipe_build_order:
```

**Comment by inclement** [comment]
From your reply on #kivy, it sounds like your problem was that will_build returns a function. This is deliberate, this function is for passing conditions to recipe builds in the depends list, not for what you're trying.

**Comment by brussee** [comment]
:thumbsup:

**Comment by kived** [comment]
That's why it's in the `patching` module. ;-) You can also use `if will_build('snappy')(self):`, though I don't know if that's really any better than just doing the check in recipe_build_order yourself.

````python
def will_build(recipe_name):
    def will(recipe, **kwargs):
        return recipe_name in recipe.ctx.recipe_build_order
    return will
````
