### ISSUE TITLE
No "--window" option

### ISSUE THREAD

**Issue by pythonic64** [kivy/python-for-android#666]
Doing:
```
p4a apk <other arguments> --window
```
with SDL2 as bootstrap raises error:
```
p4a: error: unrecognized arguments: --window
```
Is there another way to set windowed mode?

**Comment by inclement** [comment]
Apparently this option hasn't yet been added to the SDL2 build.py. You can use it with SDL2 by adding the code (a PR for this would be welcome), or possibly by doing it at runtime with pyjnius (though that's undesirable).

The option still exists when `--bootstrap=pygame`, though this backend will eventually be deprecated and SDL2 is the focus of our development efforts.

**Comment by pythonic64** [comment]
On the first look, it seems that this line: 
```
<meta-data android:name="fullscreen" android:value="{% if args.window %}0{% else %}1{% endif %}"/>
```
should be added [here](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml#L63).

**Comment by inclement** [comment]
Looks good. You'd also need to add the --window option in the build.py, I think.

**Comment by inclement** [comment]
Should be fixed by the merged PR above, thanks.
