### ISSUE TITLE
Invalid option ccache: t

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#667]
In case of the PyLevelDB recipe if I comment this line:

```
env['LDSHARED'] = env['CC'] + ' -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions'
```

it breaks: /usr/bin/ccache: invalid option -- 't'
##

**Comment by frmdstryr** [comment]
Also seeing this with... any idea why?  I don't see any -t arg anywhere

**Comment by inclement** [comment]
I think this issue was fixed, this can be reopened if it continues to occur.
