### ISSUE TITLE
LDFlags missing ' -lpython2.7'

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#668]
In case of the PyLevelDB recipe if I comment this line:

```
env['LDFLAGS'] += ' -lpython2.7'
```

it breaks on runtime with this error:

```
I/python(24256): ImportError: dlopen failed: cannot locate symbol "_Py_NoneStruct" referenced by "/data/data/org.tribler.android/files/lib/python2.7/site-packages/leveldb.so"...
```

It somehow is not added automatically apparently...
##

**Comment by inclement** [comment]
From a quick check, it looks like none of the recipe classes automatically add this (although I thought they did) - does that look the same to you? I don't think there's a reason not to link it automatically in the compiled ones, so if that's right then let's add it in their get_recipe_env.

**Comment by AndreMiras** [comment]
Yes I also noticed python linking flags seem to be missing in parent recipes.
As of today I only see it in [CppCompiledComponentsPythonRecipe.get_recipe_env()](https://github.com/kivy/python-for-android/blob/764b59e/pythonforandroid/recipe.py#L902) and [CythonRecipe.get_recipe_env()](https://github.com/kivy/python-for-android/blob/764b59e/pythonforandroid/recipe.py#L1058).
This pull request seems to tacle part of it https://github.com/kivy/python-for-android/pull/793.

I think it would greatly improve code base quality and recipes reliability to tackle that one.
