### ISSUE TITLE
Python compiled components recipe: "bad gcc/glibc config?"

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#669]
In case of the PyLevelDB recipe if I comment this line:

```
env['PYTHON_ROOT'] = self.ctx.get_python_install_dir()
#env['CFLAGS'] += ' -I' + env['PYTHON_ROOT'] + '/include/python2.7'
```

it breaks like this: https://github.com/rogerbinns/apsw/issues/206
##

**Comment by inclement** [comment]
Is this still a problem, or resolved in your later work with apsw etc?

**Comment by brussee** [comment]
This was resolved already: https://github.com/rogerbinns/apsw/issues/206#issuecomment-191744968
