### ISSUE TITLE
Pygame missing include & link path

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#687]
Somehow the include path (to Python.h) and the path to the libraries (to -lpython2.7) for linking is not setup correctly for the pygame bootstrap.

It works if I hardcode the paths in _python-for-android/build/bootstrap_builds/pygame/jni/Android.mk_:

APPLICATION_ADDITIONAL_CFLAGS := -finline-functions -O2 -DSDL_JAVA_PACKAGE_PATH=$(SDL_JAVA_PACKAGE_PATH) **-I/home/paul/.local/share/python-for-android/build/python-installs/testproject/include/python2.7**

APPLICATION_ADDITIONAL_LDFLAGS := -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions **-L/home/paul/.local/share/python-for-android/build/libs_collections/testproject/armeabi**
##

**Comment by inclement** [comment]
python-for-android does try to set an appropriate include path, and I haven't had a problem with it - do you know what is the wrong with the value it gets for you?

**Comment by inclement** [comment]
Closing as out of date since the pygame bootstrap isn't really supported any more.
