### ISSUE TITLE
Carousel: add_widget after build()

### ISSUE THREAD

**Issue by betweenthieves** [kivy/python-for-android#69]
The below example should be small enough to illustrate this issue. Basically, when a widget (slide) is added to a Carousel widget _after_ the build() function, i.e. using a Clock.schedule_once call, the widget is not properly sized to fit its container. Below this is illustrated using an AsyncImage widget. The first two slides are properly scaled, but after the allotted ten seconds have expired, the third slide is added but is _very_ small and shrinks into the bottom-left corner of its container.

This same example works without this issue when you run the same code on a desktop (here, specifically, Ubuntu 12.10); the third slide is properly added and resized. **I'm using the Kivy Launcher app on Android to run this code on an Android 4.0.3 device, which is where I'm seeing this issue.**

Thank you for your attention and time.

```
from kivy.app import App
from kivy.uix.carousel import Carousel
from kivy.factory import Factory
from kivy.clock import Clock
class Example1(App):

    def build(self):
        for i in range(2):
            src = "http://placehold.it/480x270.png&text=slide-%d&.png" % i
            image = Factory.AsyncImage(source=src, allow_stretch=True)
            carousel.add_widget(image)
        return carousel

def add_slide(dt):
    src = "http://placehold.it/480x270.png&text=slide-2&.png"
    image = Factory.AsyncImage(source=src, allow_stretch=True)
    carousel.add_widget(image)

Clock.schedule_once(add_slide,10)
carousel = Carousel(direction='right')
Example1().run()
```
##

**Comment by inclement** [comment]
This may have been fixed in Kivy and/or python-for-android's newer toolchain. Please reopen the issue if you still experience it.
