### ISSUE TITLE
Need to set locale env variable for python3 package recipes

### ISSUE THREAD

**Issue by emillynge** [kivy/python-for-android#703]
When calling `python3.5 setup.py` using sh.py, the setup can fail because the spawned process doesn't correctly set the locale to use UTF-8.

In the case of plyer, a changelog is read during setup that contains non-ascii symbols. Without correct locale, the python interpreter will try to decode the file upon  `open('changelog.md')` using ascii codec and raise an exception.

Setting the `LANG` enviroment variable to system locale solves the issue.

```
class PlyerRecipe(PythonRecipe):
    version = '1.2.5dev'
    url = 'https://github.com/emillynge/plyer/archive/browser.tar.gz'
    depends = ['pyjnius', 'python3crystax']

    def get_recipe_env(self, *args, **kwargs):
        env = super().get_recipe_env(*args, **kwargs)
        env['LANG'] = "en_GB.UTF-8"
        return env
```

Maybe this environment variable should be set by default by `PythonRecipe`?
##

**Comment by inclement** [comment]
I don't see a problem with doing this, but I'll leave it a little while in case anyone raises any issues as I've seen this kind of encoding setting have unexpected side effects before.
