### ISSUE TITLE
raise exc_info[0], exc_info[1], exc_info[2] - Syntax Error

### ISSUE THREAD

**Issue by rajwit** [kivy/python-for-android#721]
Hi,

I do see the below error message, please help me to address this.

I'm trying to deploy the HelloWorld Python 3.4.1. program to GoogleAppEngine and below is the error message I do see

File "C:\Program Files (x86)\Google\google_appengine\lib\webob-1.1.1\webob\request.py", line 1052
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax

below is the snap chat of the code
if self.is_body_seekable:
            self.body_file_raw.seek(0)
        captured = []
        output = []
        def start_response(status, headers, exc_info=None):
            if exc_info is not None and not catch_exc_info:
                raise exc_info[0], exc_info[1], exc_info[2]
            captured[:] = [status, headers, exc_info]
            return output.append
        app_iter = application(self.environ, start_response)
        if output or not captured:
            try:
                output.extend(app_iter)
            finally:
                if hasattr(app_iter, 'close'):
                    app_iter.close()
            app_iter = output
        if catch_exc_info:
            return (captured[0], captured[1], app_iter, captured[2])
        else:
            return (captured[0], captured[1], app_iter)

**Comment by kived** [comment]
What does this have to do with python-for-android? It looks like an issue with GAE.

**Comment by kived** [comment]
As this doesn't seem to have anything to do with p4a I'm going to close this. Please reopen or create a new issue if you have something p4a-related.
