### ISSUE TITLE
Default extraction of NDK version not compatible with most recent stable NDK release...

### ISSUE THREAD

**Issue by bidafiwoc** [kivy/python-for-android#723]
This is quite possibly more of a documentation bug than anything else, but I'm not sure as to full ramifications...

The p4a docs discuss user selection of the Android NDK version at 
http://python-for-android.readthedocs.org/en/latest/quickstart/#the-android-ndk-version.  That section states:

>  You can set this with any of the following methods - note that the first is preferred, and means that you probably do not have to manually set this.
> - The RELEASE.TXT file in the NDK directory. If this exists and contains the version (which it probably does automatically), you do not need to set it manually.
> - The --ndk_ver argument to any python-for-android command.
> - The ANDROIDNDKVER environment variable.

While the Android NDK r10e release (current up until March, 2016) did indeed have a RELEASE.TXT file in its distribution, the current NDK (r11c, released on March 31, 2016) does not have any RELEASE.TXT file.  Thus, the first method will not work with the most recent NDK.

Obviously, there's an easy work-around by just using the second (or third) option above and passing "--ndk_ver r11c" to p4a.

I'm filing this issue to:
- Suggest an update to the docs
- Confirm that there are no other ramifications to using the r11c NDK release.  My understanding is that p4a wants to know the NDK version so that it can properly anticipate the file structure of that NDK release.  Has p4a been tested with NDK r11 at all?  It seems to be working for me, but I've only done very limited testing so far.

Thanks!
##

**Comment by inclement** [comment]
That's annoying, maybe the ndk_ver argument will need to become compulsory for these versions. I expect p4a to work fine with this NDK, the RELEASE.txt was just a convenient assumptino.

**Comment by inclement** [comment]
Closing as this doesn't actually seem to have any repercussions, p4a does not rely on the ndk_version for anything. We could probably safely remove that option.
