### ISSUE TITLE
App crash when changing orientation

### ISSUE THREAD

**Issue by dessant** [kivy/python-for-android#730]
_From @belskikh on January 2, 2016 21:44_

When I change orientation from portrait to landscape, app closing. 
If in buildozer.spec file I change set 'android.minapi = 13', then all works fine.
##

_Copied from original issue: kivy/buildozer#264_
##

**Comment by dessant** [comment]
I can reproduce the bug with the kivy showcase app.

**Comment by dessant** [comment]
@inclement, should we move this to p4a?

**Comment by dessant** [comment]
_From @inclement on May 4, 2016 10:12_

Yes please, although there was at least one other bug report about it which may have been partially resolved.

**Comment by Tungsteno74** [comment]
If you add on_pause works?
Because I had a similar problem and I solved this way (do not crash anymore). But now I have a slightly different problem #732

**Comment by Heideachim** [comment]
This problem (app crash on rotate) is easily resolved by the counter-measure described by the original poster: 
'android.minapi = 13'
What happens, if we ship buildozer with a default spec file with this setting in place? I do not know. Thus I suggest in adding this still commented. And add a warning: If the app crashes on rotation, un-comment the minapi-line.
Should I do a pull-request for buildozer?

**Comment by inclement** [comment]
Solved by many changes since then, and also these old APIs are no longer supported.
