### ISSUE TITLE
app crash on close

### ISSUE THREAD

**Issue by jligeza** [kivy/python-for-android#734]
When I exit my app (`app.stop()`), a strange segmentation error occurs: http://pastebin.com/F8HEaeip

This is with sdl2 and kivy 1.9.2 dev.
It works fine with pygame, what makes me puzzled.

The requirements list: 
`requirements = openssl,geopy,plyer,android,tinydb,hostpython2,kivy==master`

What could be the reason of this crash?
##

**Comment by inclement** [comment]
I don't have any insight into this, I guess it needs some active debugging. If the segfault is happening during kivy's internal stop process then that's probably the first place to look.

**Comment by cidermole** [comment]
Here's the problem I experienced (with crash in the same place):

It seems to me that SDL native code references a stale `Android_Window` in `Java_org_libsdl_app_SDLActivity_nativePause()`.

Workaround:

You must call `WindowSDL.close()` before the app exits the main `EventLoop`.

An ideal way to do this is to handle the event in `App.on_stop()`:

```
from kivy.app import App
from kivy.core.window import Window

class MyFancyApplication(App):
    def on_stop(self):
        Window.close()

# ...

# somewhere else:
App.get_running_app().stop()
```

**Comment by cidermole** [comment]
@inclement can you provide more details about how the basic kivy shutdown design? I guess that the event should be bound to something which cleans up the window without needing user code?

**Comment by gooroopy** [comment]
@cidermole  I've also spent a few hours to fixed this issue a couple week ago, this is my patch :- http://pastebin.com/JthasWiG

@inclement I will submit PR to Kivy if this is make sense.

**Comment by inclement** [comment]
@gooroopy Sorry for the delay replying, and thanks a lot for the patch! I'm not familiar with this part of Kivy's internals, but if you didn't do so already it would be very welcome to open a PR in the kivy repo for it.

**Comment by inclement** [comment]
I believe this is no longer happening on p4a master. Recently I was testing this type of thing while getting pause to work with sdl2.0.9
