### ISSUE TITLE
p4a apk webview bug

### ISSUE THREAD

**Issue by jligeza** [kivy/python-for-android#738]
When I run `p4a apk --private=/path --package=org.test.webview --name="webview test" --version=0.1`, I get this error:

> [INFO]:    webviewtest has compatible recipes, using this one
> [INFO]:    -> directory context /home/stefan/.local/share/python-for-android/dists/webviewtest
> Traceback (most recent call last):
>   File "/usr/local/bin/p4a", line 9, in <module>
>     load_entry_point('python-for-android==0.3', 'console_scripts', 'p4a')()
>   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 745, in main
>     ToolchainCL()
>   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 334, in __init__
>     getattr(self, args.command)(unknown)
>   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 94, in wrapper_func
>     func(self, args)
>   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.3-py2.7.egg/pythonforandroid/toolchain.py", line 580, in apk
>     build_args = build.parse_args(args)
>   File "/home/stefan/.local/share/python-for-android/dists/webviewtest/build.py", line 487, in parse_args
>     make_package(args)
>   File "/home/stefan/.local/share/python-for-android/dists/webviewtest/build.py", line 241, in make_package
>     make_tar('assets/private.mp3', tar_dirs, args.ignore_path)
>   File "/home/stefan/.local/share/python-for-android/dists/webviewtest/build.py", line 173, in make_tar
>     files += [(x, relpath(realpath(x), sd)) for x in listfiles(sd)
>   File "/home/stefan/.local/share/python-for-android/dists/webviewtest/build.py", line 98, in listfiles
>     for item in os.listdir(d):
> OSError: [Errno 2] No such file or directory: '/home/stefan/.local/share/python-for-android/dists/webviewtest/webview_includes'

This can be fixed by creating the `webview_includes` directory manually.

**Comment by inclement** [comment]
I just pushed a fix to make sure setup.py installs this folder, so this should be fixed. Could you verify if that's indeed worked?

**Comment by jligeza** [comment]
@inclement I can confirm it works now.

**Comment by inclement** [comment]
Great, thanks for reporting it and giving the debug information!
