### ISSUE TITLE
webview - flask server crashes immediately

### ISSUE THREAD

**Issue by jligeza** [kivy/python-for-android#739]
I've used buildozer to create a ,,hello world'' app using a webview and flask. Unfortunately, it crashes right away with error `ERR_CONNECTION_RESET`, and once I press a link to `http://127.0.0.1:5000/`, the error changes to `ERR_CONNECTION_REFUSED`.

adb logcat: http://pastebin.com/W6rs1bB6

main.py:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Flask
app = Flask(__name__)


@app.route('/')
def main_page():
    return 'hello world'

app.run(debug=True, host='0.0.0.0')

```

minimal buildozer.spec:
```
[app]
title = Webview test
package.name = webviewtest
package.domain = org.webviewtest
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = webviewjni,hostpython2,flask
android.bootstrap = webview
orientation = portrait
fullscreen = 1
android.permissions = INTERNET
[buildozer]
log_level = 2
warn_on_root = 1
```
PS: the apk weight is only 5,5mb, what is quite nice.

**Comment by inclement** [comment]
I had problems using debug=True, but I can't remember what happened exactly. Could you try disabling that to see if it works? You could also remove the host argument just in case, but I don't know if that could be relevant.

**Comment by inclement** [comment]
Also, for what it's worth the webview bootstrap should automatically include the INTERNET permission so you can leave that out if you like.

**Comment by jligeza** [comment]
@inclement Indeed, removal of `debug = True` makes it mork, that means a text ''hello world'' displays correctly. It also works with `host` argument.

**Comment by inclement** [comment]
Great. I don't think this problem is something p4a can fix (since it seems to relate to flask's use of a subprocess, which won't work on android), so I'll close this issue.

**Comment by inclement** [comment]
I've added a note in the doc about it, for what that's worth.
