### ISSUE TITLE
Webview - back button bug

### ISSUE THREAD

**Issue by jligeza** [kivy/python-for-android#741]
My webview app displays ,,hello world'' text.

I open it, and close shortly after with back button (without deleting from recently opened apps): http://pastebin.com/bAhqqYPS

Then, I try to open it again (from ,,desktop'', or how to call it), and it crashes with segmentation error: http://pastebin.com/uH22kSUV

I use python 2 for this app.

**Comment by bobatsar** [comment]
The problem is, that the python_thread is not killed when the app is closed.
I have a workaround in pull request #750. Not nice but at least working for now.

**Comment by inclement** [comment]
I'll close this as I've merged @bobatsar's PR, but a better solution would be welcome.
