### ISSUE TITLE
Why does the boot image is deformed?

### ISSUE THREAD

**Issue by dessant** [kivy/python-for-android#745]
_From @HeaTTheatR on May 11, 2016 7:0_

I took the boot image from a folder python-for-android/src/res/drawable/presplash.png. The image size is not changed. Previously, all displayed properly on all monitors, and now like this:

![ScreenShot](http://msg.dimonvideo.ru/sklad/files/1941157/a7_b6_loading.png)

Ubuntu 14.04 (32-bit), Buildozer 0.33, Kivy 1.9.1

_Copied from original issue: kivy/kivy#4276_

**Comment by dessant** [comment]
@HeaTTheatR, previously means in buildozer 0.32?

**Comment by dessant** [comment]
_From @HeaTTheatR on May 11, 2016 12:7_

I do not quite understand the question. Yes, earlier I had the version 0.32. Now - 0.33dev.

**Comment by dessant** [comment]
@inclement, were there any splashscreen changes in p4a recently?

**Comment by dessant** [comment]
_From @HeaTTheatR on May 11, 2016 12:27_

Excuse me, I'm from Ukraine, so I can write illegibly. I have not tried to use the standard boot image. I'll be back home, I will tell for sure.

**Comment by dessant** [comment]
_From @inclement on May 11, 2016 18:47_

This result is due to a bug in python-for-android, but I thought it was fixed now in both toolchains.

**Comment by dessant** [comment]
_From @HeaTTheatR on May 11, 2016 22:45_

It can be fixed?

**Comment by inclement** [comment]
@HeaTTHeatR Does this still occur, using the master branch of python-for-android?

**Comment by inclement** [comment]
I think this is fixed in master following some other issues a while ago, so I'm closing it. Feel free to make another issue or reopen this if I'm wrong.
