### ISSUE TITLE
P4A and C++/SDL2/Python2/OpenGL game

### ISSUE THREAD

**Issue by tobimensch** [kivy/python-for-android#747]
Hello,

I'm trying to port a SDL2/OpenGL game written in C++ that is using libpython for in game scripts to Android.

I don't understand how I can use python-for-android in this scenario.

**Comment by inclement** [comment]
Sorry for the delay responding, I didn't see this issue when you first made it. Did you find out what you needed? Overally, it should be sufficient to use the sdl2 bootstrap and add a recipe to run your code. If you can start it with a python script, you can then use that to do so. If it needs a C shim to start, you might need do modify the sdl2 bootstrap; we can help with that if necessary, and if we understand what needs doing can add some options to make it easier.
