### ISSUE TITLE
Camera on android

### ISSUE THREAD

**Issue by alexsilva** [kivy/python-for-android#75]
Log error: http://pastebin.com/LwgjpMqQ

. / distribute.sh-m "pil Kivy pygame opencv"

error: Recipe opencv does not exit

opencv is not included in the "recipes dir".

How to fix it?
Thank you.

**Comment by gorgonaut04** [comment]
Has there been any update on this? Would it be possible to get an official recipe for OpenCV in the near future?

**Comment by jasonxunxu** [comment]
I created a recipe for OpenCV and submitted it as PR #327. The recipe patches OpenCV v2.4.10.1, builds a fully working Python module cv2.so, as well as installs native camera libraries. The Java library (libopencv_java.so) is actually not needed.

I don't have the resource to test the camera functionality on many different devices. It works fine on one phone running Android 4.1, but failed on another phone running 4.4 (as @barius mentioned earlier).

**Comment by gorgonaut04** [comment]
Hi again, Jason. Do you have any tips for using the Android camera feature of OpenCV within kivy? This seems to be uncharted territory.

**Comment by cbenhagen** [comment]
@jasonxunxu thank you very much for the recipe! Do you mind giving a small example on how one would use the camera? If it should be as simple as

```python
cap = cv2.VideoCapture(0)
```

it might just not work on my nexus 5. This is the whole code i used to test: https://gist.github.com/cbenhagen/457af62752fba44fff47

**Comment by cbenhagen** [comment]
oh never mind.. i just found your kivy fork and its camera-android branch

**Comment by jasonxunxu** [comment]
@cbenhagen Thanks for digging out my branch, I just posted a [PR for Kivy](https://github.com/kivy/kivy/pull/3236). Please let me know how it works for you.

@gorgonaut04 I hope it does the trick for you too.

**Comment by gorgonaut04** [comment]
@jasonxunxu it looks to me as if this code is good for streaming video data, but can it also be used to actually take full-resolution photo using the shutter? I apologize if I'm just completely missing this, but are there any usage examples for this code? Thanks!

**Comment by jasonxunxu** [comment]
It is a standard camera provider so works transparently with the Camera widget on Android. In addition it has a `read_frame` method to fetch current frame data (of same resolution as the preview image). It is not designed to take full resolution pictures, for which [Plyer camera](https://github.com/kivy/plyer/blob/master/plyer/platforms/android/camera.py) might be what you want.
