### ISSUE TITLE
ImportError: Import by filename is not supported.

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#751]
While running nose that uses python unittest builtin library.

Error log:
```
I/python: AND: Ran string
I/python: Run user program, change dir and execute entrypoint
I/Triblerd: Traceback (most recent call last):
I/Triblerd:   File "Triblerd.py", line 33, in <module>
I/Triblerd:     Triblerd().test()
I/Triblerd:   File "Triblerd.py", line 29, in test
I/Triblerd:     nose.run('-s ' + test_path)
I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/nose/core.py", line 301, in run
I/Triblerd:     return TestProgram(*arg, **kw).success
I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
I/Triblerd:     **extra_args)
I/Triblerd:   File "/data/user/0/org.tribler.android/files/lib/python27.zip/unittest/main.py", line 77, in __init__
I/Triblerd: ImportError: Import by filename is not supported.
I/python: Python for android ended.

main.py source:
```
    def __init__(self, module='__main__', defaultTest=None, argv=None,
                    testRunner=None, testLoader=loader.defaultTestLoader,
                    exit=True, verbosity=1, failfast=None, catchbreak=None,
                    buffer=None):
        if isinstance(module, basestring):
            self.module = __import__(module)
```

**Comment by inclement** [comment]
I wasn't aware of p4a doing anything that would break normal behaviour, though I could have forgotten about a patch doing that. Weird.

**Comment by kived** [comment]
Actually, I don't think we're doing anything to break this. Using `__import__` on a filename just isn't supported in general (at least in py2). On Ubuntu 16.04, Python 2.7.11:

```
In [1]: __import__('a/b/c.py')
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-61d17bad1646> in <module>()
----> 1 __import__('a/b/c.py')

ImportError: Import by filename is not supported.

```

**Comment by brussee** [comment]
Exactly. No fault of p4a at all! The issue was on python itself not supporting import by filename. I could work around this, and I will add a nose recipe soon.

But before I can, I have to figure out why the test module could be loaded but the test function inside it is not detected and nose ends with saying 0 tests executed.
