### ISSUE TITLE
Threads need a wrapper for calling detach()

### ISSUE THREAD

**Issue by akshayaurora** [kivy/python-for-android#758]
Threads that don't exit cleanly can cause a Java Exception.

There should be a wrapper around threads that automatically detaches the thread before exit, avoiding this kind of error.

**Comment by ecdsa** [comment]
`06-02` 16:02:14.198 29619 29655 W art     : Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[13,tid=29655,Native,Thread*=0xb984afd8,peer=0x12db40a0,"Thread-11803"]`

**Comment by inclement** [comment]
@akshayaurora I'm not familiar with this, is it something that the old toolchain had but is now missing?

**Comment by akshayaurora** [comment]
No, old toolchain did not have this either.

**Comment by zwyuan** [comment]
I ran into the same issue too. Please help resolve this, thanks

**Comment by suriyan** [comment]
Please look at :- https://github.com/kivy/pyjnius/issues/107

**Comment by ecdsa** [comment]
any news on this?

**Comment by akshayaurora** [comment]
closed by 98386606262329b29cf74bc894b048ac37dbd6cb
