### ISSUE TITLE
Cryptography recipe does not compile

### ISSUE THREAD

**Issue by pythonic64** [kivy/python-for-android#766]
I'm trying to build Kivy app with:
- sdl2 bootstrap
- recipes python2,kivy,cryptography 
- buildozer 0.32 
- latest python-for-android master branch 

In libffi recipe I had to replace [line](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/libffi/__init__.py#L43) with:
```shprint(sh.Command('autoreconf'), '-vif', _env=env)```.
Without that change p4a was raising sh.CommandNotFound error. 

Now running ```buildozer android_new debug``` produces the following error log: http://pastebin.com/22qjBJwL
buildozer.spec file: http://pastebin.com/aLe7nLHG
main.py file: http://pastebin.com/xSReYe6u

**Comment by brussee** [comment]
I ran into the same issue which was introduced in #735.
@kived Do you know a fix?
