### ISSUE TITLE
Presplash does not work with SDL2.

### ISSUE THREAD

**Issue by dzmitrykrukouski** [kivy/python-for-android#806]
I set `presplash.filename = %(source.dir)s/data/itech_20.png` in my buildozer.spec. When i built my app with target 'android' _presplash_ is showing and all work fine, but  when i use target 'android_new', it showing just black screen without image and my application is crushed. 

I commented out the line https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java#L305 and application start work, but presplash still not loading.

**Comment by inclement** [comment]
I think a recent commit introduced a problem with the splash code for some people, but I've merged another that seems to fix it. Can you update to master and test if you still have this problem?

**Comment by rtorresj** [comment]
Can confirm this isn't working still with master both buildozer and p4a.

**Comment by rafalo1333** [comment]
For me it is not working too with master branch, compiled with newest Buildozer.

**Comment by dzmitrykrukouski** [comment]
Presplash start work for me with Kivy master branch.

**Comment by inclement** [comment]
This seems to be fully fixed now.
