### ISSUE TITLE
Docs - connected toctrees, too deep?

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/python-for-android#820]
<table border="0"><tr><td width=100><img src="https://cloud.githubusercontent.com/assets/8825439/16611842/29920b2c-4364-11e6-841c-8dc9d0d3e4b1.png" height=250 /></td>
<td>I think it was available even with the old toolchain, but when you for example click on <code>Recipes</code>, it opens like this. It wouldn't be so weird if it was only like one or two branches(only <code>Getting started</code> or max <code>Advanced usage</code>.<br><br>If you at least kind of know what's where, you don't mind... but if you want to navigate properly through that navigation and you are beginner, it shouldn't throw so much stuff at you. Plus it doesn't look nice either because I just clicked on the <code>Recipes</code> and it shows whole toctree of the first page.<br><br>The same applies for: <code>Build</code>, <code>Commands</code>, <code>Bootstraps</code>, etc. </td></tr></table>

**Comment by inclement** [comment]
This is an unexpected (to me) result of adding some links to the quickstart page. Fixing it should just be a matter of changing them to doc links rather than toctree links.
