### ISSUE TITLE
Feature request: access to all permissions

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/python-for-android#843]
Don't have an option to write a PR(debugged), so I rather ask beforehand. When I use custom launcher, I put there every permission I know could be at least a little bit useful. As the launcher isn't intended for final distribution, e.g. `__init__.py` could be a nice place for a list of all available permissions.

Then `--permission ALL` would be possible as it'd only need to have a simple loop in each `build.py` that can build the launcher(or even in all builds). However, I can see ALL not available in arguments as a safety switch too for the final dist.

Is it a good idea to include ALL into p4a?  pros could be simple process of adding permissions, maybe future check if permission is typed correctly(in a list of permissions) and maybe prevent crashes this way(don't know if there is some check for this), then make updating _custom_(I don't want you to go for stable launcher with all permissions) one less frequent. This could make the launcher slowly become "ide" on android for Kivy.

Two critical cons are basically disabling permission security at all with this(app would have ALL) and a risk that some beginner would go for this craziness in final dist.
##

**Comment by KeyWeeUsr** [comment]
If not access to all, then at least to permissions that are profitable for kivy apps with plyer or for those working directly with the shell ([more](https://developer.android.com/reference/android/Manifest.permission.html)):

```
ACCESS_COARSE_LOCATION
ACCESS_FINE_LOCATION
ACCESS_NETWORK_STATE
ACCESS_NOTIFICATION_POLICY
ACCESS_WIFI_STATE
BATTERY_STATS
BLUETOOTH
BLUETOOTH_ADMIN
BODY_SENSORS
BROADCAST_SMS
BROADCAST_WAP_PUSH
CALL_PHONE
CAMERA
CAPTURE_AUDIO_OUTPUT
CAPTURE_VIDEO_OUTPUT
CHANGE_NETWORK_STATE
CHANGE_WIFI_STATE
CONTROL_LOCATION_UPDATES
FACTORY_TEST  (test root)
GET_ACCOUNTS
INTERNET
KILL_BACKGROUND_PROCESSES
NFC
PACKAGE_USAGE_STATS
READ_CALENDAR
READ_CALL_LOG
READ_CONTACTS
READ_EXTERNAL_STORAGE
READ_LOGS
READ_PHONE_STATE
READ_SMS
READ_SYNC_SETTINGS
READ_SYNC_STATS
READ_VOICEMAIL
REBOOT
RECEIVE_BOOT_COMPLETED
RECEIVE_MMS
RECEIVE_SMS
RECEIVE_WAP_PUSH
RECORD_AUDIO
SEND_SMS
SET_ALARM
STATUS_BAR
SYSTEM_ALERT_WINDOW
USE_FINGERPRINT
VIBRATE
WAKE_LOCK
WRITE_CALENDAR
WRITE_CALL_LOG
WRITE_CONTACTS
WRITE_EXTERNAL_STORAGE
WRITE_SETTINGS
```

**Comment by Julian-O** [comment]
Given we have no launchers currently live (or planned to be live), closing this as Not Planned.
