### ISSUE TITLE
non debug apk?

### ISSUE THREAD

**Issue by andresmrm** [kivy/python-for-android#844]
First: Thanks for P4A (and the entire Kivy project)! =)

When I build an apk its name ends with "debug". Does it means it's a debug version? How to build a non debug apk?
Sorry if this was already answered...

**Comment by Fak3** [comment]
I got an answer here before:
https://groups.google.com/forum/#!topic/python-android/ZkY4MlUs65Y

The only difference is that debug build is missing signature of a package.

**Comment by andresmrm** [comment]
Thanks! =)
