### ISSUE TITLE
webbrowser.open() doesn't work on Android with bootstrap=sdl2

### ISSUE THREAD

**Issue by mrhdias** [kivy/python-for-android#846]
webbrowser.open() doesn't work on Android with bootstrap=sdl2, but work with pygame.
No error, no crash, just nothing happens. Is there any solution to fix this issue?

Android Version: 6.0.1

```
import webbrowser
webbrowser.open('http:/www.kivy.org/')
```

From buildozer logs

```
# Run 'python -m pythonforandroid.toolchain
 --color=always
 --storage-dir=/home/hdias/Work/mobile_app/.buildozer/android/platform/build create
 --dist_name=mobile_app 
 --bootstrap=sdl2
 --requirements=pycrypto,plyer==master,kivy==master --arch armeabi-v7a --copy-libs'
```

**Comment by mrhdias** [comment]
To fix this error, I add the android module to the requirements in buildozer.spec.

**Comment by mrhdias** [comment]
To fix this error, I add the android module to the requirements in buildozer.spec.

**Comment by WillDHB** [comment]
I believe you also need to do an "import android" prior to calling webbrowser.open() (unless something else is automatically importing), as the android module registers the AndroidBrowser with the webbrowser module.

**Comment by inclement** [comment]
For reference, the specific code you need is as below (you can use this instead of the android module if you like):

    from pyjnius import autoclass

    def open_url(url):
        Intent = autoclass('android.content.Intent')
        Uri = autoclass('android.net.Uri')
        browserIntent = Intent()
        browserIntent.setAction(Intent.ACTION_VIEW)
        browserIntent.setData(Uri.parse(url))
        currentActivity = cast('android.app.Activity', mActivity)
        currentActivity.startActivity(browserIntent)

    # Web browser support.
    class AndroidBrowser(object):
        def open(self, url, new=0, autoraise=True):
            open_url(url)
        def open_new(self, url):
            open_url(url)
        def open_new_tab(self, url):
            open_url(url)

    import webbrowser
    webbrowser.register('android', AndroidBrowser, None, -1)

I'd like to add this to the doc somehow, but am not sure where to put it.

**Comment by inclement** [comment]
I've added some brief documentation for this, and we're discussing how to make it easily/automatically available by default.

**Comment by mrhdias** [comment]
Thanks for clues, but your solution does not work because it is not complete.
Can you fix the code with this?
http://python-for-android.readthedocs.io/en/latest/apis/

```
from kivy.utils import platform

def launch_webbrowser(url):
    import webbrowser
    if platform == 'android':
        from jnius import autoclass, cast
        def open_url(url):
            PythonActivity = autoclass('org.kivy.android.PythonActivity')
            activity = PythonActivity.mActivity
            Intent = autoclass('android.content.Intent')
            Uri = autoclass('android.net.Uri')
            browserIntent = Intent()
            browserIntent.setAction(Intent.ACTION_VIEW)
            browserIntent.setData(Uri.parse(url))
            currentActivity = cast('android.app.Activity', activity)
            currentActivity.startActivity(browserIntent)

        # Web browser support.
        class AndroidBrowser(object):
            def open(self, url, new=0, autoraise=True):
                open_url(url)
            def open_new(self, url):
                open_url(url)
            def open_new_tab(self, url):
                open_url(url)

        webbrowser.register('android', AndroidBrowser, None, -1)

    webbrowser.open(url)

launch_webbrowser('http://www.kivy.org')
```

**Comment by JanuszSpiewa** [comment]
> Thanks for the clues, but your solution does not work because it is not complete.
> Can you fix the code with this?
> http://python-for-android.readthedocs.io/en/latest/apis/
> 
> ```
> from kivy.utils import platform
> 
> def launch_webbrowser(url):
>     import webbrowser
>     if platform == 'android':
>         from jnius import autoclass, cast
>         def open_url(url):
>             PythonActivity = autoclass('org.kivy.android.PythonActivity')
>             activity = PythonActivity.mActivity
>             Intent = autoclass('android.content.Intent')
>             Uri = autoclass('android.net.Uri')
>             browserIntent = Intent()
>             browserIntent.setAction(Intent.ACTION_VIEW)
>             browserIntent.setData(Uri.parse(url))
>             currentActivity = cast('android.app.Activity', activity)
>             currentActivity.startActivity(browserIntent)
> 
>         # Web browser support.
>         class AndroidBrowser(object):
>             def open(self, url, new=0, autoraise=True):
>                 open_url(url)
>             def open_new(self, url):
>                 open_url(url)
>             def open_new_tab(self, url):
>                 open_url(url)
> 
>         webbrowser.register('android', AndroidBrowser, None, -1)
> 
>     webbrowser.open(url)
> 
> launch_webbrowser('http://www.kivy.org')
> ```

$ python web.py
  File "web.py", line 2
    webbrowser.open() doesn't work on Android with bootstrap=sdl2
                      ^
SyntaxError:
