### ISSUE TITLE
Building python for android's requirements for 64 bit Android processors

### ISSUE THREAD

**Issue by varunasingh** [kivy/python-for-android#848]
I'm unaware how to do that. Have been looking both here and at buildozer. Any direction would be helpful. Thanks!

**Comment by inclement** [comment]
Pass the argument `--arch=arm64-v8a`. I don't know if this works or has been tested, but the Arm64 target exists in the toolchain and should either build correctly or at least crash with a specific error to fix.

**Comment by inclement** [comment]
I'm going to close this issue, feel free to open another about the specific problem if you find that the 64 bit target doesn't work. You could also open a buildozer feature request issue for an arch option (rather than its hardcoded armeabi-v7a).
