### ISSUE TITLE
How can i use the custom broadcast by myself in the background service? 

### ISSUE THREAD

**Issue by linuxrootok** [kivy/python-for-android#849]
**My service file:**
--------------------------------------------------------
```
import time,base64
#from kivy.network.urlrequest import UrlRequest
#from kivy.core.audio import SoundLoader
#from plyer import vibrator
from jnius import autoclass
c = autoclass('android.content.Context')
#cw = c()

it = autoclass('android.content.Intent')
i = it()
class myservice():

    def __init__(self,*arg):
        self.arg = arg

    def checkOnline(self):
        i.setAction('org.ttt.app.MY_ACTION')
        i.putExtra('state','1')
        #c.sendOrderedBroadcast(i,None) 
        c.sendBroadcast(i)
        #cw.sendBroadcast(i)

s = myservice()
while True:
    s.checkOnline()
    time.sleep(30)
    #vibrator.vibrate(8)
```
-------------------------------------------------------------------------------
**My app main file:**
-------------------------------------------------------------------------------
```
from kivy.app import App
from kivy.uix.button import Button
from jnius import autoclass
from kivy.uix.togglebutton import ToggleButton
import android
from android.broadcast import BroadcastReceiver

class TylerApp(App):

    def build(self):
        self.flag = None
        android.start_service(title='service name',description='service description',arg='argument to service')
        #Br = autoclass('android.content.BroadcastReceiver')
        self.br = BroadcastReceiver(self.on_broadcast, actions=['org.ttt.app.MY_ACTION'], categories=['android.intent.category.DEFAULT'])
        self.br.start()

        btn = ToggleButton(text='Male',group='sex',state='normal')
        btn.bind(on_press=self.callback)

        return btn
    def callback(self,instance):
        #print(instance.state)
        if self.flag != None: 
            instance.text = 'OOOKKK'
            self.flag = None
        else:
            if instance.state == 'down':
                instance.text = 'OK'
            else:
                instance.text = 'KO'

    def on_broadcast(self,context,intent):
        extras = intent.getExtras()
        flag = bool(extras.get('state'))
        if(flag):
            self.flag = 'plugged'
        else:
            self.flag = None

if __name__ == "__main__":
    TylerApp().run()
```

I  have tried many times, but it is not work for me.  Please give me some help, thanks a lot!

**Comment by inclement** [comment]
Follow the instructions [here](https://kivy.org/docs/guide/android.html#debugging-your-application-on-the-android-platform) to debug your problem.

**Comment by linuxrootok** [comment]
W/ActivityManager(  355): No content provider found for permission revoke: file:///data/local/tmp/ttt-0.6-debug.apk
W/ActivityManager(  355): No content provider found for permission revoke: file:///data/local/tmp/ttt-0.6-debug.apk
I/PackageManager(  355): Running dexopt on: org.ttt.app
I/ActivityManager(  355): Force stopping org.ttt.app appid=10052 user=-1: update pkg
D/BackupManagerService(  355): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:org.ttt.app flg=0x4000010 (has extras) }
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
I/ActivityManager(  355): Start proc org.ttt.app:python for activity org.ttt.app/org.renpy.android.PythonActivity: pid=1055 uid=10052 gids={50052, 1028, 1015, 3003}
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
W/WindowManager(  355): Force clearing orientation change: Window{b1fc0da8 u0 Starting org.ttt.app}
I/ActivityManager(  355): Process org.ttt.app:python (pid 1055) has died.
W/ActivityManager(  355): Force removing ActivityRecord{b1f2fa40 u0 org.ttt.app/org.renpy.android.PythonActivity t2}: app died, no saved state
W/InputDispatcher(  355): channel 'b1fdacb0 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  355): channel 'b1fdacb0 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowManager(  355): Screen frozen for +3s715ms due to Window{b1fc0da8 u0 Starting org.ttt.app}
W/InputDispatcher(  355): Attempted to unregister already unregistered input channel 'b1fdacb0 org.ttt.app/org.renpy.android.PythonActivity (server)'
I/WindowState(  355): WIN DEATH: Window{b1fdacb0 u0 org.ttt.app/org.renpy.android.PythonActivity}
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
I/ActivityManager(  355): Start proc org.ttt.app:python for activity org.ttt.app/org.renpy.android.PythonActivity: pid=1093 uid=10052 gids={50052, 1028, 1015, 3003}
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
W/WindowManager(  355): Force clearing orientation change: Window{b1fe49c8 u0 Starting org.ttt.app}
I/ActivityManager(  355): Process org.ttt.app:python (pid 1093) has died.
W/ActivityManager(  355): Force removing ActivityRecord{b1f2fa40 u0 org.ttt.app/org.renpy.android.PythonActivity t3}: app died, no saved state
W/InputDispatcher(  355): channel 'b1fd68d0 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  355): channel 'b1fd68d0 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  355): Attempted to unregister already unregistered input channel 'b1fd68d0 org.ttt.app/org.renpy.android.PythonActivity (server)'
I/WindowState(  355): WIN DEATH: Window{b1fd68d0 u0 org.ttt.app/org.renpy.android.PythonActivity}
W/WindowManager(  355): Force-removing child win Window{b1fddce0 u0 SurfaceView} from container Window{b1fd68d0 u0 org.ttt.app/org.renpy.android.PythonActivity}
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
I/ActivityManager(  355): Start proc org.ttt.app:python for activity org.ttt.app/org.renpy.android.PythonActivity: pid=1119 uid=10052 gids={50052, 1028, 1015, 3003}
W/WindowManager(  355): Force clearing orientation change: Window{b2050a68 u0 Starting org.ttt.app}
I/ActivityManager(  355): Process org.ttt.app:python (pid 1119) has died.
W/InputDispatcher(  355): channel 'b201b988 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  355): channel 'b201b988 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/ActivityManager(  355): Force removing ActivityRecord{b1fa2c30 u0 org.ttt.app/org.renpy.android.PythonActivity t4}: app died, no saved state
W/InputDispatcher(  355): Attempted to unregister already unregistered input channel 'b201b988 org.ttt.app/org.renpy.android.PythonActivity (server)'
I/WindowState(  355): WIN DEATH: Window{b201b988 u0 org.ttt.app/org.renpy.android.PythonActivity}
W/WindowManager(  355): Force-removing child win Window{b1f68778 u0 SurfaceView} from container Window{b201b988 u0 org.ttt.app/org.renpy.android.PythonActivity}
I/WindowManager(  355): Screen frozen for +4s233ms due to Window{b2050a68 u0 Starting org.ttt.app}
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
I/ActivityManager(  355): Start proc org.ttt.app:python for activity org.ttt.app/org.renpy.android.PythonActivity: pid=1146 uid=10052 gids={50052, 1028, 1015, 3003}
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
W/WindowManager(  355): Force clearing orientation change: Window{b1fc0da8 u0 Starting org.ttt.app}
I/ActivityManager(  355): Process org.ttt.app:python (pid 1146) has died.
W/ActivityManager(  355): Force removing ActivityRecord{b1ff3770 u0 org.ttt.app/org.renpy.android.PythonActivity t5}: app died, no saved state
W/InputDispatcher(  355): channel 'b1fd6d00 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  355): channel 'b1fd6d00 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  355): Attempted to unregister already unregistered input channel 'b1fd6d00 org.ttt.app/org.renpy.android.PythonActivity (server)'
I/WindowState(  355): WIN DEATH: Window{b1fd6d00 u0 org.ttt.app/org.renpy.android.PythonActivity}
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
I/ActivityManager(  355): Start proc org.ttt.app:python for activity org.ttt.app/org.renpy.android.PythonActivity: pid=1170 uid=10052 gids={50052, 1028, 1015, 3003}
I/ActivityManager(  355): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ttt.app/org.renpy.android.PythonActivity} from pid 517
W/WindowManager(  355): Force clearing orientation change: Window{b1fcb668 u0 Starting org.ttt.app}
W/WindowManager(  355): Force clearing freeze: AppWindowToken{b2088ac8 token=Token{b1fe6628 ActivityRecord{b1f2fa40 u0 org.ttt.app/org.renpy.android.PythonActivity t6}}}
I/ActivityManager(  355): Process org.ttt.app:python (pid 1170) has died.
W/ActivityManager(  355): Force removing ActivityRecord{b1f2fa40 u0 org.ttt.app/org.renpy.android.PythonActivity t6}: app died, no saved state
W/InputDispatcher(  355): channel 'b1fe49c8 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  355): channel 'b1fe49c8 org.ttt.app/org.renpy.android.PythonActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  355): Attempted to unregister already unregistered input channel 'b1fe49c8 org.ttt.app/org.renpy.android.PythonActivity (server)'
I/WindowState(  355): WIN DEATH: Window{b1fe49c8 u0 org.ttt.app/org.renpy.android.PythonActivity}
W/WindowManager(  355): Force-removing child win Window{b208d340 u0 SurfaceView} from container Window{b1fe49c8 u0 org.ttt.app/org.renpy.android.PythonActivity}
