### ISSUE TITLE
error when running an apk compiled with python3crystax

### ISSUE THREAD

**Issue by rtorresj** [kivy/python-for-android#859]
The apk compiles perfectly, but when I run it on an android phone the following shows up in the logcat:

I/python (10836): Android kivy bootstrap done. name is main
I/python (10836): AND: Ran string
I/python (10836): Run user program, change dir and execute entrypoint
I/python (10836): main.py
I/python (10836): [INFO ] [Logger ] Record log in /data/data/org.test.juego/files/.kivy/logs/kivy_16-08-02_1.txt
I/python (10836): [INFO ] [Kivy ] v1.9.2-dev0
I/python (10836): [INFO ] [Python ] v3.5.0 (default, Dec 24 2015, 05:56:40)
I/python (10836): [GCC 5.3 20151204]
I/python (10836): Traceback (most recent call last):
I/python (10836): File "main.py", line 1, in
I/python (10836): from kivy.app import App
I/python (10836): File "/data/data/org.test.juego/files/crystax_python/site-packages/kivy/app.py", line 319, in
I/python (10836): from kivy.base import runTouchApp, stopTouchApp
I/python (10836): File "/data/data/org.test.juego/files/crystax_python/site-packages/kivy/base.py", line 29, in
I/python (10836): from kivy.clock import Clock
I/python (10836): File "/data/data/org.test.juego/files/crystax_python/site-packages/kivy/clock.py", line 364, in
I/python (10836): from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
I/python (10836): ImportError: dlopen failed: cannot locate symbol "_Py_NoneStruct" referenced by "_clock.so"...
I/python (10836): Python for android ended.

What can I do to help?
##

**Comment by AndreMiras** [comment]
Hi @rtorresj ,
This is a rather old issue. `python3crystax` and recipes built on top of it have moved since then. Are you still able to reproduce? If so can you share the new log and `buildozer.spec` file?
