### ISSUE TITLE
ImportError: No module named pysqlite2

### ISSUE THREAD

**Issue by spinningD20** [kivy/python-for-android#860]
Disclaimer and note, this might be an issue with sqlalchemy - it's the source of the error.  buildozer android_new generates this error, but buildozer android does not.  Please let me know what other information would be useful!

[android_build.txt](https://github.com/kivy/python-for-android/files/402123/android.txt)
[android_new_build.txt](https://github.com/kivy/python-for-android/files/402124/android_new.txt)
[android_new logcat](https://gist.github.com/spinningD20/e0d9e0221c384e60e212afc4eb4e8464)
[android logcat](https://gist.github.com/spinningD20/da20efe264f9a5ff9991f8324fd34ab7)
##

**Comment by FreakJoe** [comment]
Have you found a way to work around this issue?

**Comment by AndreMiras** [comment]
I guess this is fixed after 3 years, otherwise feel free to re-open with updated info
