### ISSUE TITLE
Can't compile with openssl

### ISSUE THREAD

**Issue by jameswhitakerwork** [kivy/python-for-android#868]
By adding openssl to the requirements in the buildozer spec, building with android_new fails. If I delete openssl from requirements, the build works. I've tried a clean and redo. I've also tried PyOpenSSL with an identical error iirc.

Here is the error log: http://pastebin.com/gbja4UTJ

Here is the buildozer spec file: http://pastebin.com/E4BjPRyT

Here is the main.py: http://pastebin.com/LzUz7X7Q

**Comment by jameswhitakerwork** [comment]
I just did a new clean and retry, got a new error. Again, it works fine if I remove openssl from requirements. http://pastebin.com/JtSTcttD

**Comment by jameswhitakerwork** [comment]
The exact same error occurs if adding pyopenssl to requirements. Other modules work fine.

**Comment by kmonson** [comment]
I was able to build with pyopenssl as of yesterday. It must be something with your environment. Sorry I can't be more helpful. Maybe you need to replace hostpython2 with python2.

I chimed in to tell you that with only the pyopenssl library you won't be able to properly connect to https sites using requests. 

The python 2 version that comes with p4a (2.7.2) has extra requirements to make ssl with requests work. In addition to pyopenssl you will need:

cryptography
pyasn1
ndg_httpsclient
python2 (I'm not sure what is needed if you are using python 3)

**Comment by kmonson** [comment]
Are you running the latest version of buildozer? I'm pretty sure the current stable version of buildozer is incompatible with the new android tool chain in the latest version p4a. 

Also, why are you running as root?

**Comment by jameswhitakerwork** [comment]
Thanks for your responses, kmonson. 

I tried replacing hostpython2 with python 2, to no avail unfortunately. 

I tried to solve the problem with the following steps, but got an identical error:

1. Deleted hard drive & reinstalled OSX (10.11.6)
2. Installed pip
3. pip install buildozer
4. buiildozer init, log_level to 2 and added hostpython2
5. buildozer android_new debug
6. Installed Xcode, java, and idk from the links prompted
7. builzoder android_new debug, worked fine, tested on device, all good. 
8. Added openssl to the spec, got identical error: "Modules/Setup.local": invalid command code M
9. Replaced it with pyopenssl, got identical error: "Modules/Setup.local": invalid command code M

My next try will be to work solely on linux. I will post back with my progress.

**Comment by kmonson** [comment]
I guess I should mention that I'm working entirely in a Linux VM to do all this .

**Comment by jameswhitakerwork** [comment]
I used the p4a tool with --debug to try and get more info: http://pastebin.com/8axhk96s

it looks like it is trying to run the following line:

running sed -i s#^SSL=.*#SSL=/Users/jameswhitaker/.python-for-android/build/other_builds/openssl/armeabi/openssl# Modules/Setup.local

with a space between openssl# and Modules/Setup.local... 

I will still try with linux and see what happens.

**Comment by jameswhitakerwork** [comment]
I tried with linux, and p4a successfuly compiled my app for android with openssl and pyopenssl.
