### ISSUE TITLE
Flask with Python3 does not seem to work.

### ISSUE THREAD

**Issue by hgrecco** [kivy/python-for-android#870]
I am not able to make the flask example work with python3. The compilation works but I get a "cannot load _ctypes" when running in the log as seen by adb logcat. The "build script" seems to be pulling python2.7 dependencies. Is that normal?
##

**Comment by inclement** [comment]
I haven't tested it with python3, but that _ctypes problem doesn't sound specific to flask. Where is the 'build script' pulling python2.7 things?

**Comment by inclement** [comment]
I've just pushed a fix for python3, are you able to test with the master branch again? Make sure to use `python3crystax` instead of `python3` in the requirements.

**Comment by inclement** [comment]
Should be fixed with the new python3 recipe.
