### ISSUE TITLE
Scipy recipe

### ISSUE THREAD

**Issue by alex-at-thimble** [kivy/python-for-android#874]
This is a request for a scipy recipe. 

Turns out scipy has a few more dependencies than numpy:
- BLAS: Can probably use https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android
- LAPACK: This one is tough; no fortran compiler in the NDK.  Can probably use this: https://github.com/simonlynen/android_libs/tree/master/lapack (clapack for android)

I'm still researching what else is needed.
##

**Comment by inclement** [comment]
People have looked into this before, but the highly complex dependencies have meant nobody got very far. I've been assuming that compiling some parts of scipy should be doable and maybe even not too hard, but I don't know much about its build process or how easy it would be.

In general, I'm happy to help anyone trying this, but it's unlikely to be a big target any time soon.

**Comment by KeyWeeUsr** [comment]
I was blindly planing to write a recipe for scipy. Then I saw what's under the hood and... hehe. But I saw [this](http://danilogiulianelli.blogspot.sk/2013/02/how-to-build-gcc-fortran-cross-compiler.html) blog post, which may be useful and if done right, could make p4a use fortran code too via recipes?

**Comment by alex-at-thimble** [comment]
@KeyWeeUsr Interesting.  There seems to be a maintained version of the toolchain with gfortran here: https://github.com/buffer51/android-gfortran 

I had a look and there is quite a lot of fortran in scipy, especially in fftpack, optimize, integrate and special.  ndimage is all c, however :)

**Comment by inclement** [comment]
Closing as not an active issue, it would be great to have a scipy recipe but it's unlikely that we will actively schedule time for it any time soon.

**Comment by rishabhjoshi** [comment]
Hi
This seems to be very heavily in demand with most apps now-a-days having some form of analytics. It would be great if you could open this probably add the labels for help and enhancement. It would be great if scipy and scikit-learn are added to kivy.

**Comment by AndreMiras** [comment]
Well we accept pull request and we love them! So feel free to submit one @rishabhjoshi 
And if you don't know how to address this specific PR, we also accept funding https://opencollective.com/kivy :smiley:

**Comment by pihash252** [comment]
> @KeyWeeUsr Interesting. There seems to be a maintained version of the ndk toolchain with gfortran here: https://github.com/buffer51/android-gfortran
> 
> I had a look and there is quite a lot of fortran in scipy, especially in fftpack, optimize, integrate and special. ndimage is all c, however :)

Have you or anyone been able to successfully use it to include Scipy in Buildozer?
