### ISSUE TITLE
No instructions for utilizing in Arch linux (i686 / x86_64)

### ISSUE THREAD

**Issue by UNIcodeX** [kivy/python-for-android#876]
**NOTE:** The following commands assume that your user has sudo access. If not, this can be accomplished by "usermod -G wheel {user}" without quotes, as root. It is also necessary to uncomment the following line in /etc/sudoers:
%wheel ALL=(ALL) ALL

**If platform is Arch x86_64 Enable multilib repository**
=========================================
Uncomment the following in /etc/pacman.conf:
[multilib]
Include = /etc/pacman.d/mirrorlist

**Update the package database** 
=======================
sudo pacman -Syu

**If platform is Arch x86_64:**
====================
sudo pacman -S jdk7-openjdk \
python2 \
python2-pip \
python2-kivy \
mesa-libgl \
lib32-mesa-libgl \
lib32-sdl2 \
lib32-sdl2_image \
lib32-sdl2_mixer \
sdl2_ttf \
unzip \
gcc-multilib \
gcc-libs-multilib

If prompted with the following, answer 'y' for both prompts:
::gcc-multilib and gcc are in conflict. Remove gcc?
::gcc-libs-multilib and gcc-libs are in conflict. Remove gcc-libs?

**If platform is Arch x86:**
==================
sudo pacman -S jdk7-openjdk \
python2 \
python2-pip \
python2-kivy \
mesa-libgl \
sdl2 \
sdl2_image \
sdl2_mixer \
sdl2_ttf \
unzip

**Install Cython:**
===========
sudo pip2 install cython

**Install buildozer:**
==============
git clone http://github.com/kivy/buildozer
sudo python2 setup.py install

**DONE!**

From here you should be able to run the buildozer build process.
- buildozer init
- modify the buildozer.conf as necessary
- buildozer android debug serve

**Comment by inclement** [comment]
Thanks for the information, I've added it to the doc at https://github.com/kivy/python-for-android/commit/5638a533d34f5946090a774c083de15892a44ef6

I notice that your dependencies don't include zlib, which I thought was necessary. Do you have that installed (probably lib32-zlib)?

**Comment by UNIcodeX** [comment]
I looked for it in installed packages (pacman -Q | grep zlib), because I
remember it being required as well, and it was listed as being installed. I
don't remember if it was the 64 bit or 32 bit version, but can verify when
I get back to the VM on Monday.

It must have either:
A) been in the default install.
B) been installed as a dependency of something else I installed.

I can track this down as well on Monday.

Package info for 64 bit version -
https://www.archlinux.org/packages/core/x86_64/zlib/

Package info for 32 bit version -
https://www.archlinux.org/packages/multilib/x86_64/lib32-zlib/

**Comment by UNIcodeX** [comment]
It got my curiosity up so I SSHd in.

Both zlib-1.2.8 64 bit and 32 bit are installed.

[image: Inline image 5]

[image: Inline image 1]

lib32-zlib depends on several packages, one of which is 64 bit zlib

[image: Inline image 2]

I see that lib32-sdl_image is in the list, and that requires lib32-sdl and
lib32-zlib which requires zlib, so my guess is that it was installed as a
dependency of sdl or something related to it.

still... it wouldn't hurt to add it to the "pacman -S ..." list to make
sure it gets installed.

hope this helps.

**Comment by inclement** [comment]
It looks like it's probably pulled in as a dependency so I won't modify the doc right now, thanks again for all the information.

**Comment by UNIcodeX** [comment]
Sounds good. You bet.
