### ISSUE TITLE
python3crystax conflicts with python3

### ISSUE THREAD

**Issue by pbienst** [kivy/python-for-android#877]
Using the  p4a from github, and trying to build one of the testapps:

>p4a apk --private $HOME/source/python-for-android/testapps/testapp_flask --package=org.example.myapp --name "My WebView Application" --version 0.1 --bootstrap=webview --requirements=flask,python3crystax --port=5000

[INFO]:    Will compile for the following archs: armeabi
[INFO]:    Found Android API target in $ANDROIDAPI
[INFO]:    Available Android APIs are (7, 8, 24)
[INFO]:    Requested API target 8 is available, continuing.
[INFO]:    Found NDK dir in $ANDROIDNDK
[INFO]:    Got NDK version from $ANDROIDNDKVER
[INFO]:    Using Crystax NDK 10.3.2
[INFO]:    Found virtualenv at /usr/bin/virtualenv
[INFO]:    Found the following toolchain versions: ['4.9', '5', 'clang3.6', 'clang3.7']
[INFO]:    Picking the latest gcc toolchain, here 5
[INFO]:    No existing dists meet the given requirements!
[INFO]:    No dist exists that meets your requirements, so one will be built.
[INFO]:    Bootstrap requires recipes ['genericndkbuild', ('python2', 'python3crystax')]
[INFO]:    Loaded recipe flask (depends on [('python2', 'python3'), 'setuptools'])
[INFO]:    Loaded recipe genericndkbuild (depends on [('python2', 'python3crystax')], conflicts ['sdl2', 'pygame', 'sdl'])
[INFO]:    Loaded recipe python3crystax (depends on ['hostpython3crystax'], conflicts ['python2', 'python3'])
[WARNING]: python3crystax conflicts with python3, but both have been included or pulled into the requirements.
[WARNING]: Due to this conflict the build cannot continue, exiting.

**Comment by inclement** [comment]
Thanks for the report, I've just pushed a fix for this (https://github.com/kivy/python-for-android/commit/18af2a15bb8d2d9a5fb69836e736ec03867d7acb).
