### ISSUE TITLE
Is it possible to add a argument to set the background color of the "loading screen"?

### ISSUE THREAD

**Issue by mrhdias** [kivy/python-for-android#881]
Like we have a argument to set the "presplash" we can have a argument to set the background color of the loading screen (sdl2 bootstarp).

Example:
nano -w pythonforandroid/bootstraps/sdl2/build/src/org/kivy/android/PythonActivity.java

```
...
        mImageView = new ImageView(this);
        mImageView.setImageBitmap(bitmap);
        mImageView.setBackgroundColor(0xFF0000FF); <=== This set the background to blue
        mImageView.setLayoutParams(new ViewGroup.LayoutParams(
        ViewGroup.LayoutParams.FILL_PARENT,
        ViewGroup.LayoutParams.FILL_PARENT));
        mImageView.setScaleType(ImageView.ScaleType.FIT_CENTER);
...
```

**Comment by inclement** [comment]
Sure. If you'd like to do a PR for this, it would be welcome, otherwise someone will probably add it when they have time.

**Comment by inclement** [comment]
This is now possible under SDL2, with the `--presplash-color` argument.
