### ISSUE TITLE
Cloud Builder - 500 Internal Server Error

### ISSUE THREAD

**Issue by al3xv3gas** [kivy/python-for-android#883]
So... I took one of your testapps and called it main.py and zipped it up in a folder and uploded it to the cloud builder. I called the package or.al3xv3gas.testapp and the app name was testapp and the version was 1.0. What am I doing wrong?

**Comment by inclement** [comment]
Are you referring to android.kivy.org? This isn't really maintained - I'm not sure who is hosting it but we should probably remove it.

Currently we only actively support building your own APKs with python-for-android (possibly via buildozer).

**Comment by dessant** [comment]
How did you find the cloud builder, from where is it linked? It has been deprecated for years.

**Comment by al3xv3gas** [comment]
Guys not so fast! The cloud builder is awesome! Becuase I cannot run linux on my windows machine and the cloud builder enables me to make my app! And btw is it possible to build a cli android app with python for android? @inclement @dessant

**Comment by al3xv3gas** [comment]
Had the link somewhere on my repo. Don't ask where because I cannot remember. @dessant

**Comment by KeyWeeUsr** [comment]
@al3xv3gas there's VM image with almost everything set, you just need to install buildozer (if it's not already there) - "Virtual Machine" [links](https://kivy.org/#download)

**Comment by al3xv3gas** [comment]
Can I use the image with VM Ware? @KeyWeeUsr

**Comment by KeyWeeUsr** [comment]
@inclement re cloud building, don't just kill it. Maybe Travis could be used to handle the APK building instead of something on kivy.org? The libs shouldn't be hard to install, python is probably there I guess... maybe storage/time limit would be a problem?

**Comment by al3xv3gas** [comment]
Well? @KeyWeeUsr

**Comment by KeyWeeUsr** [comment]
@al3xv3gas dunno, try [converting](http://www.dedoimedo.com/computers/virtualbox-convert.html) or use VirtualBox directly.

**Comment by inclement** [comment]
@KeyWeeUsr I'm not killing it, it's been dead for years. If someone wants to maintain such a thing that would be welcome, but unfortunately the Kivy core devs aren't able to commit to one right now.
