### ISSUE TITLE
PyGame backend: error while using android.copy_libs = 1

### ISSUE THREAD

**Issue by rafalo1333** [kivy/python-for-android#888]
When compiling the app with `python2` and `pygame` backend, the build process raises the error:

https://gist.github.com/rafalo1333/ead06e9641624d3d6818b23b41f5c8cf

It disappears after changing `android.copy_libs` to 0 in `buildozers.spec`.

Following the errors, I found that copying libs in pygame bootstrap raises the issue.

https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/pygame/__init__.py#L68

I do not understand it mostly, but I think its somewhere near.

**Comment by razzbee** [comment]
yea me too having the same problem

**Comment by inclement** [comment]
Closing as the pygame backend is no longer supported.
