### ISSUE TITLE
Buggy dependencies handling with multiple ./distribute.sh

### ISSUE THREAD

**Issue by tito** [kivy/python-for-android#90]
We should be smarter when using ./distribute.sh.

We should:
- seperate C libs with Python extensions, and prior C libs before any python extensions.
- be smart of the python deps: if someone compiled with -m "kivy" and then "sqlite3 kivy", sqlite3 will be compiled, but not python again. So the module sqlite3 will not appear in the final distribution!

**Comment by inclement** [comment]
I'll close this as fixed by the new toolchain.
