### ISSUE TITLE
ImportError for sqlite3

### ISSUE THREAD

**Issue by goffi-contrib** [kivy/python-for-android#910]
Hello,

After compilling a project on Arch Linux with latest buildozer and android_new target, the execution on Android fail because sqlite3 module can't be found, while it is in buildozer.spec requirements.

The module doesn't seem to be removed from blacklist.txt, if I do it manually, sqlite3 can be imported by my software.
- [build logs](https://framabin.org/?529e252fc73caaa9#C+0foMYexWYZem3InBC/Fs0NLUTPPgfFx3pbnDdu6oo=)
- [android logs](https://framabin.org/?e9be43f7374549a3#mV6+I35atTG1KoLIg7KC44wykcifUM/ytZqY8QfyPLA=)
- [buildozer.spec](https://framabin.org/?a0e4324c9e5fd2ab#dy0hZoKGQSn5x2wt8DW/llFNB4nvk9DgIQYJvwkwqss=)

In android logs we can also see the following line which may be related:

>  Android lib is missing, cannot install android hooks

buildozer.spec use a custom python-for-android, the only differences with upstream are:

```
diff --git a/pythonforandroid/bootstraps/pygame/build/blacklist.txt b/pythonforandroid/bootstraps/pygame/build/blacklist.txt
index 8b736c8..34d22d6 100644
--- a/pythonforandroid/bootstraps/pygame/build/blacklist.txt
+++ b/pythonforandroid/bootstraps/pygame/build/blacklist.txt
@@ -80,7 +80,6 @@ lib-dynload/_lsprof.so
 lib-dynload/*audioop.so
 lib-dynload/mmap.so
 lib-dynload/_hotshot.so
-lib-dynload/_csv.so
 lib-dynload/future_builtins.so
 lib-dynload/_heapq.so
 lib-dynload/_json.so
diff --git a/pythonforandroid/recipes/zope_interface/__init__.py b/pythonforandroid/recipes/zope_interface/__init__.py
index 3a54b9c..3c8afc2 100644
--- a/pythonforandroid/recipes/zope_interface/__init__.py
+++ b/pythonforandroid/recipes/zope_interface/__init__.py
@@ -1,9 +1,9 @@
-from pythonforandroid.toolchain import PythonRecipe, shprint, current_directory
-from os.path import join
+from pythonforandroid.toolchain import PythonRecipe, current_directory
 import sh


 class ZopeInterfaceRecipe(PythonRecipe):
+    call_hostpython_via_targetpython = False
     name = 'zope_interface'
     version = '4.1.3'
     url = 'https://pypi.python.org/packages/source/z/zope.interface/zope.interface-{version}.tar.gz'
```

thanks

**Comment by inclement** [comment]
Closing as stale, probably fixed in master.
