### ISSUE TITLE
My app crashed by raising error about Python3.5m, but i made apk by python2.7..!!!

### ISSUE THREAD

**Issue by moshen212** [kivy/python-for-android#933]
Hi guys
I made an apk from my project by python2 and buildozer, i installed and run on two phone by android version 4.2.2 and 4.12 and both crashed by below error:

Error: Couldn't load python3.5m: findLibrary returned null

In apk package sub address of `/lib/armeabi-v7a/` below files exists:

libmain.so
libpython2.7.so
libSDL2.so
libSDL2_image.so
libSDL2_mixer.so
libSDL2_ttf.so
libsqlite.so

Why when i used python2 for making package error raised about python3.5m?

kivy==1.9.1
Cython==0.25.1
python-for-android==0.4
buildozer==0.32
Also my OS is Ubuntu 15.10 and i used android_new target and android API v19 and 23 and 24 also i used Android NDK r12b.

**Comment by mrhdias** [comment]
Hi, check this issues:
https://github.com/kivy/python-for-android/issues/866
https://github.com/kivy/python-for-android/pull/903

The workaround:
https://github.com/kivy/python-for-android/commit/c1659b8fc195705d83cef55a7020ebce60d02958

**Comment by moshen212** [comment]
Thanks mrhdias for suggested links
I saw suggested links already, but yesterday after i changed NDK and NDK buildozer settings, my problem solved...

Thanks again
