### ISSUE TITLE
ImportError for ssl

### ISSUE THREAD

**Issue by Polynomdivision** [kivy/python-for-android#934]
When I try to import ssl using a simple import statement, e.g. `import ssl`, I get the error thrown that `_ssl` could not be found. Even when I add `openssl` to the requirements, the import error's still there.

I also tried changing the recipe for hostpython2 (In order to compile with SSL and crypto), but I get errors during the compiling process (Undefined references).

I'm wondering if that's an error of the recipe or a mistake I made

**Comment by Polynomdivision** [comment]
I found a solution:
In the recipe for python2, the patch `enable-ssl.patch` is missing.

**Comment by inclement** [comment]
Is this broken in master? Would you like to make a PR to apply your fix?

**Comment by Polynomdivision** [comment]
It appears so; I will push my changes to my fork and then create a PR

**Comment by Fak3** [comment]
@Polynomdivision do you have the same traceback as in https://github.com/kivy/python-for-android/issues/850 ?

**Comment by Polynomdivision** [comment]
If I remember correctly (because I deleted everything after I fixed this issue for myself) then it was not an issue with loading libraries. It was just that `_ssl` was not found. And after some digging around, I found out that no "compiled" python file for (I guess it was called like this; I don't remember anymore) `_ssl.py`.
