### ISSUE TITLE
Calendar.getTimeInMillis() returns a negative value

### ISSUE THREAD

**Issue by DeepSilence** [kivy/python-for-android#942]
Got this bug today. You may be able to reproduce using this :

```
    from jnius import autoclass
    Calendar = autoclass('java.util.Calendar')

    c = Calendar.getInstance()
    c.setTimeInMillis(1480103863835)
    Logger.info(c.getTimeInMillis()) //  -1659853285
```

**Comment by inclement** [comment]
I'm not sure what's wrong here, perhaps it is a pyjnius problem with converting the type.

**Comment by inclement** [comment]
@KeyWeeUsr Do you know if there was some pyjnius fix for numerical type conversions that could affect this?

**Comment by AndreMiras** [comment]
Yes recently actually https://github.com/kivy/pyjnius/commit/14fa9401a13170c8a90239a16b3d93fd0591f498
I'm closing, but feel free to reopen in https://github.com/kivy/pyjnius if this is still an issue
