### ISSUE TITLE
android module seems to eat up a character from java properties

### ISSUE THREAD

**Issue by kamathln** [kivy/python-for-android#945]
I am using kivy-remote-shell to play around the APIs and found this:
```python
import android
dir(android.python_act)
```

leads to a long output, but among that, you should find half eaten property/member names like:
```
 'estricted', 'estroyed', 'esumed', 
```
and 
```python
filter(lambda s: s.find('ayout') != -1, dir(android.python_act.mView))
```
will lead to output like
```
, 'ayoutDirectionResolved', 'ayoutRequested', 'ayoutRtl'
```

I hope It is not me who has goofed up during the build somewhere.

**Comment by kamathln** [comment]
Bump!

Should I move this to pyjnius ?

Please let me know! The silence is deafening!

**Comment by inclement** [comment]
I'm not sure if this is a pyjnius issue or a p4a issue. Have you ever triggered it in any way other than the android module?

**Comment by kamathln** [comment]
Nice timing .. I was debugging my app and found this .. note 'ocket$' . I bet it must have been 'socket$'
Also note this is in an instance of 'java.io.FileDescriptor'

I remember facing the issue somewhere else too, which was not related to the android module.

```
07-05 21:18:52.260 29354 29354 I python  :  fd.fileDescriptor: <java.io.FileDescriptor at 0xe3242720 jclass=java/io/FileDescriptor jself=<LocalRef obj=0x100d2a at 0xe286cbb0>>
07-05 21:18:52.260 29354 29354 I python  :  dir(fd.fileDescriptor): ['__class__', '__cls_storage', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', u'__javaclass__', u'__javaconstructor__', '__module__', '__new__', '__pyx_vtable__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'equals', 'err', 'getClass', 'getInt$', 'hashCode', 'in', 'int$', 'isSocket$', 'notify', 'notifyAll', 'ocket$', 'out', 'setInt$', 'sync', 'toString', 'valid', 'wait']

```

**Comment by Julian-O** [comment]
Believed to be closed with https://github.com/kivy/pyjnius/pull/325.

If you are still having this problem, please let us know.
