### ISSUE TITLE
Not a valid ELF executable

### ISSUE THREAD

**Issue by ghost** [kivy/python-for-android#957]
Hi
I made my app by a CythonRecipe, but after i made apk by below command:
`buildozer android debug`
This app crashed on android phones by an error about "not a valid ELF executable" that related to my CythonRecipe...
buildozer.spec:   https://dpaste.de/waVY
recipe.sh: https://dpaste.de/mxXP
setup.py: https://dpaste.de/QitC
logcat: https://dpaste.de/EY8e#L286,566,638

**Comment by inclement** [comment]
Closing as stale, the links have expired and it looks like an old toolchain issue.
