### ISSUE TITLE
Could not ping localhost:5000

### ISSUE THREAD

**Issue by caaarlos** [kivy/python-for-android#961]
I'm trying to use webview bootstrap but I get this message on my log:

25908 25953 V WebViewLoader: Could not ping localhost:5000

And my app stucks on Loading window.

This is my code:
`from flask import Flask
app = Flask(name)

@app.route('/')
def main_page():
return 'hello world'

app.run(debug=False, host='0.0.0.0')
`

If I open my browser on my phone or on my pc I can access my phone's IP on port 5000 and I am able to see the message 'Hello world'. So the flask server on my phone is working, but my app just show the loading message.

Am I doing something wrong?

**Comment by iiDatKat** [comment]
+1 I'm experiencing this problem too. I'm using Flask + Socket.IO in Python, and using the command to build a WebView application.

I put the python file in a folder, and specified that folder in the long p4a command. The python file can run by using `python ___.py`, no `FLASK_APP=___.py flask run` necessary. So I would think that when I open the APK app, it'll run automatically.

**Comment by inclement** [comment]
I haven't been able to reproduce this, but some following some discussion yesterday it seems that some people have problems with the packaged python installation.

Would you be able to paste the adb logcat log (http://python-for-android.readthedocs.io/en/latest/troubleshooting/#debugging-on-android) during the app start?

**Comment by inclement** [comment]
Closing as lacking a response.

**Comment by minglethepringle** [comment]
Forgot about this entirely, sorry lol.
