### ISSUE TITLE
"AndroidJoystick is not supported by your version of linux" confusing message in log

### ISSUE THREAD

**Issue by germn** [kivy/python-for-android#962]
If we use new toolchain we will see this messages:

> [ERROR ] Input: AndroidJoystick is not supported by your version of linux

and 

> [WARNING] Base: Unknown \<android\> provider

It happens because old pygame toolchain used AndroidJoystick as android provider and Kivy tells us it's unavailable in new toolchain.

While this is not a problem, this messages are confusing, especially since sdl2 doesn't use AndroidJoystick and android provider at all.

I think this messages shouldn't be in new toolchain app log.

**Comment by KeyWeeUsr** [comment]
The logs are probably from kivy directly, not from toolchain. Until pygame is deprecated completely, this probably won't be removed.

**Comment by inclement** [comment]
I think Kivy probably could just have a fix to not try this import when SDL2 is being used. Although it doesn't really matter, it's not nice to see the warning in the log.
