### ISSUE TITLE
The python2 build imports cython from the system python in /usr/lib/...

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#964]
This causes the build to fail, as python.host can't actually import the binary things it needs.

**Comment by germn** [comment]
Probably related to https://github.com/kivy/kivy/issues/4832

**Comment by inclement** [comment]
I don't think it is related, I wasn't using a recent kivy.

**Comment by razzbee** [comment]
I had the same problems , mine happened on android device < 4.4 , the only solution I had was 
1. use pygame backend 
2. use ndk 9c
3. in buildozer , set android.copy_libs to 0

Try it and maybe it might help

**Comment by inclement** [comment]
Should be fixed by https://github.com/kivy/python-for-android/commit/e3650d781b7dc80577621a29505b76b735afc5fc
