### ISSUE TITLE
Kivy with SDL2 bootstrap crushes on resuming in some cases  

### ISSUE THREAD

**Issue by germn** [kivy/python-for-android#967]
**How to reproduce № 1:**

1. Install app
2. When you see "installation complete" screen, choose "run" 
    (it's important to run app from installation screen)
3. Pause app
4. Run app with your launcher
5. App will crush instead of resuming

**How to reproduce № 2:**

1. Run app
2. Pause app
3. Try to open some file with your app
4. App will crush instead of resuming

**Sources:**

Source code: https://yadi.sk/d/X_EMFBTB34Gkp7 (example simple app; buildozer pathes and dirs should be edited)
Built apk: https://yadi.sk/d/jBrqtIf234GmEi
Adb log for № 1: https://yadi.sk/i/DKRxFYqz34GmXV
Adb log for № 2: https://yadi.sk/i/o_dZL_fY34Gmbs

If I understand correctly here crush lines from log:
```
I/SDL     ( 5353): SDL_Android_Init()
I/SDL     ( 5353): SDL_Android_Init() finished!
I/python  ( 5353): Initialize Python for Android
I/python  ( 5353): Changing directory to the one provided by ANDROID_ARGUMENT
I/python  ( 5353): /data/data/com.example.test/files/app
I/python  ( 5353): Preparing to initialize python
I/python  ( 5353): crystax_python does not exist
F/libc    ( 5353): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 5468 (SDLThread)
```

**Other info:**

None of this situations happens with old toolchain.
Recent kivy and p4a masters used.
Pyjnius was [patched](https://github.com/germn/python-for-android/commit/716489cb9315036b5c9fe27e648e1d88e48eaa09) to prevent [this](https://github.com/kivy/pyjnius/issues/249) error. It shouldn't affect way it works.
Tested on Android 5.0.1.

**Comment by inclement** [comment]
I believe this is fully working at the moment, especially after the transition to SLD2.0.9.
