### ISSUE TITLE
Kivy is broken on recent master

### ISSUE THREAD

**Issue by dessant** [kivy/python-for-android#970]
_From @germn on December 19, 2016 14:26_

`kivy==master` is broken when we try to build it for android.
Problem appeared recently, probably after [this commit](https://github.com/kivy/kivy/commit/08f5273bcff3e36c7eb7327a0be70c7ad6283cf3#diff-874717abbc54b331b987a6ad0b177c4d).

```
  RAN: '/usr/local/bin/cython ./kivy/properties.pyx'

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
           'NumericProperty', 'StringProperty', 'ListProperty',
           'ObjectProperty', 'BooleanProperty', 'BoundedNumericProperty',
           'OptionProperty', 'ReferenceListProperty', 'AliasProperty',
           'DictProperty', 'VariableListProperty', 'ConfigParserProperty')

include "config.pxi"
^
------------------------------------------------------------

kivy/properties.pyx:217:0: 'config.pxi' not found

```

_Copied from original issue: kivy/kivy#4832_

**Comment by dessant** [comment]
_From @matham on December 19, 2016 18:18_

Try master again. It may have been fixed.

**Comment by dessant** [comment]
_From @germn on December 19, 2016 20:59_

Sorry, but still same error.

**Comment by dessant** [comment]
_From @matham on December 19, 2016 22:23_

Ok, that needs to be fixed in the py4a side then. It may have assumed something about where the file is. And that has changed since it was moved to `kivy/include`. Although, I thought adding that path to the include directories in setup.py would fix it, but I guess that's not enough.

Someone familiar with android compilation should take a look.

**Comment by dessant** [comment]
_From @inclement on December 21, 2016 11:31_

I've changed p4a to use Kivy 1.9.1 for now (this should probably be the case anyway, so I don't intend to change it back to master). I couldn't fix it immediately though, will take another look soon.

**Comment by inclement** [comment]
This should be fixed now.
