### ISSUE TITLE
NDK automatic lookup tries to pick a tarball

### ISSUE THREAD

**Issue by Cheaterman** [kivy/python-for-android#972]
As the title suggests, the NDK automatic lookup feature seems to prefer a tarball over the extracted NDK path, so I have to specify --ndk-dir manually.

[INFO]:    Found possible NDK dirs in buildozer dir: android-ndk-r9c-linux-x86_64.tar.bz2, android-ndk-r9c
[INFO]:    Will attempt to use NDK at /home/cheaterman/.buildozer/android/platform/android-ndk-r9c-linux-x86_64.tar.bz2

Thanks in advance ^__^

**Comment by inclement** [comment]
Should be fixed in master. Given the error, perhaps you are the first person to use this feature!
