### ISSUE TITLE
API automatic lookup doesn't use available SDK API

### ISSUE THREAD

**Issue by Cheaterman** [kivy/python-for-android#973]
As the title says, API lookup seems to work (it detects that I have API 19) but still tries to use API 15 if I don't manually specify otherwise:

[INFO]:    Will attempt to use SDK at /home/cheaterman/.buildozer/android/platform/android-sdk-20
[INFO]:    Android API target was not set manually, using the default of 15
[INFO]:    Available Android APIs are (19)

Thanks in advance :-)

**Comment by inclement** [comment]
Closing as not a real issue, I think it's okay behaviour to not automatically detect this as the target api has implications for how/where the app can run.
