### ISSUE TITLE
P4A wants to start "ant" without using full SDK path

### ISSUE THREAD

**Issue by Cheaterman** [kivy/python-for-android#974]
As the title says, apparently P4A expects "ant" to be in the user's $PATH, despite it being capable of finding the full path of the binary (since it found the SDK already).

https://gist.github.com/anonymous/b1bd46eb7683e076588d4ff86b9dddd4

Thanks in advance :-)

**Comment by inclement** [comment]
I've added an explicit autodetection and error if ant is not found, but I'm not sure where ant is supposed to be in the SDK. Where was yours?
