### ISSUE TITLE
--presplash and --icon aren't mentioned in revamp docs

### ISSUE THREAD

**Issue by Cheaterman** [kivy/python-for-android#975]
As the title implies, the only mentions of --presplash and --icon options I could find in the docs are from old_toolchain.

It might be a good idea to fix this, and also add the cool new options like --presplash-color :-)

**Comment by inclement** [comment]
Fixed, see [Bootstrap options](http://python-for-android.readthedocs.io/en/latest/buildoptions/#id1) :)
