### ISSUE TITLE
lxml is needed in new toolchain

### ISSUE THREAD

**Issue by ngoonee** [kivy/python-for-android#976]
Ran into https://github.com/kivy/buildozer/issues/451 recently. Previously on the old toolchain this functionality for my app was working, and as I had fallback imports as lxml documentation advises, I didn't notice it had stopped working. However I did add more xml related features on desktop and this caused the android version to break silently.

Basically lxml has etree.so and objectify.so which are binary (cython), and need to be recompiled for use in android. I would append this to https://github.com/kivy/python-for-android/issues/464 but it was closed as being too generic (I think).

**Comment by ngoonee** [comment]
https://github.com/kivy/python-for-android/blob/old_toolchain/recipes/lxml/recipe.sh as a convenient link. Unfortunately I can't seem to figure out how to port this properly (or am making a rookie mistake), and it probably depends on libxml2 and libxslt (both also not yet ported) as well.

**Comment by ScissorHIll** [comment]
I've encountered same issue ([kivy/buildozer#451](https://github.com/kivy/buildozer/issues/451)) with Buildozer 0.33 as well. @ngoonee - were you able to find any workarounds?

**Comment by ngoonee** [comment]
Yes, my workaround was to use etree (specifically cElementTree which has comparable speed, at the cost of losing the xml conveniences) directly, as most of my calls were etree API anyway (maybe 3 or 4 lines of code change in the end). Sorry, this likely doesn't help.

**Comment by ScissorHIll** [comment]
Thanks. Just to clarify - does cElementTree play well with the new P4A toolchain? Are you able to use this module on Android?

**Comment by ngoonee** [comment]
Yes it does, it's built in to python after all.

**Comment by inclement** [comment]
We currently have a working libxml recipe.
