### ISSUE TITLE
Kivy with SDL2 bootstrap crashes on pausing if app doesn't support pause mode

### ISSUE THREAD

**Issue by germn** [kivy/python-for-android#978]
**How to reproduce:**
1) Create app where:
```
    def on_pause(self):
        return False
```
2) Run app
3) Use "home" button to pause app
4) App will crush

I used recent kivy/p4a masters. I also used intent_filters option, nothing more specific.
Can anyone confirm it's not only just me?

**Comment by KeyWeeUsr** [comment]
Does your installation have this line (https://github.com/kivy/python-for-android/commit/0db9af7ff1d664c7603793d6b513f35eacadc024)?

**Comment by germn** [comment]
Yes, I used later p4a from 16 december. 
Do you have same error? If not, couldn't you tell what ver. of p4a/kivy are you using?

**Comment by KeyWeeUsr** [comment]
App crashes after calling it back, not when I use `home` button. Most likely there's missing the same line I linked to somewhere, where p4a handles app that doesn't pause. Probably in the same file.

**Comment by germn** [comment]
I got it working. Looks like it's kivy bug, neither then p4a.

ok, in my case back button works fine, [here's code](https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L1400) where it handles:
```
if not self.dispatch('on_request_close', source='keyboard'):
    stopTouchApp()
    self.close()
    return True
```

More interesting about handling `on_pause`, I found two places with duplicate code ([1](https://github.com/kivy/kivy/blob/master/kivy/core/window/window_sdl2.py#L608), [2](https://github.com/kivy/kivy/blob/master/kivy/core/window/window_sdl2.py#L215)):
```
if not app.dispatch('on_pause'):
    Logger.info('WindowSDL: App doesn\'t support pause mode, stop.')
    stopTouchApp()
    return
```

Only different thing from handling back button is calling `self.close()`. I added this call in both places in `window_sdl2.py` and now home button works without crash for me.

It doesn't seems like final fix, I'll try to dig deeper later. Probably `window_sdl2.py` pausing/resuming code need to be refactored ([this](https://github.com/kivy/kivy/blob/master/kivy/core/window/window_sdl2.py#L613) is also interesting line).

**Comment by inclement** [comment]
@germn I didn't know why the crashing was happening, so this is very useful to know, thanks.

**Comment by mixmastamyk** [comment]
I'm having this problem too, any progress on this bug?

(BTW, the term is *crash,* haha.)

**Comment by germn** [comment]
@mixmastamyk hello, there is PR that fixes problem:
https://github.com/kivy/kivy/pull/4927

While this PR fixes problem, it's not merged in Kivy yet: there's few things that need to be done before merging in master.

If you want to use PR right now, you'll need to clone Kivy master, merge [this](https://github.com/germn/kivy/tree/fix_sdl2_pause_exit) branch and use this local cloned Kivy to build app (you can use local Kivy by redefining `requirements.source.kivy` in `buildozer.spec`).

**Comment by inclement** [comment]
I think this doesn't happen any more with sdl2.0.9.
