### ISSUE TITLE
Android Emulator support

### ISSUE THREAD

**Issue by ZingBallyhoo** [kivy/python-for-android#979]
Hello. I have been trying to see if I can get P4A to work with Android TV, with not much luck.

Pure python works fine, but the encoding library seems to be broken (which also breaks kivy) 

Emulator info: 
```
CPU/ABI: Android TV ARM (armeabi-v7a)
Target: android-tv [Android TV] (API level 23)
avd.ini.encoding: UTF-8 (I don't know if this is important or not, using default setting)
```

[Full log](https://gist.github.com/ZingBallyhoo/c47c0fbcbd657fbdb56c20ddb94c4e7e)

[main.py](https://gist.github.com/ZingBallyhoo/6fe4f21102ff6d31e1ce44cec953e927)

[buildozer.spec](https://gist.github.com/ZingBallyhoo/1cf3cfc950f485a3bc7513bdf5f2f87a)

Here are the interesting parts of the log:
```
01-14 15:33:45.296  1629  1648 I python  :  Traceback (most recent call last):
01-14 15:33:45.297  1629  1648 I python  :    File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/logging/__init__.py", line 865, in emit
01-14 15:33:45.298  1629  1648 I python  :  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 43: ordinal not in range(128)
01-14 15:33:45.310  1629  1648 I python  :  Logged from file __init__.py, line 947
01-14 15:33:45.321  1629  1648 I python  :  Traceback (most recent call last):
01-14 15:33:45.322  1629  1648 I python  :    File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/logging/__init__.py", line 865, in emit
01-14 15:33:45.324  1629  1648 I python  :  UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 41: ordinal not in range(128)
01-14 15:33:45.325  1629  1648 I python  :  Logged from file __init__.py, line 947
```
Logger causes an error, but works fine anyway

```
01-14 15:33:45.369  1629  1648 I python  : [CRITICAL] [Window      ] Unable to find any valuable Window provider.
01-14 15:33:45.369  1629  1648 I python  : sdl2 - UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 4: invalid start byte
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/__init__.py", line 67, in core_select_lib
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 139, in __init__
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 795, in __init__
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 284, in create_window
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 947, in create_window
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/instructions.pyx", line 752, in kivy.graphics.instructions.RenderContext.__init__ (kivy/graphics/instructions.c:12152)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 184, in kivy.graphics.shader.Shader.__init__ (kivy/graphics/shader.c:5159)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 693, in kivy.graphics.shader.Shader.vs.__set__ (kivy/graphics/shader.c:12298)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 555, in kivy.graphics.shader.Shader.build_vertex (kivy/graphics/shader.c:10181)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 578, in kivy.graphics.shader.Shader.link_program (kivy/graphics/shader.c:10496)
01-14 15:33:45.369  1629  1648 I python  :   File "kivy/graphics/shader.pyx", line 632, in kivy.graphics.shader.Shader.get_program_log (kivy/graphics/shader.c:11143)
01-14 15:33:45.369  1629  1648 I python  :   File "/home/zingballyhoo/Desktop/kivy-android/tv-test/.buildozer/android/platform/build/dists/tvtest/private/lib/python2.7/encodings/utf_8.py", line 16, in decode
01-14 15:33:45.371  1629  1648 I python  : [CRITICAL] [App         ] Unable to get a Window, abort.
```
Here is the culprit line in Kivy: https://github.com/kivy/kivy/blob/master/kivy/graphics/shader.pyx#L632

If anyone can get this working, I will be able to add proper D-Pad support to P4A

**Comment by inclement** [comment]
This is interesting but I don't really know what's wrong. It might be worth opening an issue in Kivy about it - if it comes down to handling decoding problems from shaders, it might be possible to fix it in a general way without worrying about the specific device here.

**Comment by ZingBallyhoo** [comment]
@inclement I will, but it is likely that things will be broken elsewhere (since Logger errors too).

**Comment by ZingBallyhoo** [comment]
@inclement Just realised this is not because of Android TV, it is because I am using an Android Emulator (avd). Still weird though

**Comment by FeralBytes** [comment]
I have also hit this wall; all of my compiled programs are exiting with this error in AVD. @ZingBallyhoo how did you get around it?

**Comment by ZingBallyhoo** [comment]
@FeralBytes I haven't found out why this is is happening yet, or how to fix it. When I test, I currently have to use a real device, which is annoying because I only have armeabi-v7a devices. This means that I am unable to test to see if my x86 and arm64-v8 builds actually work.

This error happens on every android emulator I have found:
* Genymotion (at its core, is VirtualBox)
* Android AVD
* Bluestacks
* Everything else

I feel like this would not be a hard fix, of only we actually new what the problem was.

On 23 Feb 2017 5:02 am, FeralBytes <notifications@github.com> wrote:

I have also hit this wall; all of my compiled programs are exiting with this error in AVD. @ZingBallyhoo<https://github.com/ZingBallyhoo> how did you get around it?

**Comment by FeralBytes** [comment]
@ZingBallyhoo You are right the same APK that fails in AVD; does work on the actual phone. Core Dev's I think this is a bigger bug; because not being able to test the APK on AVD is a huge issue. @inclement I have finally found the source of my problems. This is it; because even Pyonic was failing on me.

**Comment by ZingBallyhoo** [comment]
I have made some progress, Logger no longer errors, and I now get this output:

```[INFO   ] [Shader      ] fragment shader: <>```

This seems to be why logger was unhappy, but I don't know why this suddenly works. This also shows why Kivy doesn't work properly.

**Comment by FeralBytes** [comment]
@ZingBallyhoo what did you do or change to get this result? Also you did a good job identifying the exact line causing the issue. By reading the comments above that line it looks like that piece of code has always been finicky.

**Comment by ZingBallyhoo** [comment]
@FeralBytes I'm not sure what I did actually, but here are some things that are different from my first test:

 * API 21 instead of 19
 * NDK r10e instead of r9c
 * AVD running on Windows
 * Built automatically here: https://gitlab.com/kivymd/KivyMD/pipelines/6634370
   * The script used to build is here: https://gitlab.com/kivymd/KivyMD/blob/master/.gitlab-ci.yml
   * Full build log: https://gitlab.com/kivymd/KivyMD/builds/10974875
   * APK that I'm using: https://gitlab.com/kivymd/KivyMD/builds/10974875/artifacts/file/demos/kitchen_sink/bin/android_kitchen_arm-v7a-master-17a2e8ec.apk

**Comment by ZingBallyhoo** [comment]
Kivy issue here: https://github.com/kivy/kivy/issues/5017

**Comment by inclement** [comment]
Closing as the related Kivy issue is closed (and solved?).

For p4a this is stale as the build system has changed a lot since this report, including the things like the supported APIs and Python versions which could affect how things work. Please feel free to make a new issue if this does still occur with the master branch.
