### ISSUE TITLE
'Window.request_keyboard' without showing keyboard

### ISSUE THREAD

**Issue by ZingBallyhoo** [kivy/python-for-android#986]
Hello.

What I am trying to achieve is listening for key events (on_key_down, on_key_up) without the keyboard showing (not listening for keys that can be typed on the keyboard, D-Pad events that are passed through the keyboard provider (DPAD_UP,DPAD_DOWN,DPAD_LEFT,DPAD_RIGHT,DPAD_CENTER))

Receiving the actual events works fine, but only when the keyboard is showing. I need it to not show the keyboard, and still be able to receive the events. (opens when Window.request_keyboard, stops receiving events after you close the keyboard)

[Demo program](https://gist.github.com/ZingBallyhoo/4b9a8b5567752a7941892c5ec21440ee)

Anyone know if this is possible?

**Comment by ZingBallyhoo** [comment]
Update:

I have been able to get events after the keyboard is hidden by the user, by removing the 'unbind' from the widget. I still don't know how to not make the keyboard show at all.

**Comment by inclement** [comment]
Have you tried binding to Window.on_key_down?

**Comment by ZingBallyhoo** [comment]
@inclement Thanks. That does indeed work.

**Comment by z-huabao** [comment]
@ZingBallyhoo hello, can you tell me how to "binding to Window.on_key_down" in code billow:
```
class MyKeyboardListener(Widget):
    def __init__(self, **kwargs):
        super(MyKeyboardListener, self).__init__(**kwargs)
        self._keyboard = Window.request_keyboard(self._keyboard_closed, self, 'text')
        self._keyboard.bind(on_key_down=self._on_keyboard_down)

    def _keyboard_closed(self):
        print('My keyboard have been closed!')
        self._keyboard.unbind(on_key_down=self._on_keyboard_down)
        self._keyboard = None

    def _on_keyboard_down(self, keyboard, keycode, text, modifiers):
        print('The key', keycode, 'have been pressed')
```
