### ISSUE TITLE
Create a space for common bootstrap code along with a base class for all bootstraps

### ISSUE THREAD

**Issue by kollivier** [kivy/python-for-android#988]
Currently, each backend has a completely separate tree of Java classes for initialzing the bootstrap, although a significant amount of the code is sharable among the backends. We should create a single place for this common code and refactor the bootstraps to use them rather than duplicate them.

**Comment by AndreMiras** [comment]
Thanks for tracking the issue and thanks for the pull request. I was actually discussing this in the group recently https://groups.google.com/forum/#!topic/kivy-dev/MvAzPilialw
We'll take a look at he PR :+1:

**Comment by inclement** [comment]
Closing as work along these lines has been merged thanks to various contributors :)
