### ISSUE TITLE
PythonActivity.mActivity causes app crash with new toolchain

### ISSUE THREAD

**Issue by WillDHB** [kivy/python-for-android#995]
The following code causes an app to crash instantly:

```
from jnius import autoclass
PythonActivity = autoclass('org.renpy.android.PythonActivity')
ac = PythonActivity.mActivity
```

I have encountered this in a Kivy app I've built with buildozer, and have seen the issue across multiple devices.  I have also reproduced this issue in the remote shell.  I had not seen this occur when using the old toolchain.

**Comment by KeyWeeUsr** [comment]
What about `org.kivy.android.PythonActivity`? I works with `renpy` call anyway ([source](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/sdl2/build/src/org/renpy/android/PythonActivity.java)), so I'm not sure why this fails for you, as it works for me with with latest versions.

App output(logcat) would be really nice to have. :)

**Comment by WillDHB** [comment]
org.kivy.android.PythonActivity does not seem to have the problem:

```
>>> from jnius import autoclass
>>> PythonActivity = autoclass('org.kivy.android.PythonActivity')
>>> ac = PythonActivity.mActivity
>>> # Note how it didn't crash 
>>> PA2 = autoclass('org.renpy.android.PythonActivity')
>>> PA2.mActivity # ...and crash
```

I do not know whether it would have crashed if I'd tried to do something more substantial with org.kivy.android.PythonActivity.

Here's a log file:
[deviceid_log.txt](https://github.com/kivy/python-for-android/files/731459/deviceid_log.txt)

I have seen this issue on a OnePlus One, an AVD emulator emulating a Nexus 6, and a Pixel.

**Comment by germn** [comment]
Probably it's this [issue](https://github.com/kivy/pyjnius/issues/249). You can try temporary fix mentioned there.

**Comment by inclement** [comment]
The PythonActivity class used to be `org.renpy.android.PythonActivity` in the old toolchain (and still is in the pygame bootstrap), but in all the others it is now `org.kivy.android.PythonActivity`. If you're using the new toolchain and anything except the pygame bootstrap, just change the references in your code to `org.kivy.android.PythonActivity`.
