### ISSUE TITLE
documentation: how to run without pip install ( development mode )

### ISSUE THREAD

**Issue by trabitboy** [kivy/python-for-android#996]
I am trying to currently test python-for-android under cygwin.
I could get relatively far ( I do android sdk + ndk on this environment for a couple of years ),
however the default " c compiler path composition" fails on this setup.

To try to patch it in build.py, I uninstalled the repo version and tried to run the build chain with setup.py,
but still , I don't get how to run the checkout of the git repo without packaging it ?
( I wrote quite a bit of python but am completely lost regarding packaging )

Of course, I read the docs :)

**Comment by KeyWeeUsr** [comment]
Afaik, cygwin, or basically **any** Windows-only support isn't available. Only with Ubuntu/Win10 subsystem. Then there's #994 which should work, but has some bugs related to the final app.

**Comment by trabitboy** [comment]
ok, thanks for the pointer . I know it is not supported , but I am not afraid to mess around.

My question was more : when you test the build chain ( as a python script that has dependency on modules )
How do you run it ? What is the normal "testing" workflow ?

**Comment by inclement** [comment]
Sorry for the delay replying to this, I somehow missed the issue entirely. I'm not sure what you're asking though, what are you trying to do?

We're unlikely to support windows directly in the near future, but matham did a PR (https://github.com/kivy/python-for-android/pull/994) that seems to make p4a work there.
